'use strict';
/* Cuenta opcional: entra con Google (Firebase Authentication) para guardar tus rutas en la nube y tenerlas en cualquier
   dispositivo. Sin cuenta todo sigue funcionando y se guarda solo en este dispositivo. Requiere la misma configuración
   de Firebase que el Copiloto (README → «Cuentas»). */
const ACC={fb:null,user:null,busy:false,cloud:new Map(),status:'',guest:false};
try{ACC.guest=localStorage.getItem('tm.account')==='guest'}catch{}
/* Polilínea codificada (formato de Google, precisión 5): 3000 puntos ≈ 20 KB. */
function encodePolyline(points,precision=5){const f=10**precision;let out='',pl=0,pn=0;const enc=v=>{v=v<0?~(v<<1):v<<1;let s='';while(v>=0x20){s+=String.fromCharCode((0x20|(v&0x1f))+63);v>>=5}return s+String.fromCharCode(v+63)};for(const p of points){const la=Math.round(p.lat*f),lo=Math.round(p.lon*f);out+=enc(la-pl)+enc(lo-pn);pl=la;pn=lo}return out}
function thinPoints(points,max=3000){if(points.length<=max)return points;const step=(points.length-1)/(max-1);return Array.from({length:max},(_,i)=>points[Math.round(i*step)])}
/* Registro en la nube: solo lo necesario para reconstruir la ruta; las previsiones se vuelven a pedir al abrirla. */
function cloudRecord(rec){const r=rec.route,pts=thinPoints(r.points||[]);return{name:String(r.name||'Ruta').slice(0,140),saved:rec.saved||Date.now(),km:r.summary?.km??null,up:r.summary?.up??null,pace:rec.pace??null,climb:rec.climb??null,poly:encodePolyline(pts),ele:pts.map(p=>finite(p.ele)?Math.round(p.ele):null),v:1}}
function recordFromCloud(id,d){const pts=TMWikiloc.decodePolyline(d.poly||'').map((p,i)=>({...p,ele:finite(d.ele?.[i])?d.ele[i]:null}));if(pts.length<2)return null;const r=parseGPX(TMWikiloc.buildGPX(d.name||'Ruta',pts));return{id,version:1,saved:d.saved||Date.now(),route:{...r,sampled:sample(r.points,16)},pace:finite(d.pace)?d.pace:Number($('#pace')?.value||15),climb:finite(d.climb)?d.climb:Number($('#climb')?.value||10),contact:'',alerts:null,mountain:null,cloud:true}}

async function fbLoad(){if(ACC.fb)return ACC.fb;const cfg=typeof firebaseConfig==='function'?firebaseConfig():null;if(!cfg)throw Error('Falta configurar Firebase');const base=`https://www.gstatic.com/firebasejs/${FIREBASE_SDK}/`;const [appM,authM,fsM]=await Promise.all([import(base+'firebase-app.js'),import(base+'firebase-auth.js'),import(base+'firebase-firestore.js')]);const app=appM.getApps().find(a=>a.name==='trailmeteo')||appM.initializeApp(cfg,'trailmeteo');const auth=authM.getAuth(app);try{await authM.setPersistence(auth,authM.browserLocalPersistence)}catch{}ACC.fb={auth,authM,db:fsM.getFirestore(app),fsM};authM.onAuthStateChanged(auth,u=>{ACC.user=u||null;renderAccount();if(u)syncRoutes()});try{await authM.getRedirectResult(auth)}catch(e){ACC.status=authError(e)}return ACC.fb}
function authError(e){const c=e?.code||'';return c==='auth/unauthorized-domain'?'Este dominio no está autorizado en Firebase → Authentication → Settings → Dominios autorizados.':c==='auth/operation-not-allowed'?'Activa el proveedor Google en Firebase → Authentication → Sign-in method.':c==='auth/popup-closed-by-user'||c==='auth/cancelled-popup-request'?'Inicio de sesión cancelado.':c==='auth/network-request-failed'?'Sin conexión con Google.':e?.message||'No se pudo iniciar sesión.'}
/* La ventana de Google debe abrirse en el mismo toque: si antes hay que descargar Firebase, Safari la bloquea. Por eso se precarga y, si aún no estaba, se pide un segundo toque. */
function popupNow(){const {auth,authM}=ACC.fb;const prov=new authM.GoogleAuthProvider();prov.setCustomParameters({prompt:'select_account'});return authM.signInWithPopup(auth,prov)}
async function signIn(){const ready=!!ACC.fb;const pop=ready?popupNow():null;ACC.busy=true;ACC.status='';renderAccount();try{if(!ready){await fbLoad();ACC.status='Listo. Toca otra vez «Continuar con Google».';return}try{await pop}catch(e){if(e.code==='auth/popup-blocked'){ACC.status='El navegador ha bloqueado la ventana de Google. Permite ventanas emergentes para este sitio y vuelve a tocar.';return}if(e.code==='auth/operation-not-supported-in-this-environment'){ACC.status='Este modo de app no permite la ventana de Google. Abre TrailMeteo en Safari o Chrome, inicia sesión allí y vuelve.';return}if(['auth/popup-closed-by-user','auth/cancelled-popup-request'].includes(e.code)){ACC.status='Inicio de sesión cancelado.';return}throw e}try{localStorage.setItem('tm.account','google')}catch{}ACC.guest=false;if(typeof sfx==='function')sfx('ok')}catch(e){ACC.status=authError(e);if(typeof sfx==='function')sfx('warn')}finally{ACC.busy=false;renderAccount()}}
async function signOut(){try{await ACC.fb?.authM.signOut(ACC.fb.auth)}catch{}ACC.user=null;ACC.cloud.clear();try{localStorage.setItem('tm.account','guest')}catch{}ACC.guest=true;renderAccount();refreshLibrary()}
function useGuest(){ACC.guest=true;try{localStorage.setItem('tm.account','guest')}catch{}closeAccount();if(typeof sfx==='function')sfx('tap')}
const routesCol=()=>ACC.fb.fsM.collection(ACC.fb.db,'users',ACC.user.uid,'routes');
/* Sincronización en dos sentidos: sube lo local que falta o es más nuevo; baja lo que solo está en la nube. */
async function syncRoutes(){if(!ACC.user||!ACC.fb||ACC.syncing)return;ACC.syncing=true;ACC.status='Sincronizando rutas…';renderAccount();const {fsM}=ACC.fb;try{const snap=await fsM.getDocs(routesCol());ACC.cloud.clear();snap.forEach(d=>ACC.cloud.set(d.id,d.data()));const local=await dbOp('readonly',s=>s.getAll());const ids=new Set(local.map(r=>r.id));let up=0,down=0;
  for(const rec of local){const c=ACC.cloud.get(rec.id);if(!c||(rec.saved||0)>(c.saved||0)+1000){const data=cloudRecord(rec);await fsM.setDoc(fsM.doc(routesCol(),rec.id),data);ACC.cloud.set(rec.id,data);up++}}
  for(const [id,d] of ACC.cloud){if(ids.has(id))continue;const rec=recordFromCloud(id,d);if(rec){await dbOp('readwrite',s=>s.put(rec));down++}}
  ACC.status=`Sincronizado: ${ACC.cloud.size} rutas en tu cuenta${up?` · ${up} subidas`:''}${down?` · ${down} descargadas`:''}.`;if(down)refreshLibrary();else markCloud()}catch(e){ACC.status='No se pudo sincronizar: '+(e.code==='permission-denied'?'faltan las reglas de Firestore (README → Cuentas).':e.message)}finally{ACC.syncing=false;renderAccount()}}
async function deleteCloud(id){if(!ACC.user||!ACC.fb||!ACC.cloud.has(id))return;try{await ACC.fb.fsM.deleteDoc(ACC.fb.fsM.doc(routesCol(),id));ACC.cloud.delete(id);renderAccount()}catch{}}

/* ---------- Interfaz ---------- */
$('#soundToggle')?.insertAdjacentHTML('beforebegin','<button id="accountBtn" class="quiet account-btn" type="button" aria-label="Tu cuenta"><span class="acc-dot" aria-hidden="true"></span><span class="acc-label">Entrar</span></button>');
function initials(u){return String(u?.displayName||u?.email||'?').trim().split(/\s+/).map(x=>x[0]).slice(0,2).join('').toUpperCase()}
function renderAccount(){const b=$('#accountBtn');if(b){const u=ACC.user;b.classList.toggle('in',!!u);b.querySelector('.acc-dot').innerHTML=u?(u.photoURL&&/^https:\/\//.test(u.photoURL)?`<img src="${esc(u.photoURL)}" alt="" referrerpolicy="no-referrer">`:esc(initials(u))):'<svg viewBox="0 0 24 24" aria-hidden="true"><circle cx="12" cy="8.5" r="3.6"/><path d="M5 20c1.3-3.6 3.9-5.4 7-5.4s5.7 1.8 7 5.4"/></svg>';b.querySelector('.acc-label').textContent=u?(u.displayName||'Mi cuenta').split(' ')[0]:'Entrar';b.setAttribute('aria-label',u?'Cuenta de '+(u.displayName||u.email):'Entrar o usar sin cuenta')}const box=$('#accBody');if(box)box.innerHTML=accountHTML()}
function accountHTML(){const u=ACC.user,configured=typeof firebaseConfig==='function'&&!!firebaseConfig();
 if(u)return `<div class="acc-who">${u.photoURL&&/^https:\/\//.test(u.photoURL)?`<img src="${esc(u.photoURL)}" alt="" referrerpolicy="no-referrer">`:`<span class="acc-av">${esc(initials(u))}</span>`}<div><b>${esc(u.displayName||'Tu cuenta')}</b><small>${esc(u.email||'')}</small></div></div><p class="wl-status ${/No se pudo/.test(ACC.status)?'err':'ok'}">${esc(ACC.status||`${ACC.cloud.size} rutas en tu cuenta.`)}</p><div class="acc-list">${[...ACC.cloud].sort((a,b)=>(b[1].saved||0)-(a[1].saved||0)).slice(0,30).map(([id,d])=>`<div class="tr-row"><span class="tr-badge">☁</span><div><b>${esc(d.name)}</b><small>${finite(d.km)?fmt(d.km,1)+' km · ':''}${finite(d.up)?'+'+fmt(d.up)+' m · ':''}${new Date(d.saved).toLocaleDateString('es-ES')}</small></div><button class="quiet" type="button" data-acc-open="${esc(id)}">Abrir</button><button class="quiet" type="button" data-acc-del="${esc(id)}" aria-label="Eliminar de la nube">✕</button></div>`).join('')||'<p class="muted">Guarda una ruta en Planificar → «Guardar ruta» y aparecerá aquí y en tus otros dispositivos.</p>'}</div><div class="action-row"><button class="primary" type="button" data-acc="sync"${ACC.syncing?' disabled':''}>${ACC.syncing?'<span class="spinner"></span>Sincronizando…':'Sincronizar ahora'}</button><button class="quiet" type="button" data-acc="out">Cerrar sesión</button></div><p class="footnote">Tus rutas se guardan en Firestore bajo tu usuario; solo tú puedes leerlas. Las previsiones no se suben: se recalculan al abrir.</p>`;
 return `<p class="acc-lead">Tus rutas, en todos tus dispositivos.</p><button class="google-btn" type="button" data-acc="in"${ACC.busy||!configured?' disabled':''}><svg viewBox="0 0 48 48" aria-hidden="true"><path fill="#FFC107" d="M43.6 20.5H42V20H24v8h11.3C33.7 32.7 29.2 36 24 36c-6.6 0-12-5.4-12-12s5.4-12 12-12c3.1 0 5.8 1.2 7.9 3.1l5.7-5.7C34 6.1 29.3 4 24 4 12.9 4 4 12.9 4 24s8.9 20 20 20 20-8.9 20-20c0-1.3-.1-2.4-.4-3.5z"/><path fill="#FF3D00" d="m6.3 14.7 6.6 4.8C14.7 15.1 19 12 24 12c3.1 0 5.8 1.2 7.9 3.1l5.7-5.7C34 6.1 29.3 4 24 4 16.3 4 9.7 8.3 6.3 14.7z"/><path fill="#4CAF50" d="M24 44c5.2 0 9.9-2 13.4-5.2l-6.2-5.2c-2 1.5-4.5 2.4-7.2 2.4-5.2 0-9.6-3.3-11.3-8l-6.5 5C9.5 39.6 16.2 44 24 44z"/><path fill="#1976D2" d="M43.6 20.5H42V20H24v8h11.3c-.8 2.2-2.2 4.2-4.1 5.6l6.2 5.2C37 39.2 44 34 44 24c0-1.3-.1-2.4-.4-3.5z"/></svg>${ACC.busy?'Conectando…':'Continuar con Google'}</button><div id="gisBtn" class="gis-btn"></div><button class="quiet guest-btn" type="button" data-acc="guest">Usar sin registrarme</button>${ACC.status?`<p class="wl-status err">${esc(ACC.status)}</p>`:''}${configured?'':'<p class="footnote">El inicio de sesión aún no está activado en esta instalación: falta la configuración de Firebase (Copiloto → ⚙ Ajustes) y activar Google en Authentication. Mientras tanto todo funciona sin cuenta.</p>'}<ul class="acc-perks"><li><b>Sin cuenta</b>: todo funciona; tus rutas se guardan solo en este dispositivo.</li><li><b>Con Google</b>: copia en la nube y sincronización entre móvil y ordenador.</li><li>No hay publicidad ni se comparte nada con terceros.</li></ul>`}
function openAccount(){if($('#accSheet'))return;fbLoad().catch(()=>{});setTimeout(()=>mountGis(),0);if(typeof sfx==='function')sfx('open');document.body.insertAdjacentHTML('beforeend',`<div class="more-sheet acc-sheet" id="accSheet" role="dialog" aria-modal="true" aria-label="Tu cuenta"><div class="more-panel"><div class="more-grab"></div><p class="eyebrow">Cuenta</p><h2>${ACC.user?'Tu espacio':'Entrar'}</h2><div id="accBody">${accountHTML()}</div></div></div>`);$('#accSheet').addEventListener('click',accClick)}
function closeAccount(){$('#accSheet')?.remove()}
async function accClick(e){if(e.target.id==='accSheet'){closeAccount();return}const a=e.target.closest('[data-acc]')?.dataset.acc;if(a==='in')signIn();else if(a==='out')signOut();else if(a==='guest')useGuest();else if(a==='sync')syncRoutes();const o=e.target.closest('[data-acc-open]');if(o){const id=o.dataset.accOpen;let rec=(await dbOp('readonly',s=>s.get(id)))||recordFromCloud(id,ACC.cloud.get(id));if(rec){closeAccount();enterApp?.('route');restoreRecord(rec)}}const d=e.target.closest('[data-acc-del]');if(d&&confirm('¿Eliminar esta ruta de tu cuenta en la nube? La copia de este dispositivo se mantiene.'))deleteCloud(d.dataset.accDel)}
$('#accountBtn')?.addEventListener('click',e=>{e.stopPropagation();openAccount()});
document.addEventListener('keydown',e=>{if(e.key==='Escape')closeAccount()});

/* ---------- Integración con «Mis rutas» ---------- */
function markCloud(){$$('[data-load-route]').forEach(b=>{const row=b.closest('.saved-route'),h=row?.querySelector('h4');if(h&&!h.querySelector('.cloud-tag')&&ACC.cloud.has(b.dataset.loadRoute))h.insertAdjacentHTML('beforeend',' <span class="cloud-tag" title="Guardada en tu cuenta">☁</span>')})}
const accRefresh=refreshLibrary;refreshLibrary=async function(){await accRefresh();markCloud()};
const accSave=saveRoute;saveRoute=async function(){await accSave();if(ACC.user)syncRoutes()};
$('#saveExpedition')&&($('#saveExpedition').onclick=()=>saveRoute());
document.addEventListener('click',e=>{const b=e.target.closest('[data-delete-route]');if(b&&ACC.user)deleteCloud(b.dataset.deleteRoute)});
$('#routeLibrary h2')?.insertAdjacentHTML('afterend','<p class="acc-hint" id="accHint"></p>');
function hint(){const h=$('#accHint');if(h)h.innerHTML=ACC.user?`☁ Sincronizado con la cuenta de ${esc(ACC.user.displayName||ACC.user.email||'Google')}.`:'Se guardan en este dispositivo. <button class="linkish" type="button" data-open-account>Entra con Google</button> para tenerlas en todos tus dispositivos (opcional).'}
const accRender=renderAccount;renderAccount=function(){accRender();hint()};
document.addEventListener('click',e=>{if(e.target.closest('[data-open-account]'))openAccount()});
globalThis.TMTheme?.addMore(['account','Cuenta','Entrar con Google o usar sin cuenta','<circle cx="12" cy="8" r="4"/><path d="M4 21c1.5-4 4.5-6 8-6s6.5 2 8 6"/>'],openAccount,'home');
renderAccount();
/* Restaura la sesión sin cargar Firebase a quien nunca ha entrado. */
try{if(localStorage.getItem('tm.account')==='google'&&typeof firebaseConfig==='function'&&firebaseConfig())fbLoad().catch(()=>{})}catch{}
globalThis.TMAccount={encodePolyline,thinPoints,cloudRecord,recordFromCloud,open:openAccount,close:closeAccount,sync:syncRoutes,signIn,signOut,useGuest,get user(){return ACC.user},get cloud(){return ACC.cloud},get guest(){return ACC.guest}};

try{if(sessionStorage.getItem('tm.authRedirect')){sessionStorage.removeItem('tm.authRedirect');setTimeout(()=>{document.querySelector('#splashEnter')?.click();setTimeout(()=>globalThis.TMAccount?.open?.(),900)},400)}}catch{}

setTimeout(()=>{try{if(typeof firebaseConfig==='function'&&firebaseConfig())(globalThis.requestIdleCallback||setTimeout)(()=>fbLoad().catch(()=>{}))}catch{}},2500);

/* Botón oficial de Google (Google Identity Services): devuelve el token a esta misma página, sin redirecciones a firebaseapp.com, que en móvil (Safari, apps instaladas) pierden la sesión. Firebase entra después con ese token. */
const GIS_CLIENT='723474843956-rm3ch8lajcftq03njhk13poifkhh70ii.apps.googleusercontent.com';let gisP=null;
function gisLoad(){return gisP||(gisP=new Promise((ok,ko)=>{if(globalThis.google?.accounts?.id)return ok();const sc=document.createElement('script');sc.src='https://accounts.google.com/gsi/client';sc.async=true;sc.onload=()=>ok();sc.onerror=()=>{gisP=null;ko(Error('No se pudo cargar el botón de Google'))};document.head.append(sc)}))}
async function gisCred(r){ACC.busy=true;ACC.status='';renderAccount();try{const {auth,authM}=await fbLoad();await authM.signInWithCredential(auth,authM.GoogleAuthProvider.credential(r.credential));try{localStorage.setItem('tm.account','google')}catch{}ACC.guest=false;if(typeof sfx==='function')sfx('ok')}catch(e){ACC.status=authError(e)}finally{ACC.busy=false;renderAccount()}}
async function mountGis(){const box=$('#gisBtn');if(!box||ACC.user||box.dataset.on)return;box.dataset.on='1';try{await gisLoad();const g=google.accounts.id;if(!mountGis.init){g.initialize({client_id:GIS_CLIENT,callback:gisCred,ux_mode:'popup',auto_select:false,cancel_on_tap_outside:true,use_fedcm_for_button:true,itp_support:true});mountGis.init=1}const w=Math.min(320,Math.max(220,box.parentElement?.clientWidth||280));g.renderButton(box,{type:'standard',theme:'outline',size:'large',text:'continue_with',shape:'pill',locale:'es',width:w});box.closest('#accSheet')?.classList.add('gis-on')}catch(e){box.remove()}}
{const ra=renderAccount;renderAccount=function(){ra.apply(this,arguments);mountGis()}}
