'use strict';
const SECTORS={cain:{name:'Caín',photo:'Caín de Valdeón'},valdeon:{name:'Valdeón',photo:'Valdeón Picos de Europa'},ario:{name:'Trea · Ario · Ostón',photo:'Vega de Ario'},bulnes:{name:'Cuesta Duja · Bulnes',photo:'Bulnes Picos de Europa'}};
/* Cotas, horarios, agua y advertencias tal y como figuran en el artículo; sin grados ni datos añadidos. */
const CANAL_META={
'Moéño':{sector:'cain',profile:[['Caín · puente Grande',480],['Majada de Moéño',1310],['Tiro del Joyo La Llera',2008],['Collado',2119],['Collado Jermoso',2084]],time:'Caín–majada 2–2½ h · majada–Collado Jermoso 2–3 h',hours:[4,5.5],water:['Fuente El Palombar'],warn:['El Canalón: el punto más delicado','Caída frecuente de piedras bajo Torre Peñalba','Hielo Pamparroso (nevero en 2003)'],places:['Caín de Valdeón','Collado Jermoso']},
'Arzón':{sector:'cain',profile:[['Majada de Moéño',1310],['Collada Armellán',1395],['Collada de Arzón',1235],['Caín · puente Grande',480]],time:'Majada de Moéño–Arzón–Caín 2–3 h',hours:[2,3],water:['Fuente de Judarriego'],warn:['Caída frecuente de piedras en el fondo de la canal'],places:['Caín de Valdeón']},
'La Sotín':{sector:'valdeon',profile:[['Refugio Diego Mella',2065],['Vega de La Sotín',1450],['Cordinanes',850]],time:'Sin horario propio en el artículo',hours:null,water:[],warn:['Piedra suelta y sendas poco definidas','Precipicios en el Paso de Alfredo','Talladura vertiginosa de La Rienda'],places:['Collado Jermoso','Cordiñanes']},
'Dobresengos':{sector:'cain',profile:[['Caín · puente Grande',480],['Collado Mabro',700],['Collado El Torno',860],['La Gargantada',1900],['Collada Celada',2403],['Torre de la Palanca',2609]],time:'Caín–La Gargantada 3–4 h (sin la prolongación a la Palanca)',hours:[3,4],water:['Fuente Las Piperas','Arroyo habitualmente seco'],warn:['Sedo Mabro: grieta escalonada poco reconocible','Resaltes si te desvías a la izquierda','Prolongación por alta montaña hasta 2609 m'],trepada:true,places:['Caín de Valdeón','Torre de la Palanca']},
'Ría':{sector:'bulnes',profile:[['Puente La Vieya',330],['Jorcain de Cuebre',1025],['Pasadizo La Riega',820],['Collada del Agua',2141]],time:'Itinerario conjunto puente La Vieya → collada del Agua 6–7 h',hours:[6,7],water:[],warn:['Canal de dificultad seria según los autores','Senda expuesta en la bajada por Cuebre'],serious:true,places:['Culiembro','Refugio Jou de los Cabrones']},
'Del Agua':{sector:'bulnes',profile:[['Pasadizo La Riega',820],['Collada del Agua',2141],['Refugio J. R. Lueje',2070]],time:'Itinerario completo desde puente La Vieya 6–7 h',hours:[6,7],water:['Agua en el cauce (no garantizada)'],warn:['Entrada directa impracticable','Trepada por pared muy inclinada junto a cascadas','Evitar el canalizo izquierdo antes de 2000 m'],trepada:true,places:['Refugio Jou de los Cabrones']},
'Piedra Bellida':{sector:'bulnes',profile:[['Antiguo puente de Trea',440],['Jorcain de Cuebre',1025],['Pasadizo La Riega',820],['Horcado Turonero',940],['Collado Cerredo',1450],['Collado Cima',1385],['Bulnes · Castillo',715],['Puente La Jaya',250]],time:'Senda–Cerredo 5–6 h · Cerredo–Bulnes–La Jaya 2½–3 h',hours:[7.5,9],water:['Fuente Prieta','Cuañegra','Fuente del Tornu'],warn:['Pardo de Cuesta Duja: paso aéreo','Rampa con gravilla resbaladiza al bajar'],places:['Bulnes','Poncebos']},
'Trea':{sector:'ario',profile:[['Puente Bolín',440],['Cuarroble',1025],['Las Cruces de Ario',1580],['Refugio Vega de Ario',1625]],time:'Puente Bolín–refugio de Ario 4–5 h',hours:[4,5],water:['Fuente Cuarroble'],warn:['Paso más delicado tras el collain Huerto de Rey','Al bajar: salir de la canal ~250 m bajo la fuente Cuarroble'],places:['Refugio Vega de Ario','Caín de Valdeón']},
'Culiembro':{sector:'ario',profile:[['Refugio Vega de Ario',1625],['Collado',1662],['Prados de Ostón',1010],['Majada de Culiembro',450]],time:'Ario–Ostón 1½–2 h · Ostón–Culiembro 1½–2 h',hours:[3,4],water:['Fuente Gonzomera'],warn:['Senda tallada en zigzag bajo La Peña'],places:['Refugio Vega de Ario','Culiembro']},
'La Raya o La Viña':{sector:'ario',profile:[['Ostón',1010],['La Viña · Senda del Cares',425]],time:'Ostón–La Raya–La Viña 1½–2 h',hours:[1.5,2],water:['Abrevadero de Valdelafuente'],warn:['La canal directa era impracticable (2003)','Exposición; transitabilidad actual no acreditada'],places:['Culiembro']},
'La Jerrera':{sector:'cain',profile:[['Caín de Abajo',480],['Sedo de Oliseda',1175],['Majada de Oliseda',1450],['Collado Joracao',1829],['Jultayo',1940]],time:'Subida 5–6 h · regreso por Hierbas Altas 3–4 h',hours:[8,10],water:['Fuente de Oliseda','Fuente Cuarroble','Agua La Bersolina'],warn:['Sedo de Oliseda: trepada casi vertical de ~12 m (experiencia en escalada)','Variante por Monero: más larga y, según los autores, más segura'],trepada:true,places:['Caín de Valdeón','Jultayu']},
'Mesones':{sector:'cain',profile:[['Caín de Abajo',480],['Caín de Arriba',620],['Sedo Armao',1080],['Majada de Mesones',1450]],time:'Caín–majada Mesones–Carbanal 4–4½ h',hours:[4,4.5],water:['Fuente El Cuciao','Fuente de Mesones (seca en verano)','Fuente El Frade'],warn:['Sedo Mesones: delicado (barrenado en los 80)','Sedo Armao: escalones y paso estrecho'],places:['Caín de Valdeón']},
'Capozo':{sector:'valdeon',profile:[['Mirador del Tombo',830]],time:'Carbanal–Capozo–El Tombo 2½–3 h',hours:[2.5,3],water:['Joyo del Cabrero','Cueva del Agua','La Farfada'],warn:['Pared corta en la parte alta','Zigzags tallados del Cabido Cimero'],places:['Mirador del Tombo','Cordiñanes']},
'Pambuches':{sector:'valdeon',profile:[['Posada de Valdeón',940],['Collado de Pantivalles',1180],['Collado Pambuches',1880],['Collado',2334],['La Bermeja',2393]],time:'Posada–collado Pambuches–La Bermeja 3–4 h',hours:[3,4],water:['Fuente de Hoyobladas','Pilón de Piergua','Fuente del Hurden'],warn:['Casi 1500 m de desnivel desde Posada'],places:['Posada de Valdeón','Peña Bermeja']},
'Del Perro':{sector:'valdeon',profile:[['La Bermeja',2393],['Cimera del Frade',1800],['Vega Llos',1540],['Soto de Valdeón',945]],time:'La Bermeja–canal del Perro–Vega Llos–Soto 2½–3 h',hours:[2.5,3],water:['Vega Llos: fuente-abrevadero','Manantial de Juan Burón'],warn:['Cresta con cuatro brechas y pasos aéreos (experiencia en escalada)','Alternativa por terreno muy descompuesto','Posible nevero a principios de verano'],trepada:true,places:['Soto de Valdeón','Peña Bermeja']}
};
/* Documentación complementaria con fuente y fecha (revisada en septiembre de 2026 en la versión 5 de la app). */
const CANAL_EXTRA={'Trea':{reviewed:'2026-09-10',sources:[{id:'R1',name:'Refugio Vega de Ario · cómo llegar',url:'https://www.refugiovegadeario.es/como-llegar/'},{id:'R2',name:'Reseña Wikiloc · Caín–Canal de Trea–Vega de Ario (agosto 2026)',url:'https://es.wikiloc.com/rutas-senderismo/28-8-2026-anillo-vindio-etapa-cain-canal-de-trea-refugio-vega-de-ario-283433297'},{id:'R3',name:'Parque Nacional · avisos de acceso (junio 2026)',url:'https://parquenacionalpicoseuropa.es/2026/06/'}],notes:[['Distancia y desnivel según el refugio','Unos 4 km, 1.200 m de desnivel y 3,5 h para el acceso desde el Cares; concentra esos 1.200 m en unos 3 km de canal. Lo describe como moderado, sin pasos técnicos ni aéreos.','R1'],['Recorrido completo desde Caín','Una reseña de agosto de 2026 registra 8,85 km y 1.536 m de ascenso desde Caín y lo clasifica como difícil. Recorridos y criterios distintos al del refugio.','R2'],['Agua citada recientemente','El refugio menciona un manantial a mitad de canal; la reseña cita Fuente El Peyu, Collado Las Cruces y Fuente Las Jallellas. No confirma caudal ni potabilidad el día de tu salida.','R1 · R2'],['Incendio de 2025','El Parque recogió la reapertura del Cares y de canales practicables, incluida Trea, desde el 6 de noviembre de 2025 tras el incendio de ese verano. Comprueba los avisos vigentes antes de salir.','R3']]}};
/* Catálogo de canales de los tres macizos (OpenStreetMap) + fichas documentadas del Cares (Pyrenaica, 2003). */
const CN={items:[],selected:null,filter:'all',query:'',atlas:null,atlasLayer:null,sheetMap:null,status:'',loaded:false};
const PICOS=[43.07,-5.13,43.35,-4.57];
const MASSIF={occidental:['Occidental · Cornión','#1d8ea3'],central:['Central · Urrieles','#2f3a44'],oriental:['Oriental · Ándara','#ff5a1f']};
/* Ríos que separan los macizos (Cares y Duje), puntos aproximados para agrupar. */
const CARES_LINE=[[43.10,-4.955],[43.15,-4.918],[43.214,-4.905],[43.256,-4.829],[43.30,-4.813]],DUJE_LINE=[[43.12,-4.74],[43.166,-4.756],[43.20,-4.75],[43.233,-4.749],[43.25,-4.77],[43.30,-4.813]];
function lonAt(line,lat){if(lat<=line[0][0])return line[0][1];for(let i=1;i<line.length;i++)if(lat<=line[i][0]){const [a,b]=[line[i-1],line[i]],t=(lat-a[0])/(b[0]-a[0]);return a[1]+(b[1]-a[1])*t}return line.at(-1)[1]}
function massifOf(lat,lon){if(lon<lonAt(CARES_LINE,lat))return'occidental';if(lon>lonAt(DUJE_LINE,lat))return'oriental';return'central'}
const norm=s=>String(s||'').toLowerCase().normalize('NFD').replace(/[̀-ͯ]/g,'').replace(/[^a-z0-9]+/g,' ').trim();
const DOC_KEYS={'Moéño':'moeno','Arzón':'arzon','La Sotín':'sotin','Dobresengos':'dobresengos','Ría':'ria','Del Agua':'agua','Piedra Bellida':'piedra bellida','Trea':'trea','Culiembro':'culiembro','La Raya o La Viña':'raya|vina','La Jerrera':'jerrera','Mesones':'mesones','Capozo':'capozo','Pambuches':'pambuches','Del Perro':'perro'};
const docs=(typeof CARES_ROUTES!=='undefined'?CARES_ROUTES:[]).map((r,i)=>({...r,i,...(CANAL_META[r.name]||{profile:[],warn:[],water:[],places:[]})}));
function docFor(name){const n=' '+norm(name)+' ';return docs.find(d=>DOC_KEYS[d.name].split('|').some(k=>n.includes(' '+k+' ')))||null}
const SAC={hiking:'T1',mountain_hiking:'T2',demanding_mountain_hiking:'T3',alpine_hiking:'T4',demanding_alpine_hiking:'T5',difficult_alpine_hiking:'T6'};
const SAC_ORDER=Object.keys(SAC);
const km=(a,b)=>TM.distance(a,b);
const lineKm=l=>l.reduce((s,p,i)=>i?s+km(l[i-1],p):0,0);
/* Une tramos que se tocan en una sola polilínea (el más largo como eje). */
function joinLines(lines){const pool=lines.map(l=>l.slice()).filter(l=>l.length>1).sort((a,b)=>lineKm(b)-lineKm(a));if(!pool.length)return[];let chain=pool.shift(),grown=true;while(grown){grown=false;for(let i=0;i<pool.length;i++){const l=pool[i],h=chain[0],t=chain.at(-1),near=(a,b)=>km(a,b)<.03;if(near(t,l[0]))chain=chain.concat(l.slice(1));else if(near(t,l.at(-1)))chain=chain.concat(l.slice(0,-1).reverse());else if(near(h,l.at(-1)))chain=l.slice(0,-1).concat(chain);else if(near(h,l[0]))chain=l.slice(1).reverse().concat(chain);else continue;pool.splice(i,1);grown=true;break}}return chain}
function resample(line,n=100){if(line.length<=n)return line.map(p=>({...p}));const total=lineKm(line),out=[{...line[0]}];let acc=0,j=1,next=total/(n-1);for(let i=1;i<line.length&&out.length<n-1;i++){const d=km(line[i-1],line[i]);while(acc+d>=next&&out.length<n-1){const t=(next-acc)/d;out.push({lat:line[i-1].lat+(line[i].lat-line[i-1].lat)*t,lon:line[i-1].lon+(line[i].lon-line[i-1].lon)*t});next+=total/(n-1)}acc+=d}out.push({...line.at(-1)});return out}
function overpassQL(){const b=PICOS.join(','),re='"^(Canal|Canalón|Canalon|Canaleta|Canalona|Canalu|Canalín)( |$)",i';return `[out:json][timeout:60];(way["name"~${re}]["waterway"!~"."]["man_made"!~"."]["highway"!~"^(motorway|trunk|primary|secondary|tertiary|residential|unclassified)$"](${b});relation["name"~${re}]["waterway"!~"."](${b});node["name"~${re}]["natural"](${b}););out tags geom qt;`}
async function overpass(ql,ms=60000){const c=new AbortController(),t=setTimeout(()=>c.abort(),ms);try{const r=await fetch('https://overpass-api.de/api/interpreter',{method:'POST',body:new URLSearchParams({data:ql}),signal:c.signal});if(!r.ok)throw Error('OpenStreetMap ocupado ('+r.status+')');const d=await r.json();if(!Array.isArray(d.elements))throw Error('Respuesta incompleta');return d.elements}catch(e){if(c.signal.aborted)throw Error('OpenStreetMap tardó demasiado');throw e}finally{clearTimeout(t)}}
function buildCatalog(elements){const groups=new Map();for(const e of elements){const name=e.tags?.name;if(!name||e.tags.waterway||e.tags.man_made||/^(motorway|trunk|primary|secondary|tertiary|residential|unclassified)$/.test(e.tags.highway||''))continue;const key=norm(name);if(!groups.has(key))groups.set(key,{key,names:{},lines:[],points:[],tags:{},refs:[]});const g=groups.get(key);g.names[name]=(g.names[name]||0)+1;g.refs.push(e.type+'/'+e.id);Object.assign(g.tags,e.tags);if(e.type==='way'&&e.geometry?.length>1)g.lines.push(e.geometry.map(p=>({lat:+p.lat.toFixed(5),lon:+p.lon.toFixed(5)})));else if(e.type==='relation'){for(const m of e.members||[])if(m.geometry?.length>1)g.lines.push(m.geometry.map(p=>({lat:+p.lat.toFixed(5),lon:+p.lon.toFixed(5)})))}else if(e.type==='node'&&finite(e.lat))g.points.push({lat:+e.lat.toFixed(5),lon:+e.lon.toFixed(5)});const sac=e.tags?.sac_scale;if(sac&&SAC[sac]&&(!g.sac||SAC_ORDER.indexOf(sac)>SAC_ORDER.indexOf(g.sac)))g.sac=sac}
 const items=[...groups.values()].map(g=>{const all=[...g.lines.flat(),...g.points];if(!all.length)return null;const c={lat:all.reduce((s,p)=>s+p.lat,0)/all.length,lon:all.reduce((s,p)=>s+p.lon,0)/all.length};const name=Object.entries(g.names).sort((a,b)=>b[1]-a[1])[0][0];const doc=docFor(name);return{id:'osm-'+g.key.replace(/ /g,'-'),name,lines:g.lines,points:g.points,center:c,massif:massifOf(c.lat,c.lon),lengthKm:g.lines.reduce((s,l)=>s+lineKm(l),0),sac:g.sac||null,refs:g.refs.slice(0,20),natural:g.tags.natural||null,doc:doc?doc.i:null}}).filter(Boolean);
 for(const d of docs)if(!items.some(x=>x.doc===d.i))items.push({id:'doc-'+d.i,name:'Canal de '+d.name,lines:[],points:[],center:null,massif:['Moéño','Arzón','La Sotín','Dobresengos','Ría','Del Agua','Piedra Bellida'].includes(d.name)?'central':'occidental',lengthKm:0,sac:null,refs:[],doc:d.i,docOnly:true});
 const mi={occidental:0,central:1,oriental:2};return items.sort((a,b)=>mi[a.massif]-mi[b.massif]||a.name.localeCompare(b.name,'es'))}
function loadCached(){try{const c=JSON.parse(localStorage.getItem('tm.canales.v1'));if(c&&Date.now()-c.at<14*86400000&&Array.isArray(c.items))return c}catch{}return null}
async function loadCatalog(force=false){const cached=!force&&loadCached();if(cached){CN.items=cached.items;CN.status=`${CN.items.length} canales · OpenStreetMap ${new Date(cached.at).toLocaleDateString('es-ES')}`;renderCatalog();return}CN.status='Descargando canales de OpenStreetMap…';CN.items=buildCatalog([]);renderCatalog();try{const els=await overpass(overpassQL());CN.items=buildCatalog(els);try{localStorage.setItem('tm.canales.v1',JSON.stringify({at:Date.now(),items:CN.items}))}catch{}CN.status=`${CN.items.filter(x=>!x.docOnly).length} canales cartografiadas en OpenStreetMap · ${docs.length} con ficha documentada`}catch(e){CN.status='No se pudo descargar el catálogo ('+e.message+'). Se muestran las fichas documentadas del Cares.'}renderCatalog()}

/* ---------- Mapas ---------- */
const IGN_MTN='https://www.ign.es/wmts/mapa-raster?SERVICE=WMTS&REQUEST=GetTile&VERSION=1.0.0&LAYER=MTN&STYLE=default&TILEMATRIXSET=GoogleMapsCompatible&FORMAT=image/jpeg&TILEMATRIX={z}&TILEROW={y}&TILECOL={x}';
const IGN_PNOA='https://www.ign.es/wmts/pnoa-ma?SERVICE=WMTS&REQUEST=GetTile&VERSION=1.0.0&LAYER=OI.OrthoimageCoverage&STYLE=default&TILEMATRIXSET=GoogleMapsCompatible&FORMAT=image/jpeg&TILEMATRIX={z}&TILEROW={y}&TILECOL={x}';
function baseLayers(){return{topo:L.tileLayer(IGN_MTN,{maxZoom:19,maxNativeZoom:17,attribution:'Mapa topográfico © IGN'}),orto:L.tileLayer(IGN_PNOA,{maxZoom:19,attribution:'Ortofoto © IGN · PNOA'}),osm:L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'© OpenStreetMap contributors'}),otm:L.tileLayer('https://{s}.tile.opentopomap.org/{z}/{x}/{y}.png',{maxZoom:19,maxNativeZoom:17,subdomains:'abc',attribution:'© OpenTopoMap (CC-BY-SA) · © OpenStreetMap'})}}
function layerSwitch(map,host){const layers=baseLayers();let cur=layers.topo.addTo(map);let fails=0;layers.topo.on('tileerror',()=>{if(++fails===6&&cur===layers.topo){cur.remove();cur=layers.osm.addTo(map);host.querySelector('[data-layer=osm]')?.click()}});host.insertAdjacentHTML('beforeend','<div class="map-layers" role="group" aria-label="Mapa base"><button type="button" data-layer="topo" aria-pressed="true">IGN</button><button type="button" data-layer="orto" aria-pressed="false">Orto</button><button type="button" data-layer="otm" aria-pressed="false">Topo</button><button type="button" data-layer="osm" aria-pressed="false">OSM</button><button type="button" data-overlay="trails" aria-pressed="false" title="Senderos señalizados (Waymarked Trails)">PR·GR</button></div>');let trails=null;host.querySelector('.map-layers').addEventListener('click',e=>{const o=e.target.closest('[data-overlay]');if(o){e.stopPropagation();if(trails){trails.remove();trails=null}else trails=L.tileLayer('https://tile.waymarkedtrails.org/hiking/{z}/{x}/{y}.png',{maxZoom:19,maxNativeZoom:18,opacity:.85,attribution:'Senderos © Waymarked Trails · OSM'}).addTo(map);o.setAttribute('aria-pressed',String(!!trails));return}const b=e.target.closest('[data-layer]');if(!b)return;e.stopPropagation();cur.remove();cur=layers[b.dataset.layer].addTo(map);cur.bringToBack();host.querySelectorAll('[data-layer]').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));trails?.bringToFront()});L.DomEvent.disableClickPropagation(host.querySelector('.map-layers'))}

/* ---------- Vista de catálogo ---------- */
$('#canalesApp').insertAdjacentHTML('afterbegin',`<section id="canalesVisual"><div class="cn-hero"><div class="cn-hero-photo" id="cnHeroPhoto"></div><div><p class="eyebrow">Picos de Europa · tres macizos</p><h2>Todas las <em>canales</em></h2><p>Trazado exacto sobre el mapa topográfico del IGN, perfil real, accesos, enlaces con otras sendas y canales, agua, sol dentro de la canal y la previsión del día. Datos de OpenStreetMap y fichas documentadas.</p></div></div>
<div class="cn-kpis" id="cnKpis"></div><div class="cn-atlas"><div class="map" id="cnAtlas" aria-label="Mapa de canales de Picos de Europa"></div></div><p class="cn-status" id="cnStatus"></p>
<input id="cnSearch" class="cn-search" type="search" placeholder="Buscar canal, majada, collado…" aria-label="Buscar canal"><div class="cn-filters" role="toolbar" aria-label="Filtros">${[['all','Todas'],...Object.entries(MASSIF).map(([k,[l]])=>[k,l]),['doc','Con ficha 2003'],['sac','Con dificultad OSM']].map(([k,l])=>`<button type="button" data-cn-filter="${k}" aria-pressed="${k==='all'}">${esc(l)}</button>`).join('')}<button type="button" id="cnReload" class="quiet">↻ Actualizar</button></div>
<div class="cn-list" id="cnList"></div><p class="footnote">Trazados © OpenStreetMap contributors (ODbL). La agrupación por macizo usa los ríos Cares y Duje de forma aproximada. Lo que no está cartografiado en OpenStreetMap no aparece con mapa: puedes añadirlo en openstreetmap.org y se verá aquí.</p></section>`);
function filtered(){const q=norm(CN.query);return CN.items.filter(c=>{if(MASSIF[CN.filter]&&c.massif!==CN.filter)return false;if(CN.filter==='doc'&&c.doc==null)return false;if(CN.filter==='sac'&&!c.sac)return false;if(q){const d=c.doc!=null?docs[c.doc]:null,hay=norm(c.name+' '+(d?d.connection+' '+d.profile.map(p=>p[0]).join(' '):''));return q.split(' ').every(w=>hay.includes(w))}return true})}
function renderCatalog(){if(!$('#cnList'))return;const list=filtered();$('#cnStatus').textContent=CN.status;const by=k=>CN.items.filter(c=>c.massif===k&&!c.docOnly).length;$('#cnKpis').innerHTML=`<div><span>Canales</span><strong>${CN.items.length}</strong></div>${Object.entries(MASSIF).map(([k,[l]])=>`<div><span>${l.split(' · ')[0]}</span><strong>${by(k)}</strong></div>`).join('')}`;
 $('#cnList').innerHTML=list.length?list.map((c,k)=>`<button type="button" class="cn-item" data-canal="${esc(c.id)}" style="animation-delay:${Math.min(k,20)*30}ms"><h3>${esc(c.name)}</h3><small>${esc(MASSIF[c.massif][0])}${c.lengthKm?` · ${fmt(c.lengthKm,1)} km cartografiados`:c.docOnly?' · sin trazado en OSM':' · punto'}</small><span class="cn-badges" style="grid-column:1">${c.sac?`<span class="cn-badge warn">${SAC[c.sac]} OSM</span>`:''}${c.doc!=null?'<span class="cn-badge doc">Ficha 2003</span>':''}${c.doc!=null&&docs[c.doc].hours?`<span class="cn-badge time">${String(docs[c.doc].hours[0]).replace('.',',')}–${String(docs[c.doc].hours[1]).replace('.',',')} h</span>`:''}</span><svg class="cn-mini" viewBox="0 0 84 34" aria-hidden="true">${miniPath(c)}</svg></button>`).join(''):'<p class="muted">Ninguna canal coincide.</p>';drawAtlas()}
function miniPath(c){const line=c.lines.length?joinLines(c.lines):[];if(line.length<2)return'';const xs=line.map(p=>p.lon),ys=line.map(p=>p.lat),x0=Math.min(...xs),x1=Math.max(...xs),y0=Math.min(...ys),y1=Math.max(...ys),s=Math.max(x1-x0,(y1-y0)*1.37,1e-6);return `<path d="${line.map((p,i)=>`${i?'L':'M'}${(4+(p.lon-x0)/s*76).toFixed(1)},${(30-(p.lat-y0)*1.37/s*26).toFixed(1)}`).join(' ')}"/>`}
function ensureAtlas(){if(CN.atlas||!window.L||$('#cnAtlas')?.offsetParent===null)return;CN.atlas=L.map('cnAtlas',{maxZoom:18,scrollWheelZoom:false}).fitBounds([[PICOS[0]+.05,PICOS[1]+.05],[PICOS[2]-.04,PICOS[3]-.05]]);layerSwitch(CN.atlas,$('#cnAtlas').parentElement);drawAtlas()}
function drawAtlas(){if(!CN.atlas)return;CN.atlasLayer?.remove();const layers=[];for(const c of filtered()){const col=MASSIF[c.massif][1],pop=`<b>${esc(c.name)}</b><br>${esc(MASSIF[c.massif][0])}<br><button type="button" class="quiet" data-canal="${esc(c.id)}" style="min-height:32px;margin-top:6px">Abrir ficha</button>`;for(const l of c.lines){const pl=L.polyline(l.map(p=>[p.lat,p.lon]),{color:col,weight:4,opacity:.9}).bindPopup(pop);layers.push(L.polyline(l.map(p=>[p.lat,p.lon]),{color:'#fff',weight:9,opacity:.6,interactive:false}),pl)}for(const p of c.points)layers.push(L.circleMarker([p.lat,p.lon],{radius:6,color:'#fff',weight:2,fillColor:col,fillOpacity:1}).bindPopup(pop))}CN.atlasLayer=L.featureGroup(layers).addTo(CN.atlas)}
$('#cnSearch').oninput=e=>{CN.query=e.target.value;renderCatalog()};
$('#canalesVisual').addEventListener('click',e=>{const f=e.target.closest('[data-cn-filter]');if(f){CN.filter=f.dataset.cnFilter;$$('[data-cn-filter]').forEach(x=>x.setAttribute('aria-pressed',String(x===f)));renderCatalog()}if(e.target.closest('#cnReload'))loadCatalog(true)});
document.addEventListener('click',e=>{const b=e.target.closest('[data-canal]');if(b){e.preventDefault();openCanal(b.dataset.canal)}});

/* ---------- Ficha ---------- */
function docProfileSVG(c){const p=c.profile.filter(x=>finite(x[1]));if(p.length<2)return'';const w=760,h=280,lo=Math.min(...p.map(x=>x[1]))-80,hi=Math.max(...p.map(x=>x[1]))+80,X=i=>70+i/(p.length-1)*(w-140),Y=v=>h-60-(v-lo)/(hi-lo)*(h-110);const d=p.map((x,i)=>`${i?'L':'M'}${X(i).toFixed(1)},${Y(x[1]).toFixed(1)}`).join(' ');return `<svg class="cn-profile" viewBox="0 0 ${w} ${h}" role="img" aria-label="Cotas citadas en el artículo"><path class="line" d="${d}"/>${p.map((x,i)=>`<circle cx="${X(i)}" cy="${Y(x[1])}" r="5"/><text x="${X(i)}" y="${Y(x[1])-12}" text-anchor="middle">${fmt(x[1])}</text><text class="lbl" x="${X(i)}" y="${h-30+(i%2)*18}" text-anchor="middle">${esc(x[0].length>22?x[0].slice(0,21)+'…':x[0])}</text>`).join('')}</svg>`}
function realProfileSVG(prof){const w=760,h=240,lo=Math.min(...prof.map(p=>p.ele)),hi=Math.max(...prof.map(p=>p.ele)),tot=prof.at(-1).d,X=d=>50+d/tot*(w-80),Y=e=>h-40-(e-lo)/Math.max(1,hi-lo)*(h-80);const d=prof.map((p,i)=>`${i?'L':'M'}${X(p.d).toFixed(1)},${Y(p.ele).toFixed(1)}`).join(' ');return `<svg class="cn-profile" viewBox="0 0 ${w} ${h}" role="img" aria-label="Perfil real de ${fmt(lo)} a ${fmt(hi)} m"><defs><linearGradient id="cnGrad2" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stop-color="#1d8ea3" stop-opacity=".35"/><stop offset="1" stop-color="#2f3a44" stop-opacity="0"/></linearGradient></defs><path class="area" d="${d} L${X(tot)},${h-40} L${X(0)},${h-40} Z"/><path class="line" d="${d}"/><text x="50" y="${h-12}">0 km</text><text x="${w-30}" y="${h-12}" text-anchor="end">${fmt(tot,2)} km</text><text x="50" y="22">${fmt(hi)} m</text><text x="50" y="${h-50}" class="lbl">${fmt(lo)} m</text></svg>`}
async function profileOf(line){const pts=resample(line,100),z=await TMRelief.elevations(pts);let d=0;const prof=pts.map((p,i)=>{if(i)d+=km(pts[i-1],p);return{...p,ele:z[i],d}}).filter(p=>finite(p.ele));if(prof.length<2)return null;if(prof[0].ele>prof.at(-1).ele){const tot=prof.at(-1).d;prof.reverse().forEach(p=>p.d=tot-p.d)}let up=0,down=0,maxSlope=0;for(let i=1;i<prof.length;i++){const dz=prof[i].ele-prof[i-1].ele;dz>0?up+=dz:down-=dz}for(let i=0;i<prof.length;i++){let j=i;while(j<prof.length-1&&prof[j].d-prof[i].d<.2)j++;const dd=(prof[j].d-prof[i].d)*1000;if(dd>=150)maxSlope=Math.max(maxSlope,Math.abs(prof[j].ele-prof[i].ele)/dd*100)}return{prof,up,down,lo:prof[0].ele,hi:Math.max(...prof.map(p=>p.ele)),maxSlope}}
function contextQL(b){const p=b.map((v,i)=>v+(i<2?-.012:.012)),q=b.map((v,i)=>v+(i<2?-.045:.045)),bb=p.map(v=>v.toFixed(4)).join(','),bq=q.map(v=>v.toFixed(4)).join(',');return `[out:json][timeout:40];(way["highway"~"^(path|footway|track|steps|bridleway)$"](${bb});node["natural"~"^(saddle|peak|spring)$"](${bb});nwr["tourism"~"^(alpine_hut|wilderness_hut)$"](${bb});nwr["amenity"~"^(drinking_water|shelter)$"](${bb});node["place"~"^(village|hamlet|locality|isolated_dwelling)$"](${bq});nwr["amenity"="parking"](${bq}););out tags geom center qt;`}
function bboxOf(pts){return[Math.min(...pts.map(p=>p.lat)),Math.min(...pts.map(p=>p.lon)),Math.max(...pts.map(p=>p.lat)),Math.max(...pts.map(p=>p.lon))]}
function densify(l,step){const out=[l[0]];for(let i=1;i<l.length;i++){const d=km(l[i-1],l[i]),n=Math.min(60,Math.ceil(d/step));for(let k=1;k<=n;k++)out.push({lat:l[i-1].lat+(l[i].lat-l[i-1].lat)*k/n,lon:l[i-1].lon+(l[i].lon-l[i-1].lon)*k/n})}return out}
function minDist(a,set){let best=Infinity;const c=Math.cos(a.lat*Math.PI/180);for(const p of set){const dx=(p.lon-a.lon)*c,dy=p.lat-a.lat,d=dx*dx+dy*dy;if(d<best)best=d}return Math.sqrt(best)*111.2}
const FEAT_LABEL=t=>t.natural==='saddle'?'collado':t.natural==='peak'?'cumbre':t.natural==='spring'?'fuente':t.tourism==='alpine_hut'?'refugio':t.tourism==='wilderness_hut'?'refugio libre':t.amenity==='parking'?'aparcamiento':t.amenity==='shelter'?'abrigo':t.amenity==='drinking_water'?'agua':t.place?'pueblo / lugar':'';
function accessInfo(c,chain,els){const pos=e=>finite(e.lat)?{lat:e.lat,lon:e.lon}:e.center?{lat:e.center.lat,lon:e.center.lon}:e.geometry?.[0]?{lat:e.geometry[0].lat,lon:e.geometry[0].lon}:null;const own=new Set(c.refs);const feats=els.filter(e=>e.tags&&!e.tags.highway).map(e=>({...e,p:pos(e),label:FEAT_LABEL(e.tags)})).filter(e=>e.p&&e.label);const ends=[chain[0],chain.at(-1)];
 const endInfo=end=>{const named=feats.filter(f=>f.tags.name&&!['parking','drinking_water'].includes(f.tags.amenity)).map(f=>({f,d:km(end,f.p)})).filter(x=>x.d<1.4).sort((a,b)=>a.d-b.d).slice(0,3);const park=feats.filter(f=>f.tags.amenity==='parking').map(f=>({f,d:km(end,f.p)})).sort((a,b)=>a.d-b.d)[0];const town=feats.filter(f=>f.tags.place&&['village','hamlet'].includes(f.tags.place)&&f.tags.name).map(f=>({f,d:km(end,f.p)})).sort((a,b)=>a.d-b.d)[0];return{named,park,town}};
 const chainK=chain.map((p,i)=>({...p,segment:0,up:0,km:0}));for(let i=1;i<chainK.length;i++)chainK[i].km=chainK[i-1].km+km(chainK[i-1],chainK[i]);const paths=els.filter(e=>e.type==='way'&&e.tags?.highway&&!own.has('way/'+e.id)&&e.geometry?.length>1).map(e=>{const g=densify(e.geometry.map(p=>({lat:p.lat,lon:p.lon})),.015);let best=Infinity,at=null;for(const p of g){const d=minDist(p,chain);if(d<best){best=d;at=p}}return{e,best,at}}).filter(x=>x.best<.025).map(x=>{const q=Expedition.locate(chainK,x.at);return{name:x.e.tags.name||null,sac:x.e.tags.sac_scale||null,hw:x.e.tags.highway,id:x.e.id,km:q?.km??null,trail:x.e.tags.trail_visibility||null}}).sort((a,b)=>(a.km??0)-(b.km??0));
 const springs=feats.filter(f=>['spring','drinking_water'].includes(f.tags.natural||f.tags.amenity)&&minDist(f.p,chain)<.2);
 const links=CN.items.filter(o=>o.id!==c.id&&o.lines.length).filter(o=>o.lines.some(l=>l.some(p=>minDist(p,chain)<.15)));return{bottom:endInfo(ends[0]),top:endInfo(ends[1]),paths,springs,links}}
function endHTML(label,info,end){const near=info.named.map(x=>`${esc(x.f.tags.name)} (${x.f.label}, ${fmt(x.d*1000)} m)`).join(' · ');return `<div class="access-row"><span class="k">${label}</span><div><b>${end?`${end.lat.toFixed(5)}, ${end.lon.toFixed(5)}`:''}</b>${finite(end?.ele)?` · ${fmt(end.ele)} m`:''}<br>${near||'<span class="muted">Sin lugares con nombre cartografiados a menos de 1,4 km.</span>'}${info.town?`<br><small class="muted">Pueblo más cercano: ${esc(info.town.f.tags.name)} a ${fmt(info.town.d,1)} km en línea recta</small>`:''}${info.park?`<br><small class="muted">Aparcamiento cartografiado más cercano: ${esc(info.park.f.tags.name||'sin nombre')} a ${fmt(info.park.d,1)} km en línea recta</small>`:''}</div></div>`}
async function openCanal(id){const c=CN.items.find(x=>x.id===id);if(!c)return;CN.selected=c;closeCanal(true);const d=c.doc!=null?docs[c.doc]:null,extra=d?CANAL_EXTRA[d.name]:null,chain=c.lines.length?joinLines(c.lines):[];c.chain=chain;if(typeof sfx==='function')sfx('open');
 document.body.insertAdjacentHTML('beforeend',`<div class="cn-detail" id="cnDetail" role="dialog" aria-modal="true" aria-labelledby="cnTitle"><div class="cn-sheet"><div class="cn-sheet-hero"><div class="map" id="cnSheetMap"></div><button class="quiet cn-close" type="button" id="cnClose" aria-label="Cerrar ficha">✕</button></div><div class="cn-sheet-body"><p class="eyebrow">${esc(MASSIF[c.massif][0])}${c.sac?' · '+SAC[c.sac]+' en OpenStreetMap':''}</p><h2 id="cnTitle">${esc(c.name)}</h2>${d?`<p class="muted">${esc(d.connection)}</p>`:''}
 <div class="cn-actions">${chain.length?'<button class="primary" type="button" id="cnPlan">Planificar esta canal</button><button class="quiet" type="button" id="cnFly">◭ Vuelo 3D</button>':''}<button class="quiet" type="button" id="cnWikiloc">Tracks en Wikiloc</button><button class="quiet" type="button" id="cnAsk">✦ Estado actual con IA</button></div>
 <div class="cn-kpis" id="cnStats">${chain.length?'<div><span>Perfil</span><strong><span class="spinner"></span></strong></div>':'<div><span>Trazado</span><strong>—</strong></div>'}</div><div id="cnProfile"></div>
 ${chain.length?'<h3>Accesos, salidas y enlaces</h3><div class="access" id="cnAccess"><p class="muted"><span class="spinner"></span>Leyendo caminos, collados y aparcamientos del entorno…</p></div>':`<p class="muted">Esta canal no está cartografiada como trazado en OpenStreetMap. Se muestra la ficha documentada.</p>`}
 <h3>Senderos y tracks</h3><div id="cnSources"></div>
 ${chain.length?'<div id="cnSlopeLegend"></div>':''}
 ${chain.length?`<h3>Sol dentro de la canal</h3><div class="route-settings"><label>Día<input type="date" id="cnSunDay"></label></div><div id="cnSun" class="muted">Calculando con el relieve…</div>`:''}
 <h3>Previsión en la canal</h3><div id="cnWx" class="muted">Consultando…</div>${chain.length?'<h3>Nieve en la canal</h3><div id="cnSnow" class="muted"><span class="spinner"></span>Consultando nieve en la parte alta…</div>':''}
 ${d?`<h3>Ficha documentada · Pyrenaica 2003</h3>${docProfileSVG(d)}${d.warn.length?`<div class="cn-badges" style="margin:10px 0">${d.warn.map(w=>`<span class="cn-badge warn">⚠ ${esc(w)}</span>`).join('')}</div>`:''}${d.water.length?`<div class="cn-badges">${d.water.map(w=>`<span class="cn-badge water">💧 ${esc(w)}</span>`).join('')}</div>`:''}<p class="muted">${esc(d.time)}</p><ol class="cn-steps">${d.sections.map(([t,x],k)=>`<li data-n="${k+1}"><h4>${esc(t)}</h4><p>${esc(x)}</p></li>`).join('')}</ol>`:''}
 ${extra?`<h3>Documentación complementaria</h3><ol class="cn-steps">${extra.notes.map(([t,x,s],k)=>`<li data-n="${String.fromCharCode(65+k)}"><h4>${esc(t)}</h4><p>${esc(x)} <small class="muted">[${esc(s)}]</small></p></li>`).join('')}</ol>`:''}
 <div class="cn-ai" id="cnAI" hidden></div><h3>Fuentes</h3><div class="cn-links">${linksFor(c,d,extra)}</div><p class="footnote">Trazado y caminos © OpenStreetMap contributors (ODbL) · mapa © IGN · perfil: MDT Copernicus 90 m (Open-Meteo). ${d?`Ficha: ${esc(CARES_SOURCE.authors)} (2003), «${esc(CARES_SOURCE.title)}», ${esc(CARES_SOURCE.publication)}; describe lo publicado entonces.`:''} Comprueba siempre avisos del Parque y de AEMET.</p></div></div></div>`);
 const close=()=>closeCanal();$('#cnClose').onclick=close;$('#cnDetail').onclick=e=>{if(e.target.id==='cnDetail')close()};document.addEventListener('keydown',canalKey);
 setTimeout(()=>sheetMap(c,chain),60);globalThis.TMTrails?.canalSources(c);
 const center=c.center||(d?.places?.length?null:S.location);
 $('#cnWikiloc').onclick=()=>{closeCanal();showTab('route');const q=c.name+' Picos de Europa';if($('#wlQuery')){$('#wlQuery').value=q;TMWikiloc.search(q);$('#routeFinder')?.scrollIntoView({behavior:'smooth'})}};
 $('#cnAsk').onclick=async()=>{const out=$('#cnAI');out.hidden=false;out.innerHTML='<p><span class="spinner"></span>Buscando reseñas recientes y avisos…</p>';const res=await globalThis.Copilot?.ask(`Investiga el estado actual de la ${c.name} (Picos de Europa, macizo ${MASSIF[c.massif][0]}): accesos, cierres del Parque, desprendimientos, nieve, agua y reseñas recientes con fecha. Resume en 5 líneas y cita fuentes.`,{research:c.name+' Picos de Europa',label:'Estado actual: '+c.name});out.innerHTML=res?`<p class="eyebrow">Investigación IA</p>${Copilot.md(res.text)}${res.sources?.length?'<div class="cp-sources">'+res.sources.slice(0,8).map(s=>{const h=safeLink(s.url);return h?`<a href="${esc(h)}" target="_blank" rel="noopener">↗ ${esc(String(s.title).slice(0,48))}</a>`:''}).join('')+'</div>':''}`:'<p class="muted">No se completó la investigación.</p>'};
 if(chain.length){$('#cnPlan').onclick=async()=>{const pts=c.profile?.prof||resample(chain,300);await importRoute(new File([TMWikiloc.buildGPX(c.name,pts)],'canal.gpx',{type:'application/gpx+xml'}));closeCanal();showTab('route')};$('#cnFly').onclick=()=>TMFly.open({name:c.name,points:(c.profile?.prof||resample(chain,200)).map(p=>({...p,km:p.d}))});
  const day=new Date();day.setDate(day.getDate()+1);$('#cnSunDay').value=localInput(day).slice(0,10);$('#cnSunDay').onchange=()=>sunInCanal(c,chain);
  profileOf(chain).then(pr=>{if(CN.selected!==c)return;c.profile=pr;if(!pr){$('#cnStats').innerHTML='<div><span>Perfil</span><strong>—</strong></div>';return}const tot=pr.prof.at(-1).d;$('#cnStats').innerHTML=`<div><span>Longitud</span><strong>${fmt(tot,2)} km</strong></div><div><span>Cota baja → alta</span><strong>${fmt(pr.lo)}→${fmt(pr.hi)}</strong></div><div><span>Desnivel +</span><strong>${fmt(pr.up)} m</strong></div><div><span>Pendiente máx.</span><strong>${fmt(pr.maxSlope)} %</strong></div>`;$('#cnProfile').innerHTML=realProfileSVG(pr.prof);sunInCanal(c,chain);cnWeather(c,pr);if(CN.sheetMap&&globalThis.TMTrails){TMTrails.drawSlope(CN.sheetMap,pr.prof)}if($('#cnSlopeLegend')&&globalThis.TMTrails)$('#cnSlopeLegend').innerHTML='<p class="eyebrow" style="margin:14px 0 6px">Pendiente en el mapa</p>'+legendSlope();cnSnow(c,pr)}).catch(()=>{$('#cnStats').innerHTML='<div><span>Perfil</span><strong>—</strong></div>'});
  overpass(contextQL(bboxOf(chain)),45000).then(els=>{if(CN.selected!==c)return;const a=accessInfo(c,chain,els);c.access=a;const b=c.profile?.prof?.[0],t=c.profile?.prof?.at(-1);$('#cnAccess').innerHTML=endHTML('Entrada · abajo',a.bottom,b||chain[0])+endHTML('Salida · arriba',a.top,t||chain.at(-1))+`<div class="access-row"><span class="k">Enlaces</span><div>${a.paths.length?a.paths.filter(p=>p.name||p.sac).slice(0,10).map(p=>`${p.km!=null?`km ${fmt(p.km,1)}: `:''}<a href="https://www.openstreetmap.org/way/${p.id}" target="_blank" rel="noopener">${esc(p.name||'sendero sin nombre')}</a>${p.sac?` · ${SAC[p.sac]||p.sac}`:''}${p.trail?` · visibilidad ${esc(p.trail)}`:''}`).join('<br>')+(a.paths.filter(p=>!p.name&&!p.sac).length?`<br><small class="muted">+${a.paths.filter(p=>!p.name&&!p.sac).length} sendas sin nombre que tocan la canal</small>`:''):'<span class="muted">Ningún otro camino cartografiado toca la canal.</span>'}</div></div><div class="access-row"><span class="k">Otras canales</span><div>${a.links.length?a.links.map(o=>`<a href="#" data-canal="${esc(o.id)}">${esc(o.name)}</a>`).join(' · '):'<span class="muted">No enlaza con otras canales cartografiadas.</span>'}</div></div><div class="access-row"><span class="k">Agua</span><div>${a.springs.length?a.springs.map(s=>esc(s.tags.name||FEAT_LABEL(s.tags))).join(' · ')+' <small class="muted">(cartografiada; no garantiza caudal)</small>':'<span class="muted">Sin fuentes cartografiadas junto a la canal.</span>'}</div></div>`;drawAccessOnMap(a)}).catch(e=>{if($('#cnAccess'))$('#cnAccess').innerHTML=`<p class="muted">No se pudieron leer los accesos (${esc(e.message)}).</p>`})}
 else cnWeather(c,null)}
async function sunInCanal(c,chain){const out=$('#cnSun');if(!out)return;const pr=c.profile?.prof||resample(chain,30);const pick=[pr[0],pr[Math.floor(pr.length/2)],pr.at(-1)];const day=new Date(($('#cnSunDay')?.value||'')+'T12:00').getTime();if(!finite(day))return;out.innerHTML='<span class="spinner"></span>Calculando sombras del relieve…';try{const info=await TMRelief.analyze(pick);if(CN.selected!==c)return;const names=['Parte baja','Mitad','Parte alta'];out.innerHTML=`<div class="shade-list">${pick.map((p,i)=>{const s=TMRelief.sunHours(info[i],p,day);return `<div class="shade-row"><span class="k">${names[i]}</span><span class="sun-dot ${s.minutes?'sun':'shade'}">${s.minutes?'☀':'◐'}</span><span>${s.minutes?s.spans.map(([a,b])=>`${fTimeC(a)}–${fTimeC(b)}`).join(' · '):'Sin sol directo ese día'}<br><small class="muted">${fmt(s.minutes/60,1)} h de sol · orientada al ${finite(info[i].aspect)?FieldCore.cardinal(info[i].aspect):'—'} · pendiente ${fmt(info[i].slope)}°</small></span><span>${!s.minutes||s.minutes<120?'<span class="tag ice">umbría</span>':s.minutes>360?'<span class="tag heat">solana</span>':''}</span></div>`}).join('')}</div><p class="footnote">Sol directo calculado con el horizonte del relieve (MDT 90 m). Las paredes estrechas de una canal pueden dar más sombra de la calculada.</p>`}catch(e){out.textContent='No se pudo calcular: '+e.message}}
const fTimeC=t=>new Date(t).toLocaleTimeString('es-ES',{hour:'2-digit',minute:'2-digit'});
async function cnWeather(c,pr){const out=$('#cnWx');if(!out)return;const p=pr?pr.prof[Math.floor(pr.prof.length/2)]:(c.center||S.location);if(!p){out.textContent='Sin posición para consultar.';return}try{const d=await json(forecastURL(p.lat.toFixed(4),p.lon.toFixed(4),{...(pr?{elevation:String(Math.round(p.ele))}:{}),forecast_days:'5'}));if(CN.selected!==c)return;const dl=d.daily||{};out.innerHTML=`<div class="tablewrap"><table><thead><tr><th>Día</th><th>Mín/máx</th><th>Lluvia</th><th>Racha</th></tr></thead><tbody>${(dl.time||[]).slice(0,5).map((t,i)=>`<tr><td>${new Date(t*1000).toLocaleDateString('es-ES',{weekday:'short',day:'numeric'})}</td><td>${fmt(dl.temperature_2m_min?.[i])} / ${fmt(dl.temperature_2m_max?.[i])} °C</td><td>${fmt(dl.precipitation_sum?.[i],1)} mm</td><td>${fmt(dl.wind_gusts_10m_max?.[i])} km/h</td></tr>`).join('')}</tbody></table></div><p class="footnote">Open-Meteo${pr?` a ${fmt(p.ele)} m, mitad de la canal`:''}.</p>`}catch(e){out.textContent='Previsión no disponible: '+e.message}}
function sheetMap(c,chain){if(!window.L||!$('#cnSheetMap'))return;CN.sheetMap=L.map('cnSheetMap',{maxZoom:18,zoomControl:true});layerSwitch(CN.sheetMap,$('#cnSheetMap').parentElement);const items=[];for(const l of c.lines){items.push(L.polyline(l.map(p=>[p.lat,p.lon]),{color:'#fff',weight:10,opacity:.7}));items.push(L.polyline(l.map(p=>[p.lat,p.lon]),{color:MASSIF[c.massif][1],weight:5}))}for(const p of c.points)items.push(L.circleMarker([p.lat,p.lon],{radius:8,color:'#fff',weight:2,fillColor:MASSIF[c.massif][1],fillOpacity:1}));if(chain.length){items.push(L.circleMarker([chain[0].lat,chain[0].lon],{radius:7,color:'#10161a',weight:2,fillColor:'#fff',fillOpacity:1}).bindTooltip('Extremo A'));items.push(L.circleMarker([chain.at(-1).lat,chain.at(-1).lon],{radius:7,color:'#10161a',weight:2,fillColor:'#10161a',fillOpacity:1}).bindTooltip('Extremo B'))}const g=L.featureGroup(items).addTo(CN.sheetMap);if(items.length)CN.sheetMap.fitBounds(g.getBounds(),{padding:[40,40],maxZoom:16});if(c.profile?.prof&&globalThis.TMTrails)TMTrails.drawSlope(CN.sheetMap,c.profile.prof);else{const p=S.location;CN.sheetMap.setView([p.lat,p.lon],12)}}
function legendSlope(){return `<div class="legend-dots">${[['#1d8ea3','< 15 %'],['#7aa35a','15–30 %'],['#d4861a','30–45 %'],['#ff5a1f','45–60 %'],['#b3261e','> 60 %']].map(([c,l])=>`<span><i style="background:${c}"></i>${l}</span>`).join('')}</div>`}
async function cnSnow(c,pr){const out=$('#cnSnow');if(!out||!globalThis.TMSnow)return;const top=pr.prof.reduce((a,b)=>b.ele>a.ele?b:a);try{const s=await TMSnow.at(top.lat,top.lon,top.ele);if(CN.selected!==c||!$('#cnSnow'))return;const deep=finite(s.depth)&&s.depth>=.05,inZone=finite(s.line)&&pr.hi>=s.line;out.classList.remove('muted');out.innerHTML=`<p class="sky-verdict">${deep?`Hay nieve en la parte alta (${fmt(s.depth*100)} cm a ${fmt(top.ele)} m): una canal nevada es otra actividad; piolet, crampones y valorar aludes.`:s.next72>=3?`Llegan ${fmt(s.next72,0)} cm de nieve en 72 h a la parte alta.`:inZone?`La cota de nieve (${fmt(s.line)} m) está por debajo de lo alto de la canal: posible nieve o hielo arriba.`:'Sin nieve en el modelo en la parte alta de la canal.'}</p><div class="ground"><div><span>Espesor arriba</span><strong>${finite(s.depth)?fmt(s.depth*100)+' cm':'—'}</strong><p>a ${fmt(top.ele)} m</p></div><div><span>Nevada 72 h</span><strong>${fmt(s.fell72,1)} cm</strong><p>caída</p></div><div><span>Próximas 72 h</span><strong>${fmt(s.next72,1)} cm</strong><p>prevista</p></div><div><span>Cota de nieve</span><strong>${finite(s.line)?fmt(s.line)+' m':'—'}</strong><p>ahora</p></div></div><p class="footnote">Modelo a la cota indicada. Los neveros de umbría duran semanas tras desaparecer del modelo: en canales norte y al inicio del verano, asume nieve dura.</p>`}catch(e){out.textContent='No se pudo consultar la nieve: '+e.message}}
function drawAccessOnMap(a){if(!CN.sheetMap)return;const items=[];for(const end of [a.bottom,a.top]){for(const x of end.named)items.push(L.circleMarker([x.f.p.lat,x.f.p.lon],{radius:5,color:'#fff',weight:1.5,fillColor:'#10161a',fillOpacity:.85}).bindTooltip(`${x.f.tags.name} · ${x.f.label}`));if(end.park)items.push(L.circleMarker([end.park.f.p.lat,end.park.f.p.lon],{radius:6,color:'#fff',weight:2,fillColor:'#2b86c5',fillOpacity:1}).bindTooltip('Aparcamiento'))}for(const s of a.springs)items.push(L.circleMarker([s.p.lat,s.p.lon],{radius:5,color:'#fff',weight:1.5,fillColor:'#1d8ea3',fillOpacity:1}).bindTooltip(s.tags.name||'Fuente'));L.featureGroup(items).addTo(CN.sheetMap)}
function linksFor(c,d,extra){const q=encodeURIComponent(c.name+' Picos de Europa');const p=c.chain?.[0]||c.center;const L_=[];if(c.refs?.[0])L_.push(['OpenStreetMap','Trazado y etiquetas originales','https://www.openstreetmap.org/'+c.refs[0]]);if(p)L_.push(['Visor del IGN','Mapa topográfico oficial',`https://www.ign.es/iberpix/visor/?center=${p.lon.toFixed(5)},${p.lat.toFixed(5)}&zoom=15`],['OpenTopoMap','Curvas de nivel',`https://opentopomap.org/#map=15/${p.lat.toFixed(5)}/${p.lon.toFixed(5)}`]);L_.push(['Wikiloc','Tracks publicados',`https://www.google.com/search?q=${q}+site%3Awikiloc.com`],['Reseñas recientes','Búsqueda web',`https://www.google.com/search?q=%22${encodeURIComponent(c.name)}%22+Picos+de+Europa`],['Parque Nacional','Avisos y cierres oficiales','https://parquenacionalpicoseuropa.es/'],['AEMET montaña','Boletín Picos de Europa','https://www.aemet.es/es/eltiempo/prediccion/montana']);if(d)L_.push(['Pyrenaica 211 (2003)','Artículo original, p. PDF '+d.pages.join(', '),`${CARES_SOURCE.pdf}#page=${d.pages[0]}`]);for(const s of extra?.sources||[])L_.push([s.name,'Fuente ['+s.id+']',s.url]);return L_.map(([t,s,u])=>`<a href="${esc(u)}" target="_blank" rel="noopener"><b>${esc(t)} ↗</b><small>${esc(s)}</small></a>`).join('')}
function canalKey(e){if(e.key==='Escape')closeCanal()}
function closeCanal(silent){try{CN.sheetMap?.remove()}catch{}CN.sheetMap=null;if($('#cnDetail')){$('#cnDetail').remove();if(!silent&&typeof sfx==='function')sfx('close')}document.removeEventListener('keydown',canalKey)}
function contextFor(c){const d=c.doc!=null?docs[c.doc]:null;return{canal:c.name,macizo:MASSIF[c.massif][0],longitud_km:c.profile?Math.round(c.profile.prof.at(-1).d*100)/100:null,cota_baja:c.profile?Math.round(c.profile.lo):null,cota_alta:c.profile?Math.round(c.profile.hi):null,desnivel:c.profile?Math.round(c.profile.up):null,pendiente_max_pct:c.profile?Math.round(c.profile.maxSlope):null,dificultad_osm:c.sac?SAC[c.sac]:null,enlaces:c.access?{caminos:c.access.paths.filter(p=>p.name).map(p=>p.name).slice(0,8),otras_canales:c.access.links.map(o=>o.name),cerca_abajo:c.access.bottom.named.map(x=>x.f.tags.name),cerca_arriba:c.access.top.named.map(x=>x.f.tags.name)}:null,ficha_2003:d?{conexion:d.connection,horario:d.time,agua:d.water,avisos:d.warn,secciones:d.sections.map(([t,x])=>t+': '+x.slice(0,500))}:null,limite:'Datos de OpenStreetMap y ficha de 2003; no acreditan estado actual.'}}
function mountCanales(){renderCatalog();loadCatalog();globalThis.TMPhotos?.commonsPhotos('Picos de Europa canal',6).then(async l=>{const p=l[new Date().getDate()%Math.max(1,l.length)];if(!p)return;try{await TMPhotos.preload(p.url)}catch{return}const el=$('#cnHeroPhoto');if(el){el.style.backgroundImage=`url("${p.url.replace(/"/g,'%22')}")`;el.classList.add('on');el.title=p.title+' · '+p.artist+' · '+p.license}})}
const cnShowTab=showTab;showTab=function(tab){cnShowTab(tab);if(tab==='canales')setTimeout(()=>{ensureAtlas();CN.atlas?.invalidateSize()},80)};
mountCanales();
globalThis.TMCanales={get selected(){return CN.selected},get map(){return CN.sheetMap},contextFor,open:openCanal,close:closeCanal,get list(){return CN.items},build:buildCatalog,massifOf,joinLines,accessInfo,load:loadCatalog,docs};
