'use strict';
/* Parte para el grupo: una imagen vertical lista para WhatsApp con ruta, hora, semáforo y claves. */
$('#saveExpedition')?.insertAdjacentHTML('afterend','<button id="cardMake" class="quiet" type="button">🖼 Parte para el grupo</button>');
$('#expeditionBrief')?.parentElement?.insertAdjacentHTML('beforeend','<div id="cardOut"></div>');
function roundRect(c,x,y,w,h,r){c.beginPath();c.moveTo(x+r,y);c.arcTo(x+w,y,x+w,y+h,r);c.arcTo(x+w,y+h,x,y+h,r);c.arcTo(x,y+h,x,y,r);c.arcTo(x,y,x+w,y,r);c.closePath()}
function wrap(c,text,x,y,max,lh,lines=3){const words=String(text).split(' ');let line='',n=0;for(const w of words){const t=line?line+' '+w:w;if(c.measureText(t).width>max&&line){c.fillText(line,x,y);y+=lh;line=w;if(++n>=lines-1){line=words.slice(words.indexOf(w)).join(' ');while(c.measureText(line+'…').width>max&&line.length)line=line.slice(0,-1);c.fillText(line+(line.length<text.length?'…':''),x,y);return y+lh}}else line=t}if(line)c.fillText(line,x,y);return y+lh}
async function makeCard(){const r=S.route,p=typeof currentPlan==='function'?currentPlan():null;if(!r||!p)return null;try{await document.fonts?.ready}catch{}const W=1080,H=1350,cv=document.createElement('canvas');cv.width=W;cv.height=H;const c=cv.getContext('2d');if(!c)return null;
 c.fillStyle='#eef1ef';c.fillRect(0,0,W,H);const blob=(x,y,rad,col)=>{const g=c.createRadialGradient(x,y,0,x,y,rad);g.addColorStop(0,col);g.addColorStop(1,'rgba(238,241,239,0)');c.fillStyle=g;c.fillRect(0,0,W,H)};blob(900,80,760,'rgba(29,142,163,.22)');c.strokeStyle='rgba(16,22,26,.06)';c.lineWidth=2;for(let k=1;k<9;k++){c.beginPath();c.ellipse(W*.78,H*.3,k*70,k*46,-.3,0,Math.PI*2);c.stroke()}c.fillStyle='#ff5a1f';c.fillRect(72,120,64,6);
 const D="'Source Serif 4', Georgia, serif",M="'Source Sans 3', sans-serif",B="'Source Sans 3', sans-serif";c.fillStyle='#10161a';c.font=`400 26px ${M}`;c.fillText('TRAILMETEO · PARTE DE SALIDA',72,96);
 c.font=`600 74px ${D}`;let y=wrap(c,r.name,72,220,W-144,84,3);
 const level=p.high?'high':p.rows.some(q=>q.assessment.level==='medium')?'medium':p.complete?'low':'unknown',col={high:'#e14545',medium:'#d4861a',low:'#1d9b72',unknown:'#6a767c'}[level],word={high:'STOP',medium:'OJO',low:'GO',unknown:'?'}[level];
 y+=20;c.strokeStyle=col;c.lineWidth=5;c.beginPath();c.arc(150,y+70,70,0,Math.PI*2);c.stroke();c.fillStyle=col;c.font=`500 40px ${D}`;c.textAlign='center';c.fillText(word,150,y+84);c.textAlign='left';c.fillStyle='#10161a';c.font=`400 40px ${B}`;c.fillText(`Salida ${exTime(p.start)}`,260,y+56);c.fillStyle='#2d383e';c.font=`300 34px ${B}`;c.fillText(`Llegada ≈ ${exTime(p.arrival)}`,260,y+108);y+=200;
 const stats=[['Distancia',fmt(r.summary.km,1)+' km'],['Desnivel',r.summary.elevationComplete?'+'+fmt(r.summary.up)+' m':'—'],['Racha máx.',fmt(p.maxGust)+' km/h'],['Lluvia máx.',fmt(p.maxRain,1)+' mm/h'],['Sectores exigentes',`${p.high}/${p.rows.length}`],['Luz a la llegada',p.arrivalLight?(p.arrivalLight.day?fmt(p.arrivalLight.remaining)+' min':'de noche'):'—']];stats.forEach(([k,v],i)=>{const x=72+(i%3)*320,yy=y+Math.floor(i/3)*150;c.fillStyle='#6a767c';c.font=`300 24px ${M}`;c.fillText(k.toUpperCase(),x,yy);c.fillStyle='#10161a';c.font=`200 58px ${D}`;c.fillText(v,x,yy+70)});y+=320;
 const pts=sample(r.points,160).filter(q=>finite(q.ele));if(pts.length>2){const lo=Math.min(...pts.map(q=>q.ele)),hi=Math.max(...pts.map(q=>q.ele)),X=q=>72+q.km/r.summary.km*(W-144),Yp=e=>y+190-(e-lo)/Math.max(1,hi-lo)*170;const g=c.createLinearGradient(0,y,0,y+200);g.addColorStop(0,'rgba(29,142,163,.30)');g.addColorStop(1,'rgba(29,142,163,0)');c.beginPath();pts.forEach((q,i)=>i?c.lineTo(X(q),Yp(q.ele)):c.moveTo(X(q),Yp(q.ele)));c.lineTo(X(pts.at(-1)),y+200);c.lineTo(X(pts[0]),y+200);c.fillStyle=g;c.fill();for(let i=1;i<pts.length;i++){const a=pts[i-1],b=pts[i],row=p.rows.reduce((best,q)=>!best||Math.abs(q.km-b.km)<Math.abs(best.km-b.km)?q:best,null);c.strokeStyle={high:'#e14545',medium:'#d4861a',low:'#1d9b72',unknown:'#9aa4a8'}[row?.assessment.level||'unknown'];c.lineWidth=6;c.beginPath();c.moveTo(X(a),Yp(a.ele));c.lineTo(X(b),Yp(b.ele));c.stroke()}c.fillStyle='#6a767c';c.font=`300 24px ${M}`;c.fillText(`${fmt(lo)}–${fmt(hi)} m`,72,y+240)}y+=290;
 const risks=[...new Set(p.rows.flatMap(q=>q.assessment.risks))].slice(0,3),gear=typeof gearItems==='function'?gearItems(p).filter(g=>g.level!=='low').map(g=>g.name).slice(0,4):[];c.fillStyle='#10161a';c.font=`400 30px ${B}`;y=wrap(c,risks.length?'Vigilar: '+risks.join(' · '):'Sin señales adversas en los puntos consultados.',72,y,W-144,42,2);if(gear.length){c.fillStyle='#2d383e';c.font=`300 28px ${B}`;y=wrap(c,'Llevar: '+gear.join(' · '),72,y+6,W-144,40,2)}
 c.fillStyle='#6a767c';c.font=`300 22px ${M}`;c.fillText(`Previsión ${exTime(r.weatherAt)} · Open-Meteo / AEMET · no certifica seguridad`,72,H-70);
 return cv}
$('#cardMake')?.addEventListener('click',async()=>{const cv=await makeCard();if(!cv){$('#cardOut').innerHTML='<p class="muted">Analiza la ruta primero.</p>';return}const url=cv.toDataURL('image/png');$('#cardOut').innerHTML=`<div class="card-preview"><img src="${url}" alt="Parte de salida para compartir"></div><div class="action-row"><button class="primary" type="button" id="cardShare">↗ Compartir</button><a id="cardDl" download="parte-${esc((S.route.name||'ruta').replace(/[^\w-]+/g,'_'))}.png" href="${url}">⬇ Descargar</a></div>`;$('#cardShare').onclick=async()=>{try{const blob=await new Promise(r=>cv.toBlob(r,'image/png'));const file=new File([blob],'parte-trailmeteo.png',{type:'image/png'});if(navigator.canShare?.({files:[file]}))await navigator.share({files:[file],title:'Parte · '+S.route.name});else $('#cardDl').click()}catch{}};if(typeof sfx==='function')sfx('ok')});
globalThis.TMCard={make:makeCard};
