'use strict';
/* Buzón de sugerencias y contacto. Sin servidor propio: se envía por correo (mailto) y, si Firebase está configurado,
   también queda guardado en Firestore (colección «feedback», solo escritura; ver reglas en el README). */
const CONTACT_EMAIL='mariawilderwest@gmail.com';
const FB_TYPES=[['idea','Idea o mejora'],['error','Algo falla'],['dato','Dato de una canal o ruta'],['otro','Otra cosa']];
function mailtoURL({type,message,email}){const label=(FB_TYPES.find(t=>t[0]===type)||FB_TYPES[3])[1];const body=`${message}\n\n—\nTipo: ${label}${email?`\nResponder a: ${email}`:''}\nSección: ${S.tab||'—'}${S.route?.name?`\nRuta cargada: ${S.route.name}`:''}\nTrailMeteo 11 · ${navigator.userAgent.slice(0,120)}`;return `mailto:${CONTACT_EMAIL}?subject=${encodeURIComponent('TrailMeteo · '+label)}&body=${encodeURIComponent(body)}`}
async function storeFeedback(f){const cfg=typeof firebaseConfig==='function'?firebaseConfig():null;if(!cfg)return false;const base=`https://www.gstatic.com/firebasejs/${FIREBASE_SDK}/`;const [appM,fsM]=await Promise.all([import(base+'firebase-app.js'),import(base+'firebase-firestore.js')]);const app=appM.getApps().find(a=>a.name==='trailmeteo')||appM.initializeApp(cfg,'trailmeteo');await fsM.addDoc(fsM.collection(fsM.getFirestore(app),'feedback'),{type:f.type,message:f.message.slice(0,3900),email:f.email.slice(0,200),at:Date.now(),uid:globalThis.TMAccount?.user?.uid||'',page:String(S.tab||'').slice(0,20),ua:navigator.userAgent.slice(0,200)});return true}
function openContact(){if($('#fbSheet'))return;if(typeof sfx==='function')sfx('open');const u=globalThis.TMAccount?.user;document.body.insertAdjacentHTML('beforeend',`<div class="more-sheet fb-sheet" id="fbSheet" role="dialog" aria-modal="true" aria-labelledby="fbTitle"><div class="more-panel"><div class="more-grab"></div><p class="eyebrow">Buzón</p><h2 id="fbTitle">¿Qué mejorarías?</h2><p class="muted">Ideas, errores, una canal que falta o un dato que corregir. Lo leo todo.</p><form id="fbForm" class="fb-form"><div class="seg" role="radiogroup" aria-label="Tipo">${FB_TYPES.map(([k,l],i)=>`<button type="button" role="radio" data-fb-type="${k}" aria-pressed="${!i}" aria-checked="${!i}">${l}</button>`).join('')}</div><label class="sr" for="fbMsg">Mensaje</label><textarea id="fbMsg" rows="5" maxlength="3900" required placeholder="Escribe aquí…"></textarea><label class="sr" for="fbMail">Tu correo (opcional)</label><input id="fbMail" type="email" maxlength="200" placeholder="Tu correo, si quieres respuesta (opcional)" value="${esc(u?.email||'')}"><div class="action-row"><button class="primary" type="submit">Enviar</button><a class="quiet" href="mailto:${CONTACT_EMAIL}">✉ ${CONTACT_EMAIL}</a></div><p id="fbStatus" class="wl-status" role="status"></p></form><p class="footnote">Contacto: <a href="mailto:${CONTACT_EMAIL}">${CONTACT_EMAIL}</a>. Tu mensaje solo se usa para mejorar TrailMeteo.</p></div></div>`);
 const el=$('#fbSheet');let type='idea';el.addEventListener('click',e=>{if(e.target===el){closeContact();return}const t=e.target.closest('[data-fb-type]');if(t){type=t.dataset.fbType;$$('#fbSheet [data-fb-type]').forEach(x=>{x.setAttribute('aria-pressed',String(x===t));x.setAttribute('aria-checked',String(x===t))})}});
 $('#fbForm').onsubmit=async e=>{e.preventDefault();const f={type,message:$('#fbMsg').value.trim(),email:$('#fbMail').value.trim()};if(f.message.length<3){$('#fbStatus').textContent='Escribe tu mensaje.';return}const st=$('#fbStatus');st.className='wl-status';st.innerHTML='<span class="spinner"></span>Enviando…';let saved=false;try{saved=await storeFeedback(f)}catch{}const mail=mailtoURL(f);if(saved){st.className='wl-status ok';st.innerHTML=`✓ Recibido, gracias. <a href="${esc(mail)}">Enviar también por correo</a>`;$('#fbMsg').value='';if(typeof sfx==='function')sfx('msg')}else{st.className='wl-status ok';st.innerHTML=`Se abrirá tu aplicación de correo con el mensaje listo para <b>${CONTACT_EMAIL}</b>. Si no se abre, <a href="${esc(mail)}">pulsa aquí</a> o escribe directamente.`;location.href=mail}};
 setTimeout(()=>$('#fbMsg')?.focus(),120)}
function closeContact(){$('#fbSheet')?.remove()}
document.addEventListener('keydown',e=>{if(e.key==='Escape')closeContact()});
document.addEventListener('click',e=>{if(e.target.closest('[data-open-contact]')){e.preventDefault();openContact()}});
globalThis.TMTheme?.addMore(['contact','Buzón y contacto','Sugerencias · '+CONTACT_EMAIL,'<path d="M3 6h18v12H3Z"/><path d="m3 7 9 6 9-6"/>'],openContact,'home');
const foot=$('footer');if(foot){foot.querySelector('b')&&(foot.querySelector('b').textContent='11');foot.insertAdjacentHTML('beforeend',`<a href="#" data-open-contact>Buzón de sugerencias</a><a href="mailto:${CONTACT_EMAIL}">${CONTACT_EMAIL}</a>`)}
globalThis.TMContact={email:CONTACT_EMAIL,open:openContact,close:closeContact,mailtoURL};
