'use strict';
/* Copiloto experto de TrailMeteo: responde siempre, sin red ni claves, razonando sobre los datos reales de la app.
   Es el último eslabón de la cadena de IA (Gemini → IA de Chrome → IA comunitaria → este motor). */
(function(){
const n=v=>typeof v==='number'&&Number.isFinite(v);
const f=(v,d=0)=>n(v)?v.toLocaleString('es-ES',{maximumFractionDigits:d,minimumFractionDigits:d}):'—';
const norm=s=>String(s||'').toLowerCase().normalize('NFD').replace(/[̀-ͯ]/g,'');
const uniq=a=>[...new Set(a.filter(Boolean))];
const has=(q,re)=>re.test(q);

function question(messages){const last=messages?.at?.(-1)?.content||'';const i=last.lastIndexOf('PREGUNTA:');return(i>=0?last.slice(i+9):last).split('\n\nFUENTES WEB RECUPERADAS')[0].trim()}
function sources(messages){const last=messages?.at?.(-1)?.content||'';const i=last.indexOf('FUENTES WEB RECUPERADAS');if(i<0)return[];return[...last.slice(i).matchAll(/\[(F\d+)\]\s+([^\n—]+)—\s+(\S+)\n([^\n]{0,400})/g)].map(m=>({id:m[1],title:m[2].trim(),url:m[3],text:m[4].trim()}))}

/* ---------- Lecturas de los datos ---------- */
function planInfo(c){const p=c.ruta?.plan;if(!p)return null;const sec=p.sectores||[];const risks=uniq(sec.flatMap(s=>s.riesgos||[]));const worst=sec.filter(s=>n(s.rachas)||n(s.lluvia)).sort((a,b)=>((b.rachas||0)/5+(b.lluvia||0)*8+(b.riesgos?.length||0)*8)-((a.rachas||0)/5+(a.lluvia||0)*8+(a.riesgos?.length||0)*8))[0];const temps=sec.map(s=>s.t).filter(n),iso=sec.map(s=>s.isoterma0).filter(n),alts=sec.map(s=>s.alt_m).filter(n);
 const level=p.puntos_exigentes>0?'STOP':risks.length?'OJO':sec.length?'GO':'?';return{p,sec,risks,worst,level,tmin:temps.length?Math.min(...temps):null,tmax:temps.length?Math.max(...temps):null,isoMin:iso.length?Math.min(...iso):null,altMax:alts.length?Math.max(...alts):null}}
function verdictText(i){return{STOP:'**STOP · replantea la salida.** Hay '+i.p.puntos_exigentes+' puntos con condiciones exigentes a tu hora de paso.',OJO:'**OJO · sal con precauciones.** Señales a vigilar: '+i.risks.slice(0,3).join(', ').toLowerCase()+'.',GO:'**GO · ventana favorable.** Sin señales adversas en los puntos consultados (no certifica el terreno).','?':'**Datos incompletos.** Actualiza la previsión o elige una salida más próxima.'}[i.level]}
function bestDeparture(c){const alts=c.ruta?.salidas_alternativas||[];if(!alts.length)return null;return[...alts].sort((a,b)=>(a.exigentes-b.exigentes)||((b.luz?1:0)-(a.luz?1:0))||((a.racha_max||0)-(b.racha_max||0)))[0]}
function nowLine(c){const a=c.ahora;if(!a)return null;return `Ahora en **${c.ubicacion?.nombre||'la zona'}**: ${a.estado?a.estado.toLowerCase()+', ':''}**${f(a.temperatura)} °C** (sensación ${f(a.sensacion)} °C), rachas de **${f(a.rachas_kmh)} km/h**${n(a.precip_mm)&&a.precip_mm>0?`, ${f(a.precip_mm,1)} mm`:''}.${a.copia_guardada?' _(copia guardada: actualiza si tienes conexión)_':''}`}
function nextHours(c,k=6){const h=(c.proximas_horas||[]).slice(0,k);if(!h.length)return null;const rain=h.filter(x=>(x.lluvia_mm||0)>=.3),gust=Math.max(...h.map(x=>x.rachas||0)),bad=h.filter(x=>/exigentes/i.test(x.lectura||''));return `Próximas ${h.length*2} h: ${rain.length?`lluvia hacia las ${rain[0].hora}`:'sin lluvia relevante'}, rachas de hasta **${f(gust)} km/h**${bad.length?`, **condiciones exigentes** desde ${bad[0].hora}`:''}.`}
function sunLine(c){const L=c.ruta?.plan?.luz_llegada;if(L)return L.con_luz?`Llegas con luz: ocaso ${L.ocaso}, margen de **${f(L.margen_min)} min**.`:`**Llegarías sin luz** (ocaso ${L.ocaso}). Adelanta la salida o lleva frontal.`;const d=c.siete_dias?.[0];return d?.ocaso?`Hoy amanece a las ${d.amanecer} y anochece a las ${d.ocaso}.`:null}
function mide(c){const r=c.ruta;if(!r||!n(r.km))return null;const th=r.km/4,tu=n(r.desnivel_pos_m)?r.desnivel_pos_m/400:0,td=n(r.desnivel_neg_m)?r.desnivel_neg_m/600:0,tv=tu+td;return th>tv?th+tv/2:tv+th/2}
function hm(h){if(!n(h))return'—';const m=Math.round(h*60);return `${Math.floor(m/60)} h ${String(m%60).padStart(2,'0')} min`}

/* ---------- Respuestas por intención ---------- */
const A={};
A.parte3=(c,i)=>{if(!i)return A.weather(c);const b=bestDeparture(c);return [verdictText(i).replace(/\*\*/g,'**'),b?`Hora recomendada: **${b.salida}** (llegada ${b.llegada}, ${b.exigentes} puntos exigentes${b.luz===false?', sin luz al llegar':''}).`:`Salida prevista ${i.p.salida} · llegada ${i.p.llegada}.`,i.worst?`Vigila el **km ${f(i.worst.km,1)} hacia las ${i.worst.hora}**: rachas ${f(i.worst.rachas)} km/h, lluvia ${f(i.worst.lluvia,1)} mm/h${i.worst.riesgos?.length?' ('+i.worst.riesgos.join(', ').toLowerCase()+')':''}.`:'Sin un punto crítico destacado.'].join('\n')};
A.briefing=(c,i)=>{if(!i)return A.weather(c);const r=c.ruta,b=bestDeparture(c),t=mide(c);return [`## ${r.nombre}`,verdictText(i),'',`- **Recorrido:** ${f(r.km,1)} km${n(r.desnivel_pos_m)?` · +${f(r.desnivel_pos_m)} / −${f(r.desnivel_neg_m)} m`:''}${n(i.altMax)?` · cota máx. ${f(i.altMax)} m`:''}.`,`- **Plan:** salida ${i.p.salida} → llegada ${i.p.llegada}${t?` (horario MIDE de referencia ≈ ${hm(t)})`:''}.`,`- **Temperatura en ruta:** ${f(i.tmin)} a ${f(i.tmax)} °C · rachas máx. **${f(i.p.racha_max)} km/h** · lluvia máx. ${f(i.p.lluvia_max_h,1)} mm/h.`,n(i.isoMin)?`- **Isoterma 0 °C:** desde ${f(i.isoMin)} m${n(i.altMax)&&i.isoMin<i.altMax+200?' → **posible hielo o nieve en lo alto**':''}.`:null,sunLine(c)?`- **Luz:** ${sunLine(c)}`:null,i.worst?`- **Momento crítico:** km ${f(i.worst.km,1)} a las ${i.worst.hora} (${(i.worst.riesgos||[]).join(', ').toLowerCase()||'el peor punto de la ruta'}).`:null,b&&b.salida!==i.p.salida?`- **Mejor hora según los datos:** ${b.salida} (${b.exigentes} puntos exigentes).`:null,c.avisos_aemet_en_ruta?.length?`- **Avisos AEMET en tu recorrido:** ${c.avisos_aemet_en_ruta.map(a=>a.evento).join(' · ')}.`:null,'',`Revisa la previsión justo antes de salir. Emergencias: **112**.`].filter(x=>x!==null).join('\n')};
A.when=(c,i)=>{const alts=c.ruta?.salidas_alternativas||[];if(alts.length){const s=[...alts].sort((a,b)=>(a.exigentes-b.exigentes)||((b.luz?1:0)-(a.luz?1:0))||((a.racha_max||0)-(b.racha_max||0)));return [`**Mejor salida: ${s[0].salida}** → llegada ${s[0].llegada}.`,'',...s.slice(0,4).map(a=>`- ${a.salida}: ${a.exigentes} puntos exigentes, racha máx. ${f(a.racha_max)} km/h, lluvia máx. ${f(a.lluvia_max,1)} mm/h${a.luz===false?', **llegada sin luz**':''}.`),'','Comparo tu mismo ritmo desplazando la hora de salida. Pulsa una hora en «Cuándo salir» para aplicarla.'].join('\n')}const w=c.mejores_ventanas_3h||[];if(w.length)return [`Sin ruta cargada, las mejores ventanas de 3 h en ${c.ubicacion?.nombre||'la zona'} son:`,...w.slice(0,3).map((x,k)=>`${k+1}. **${x.inicio}**`),'','Carga un GPX o busca una ruta y calcularé la hora exacta de paso por cada tramo.'].join('\n');return 'Carga una ruta (buscador de **Planificar** o un GPX) y te digo a qué hora salir comparando las próximas 12 horas.'};
A.gear=(c,i)=>{let items=[];try{const p=typeof currentPlan==='function'&&currentPlan();if(p&&typeof gearItems==='function')items=gearItems(p)}catch{}if(items.length)return ['**Material para esta salida** (según la previsión a tu hora de paso):','',...items.slice(0,14).map(it=>`- **${it.name}** — ${it.why}`),'','Marca lo que ya llevas en la lista de «Mochila» del plan.'].join('\n');const a=c.ahora||{},cold=n(a.sensacion)&&a.sensacion<8,wet=(c.proximas_horas||[]).some(h=>(h.lluvia_mm||0)>=.3),wind=(c.proximas_horas||[]).some(h=>(h.rachas||0)>=35);return ['**Básico de montaña:**','- Agua (0,5 L por hora de marcha) y comida.','- Capa cortavientos'+(wind?' — **habrá viento**':'')+'.',wet?'- **Impermeable**: hay lluvia prevista.':'- Impermeable ligero por si acaso.',cold?'- **Capa térmica, guantes y gorro**: sensación térmica baja.':'- Capa de abrigo para paradas.','- Frontal, móvil cargado, batería y botiquín.','- Mapa/GPX descargado (modo sin cobertura).','','Carga tu ruta para una lista ajustada a cada tramo.'].join('\n')};
A.planb=(c,i)=>{if(!i)return 'Carga y analiza una ruta: con las horas de paso te digo dónde y cuándo darte la vuelta.';const sec=i.sec,turn=sec.find(s=>(s.riesgos||[]).length)||null,L=c.ruta.plan.luz_llegada,half=sec[Math.floor(sec.length/2)];return ['**Plan B**','',turn?`- **Primer aviso en el km ${f(turn.km,1)} (${turn.hora})**: ${turn.riesgos.join(', ').toLowerCase()}. Decide ahí con margen; no esperes al tramo expuesto.`:'- No hay señales meteorológicas en los tramos: el plan B depende sobre todo de la luz y del cansancio.',half?`- **Hora límite orientativa:** si a las ${half.hora} no has pasado el km ${f(half.km,1)}, valora volver.`:null,L?`- ${L.con_luz?`Llegada con ${f(L.margen_min)} min de luz: si vas más lento, esa reserva se consume.`:'**Llegarías de noche**: adelanta la salida o recorta la ruta.'}`:null,i.worst?`- Peor punto: km ${f(i.worst.km,1)} a las ${i.worst.hora} (rachas ${f(i.worst.rachas)} km/h).`:null,'- Retírate por el mismo camino conocido antes que por variantes sin referencias.','- Si alguien queda atrapado o herido: **112**, posición GPS desde «En ruta».'].filter(Boolean).join('\n')};
A.wind=(c,i)=>{if(i)return [`**Viento en tu ruta:** racha máxima **${f(i.p.racha_max)} km/h**.`,...i.sec.filter(s=>(s.rachas||0)>=35).slice(0,5).map(s=>`- km ${f(s.km,1)} (${s.hora}, ${f(s.alt_m)} m): ${f(s.rachas)} km/h`),i.sec.some(s=>(s.rachas||0)>=60)?'\n**Rachas ≥ 60 km/h:** evita crestas y pasos expuestos.':(i.p.racha_max>=35?'\nEn crestas y collados notarás el viento; lleva cortavientos.':'\nViento sin importancia en los puntos consultados.')].join('\n');const h=c.proximas_horas||[];return h.length?`Rachas en ${c.ubicacion?.nombre}: ${h.slice(0,6).map(x=>`${x.hora} ${f(x.rachas)} km/h`).join(' · ')}.`:'No tengo datos de viento todavía.'};
A.rain=(c,i)=>{if(i){const wet=i.sec.filter(s=>(s.lluvia||0)>=.3);return wet.length?[`**Lluvia en ${wet.length} de ${i.sec.length} tramos** (máx. ${f(i.p.lluvia_max_h,1)} mm/h):`,...wet.slice(0,5).map(s=>`- km ${f(s.km,1)} a las ${s.hora}: ${f(s.lluvia,1)} mm/h`),'','Roca mojada y barro: más tiempo en bajadas y pasos con cadenas.'].join('\n'):'**Sin lluvia relevante** a tu hora de paso en los tramos consultados.'}const h=(c.proximas_horas||[]).filter(x=>(x.lluvia_mm||0)>=.3);return h.length?`Lluvia prevista en ${c.ubicacion?.nombre}: ${h.slice(0,4).map(x=>`${x.hora} (${f(x.lluvia_mm,1)} mm, ${x.prob??'—'} %)`).join(' · ')}.`:`Sin lluvia relevante en las próximas horas en ${c.ubicacion?.nombre||'la zona'}.`};
A.snow=(c,i)=>{const iso=i?.isoMin??Math.min(...(c.proximas_horas||[]).map(h=>h.isoterma0_m).filter(n));const top=i?.altMax;const lines=[];if(n(iso))lines.push(`**Isoterma 0 °C:** ${f(iso)} m.`);if(n(iso)&&n(top))lines.push(iso<top?`Tu cota máxima (${f(top)} m) queda **por encima** de la isoterma: **posible hielo o nieve**. Valora crampones o microcrampones y no te fíes de la roca a primera hora.`:`Tu cota máxima (${f(top)} m) queda ${f(iso-top)} m por debajo de la isoterma: hielo poco probable por temperatura.`);const s=c.boletin_aemet_montana?.campos?.find(x=>/nieve|innivaci|aludes/i.test(Object.keys(x)[0]));if(s)lines.push(`AEMET (${Object.keys(s)[0]}): ${Object.values(s)[0]}`);if(c.carretera?.cadenas||/cadena/i.test(JSON.stringify(c.carretera||{})))lines.push('Hay información de **cadenas** en la carretera: revisa «Carretera».');return lines.length?lines.join('\n\n'):'No tengo datos de isoterma o nieve: actualiza la previsión o abre la pestaña de nieve.'};
A.storm=(c,i)=>{const sec=i?.sec?.filter(s=>(s.riesgos||[]).some(r=>/tormenta/i.test(r)))||[];const hrs=(c.proximas_horas||[]).filter(h=>/exigentes/i.test(h.lectura||''));if(sec.length)return `**Tormenta prevista** en ${sec.length} tramos: ${sec.slice(0,4).map(s=>`km ${f(s.km,1)} (${s.hora})`).join(', ')}. Evita cimas y crestas en esas horas; sal antes o cambia de día.`;return `No hay tormentas previstas ${i?'a tu hora de paso':'en las próximas horas'}${hrs.length?', aunque sí condiciones exigentes desde '+hrs[0].hora:''}. Las tormentas de verano pueden formarse rápido por la tarde: madruga y vigila el cielo.`};
A.temp=(c,i)=>{if(i)return `En ruta tendrás entre **${f(i.tmin)} y ${f(i.tmax)} °C**${n(i.isoMin)?` · isoterma 0 °C a ${f(i.isoMin)} m`:''}. ${i.tmin<=2?'**Frío**: capas, guantes y gorro.':i.tmax>=26?'**Calor**: más agua y evita las horas centrales en solana.':'Temperatura cómoda para andar; lleva una capa para las paradas.'}`;return nowLine(c)||'Sin datos de temperatura.'};
A.weather=(c,i)=>{const pd=c.parte_del_dia;const lines=[pd?`**Parte de hoy · ${pd.titular}.** ${(pd.resumen||[])[0]||''}`:null,nowLine(c),nextHours(c)];if(i)lines.push('',`**Tu ruta «${c.ruta.nombre}»:** `+verdictText(i).replace(/^\*\*[^*]+\*\*\s*/,'')+` Salida ${i.p.salida}, llegada ${i.p.llegada}, ${f(i.tmin)}–${f(i.tmax)} °C, rachas máx. ${f(i.p.racha_max)} km/h.`);const d=c.siete_dias?.slice(0,3);if(d?.length)lines.push('',...d.map(x=>`- **${x.dia}:** ${f(x.min)}/${f(x.max)} °C · lluvia ${f(x.lluvia_mm,1)} mm · racha ${f(x.racha_max)} km/h`));const s=sunLine(c);if(s)lines.push('',s);const out=lines.filter(x=>x!==null&&x!==undefined).join('\n');return out.trim()||'Aún no tengo la previsión cargada. Elige un lugar en **Cielo** o pulsa **Actualizar**.'};
A.aemet=(c)=>{const b=c.boletin_aemet_montana;if(!b?.campos?.length)return 'El boletín de montaña de AEMET aún no está cargado. Ábrelo en **Más → AEMET montaña**.';return [`**Boletín AEMET · ${b.zona}** (${b.validez||'vigente'}):`,'',...b.campos.slice(0,6).map(x=>{const k=Object.keys(x)[0];return `- **${k}:** ${String(x[k]).slice(0,260)}`}),'',c.modelos_en_6h?.length?`Modelos a 6 h: ${c.modelos_en_6h.map(m=>`${m.modelo} ${f(m.t)} °C/${f(m.rachas)} km/h`).join(' · ')}. Si discrepan con AEMET, prioriza el boletín para cotas altas.`:''].join('\n')};
A.pace=(c,i)=>{const r=c.ruta;if(!r)return 'Carga una ruta y comparo tu ritmo con el horario MIDE de referencia.';const t=mide(c);return [`**Horario MIDE de referencia:** ≈ ${hm(t)} (4 km/h en horizontal, 400 m/h subiendo, 600 m/h bajando).`,`Tu plan: ${r.ritmo_llano_min_km} min/km en llano + ${r.min_por_100m} min por cada 100 m de ascenso${i?` → salida ${i.p.salida}, llegada ${i.p.llegada}`:''}.`,'','Si tu estimación es mucho menor que MIDE, añade margen: paradas, fotos y terreno técnico no están incluidos. En «Tu ritmo real» puedes calibrarlo con un GPX tuyo con tiempos.'].join('\n')};
A.road=(c)=>{const rd=c.carretera;if(!rd)return 'Abre **Más → Carretera**, pon origen y destino y te diré trayecto, avisos DGT, cadenas y tiempo en carretera.';return ['**Carretera**','',...Object.entries(rd).slice(0,10).map(([k,v])=>`- **${k.replace(/_/g,' ')}:** ${typeof v==='object'?JSON.stringify(v).replace(/[{}"[\]]/g,' ').replace(/\s+/g,' ').slice(0,200):v}`)].join('\n')};
A.research=(c,i,src)=>{if(src.length)return [`He leído **${src.length} fuentes públicas**:`,'',...src.slice(0,6).map(s=>`- **[${s.id}] ${s.title}** — ${s.text.slice(0,220)}${s.text.length>220?'…':''} ([abrir](${s.url}))`),'','Contrasta fechas: las reseñas antiguas no prueban el estado actual del terreno.'].join('\n');return 'No he podido recuperar fuentes web ahora. Prueba de nuevo en un minuto o abre «Fuentes para tu ruta» en Planificar.'};
A.canal=(c)=>{const k=c.canal;if(!k)return null;return [`**${k.canal||'Canal'}**`,'',...Object.entries(k).filter(([key])=>key!=='canal').slice(0,10).map(([key,v])=>`- **${key.replace(/_/g,' ')}:** ${typeof v==='object'?JSON.stringify(v).slice(0,200):String(v).slice(0,240)}`)].join('\n')};
A.help=()=>['Puedo ayudarte con:','- **Parte en 3 líneas** o **briefing** de tu salida','- **¿A qué hora salgo?** comparando alternativas','- **Material**, **plan B**, **viento**, **lluvia**, **nieve/hielo**, **tormentas**','- **AEMET**, **ritmo y tiempos (MIDE)**, **carretera y cadenas**','','Carga una ruta en **Planificar** para respuestas tramo a tramo.'].join('\n');

function route(q){q=norm(q);
 if(has(q,/3 lineas|tres lineas|parte rapido|veredicto/))return'parte3';
 if(has(q,/briefing|resumen|parte de la salida|analiza|como lo ves|que te parece|merece la pena|es buena idea|puedo ir/))return'briefing';
 if(has(q,/investiga|fuentes|resenas|que dicen|estado del sendero|informacion de la ruta/))return'research';
 if(has(q,/a que hora|cuando salgo|cuando salir|hora de salida|mejor hora|ventana|que dia/))return'when';
 if(has(q,/material|llevo|llevar|mochila|ropa|equipo|crampon/))return'gear';
 if(has(q,/plan b|darme la vuelta|vuelta|retirada|retirarme|empeora|abortar|escape/))return'planb';
 if(has(q,/tormenta|rayo|electric|granizo/))return'storm';
 if(has(q,/viento|racha|ventoso/))return'wind';
 if(has(q,/nieve|hielo|isoterma|helad|alud|cadenas/))return'snow';
 if(has(q,/lluvia|llover|llueve|precip|mojad|agua cae/))return'rain';
 if(has(q,/temperatura|frio|calor|grados/))return'temp';
 if(has(q,/aemet|boletin/))return'aemet';
 if(has(q,/ritmo|tiempos|cuanto tardo|duracion|mide|realista/))return'pace';
 if(has(q,/carretera|dgt|coche|llegar en|trafico/))return'road';
 if(has(q,/canal/))return'canal';
 if(has(q,/tiempo|meteo|clima|hace hoy|condiciones|parte/))return'weather';
 if(has(q,/ayuda|que puedes|que sabes/))return'help';
 return'weather'}

function answer(q,c,src=[]){c=c||{};const i=planInfo(c);const intent=route(q);let out=(A[intent]||A.weather)(c,i,src);if(!out)out=A.weather(c,i);return{intent,text:out}}

function register(){if(typeof AI==='undefined'||!AI.engines)return false;AI.engines.expert={grounding:false,label:'Copiloto TrailMeteo',async generate({messages,onToken}){let c={};try{c=Copilot.contextObj()}catch{}const q=question(messages);const {text}=answer(q,c,sources(messages));onToken?.(text);return{text,sources:[],model:'motor propio'}}};return true}
register();

/* Gemini Nano integrado en Chrome: gratis y en el dispositivo. La descarga necesita un toque del usuario. */
async function nanoState(){try{if(!('LanguageModel'in globalThis))return'unavailable';return await LanguageModel.availability({expectedOutputs:[{type:'text',languages:['es']}]})}catch{return'unavailable'}}
async function setupNano(){const row=document.querySelector('#cpSettings .action-row');if(!row||document.querySelector('#cpNano'))return;const st=await nanoState();if(st==='unavailable')return;row.insertAdjacentHTML('afterbegin',`<button id="cpNano" class="quiet" type="button">${st==='available'?'✓ IA de Chrome activa':'⬇ Activar IA de Chrome (gratis)'}</button>`);const b=document.querySelector('#cpNano');if(st==='available'){b.disabled=true;return}b.onclick=async()=>{const s=document.querySelector('#cpSettingsStatus');b.disabled=true;try{const m=await LanguageModel.create({expectedOutputs:[{type:'text',languages:['es']}],monitor(mon){mon.addEventListener('downloadprogress',e=>{if(s)s.textContent='Descargando Gemini Nano: '+Math.round(e.loaded*100)+' %'})}});m.destroy?.();b.textContent='✓ IA de Chrome activa';if(s)s.textContent='Gemini Nano listo: el copiloto lo usará cuando Gemini en la nube no responda.'}catch(e){b.disabled=false;if(s)s.textContent='No se pudo activar: '+e.message}}}
setupNano();
globalThis.TMExpert={answer,route,planInfo,mide};
})();
