/* Pure calculations shared by the app and regression checks. */
(function(root){
const finite=v=>typeof v==='number'&&Number.isFinite(v);
const mean=a=>{a=a.filter(finite);return a.length?a.reduce((s,v)=>s+v,0)/a.length:null};
function distance(a,b){const r=Math.PI/180,x=(b.lat-a.lat)*r,y=(b.lon-a.lon)*r,q=Math.sin(x/2)**2+Math.cos(a.lat*r)*Math.cos(b.lat*r)*Math.sin(y/2)**2;return 6371*2*Math.asin(Math.sqrt(Math.min(1,q)))}
function hours(d,suffix=''){const h=d?.hourly;if(!h?.time)return[];return h.time.map((time,i)=>{const row={time:time*1000};for(const [k,v]of Object.entries(h)){if(k==='time')continue;if(suffix){if(k.endsWith('_'+suffix))row[k.slice(0,-suffix.length-1)]=v[i]}else row[k]=v[i]}return row})}
function nearest(rows,time,maxGap=3600000){let best=null,gap=Infinity;for(const r of rows){let d=Math.abs(r.time-time);if(d<gap){best=r;gap=d}}return gap<=maxGap?best:null}
function assess(h){if(!h)return{level:'unknown',label:'Sin datos',risks:['Previsión no disponible']};const risks=[];let severe=false;
if(!finite(h.temperature_2m)||!finite(h.precipitation)||!finite(h.wind_gusts_10m))return{level:'unknown',label:'Datos incompletos',risks:['Faltan temperatura, lluvia o rachas']};
if(h.weather_code>=95){risks.push('Tormenta prevista');severe=true}if(h.wind_gusts_10m>=60){risks.push('Rachas fuertes');severe=true}else if(h.wind_gusts_10m>=35)risks.push('Viento en zonas expuestas');
if(h.precipitation>=4){risks.push('Precipitación intensa');severe=true}else if(h.precipitation>=.3)risks.push('Lluvia y terreno mojado');
const t=finite(h.apparent_temperature)?h.apparent_temperature:h.temperature_2m;if(t<=0)risks.push('Frío y posible hielo');if(t>=30){risks.push('Calor intenso');severe=true}else if(t>=26)risks.push('Calor');
if(finite(h.visibility)&&h.visibility<1000){risks.push('Visibilidad muy reducida');severe=true}else if(finite(h.visibility)&&h.visibility<3000)risks.push('Visibilidad reducida');
if(finite(h.uv_index)&&h.uv_index>=7)risks.push('Radiación UV alta');return{level:severe?'high':risks.length?'medium':'low',label:severe?'Condiciones exigentes':risks.length?'Con precauciones':'Sin señal adversa destacada',risks}}
function penalty(h){const a=assess(h);if(a.level==='unknown')return Infinity;return(a.level==='high'?100:0)+a.risks.length*8+h.precipitation*8+h.wind_gusts_10m/5}
function stats(points){let km=0,up=0,down=0,anchor=null,known=0;return{...points.reduce((s,p,i)=>{if(finite(p.ele))known++;if(!i||p.segment!==points[i-1].segment){anchor=finite(p.ele)?p.ele:null;p.km=km;p.up=up;return s}km+=distance(points[i-1],p);if(finite(p.ele)&&anchor!==null){const delta=p.ele-anchor;if(Math.abs(delta)>=3){if(delta>0)up+=delta;else down-=delta;anchor=p.ele}}else anchor=finite(p.ele)?p.ele:null;p.km=km;p.up=up;return s},{}),km,up,down,elevationComplete:known===points.length,elevationCount:known}}
function sample(points,n=16){if(points.length<=n)return points.map((p,i)=>({...p,idx:i}));const out=[{...points[0],idx:0}],total=points.at(-1).km;let j=1;for(let k=1;k<n-1;k++){const target=total*k/(n-1);while(j<points.length-1&&points[j].km<target)j++;if(out.at(-1).idx!==j)out.push({...points[j],idx:j})}if(out.at(-1).idx!==points.length-1)out.push({...points.at(-1),idx:points.length-1});return out}
function eta(points,start,pace,climb){if(!finite(start)||!finite(pace)||pace<=0||!finite(climb)||climb<0)throw Error('Revisa la fecha, el ritmo y el tiempo de ascenso.');return points.map(p=>({...p,eta:start+(p.km*pace+p.up/100*climb)*60000}))}
function parseGPX(text,Parser=root.DOMParser){if(text.length>25*1024*1024)throw Error('El archivo supera 25 MB. Exporta una ruta simplificada.');if(/<!DOCTYPE|<!ENTITY/i.test(text))throw Error('El GPX contiene declaraciones XML no admitidas.');const xml=new Parser().parseFromString(text,'application/xml');const all=n=>Array.from(xml.getElementsByTagNameNS('*',n));if(all('parsererror').length||xml.documentElement.localName!=='gpx')throw Error('El archivo no es un GPX válido.');let groups=all('trkseg');let pointTag='trkpt';if(!groups.length){groups=all('rte');pointTag='rtept'}const points=[];groups.forEach((group,segment)=>{for(const n of Array.from(group.getElementsByTagNameNS('*',pointTag))){const la=n.getAttribute('lat'),lo=n.getAttribute('lon'),lat=la?.trim()?Number(la):NaN,lon=lo?.trim()?Number(lo):NaN;if(!finite(lat)||!finite(lon)||Math.abs(lat)>90||Math.abs(lon)>180)throw Error('Hay coordenadas inválidas en el GPX.');const el=n.getElementsByTagNameNS('*','ele')[0]?.textContent?.trim();points.push({lat,lon,ele:el&&finite(Number(el))?Number(el):null,segment})}});if(points.length<2)throw Error('El GPX necesita al menos dos puntos de track o ruta.');if(points.length>150000)throw Error('La ruta supera 150.000 puntos. Simplifícala antes de importarla.');const track=all('trk')[0]||all('rte')[0];const name=track?.getElementsByTagNameNS('*','name')[0]?.textContent?.trim()||'Mi ruta';const summary=stats(points);if(summary.km<.001)throw Error('Los puntos no forman una ruta con distancia.');return{name,points,summary}}
const api={finite,mean,distance,hours,nearest,assess,penalty,stats,sample,eta,parseGPX};root.TM=api;if(typeof module!=='undefined')module.exports=api;
})(typeof globalThis!=='undefined'?globalThis:this);
