'use strict';
const X={alerts:null,modelJobs:new WeakMap(),terrainJobs:new WeakMap(),progress:null,watch:null,library:[],colors:{low:'#26766b',medium:'#ac6a16',high:'#ba3d46',unknown:'#77838b'}};
const exTime=t=>finite(t)?dateText(t,{day:'numeric',month:'short',hour:'2-digit',minute:'2-digit'},null):'—';
function safeLink(url){try{const u=new URL(url);return ['https:','http:'].includes(u.protocol)?u.href:''}catch{return ''}}
function currentPlan(){const r=S.route;if(!r?.data)return null;return Expedition.plan(r,r.start,Number($('#pace').value),Number($('#climb').value),X.progress)}
$('#routeContent').insertAdjacentHTML('beforeend',`
<section id="expeditionPanel" class="expedition-panel" hidden>
<div class="sectionhead"><div><p class="eyebrow">DÉCISIONES PARA TU RECORRIDO</p><h2>Parte de ruta</h2></div><button id="refreshRouteWeather" class="quiet">Actualizar datos de ruta</button></div>
<article class="card"><div id="expeditionBrief" aria-live="polite"></div><p id="routeDataAge" class="footnote"></p><div class="action-row"><button id="saveExpedition" class="primary">Guardar sin cobertura</button><button id="exportExpedition" class="quiet">Descargar parte</button><button id="routeOnRadar" class="quiet">Ver recorrido en radar</button></div><p id="saveStatus" role="status"></p></article>
<article class="card"><h3>Altitud y tiempo a la hora de paso</h3><label>Seleccionar sector<input id="sectorSelect" type="range" min="0" max="15" value="0"></label><div id="combinedProfile"></div><div id="selectedSector" aria-live="polite"></div><p class="footnote">Color del recorrido: verde azulado sin umbral destacado, ámbar precauciones, rojo condiciones exigentes, gris sin datos. Se muestrean hasta 16 puntos; entre ellos el color es orientativo. La altura del GPX y la isoterma son magnitudes distintas.</p></article>
<article class="card"><h3>Incertidumbre a lo largo de la ruta</h3><p id="routeModelStatus" role="status">Preparando comparación…</p><div id="routeUncertainty" class="tablewrap"></div><p class="footnote">Rangos entre ECMWF IFS, DWD ICON y NOAA GFS, mediante Open-Meteo, a la misma hora y coordenadas. No son probabilidades ni tres proveedores independientes.</p></article>
<article class="card"><div class="sectionhead"><h3>Avisos oficiales en tu recorrido</h3><button id="reloadAlerts" class="quiet">Actualizar avisos</button></div><div id="routeAlerts" aria-live="polite"></div><a href="https://www.aemet.es/es/eltiempo/prediccion/avisos" target="_blank" rel="noopener">Contrastar en AEMET ↗</a></article>
<article class="card"><h3>Durante la marcha</h3><p>Marca tu progreso para recalcular la llegada con tu posición y el tiempo transcurrido. El seguimiento funciona mientras la web permanece abierta; no envía tu posición a otras personas.</p><div class="route-settings"><label>Kilómetro actual<input id="progressKm" type="number" min="0" step=".1" value="0"></label><button id="applyProgress" class="quiet">Estoy aquí ahora</button><button id="trackProgress" class="primary">Usar GPS en marcha</button><button id="stopProgress" class="quiet">Volver al plan inicial</button></div><p id="progressStatus" role="status"></p><p id="emergencyPosition"></p><label>Contacto de emergencia · guardado solo aquí<input id="emergencyContact" maxlength="180" placeholder="Nombre y teléfono"></label><p>Emergencias en España y la UE: <a href="tel:112">112</a>. Esta web no contacta automáticamente con emergencias.</p></article>
</section>`);
const oldRouteForecast=renderRouteForecast;
renderRouteForecast=function(){oldRouteForecast();renderExpedition();loadRouteModels(S.route);if(typeof loadTerrain==='function')loadTerrain(S.route)};
const oldImportRoute=importRoute;
importRoute=async function(file){if(!file)return;stopTracking();X.progress=null;X.weatherLayer?.remove();X.radarRoute?.remove();$('#routeModelStatus').textContent='Preparando comparación…';$('#terrainStatus').textContent='Preparando consulta cartográfica…';$('#expeditionPanel').hidden=true;const prior=S.route;await oldImportRoute(file);if(S.route!==prior&&S.route){$('#emergencyContact').value='';renderExpedition();if(typeof renderTerrain==='function')renderTerrain();if(typeof syncRadarRoute==='function')syncRadarRoute()}};
const oldShowTab=showTab;
showTab=function(tab){oldShowTab(tab);if(tab==='route'&&S.route?.rows)renderExpedition();if(tab==='radar')syncRadarRoute()};
function renderExpedition(){const r=S.route,p=currentPlan();if(!r||!p)return;$('#expeditionPanel').hidden=false;const high=p.rows.filter(row=>row.assessment.level==='high'),worst=p.rows.filter(row=>row.h).sort((a,b)=>penalty(b.h)-penalty(a.h))[0],gaps=r.points.some((q,i)=>i&&q.segment!==r.points[i-1].segment);$('#expeditionBrief').innerHTML=`<h3>${esc(r.name)}</h3><p>Salida ${exTime(p.start)} · llegada estimada <b>${exTime(p.arrival)}</b>${X.progress?' · recalculada desde tu progreso':''}.</p><p>${p.known}/${p.rows.length} puntos con meteorología suficiente. ${high.length?`Hay ${high.length} puntos con condiciones exigentes.`:'No se detectan condiciones exigentes en los puntos con datos.'}</p>${worst?`<p>El punto con mayor señal meteorológica está en <a href="#selectedSector" data-select-sector="${p.rows.indexOf(worst)}">km ${fmt(worst.km,1)} a las ${exTime(worst.eta)}</a>: rachas ${fmt(worst.h.wind_gusts_10m)} km/h y precipitación ${fmt(worst.h.precipitation,1)} mm/h. ${esc(worst.assessment.risks.join(' · '))}</p>`:''}<p>${p.arrivalLight?`Llegada ${p.arrivalLight.day?'con luz solar':'fuera de las horas de sol'}. Puesta de sol de referencia: ${exTime(p.arrivalLight.sunset)}. ${p.arrivalLight.remaining>=0?`Margen hasta esa puesta de sol: ${fmt(p.arrivalLight.remaining)} min.`:''}`:'Sin datos de luz solar para la llegada.'}</p><p class="footnote">Resumen por reglas a partir de los puntos consultados. ${!r.summary.elevationComplete?'Faltan alturas: la duración no incluye ascenso. ':''}${gaps?'GPX con varios segmentos: los huecos no cuentan como recorrido ni duración. ':''}El ritmo no incluye paradas ni penalización por terreno técnico. La luz astronómica no contempla sombras del relieve.</p>`;
$('#routeDataAge').textContent='Previsión consultada '+exTime(r.weatherAt)+' · '+(Date.now()-r.weatherAt>6*3600000?'COPIA DE MÁS DE 6 HORAS. Actualiza antes de decidir.':'Puede cambiar; revisa antes de salir.');
$$('[data-select-sector]').forEach(b=>b.onclick=()=>{$('#sectorSelect').value=b.dataset.selectSector;renderSelectedSector()});renderProfile(p);renderDepartures();renderUncertainty();renderAlerts();drawWeatherSegments(p);if(typeof renderTerrain==='function')renderTerrain();}
function renderProfile(p){const r=S.route,pts=sample(r.points,240),vals=pts.map(q=>q.ele).filter(finite),freezing=p.rows.map(q=>q.h?.freezing_level_height).filter(finite),all=[...vals,...freezing],top=all.length?Math.max(...all)+100:100,bottom=all.length?Math.min(...all)-100:0,xx=q=>35+q.km/r.summary.km*720,yy=v=>170-(v-bottom)/Math.max(1,top-bottom)*135;let paths='';for(let i=1;i<pts.length;i++){const a=pts[i-1],b=pts[i];if(a.segment!==b.segment||!finite(a.ele)||!finite(b.ele))continue;const row=p.rows.reduce((best,q)=>!best||Math.abs(q.km-b.km)<Math.abs(best.km-b.km)?q:best,null),color=X.colors[row?.assessment.level||'unknown'];paths+=`<path d="M${xx(a)},${yy(a.ele)} L${xx(b)},${yy(b.ele)}" stroke="${color}" stroke-width="3"/>`}
const temps=p.rows.map(q=>q.h?.temperature_2m).filter(finite),tmin=temps.length?Math.min(...temps)-1:0,tmax=temps.length?Math.max(...temps)+1:1,ty=t=>275-(t-tmin)/(tmax-tmin)*55;for(let i=1;i<p.rows.length;i++){const a=p.rows[i-1],b=p.rows[i];if(a.segment!==b.segment)continue;if(finite(a.h?.freezing_level_height)&&finite(b.h?.freezing_level_height))paths+=`<path d="M${xx(a)},${yy(a.h.freezing_level_height)} L${xx(b)},${yy(b.h.freezing_level_height)}" stroke="#577bb2" stroke-width="2" stroke-dasharray="5 4"/>`;if(finite(a.h?.temperature_2m)&&finite(b.h?.temperature_2m))paths+=`<path d="M${xx(a)},${ty(a.h.temperature_2m)} L${xx(b)},${ty(b.h.temperature_2m)}" stroke="#b17438" stroke-width="3"/>`;}
$('#combinedProfile').innerHTML=vals.length?`<svg class="combined-profile" viewBox="0 0 800 345" role="img" aria-label="Perfil GPX, isoterma cero discontinua azul y temperatura en panel inferior"><text x="35" y="20">Altitud (m) · GPX / isoterma cero</text>${paths}<text x="35" y="194">${fmt(bottom+100)}–${fmt(top-100)} m · ${freezing.length?'isoterma: línea azul discontinua':'sin dato de isoterma'}</text><text x="35" y="218">Temperatura: ${temps.length?fmt(tmin+1)+'–'+fmt(tmax-1)+' °C':'sin datos'}</text><text x="35" y="330">0 km</text><text x="670" y="330">${fmt(r.summary.km,1)} km</text></svg>`:'No se dibuja perfil sin alturas del GPX.';$('#sectorSelect').max=Math.max(0,p.rows.length-1);renderSelectedSector()}
function renderSelectedSector(){const p=currentPlan(),i=Math.min(Number($('#sectorSelect').value),p?.rows.length-1),q=p?.rows[i];if(!q)return;$('#selectedSector').innerHTML=`<h4>Km ${fmt(q.km,1)} · ${exTime(q.eta)}</h4><div class="day-summary"><div><span>Altitud GPX</span><strong>${fmt(q.ele)} m</strong></div><div><span>Temperatura</span><strong>${fmt(q.h?.temperature_2m)} °C</strong></div><div><span>Rachas</span><strong>${fmt(q.h?.wind_gusts_10m)} km/h</strong></div><div><span>Precipitación / h</span><strong>${fmt(q.h?.precipitation,1)} mm</strong></div><div><span>Visibilidad</span><strong>${fmt(finite(q.h?.visibility)?q.h.visibility/1000:null,1)} km</strong></div><div><span>Isoterma cero · modelo</span><strong>${fmt(q.h?.freezing_level_height)} m</strong></div></div><p>${esc(q.assessment.risks.join(' · ')||q.assessment.label)}</p>`;if(S.routeMap)S.routeMap.panTo([q.lat,q.lon],{animate:false})}
function drawWeatherSegments(p){if(!S.routeMap||!window.L)return;X.weatherLayer?.remove();const r=S.route,layers=[];for(let i=1;i<r.sampled.length;i++){const a=r.sampled[i-1],b=r.sampled[i],parts=new Map(),q=p.rows.find(q=>q.idx===b.idx)||p.rows.find(q=>q.idx===a.idx);for(const point of r.points.slice(a.idx,b.idx+1)){if(!parts.has(point.segment))parts.set(point.segment,[]);parts.get(point.segment).push([point.lat,point.lon])}for(const line of parts.values())if(line.length>1)layers.push(L.polyline(line,{color:X.colors[q?.assessment.level||'unknown'],weight:6,opacity:.85}).bindPopup(`Km ${fmt(a.km,1)}–${fmt(b.km,1)} · ${q?exTime(q.eta):'Sin dato'}<br>Color aproximado entre muestras`))}X.weatherLayer=L.featureGroup(layers).addTo(S.routeMap)}
function renderDepartures(){const r=S.route;if(!r?.data)return;const choices=Expedition.departures(r,r.start,Number($('#pace').value),Number($('#climb').value));$('#routeWindows').innerHTML='<h3>Comparar horas de salida</h3><p>De 4 horas antes a 12 horas después, cada 2 horas. Se omiten horas pasadas. Compara lluvia, viento, cobertura y luz; no se asigna una puntuación de seguridad.</p><div class="tablewrap"><table><thead><tr><th>Salida</th><th>Llegada</th><th>Puntos exigentes</th><th>Lluvia máx. / h</th><th>Rachas máx.</th><th>Luz a la llegada</th><th></th></tr></thead><tbody>'+choices.map(c=>`<tr><td>${exTime(c.start)}</td><td>${exTime(c.arrival)}</td><td>${c.high} · ${c.known}/${c.rows.length} con datos</td><td>${fmt(c.maxRain,1)} mm</td><td>${fmt(c.maxGust)} km/h</td><td>${c.arrivalLight?c.arrivalLight.day?'Sí · '+fmt(c.arrivalLight.remaining)+' min de margen':'Fuera de horas de sol':'Sin datos'}</td><td><button class="quiet" data-plan-start="${c.start}">Elegir</button></td></tr>`).join('')+'</tbody></table></div>';$$('[data-plan-start]').forEach(b=>b.onclick=()=>{X.progress=null;$('#startTime').value=localInput(new Date(Number(b.dataset.planStart)));analyzeRoute()})}
async function loadRouteModels(r){if(!r?.data||r.multi||X.modelJobs.has(r))return;const job=(async()=>{try{const all=[];$('#routeModelStatus').textContent='Consultando tres modelos en los puntos de la ruta…';for(let i=0;i<r.sampled.length;i+=4){const b=r.sampled.slice(i,i+4),d=await json(forecastURL(b.map(p=>p.lat.toFixed(4)).join(','),b.map(p=>p.lon.toFixed(4)).join(','),{current:'',daily:'',timezone:'GMT',hourly:'temperature_2m,precipitation,wind_gusts_10m',models:'ecmwf_ifs025,icon_seamless,gfs_seamless',...r.summary.elevationComplete?{elevation:b.map(p=>Math.round(p.ele)).join(',')}:{}}));all.push(...Array.isArray(d)?d:[d])}r.multi=all.map(d=>MODEL.slice(0,3).map(([id,name])=>({id,name,rows:hours(d,id)})));r.multiAt=Date.now();if(S.route===r)renderUncertainty()}catch(e){if(S.route===r)$('#routeModelStatus').textContent='Comparación no disponible: '+e.message}finally{X.modelJobs.delete(r)}})();X.modelJobs.set(r,job);return job}
function renderUncertainty(){const r=S.route,p=currentPlan();if(!p)return;if(!r.multi){$('#routeUncertainty').textContent='Todavía no hay comparación de modelos para esta ruta.';return}$('#routeModelStatus').textContent='Consultados '+exTime(r.multiAt)+'. La dispersión mide diferencias entre modelos, no error observado.';const range=(v,unit)=>v?`${fmt(v.min,1)}–${fmt(v.max,1)} ${unit} (${v.n})`:'Faltan 2 modelos';$('#routeUncertainty').innerHTML='<table><thead><tr><th>Punto / hora</th><th>Temperatura</th><th>Lluvia / h</th><th>Rachas</th></tr></thead><tbody>'+p.rows.map(q=>{const idx=r.sampled.findIndex(a=>a.idx===q.idx),u=Expedition.uncertainty(r.multi[idx],q.eta);return `<tr><td>${fmt(q.km,1)} km · ${exTime(q.eta)}</td><td>${range(u.temperature,'°C')}</td><td>${range(u.rain,'mm')}</td><td>${range(u.gust,'km/h')}</td></tr>`}).join('')+'</tbody></table>'}
async function loadAlerts(){try{const r=await fetch('./data/alerts.json',{cache:'no-store'});if(!r.ok)throw Error();X.alerts=await r.json();renderAlerts()}catch{if(X.alerts){renderAlerts();$('#routeAlerts').insertAdjacentHTML('afterbegin','<p><b>No se han podido actualizar los avisos; se mantiene la copia anterior.</b></p>')}else if($('#routeAlerts'))$('#routeAlerts').textContent='No se han podido consultar los avisos. No equivale a ausencia de avisos.'}}
function renderAlerts(){const p=currentPlan(),d=X.alerts;if(!p||!d)return;const route=S.route,pace=Number($('#pace').value),climb=route.summary.elevationComplete?Number($('#climb').value):0;let rows=eta(route.points,p.start,pace,climb);if(X.progress)rows=rows.filter(q=>q.km>=X.progress.km).map(q=>({...q,eta:X.progress.time+((q.km-X.progress.km)*pace+(q.up-X.progress.up)/100*climb)*60000}));const hits=(d.alerts||[]).filter(a=>Expedition.alertMatches(a,rows)),stale=!d.complete||!finite(Date.parse(d.fetched))||Date.now()-Date.parse(d.fetched)>2*3600000;$('#routeAlerts').innerHTML=`<p>${stale?'<b>Copia incompleta o de más de 2 horas. No permite descartar avisos.</b>':'Copia consultada '+exTime(Date.parse(d.fetched))+'.'} Actualización programada cada hora; puede retrasarse.</p>`+hits.map(a=>`<div class="official-alert"><h4>${esc(a.headline||a.event)}</h4><p>${esc(a.area)} · ${exTime(Date.parse(a.onset))}–${exTime(Date.parse(a.expires))}</p><p>${esc(a.description)}</p><p>${esc(a.instruction)}</p><a href="${esc(safeLink(a.url)||'https://www.aemet.es/es/eltiempo/prediccion/avisos')}" target="_blank" rel="noopener">Fuente AEMET ↗</a></div>`).join('')+(!hits.length?'<p>No se han encontrado intersecciones entre la ruta, su horario y los polígonos de esta copia. Esto no confirma ausencia de peligro ni de avisos fuera de su horizonte.</p>':'')+'<p class="footnote">© AEMET · Se comprueban tramos completos del GPX y periodos CAP, sin unir huecos entre segmentos. Los mensajes sin geometría no pueden situarse sobre la ruta.</p>'}
function syncRadarRoute(){if(!S.radar.map||!S.route||!window.L)return;X.radarRoute?.remove();const groups=new Map();for(const p of S.route.points){if(!groups.has(p.segment))groups.set(p.segment,[]);groups.get(p.segment).push([p.lat,p.lon])}X.radarRoute=L.featureGroup([...groups.values()].map(points=>L.polyline(points,{color:'#bd3360',weight:4}))).addTo(S.radar.map)}
function stopTracking(){if(X.watch!==null)navigator.geolocation?.clearWatch(X.watch);X.watch=null;$('#trackProgress').textContent='Usar GPS en marcha'}
function progressAt(km,accuracy=null){const r=S.route;if(!r?.data||!finite(km)||km<0||km>r.summary.km){$('#progressStatus').textContent='Revisa el kilómetro dentro de esta ruta.';return}const now=Date.now();if(now<=r.start||km<.1){$('#progressStatus').textContent='Para estimar el ritmo real, la salida debe haber comenzado y debes llevar al menos 100 m.';return}const nearestPoint=r.points.reduce((b,p)=>Math.abs(p.km-km)<Math.abs(b.km-km)?p:b),mins=(now-r.start)/60000,climb=r.summary.elevationComplete?Number($('#climb').value):0,pace=(mins-nearestPoint.up/100*climb)/km;if(!finite(pace)||pace<2||pace>60){$('#progressStatus').textContent='El ritmo calculado queda fuera de 2–60 min/km. Revisa la salida o ajusta el ritmo manualmente.';return}$('#pace').value=pace.toFixed(1);X.progress={km,up:nearestPoint.up,time:now};$('#progressKm').value=km.toFixed(2);$('#progressStatus').textContent=`Progreso ${fmt(km,2)} km · ritmo estimado ${fmt(pace,1)} min/km${finite(accuracy)?' · precisión GPS ±'+fmt(accuracy)+' m':''}. Incluye tus paradas hasta ahora.`;renderExpedition()}
$('#sectorSelect').oninput=renderSelectedSector;
$('#reloadAlerts').onclick=loadAlerts;
$('#refreshRouteWeather').onclick=()=>{if(!S.route)return;S.route.data=null;S.route.multi=null;memory.clear();analyzeRoute()};
$('#routeOnRadar').onclick=()=>{showTab('radar');if(X.radarRoute)S.radar.map.fitBounds(X.radarRoute.getBounds(),{padding:[20,20]})};
$('#applyProgress').onclick=()=>progressAt(Number($('#progressKm').value));
$('#stopProgress').onclick=()=>{stopTracking();X.progress=null;$('#progressStatus').textContent='Mostrando el plan inicial con el ritmo indicado.';renderExpedition()};
$('#trackProgress').onclick=()=>{if(X.watch!==null){stopTracking();return}if(!navigator.geolocation){$('#progressStatus').textContent='GPS no disponible.';return}$('#trackProgress').textContent='Detener GPS';let last=0;X.watch=navigator.geolocation.watchPosition(pos=>{const p={lat:pos.coords.latitude,lon:pos.coords.longitude};$('#emergencyPosition').textContent=`Última posición: ${p.lat.toFixed(5)}, ${p.lon.toFixed(5)} · ${exTime(pos.timestamp)} · ±${fmt(pos.coords.accuracy)} m`;if(Date.now()-last<30000)return;last=Date.now();const q=Expedition.locate(S.route.points,p);if(!q||q.distance>.1||pos.coords.accuracy>50){$('#progressStatus').textContent='Posición alejada del track o precisión insuficiente. No se recalcula automáticamente; usa el kilómetro manual.';return}progressAt(q.km,pos.coords.accuracy)},()=>{$('#progressStatus').textContent='No se pudo obtener el GPS. Puedes indicar el kilómetro manualmente.';stopTracking()},{enableHighAccuracy:true,maximumAge:10000,timeout:20000})};
['pace','climb','startTime'].forEach(id=>$('#'+id).addEventListener('change',()=>{X.progress=null;$('#expeditionPanel').hidden=true}));
loadAlerts();
/* Optional orthophotography: imagery is not a live weather observation. */
const pnoaURL='https://www.ign.es/wmts/pnoa-ma?SERVICE=WMTS&REQUEST=GetTile&VERSION=1.0.0&LAYER=OI.OrthoimageCoverage&STYLE=default&TILEMATRIXSET=GoogleMapsCompatible&FORMAT=image/jpeg&TILEMATRIX={z}&TILEROW={y}&TILECOL={x}';
$('#baseMap').insertAdjacentHTML('beforeend','<option value="pnoa">Ortofoto IGN · España</option>');
const previousBasemap=setBasemap;
setBasemap=function(){if($('#baseMap').value!=='pnoa'){previousBasemap();return}const r=S.radar;if(!r.map)return;r.base?.remove();r.base=L.tileLayer(pnoaURL,{attribution:'Ortofotos © IGN / PNOA',maxNativeZoom:19,maxZoom:19}).addTo(r.map);r.base.bringToBack();r.base.on('tileerror',()=>$('#radarError').textContent='Ortofoto no disponible aquí. Su cobertura es España; selecciona OpenStreetMap.')};
$('#baseMap').onchange=setBasemap;
$('.route-map-tools').insertAdjacentHTML('beforeend','<label class="check"><input id="routeOrtho" type="checkbox"> Ortofoto IGN · España</label>');
$('#routeOrtho').onchange=()=>{X.ortho?.remove();if($('#routeOrtho').checked&&S.routeMap){X.ortho=L.tileLayer(pnoaURL,{attribution:'Ortofotos © IGN / PNOA',maxZoom:19}).addTo(S.routeMap);X.ortho.on('tileerror',()=>$('#routeRadarStatus').textContent='No se pudo cargar la ortofoto; cobertura España.') ;if(S.routeRadar)S.routeRadar.bringToFront()}};
$('#pane-radar').insertAdjacentHTML('beforeend','<article class="card"><h3>Más observaciones oficiales</h3><p>La ortofoto muestra el terreno, no el estado actual de nieve ni las nubes. Las observaciones de satélite, rayos y aludes se consultan en AEMET.</p><div class="action-row"><a href="https://www.aemet.es/es/eltiempo/observacion/satelite" target="_blank" rel="noopener">Satélite meteorológico ↗</a><a href="https://www.aemet.es/es/eltiempo/observacion/rayos" target="_blank" rel="noopener">Rayos observados ↗</a><a href="https://www.aemet.es/es/eltiempo/prediccion/montana/boletin_peligro_aludes" target="_blank" rel="noopener">Boletines de aludes ↗</a></div><a href="https://pnoa.ign.es/pnoa-imagen/ortofotos-pnoa-maxima-actualidad" target="_blank" rel="noopener">Procedencia de las ortofotos PNOA ↗</a></article>');
