/* Evidence-aware planning. No terrain difficulty is inferred from slope or altitude. */
(function(root){
const {finite,distance,nearest,assess,eta}=root.TM;
function project(p,a,b){const c=Math.cos(p.lat*Math.PI/180),x=(b.lon-a.lon)*c,y=b.lat-a.lat,px=(p.lon-a.lon)*c,py=p.lat-a.lat,t=Math.max(0,Math.min(1,(px*x+py*y)/(x*x+y*y||1)));const q={lat:a.lat+t*(b.lat-a.lat),lon:a.lon+t*(b.lon-a.lon)};return{t,distance:distance(p,q),point:q}}
function locate(points,p){let best=null;for(let i=1;i<points.length;i++){const a=points[i-1],b=points[i];if(a.segment!==b.segment)continue;const q=project(p,a,b);if(!best||q.distance<best.distance)best={...q,km:a.km+(b.km-a.km)*q.t,up:a.up+(b.up-a.up)*q.t,index:i}}return best}
function daylight(d,time){if(!d?.sunrise||!d?.sunset)return null;const i=d.sunrise.findIndex((s,j)=>finite(s)&&finite(d.sunset[j])&&time>=s*1000&&time<=d.sunset[j]*1000);if(i>=0)return{day:true,sunset:d.sunset[i]*1000,remaining:(d.sunset[i]*1000-time)/60000};const near=d.sunset.map((s,j)=>({s,j})).filter(x=>finite(x.s)&&Math.abs(x.s*1000-time)<18*3600000).sort((a,b)=>Math.abs(a.s*1000-time)-Math.abs(b.s*1000-time))[0];return near?{day:false,sunset:near.s*1000,remaining:(near.s*1000-time)/60000}:null}
function plan(route,start,pace,climb,progress=null){const rows=eta(route.sampled,start,pace,route.summary.elevationComplete?climb:0).map((p,i)=>{if(progress)p.eta=progress.time+Math.max(0,(p.km-progress.km)*pace+(p.up-progress.up)/100*(route.summary.elevationComplete?climb:0))*60000;const h=nearest(route.data?.[i]||[],p.eta,1800000);return{...p,h,assessment:assess(h),light:daylight(route.daily?.[i],p.eta)}}).filter(p=>!progress||p.km>=progress.km);
const known=rows.filter(p=>p.assessment.level!=='unknown'),high=known.filter(p=>p.assessment.level==='high'),gusts=known.map(p=>p.h.wind_gusts_10m),rain=known.map(p=>p.h.precipitation);return{start,rows,arrival:rows.at(-1)?.eta,complete:known.length===rows.length&&rows.length>0,known:known.length,high:high.length,wet:known.filter(p=>p.h.precipitation>=.3).length,maxGust:gusts.length?Math.max(...gusts):null,maxRain:rain.length?Math.max(...rain):null,night:rows.filter(p=>p.light&&!p.light.day).length,lightKnown:rows.filter(p=>p.light).length,arrivalLight:rows.at(-1)?.light}}
function departures(r,start,pace,climb,now=Date.now()){const out=[];for(let shift=-4;shift<=12;shift+=2){const t=start+shift*3600000;if(t<now)continue;out.push(plan(r,t,pace,climb))}return out}
function uncertainty(models,time){const rows=(models||[]).map(m=>({...m,h:nearest(m.rows||[],time,1800000)})).filter(m=>m.h);function range(key){const v=rows.map(m=>m.h[key]).filter(finite);return v.length>=2?{min:Math.min(...v),max:Math.max(...v),n:v.length}:null}return{rows,temperature:range('temperature_2m'),rain:range('precipitation'),gust:range('wind_gusts_10m')}}
function inside(p,poly){let yes=false;for(let i=0,j=poly.length-1;i<poly.length;j=i++){const a={lat:poly[i][0],lon:poly[i][1]},b={lat:poly[j][0],lon:poly[j][1]};if(project(p,a,b).distance<.001)return true;if((a.lat>p.lat)!==(b.lat>p.lat)&&p.lon<(b.lon-a.lon)*(p.lat-a.lat)/(b.lat-a.lat)+a.lon)yes=!yes}return yes}
function intersect(a,b,c,d){const cross=(u,v,w)=>(v.lon-u.lon)*(w.lat-u.lat)-(v.lat-u.lat)*(w.lon-u.lon);return cross(a,b,c)*cross(a,b,d)<0&&cross(c,d,a)*cross(c,d,b)<0}
function alertMatches(alert,rows){const from=Date.parse(alert.onset),to=Date.parse(alert.expires);if(!finite(from)||!finite(to))return false;const inArea=p=>(alert.polygons||[]).some(poly=>inside(p,poly));for(let i=0;i<rows.length;i++){const p=rows[i];if(p.eta>=from&&p.eta<=to&&inArea(p))return true;if(!i)continue;const a=rows[i-1];if(a.segment!==p.segment||p.eta<from||a.eta>to)continue;const t0=Math.max(0,(from-a.eta)/(p.eta-a.eta||1)),t1=Math.min(1,(to-a.eta)/(p.eta-a.eta||1)),lerp=t=>({lat:a.lat+(p.lat-a.lat)*t,lon:a.lon+(p.lon-a.lon)*t});const u=lerp(t0),v=lerp(t1);if(inArea(u)||inArea(v))return true;if((alert.polygons||[]).some(poly=>poly.some((q,j)=>intersect(u,v,{lat:q[0],lon:q[1]},{lat:poly[(j+1)%poly.length][0],lon:poly[(j+1)%poly.length][1]}))))return true}return false}
function sections(points,size=.25){const out=[];let first=0;for(let i=1;i<points.length;i++){const split=points[i].segment!==points[i-1].segment;if(split||points[i].km-points[first].km>=size||i===points.length-1){const end=split?i-1:i;if(end>first){const a=points[first],b=points[end],slice=points.slice(first,end+1),mid=slice[Math.floor(slice.length/2)];out.push({from:a.km,to:b.km,a,b,mid,idx:first,end,slope:slice.every(p=>finite(p.ele))&&b.km-a.km>=.05?(b.ele-a.ele)/((b.km-a.km)*10):null})}first=i}}return out}
function matchWays(section,ways){const samples=[section.a,section.mid,section.b];const candidates=ways.filter(w=>w.geometry?.length>1&&(!w.bounds||samples.every(p=>p.lat>=w.bounds[0]-.0003&&p.lat<=w.bounds[2]+.0003&&p.lon>=w.bounds[1]-.0003/Math.max(.05,Math.cos(p.lat*Math.PI/180))&&p.lon<=w.bounds[3]+.0003/Math.max(.05,Math.cos(p.lat*Math.PI/180))))).map(w=>{const ds=samples.map(p=>{let d=Infinity;for(let i=1;i<w.geometry.length;i++)d=Math.min(d,project(p,w.geometry[i-1],w.geometry[i]).distance);return d});return{way:w,distance:Math.max(...ds),mean:ds.reduce((a,b)=>a+b,0)/ds.length}}).filter(m=>m.distance<=.025).sort((a,b)=>a.mean-b.mean);return{status:candidates.length===1?'candidate':candidates.length>1?'ambiguous':'unknown',candidates:candidates.slice(0,3)}}
const api={project,locate,daylight,plan,departures,uncertainty,inside,alertMatches,sections,matchWays};root.Expedition=api;if(typeof module!=='undefined')module.exports=api;
})(typeof globalThis!=='undefined'?globalThis:this);
