'use strict';
/* Buscador de rutas con carga automática del trazado.
   Fuentes abiertas que sí entregan la geometría: senderos y rutas de OpenStreetMap (PR, GR, SL, sendas con nombre)
   y el catálogo de canales de Picos. Wikiloc bloquea la lectura automática: con un enlace suyo,
   TrailMeteo deduce el nombre de la ruta y carga el mismo sendero desde OpenStreetMap. */
(function(){
const FR={seq:0,ctrl:null,results:[]};
const OVERPASS=['https://overpass-api.de/api/interpreter','https://overpass.private.coffee/api/interpreter','https://maps.mail.ru/osm/tools/overpass/api/interpreter','https://overpass.kumi.systems/api/interpreter'];
const fold=s=>String(s||'').toLowerCase().normalize('NFD').replace(/[̀-ͯ]/g,'');
const STOP=new Set(['de','del','la','las','el','los','y','a','al','en','por','ruta','senda','sendero','camino','circular','desde','hasta','ida','vuelta','pr','gr','sl','to']);

/* ---------- Interfaz ---------- */
const finder=$('#routeFinder');
if(finder){
 const tabs=finder.querySelector('.finder-tabs');
 tabs.insertAdjacentHTML('afterbegin','<button type="button" role="tab" aria-selected="true" data-finder="osm">🧭 Buscar ruta</button>');
 const wl=tabs.querySelector('[data-finder="wikiloc"]');if(wl){wl.setAttribute('aria-selected','false');wl.hidden=true}
 const link=tabs.querySelector('[data-finder="link"]');if(link)link.innerHTML='🔗 Enlace · Wikiloc o GPX';
 finder.querySelector('[data-finder-pane="wikiloc"]').hidden=true;
 finder.querySelector('.finder-tabs').insertAdjacentHTML('afterend',`<div class="finder-body" data-finder-pane="osm"><form class="finder-form" id="frForm"><label class="sr" for="frQuery">Nombre de la ruta, sendero o canal</label><input id="frQuery" maxlength="120" placeholder="Ej.: Ruta del Cares, PR-PNPE 2, Canal de Trea, Vega de Ario…" autocomplete="off" enterkeyhint="search"><button class="primary" type="submit">Buscar</button></form><p class="finder-hint">Busca en los senderos de <b>OpenStreetMap</b> (PR, GR, SL y sendas con nombre) y en las canales de Picos. Al tocar una ruta se carga su trazado y se analiza al momento, sin descargar nada.</p><details class="fr-ab" id="frAB"><summary>✦ Ruta a medida: de un punto a otro</summary><form class="fr-ab-form" id="frABForm"><label>Desde<input id="frFrom" maxlength="80" placeholder="Poncebos" autocomplete="off"></label><label>Hasta<input id="frTo" maxlength="80" placeholder="Caín" autocomplete="off"></label><label class="fr-check"><input type="checkbox" id="frRound"> Ida y vuelta</label><button class="primary" type="submit">Trazar y analizar</button></form><p class="finder-hint">Se traza por senderos reales de OpenStreetMap con un enrutador de montaña (BRouter), con altitudes incluidas.</p></details><p id="frStatus" class="wl-status" role="status"></p><div id="frResults" class="wl-results fr-results"></div></div>`);
 const hint=finder.querySelector('[data-finder-pane="link"] .finder-hint');if(hint)hint.innerHTML='Pega un enlace de <b>Wikiloc</b> (web o app) o de un archivo <b>.gpx</b>. Wikiloc no deja leer su track automáticamente: TrailMeteo reconoce la ruta por su nombre y carga el mismo sendero desde OpenStreetMap. Si quieres el track exacto del autor, descarga el GPX e impórtalo.';
 const hero=$('.route-hero p:not(.eyebrow)');if(hero)hero.textContent='Busca un sendero o una canal, pega un enlace o importa tu GPX. TrailMeteo calcula cuándo pasarás por cada tramo y qué tiempo hará allí.';
}

/* ---------- Overpass ---------- */
const OVCACHE=new Map();
async function overpass(ql,signal){if(OVCACHE.has(ql))return OVCACHE.get(ql);const ctrls=[];const abortAll=()=>ctrls.forEach(c=>c.abort());signal?.addEventListener('abort',abortAll,{once:true});
 const one=async(ep,delay)=>{await new Promise(r=>setTimeout(r,delay));if(signal?.aborted)throw Error('Cancelado');const c=new AbortController();ctrls.push(c);const t=setTimeout(()=>c.abort(),28000);try{const r=await fetch(ep,{method:'POST',body:'data='+encodeURIComponent(ql),headers:{'Content-Type':'application/x-www-form-urlencoded'},signal:c.signal,credentials:'omit'});if(!r.ok)throw Error('OpenStreetMap no respondió ('+r.status+')');const d=await r.json();if(d.remark&&/runtime error|timed out/i.test(d.remark)&&!d.elements?.length)throw Error('OpenStreetMap saturado');return d.elements||[]}finally{clearTimeout(t)}};
 try{const els=await Promise.any(OVERPASS.map((ep,i)=>one(ep,i*700)));OVCACHE.set(ql,els);return els}catch(e){if(signal?.aborted)throw Error('Cancelado');throw Error(e.errors?.[0]?.message||'OpenStreetMap no disponible')}finally{abortAll();signal?.removeEventListener('abort',abortAll)}}
function pattern(q){const words=fold(q).replace(/[^a-z0-9ñ\s-]/g,' ').trim().split(/\s+/).filter(Boolean);const core=words.filter(w=>!STOP.has(w));if(core.length&&core.length<words.length&&!/^(pr|gr|sl)\b/.test(fold(q)))q=core.join(' ');return fold(q).replace(/[^a-z0-9ñ\s-]/g,' ').trim().split(/\s+/).filter(Boolean).map(w=>w.replace(/[aeiou]/g,v=>({a:'[aáà]',e:'[eéè]',i:'[iíï]',o:'[oóò]',u:'[uúü]'}[v])).replace(/n/g,'[nñ]').replace(/-/g,'[- ]?')).join('.*')}
function area(){const l=S.route?.points?.[0]||S.location||{lat:43.2,lon:-4.85};const lat=l.lat,lon=l.lon;return[lat-.7,lon-.95,lat+.7,lon+.95].map(v=>v.toFixed(3)).join(',')}
const NORTH='41.5,-9.4,43.9,-0.5';

async function searchOSM(query,signal,bbox=area()){const p=pattern(query);if(!p)return[];const ql=`[out:json][timeout:25];(relation["route"~"^(hiking|foot|walking)$"]["name"~"${p}",i](${bbox});relation["route"~"^(hiking|foot|walking)$"]["ref"~"${p}",i](${bbox});way["highway"~"^(path|footway|track|steps|bridleway|via_ferrata)$"]["name"~"${p}",i](${bbox}););out tags center 80;`;const els=await overpass(ql,signal);const out=[],groups=new Map();
 for(const e of els){const t=e.tags||{};if(e.type==='relation'){out.push({kind:'relation',id:e.id,name:t.name||t.ref||'Ruta sin nombre',ref:t.ref||'',km:Number(String(t.distance||'').replace(',','.'))||null,network:t.network||'',from:t.from||'',to:t.to||'',center:e.center,desc:t.description||''})}else{if(!t.name)continue;const key=fold(t.name).replace(/[^a-z0-9ñ\s]/g,' ').split(/\s+/).filter(w=>w&&!STOP.has(w)).join(' ')||fold(t.name);if(!groups.has(key))groups.set(key,{kind:'ways',name:t.name,names:new Set(),ids:[],center:e.center,surface:t.sac_scale||''});const g=groups.get(key);g.names.add(t.name);g.ids.push(e.id)}}
 for(const g of groups.values()){const ns=[...g.names];g.name=ns.find(n=>/^ruta/i.test(n))||ns.sort((x,y)=>x.length-y.length)[0];g.alias=ns.filter(n=>n!==g.name);out.push(g)}
 const ref=S.location||{lat:43.2,lon:-4.85},qf=fold(query);out.forEach(x=>{x.dist=x.center?TM.distance(ref,{lat:x.center.lat,lon:x.center.lon}):999;x.score=(fold(x.name)===qf||fold(x.ref)===qf?0:fold(x.name).startsWith(qf)?1:2)+(x.kind==='relation'?0:.5)+x.dist/400});return out.sort((a,b)=>a.score-b.score).slice(0,24)}
function searchCanales(query){const list=globalThis.TMCanales?.list||[];const q=fold(query).replace(/^canal (de |del )?/,'');if(q.length<3)return[];return list.filter(c=>fold(c.name).includes(q)).slice(0,6).map(c=>({kind:'canal',id:c.id,name:'Canal '+(/^(de|del) /i.test(c.name)?'':'de ')+c.name,massif:c.massif,canal:c}))}

/* ---------- Geometría ---------- */
function stitch(lines){lines=lines.filter(l=>l.length>1);if(!lines.length)return[];if(globalThis.TMCanales?.joinLines){try{const j=TMCanales.joinLines(lines);if(j?.length>1)return j}catch{}}
 lines.sort((a,b)=>b.length-a.length);let chain=[...lines.shift()];const d=(a,b)=>TM.distance(a,b);let guard=0;while(lines.length&&guard++<5000){let best=null;for(let i=0;i<lines.length;i++){const l=lines[i],cands=[[d(chain.at(-1),l[0]),'end',false],[d(chain.at(-1),l.at(-1)),'end',true],[d(chain[0],l.at(-1)),'start',false],[d(chain[0],l[0]),'start',true]];for(const [g,side,rev] of cands)if(!best||g<best.g)best={g,i,side,rev}}if(best.g>.35)break;let l=lines.splice(best.i,1)[0];if(best.rev)l=[...l].reverse();chain=best.side==='end'?chain.concat(l.slice(1)):l.slice(0,-1).concat(chain)}return chain}
const len=l=>l.reduce((s,p,i)=>i?s+TM.distance(l[i-1],p):0,0);
function components(lines){lines=lines.filter(l=>l.length>1).map(l=>[...l]);const out=[];while(lines.length){lines.sort((a,b)=>len(b)-len(a));let chain=lines.shift();let grown=true;while(grown){grown=false;for(let i=0;i<lines.length;i++){const l=lines[i],g=[[TM.distance(chain.at(-1),l[0]),'end',false],[TM.distance(chain.at(-1),l.at(-1)),'end',true],[TM.distance(chain[0],l.at(-1)),'start',false],[TM.distance(chain[0],l[0]),'start',true]].sort((a,b)=>a[0]-b[0])[0];if(g[0]<=.05){let seg=g[2]?[...l].reverse():l;chain=g[1]==='end'?chain.concat(seg.slice(1)):seg.slice(0,-1).concat(chain);lines.splice(i,1);grown=true;break}}}out.push(chain)}return out}
function smoothEle(pts,w=4){return pts.map((p,i)=>{let s=0,n=0;for(let k=Math.max(0,i-w);k<=Math.min(pts.length-1,i+w);k++)if(finite(pts[k].ele)){s+=pts[k].ele;n++}return{...p,ele:n?Math.round(s/n*10)/10:p.ele}})}
async function brouter(points,signal){const ll=points.map(p=>p.lon.toFixed(6)+','+p.lat.toFixed(6)).join('|');for(const profile of ['hiking-mountain','trekking']){const c=new AbortController(),abort=()=>c.abort();signal?.addEventListener('abort',abort,{once:true});const t=setTimeout(abort,25000);try{const r=await fetch(`https://brouter.de/brouter?lonlats=${ll}&profile=${profile}&alternativeidx=0&format=geojson`,{signal:c.signal,credentials:'omit'});if(!r.ok)continue;const d=await r.json();const co=d.features?.[0]?.geometry?.coordinates;if(co?.length>1)return smoothEle(co.map(([lon,lat,ele])=>({lat,lon,ele:finite(ele)?ele:null})))}catch(e){if(signal?.aborted)throw Error('Cancelado')}finally{clearTimeout(t);signal?.removeEventListener('abort',abort)}}throw Error('El enrutador de senderos no respondió')}
function viaPoints(comps){const ends=comps.flatMap(c=>[c[0],c.at(-1)]);let A=ends[0],B=ends[1],best=-1;for(const a of ends)for(const b of ends){const d=TM.distance(a,b);if(d>best){best=d;A=a;B=b}}const ax=B.lon-A.lon,ay=B.lat-A.lat,proj=p=>((p.lon-A.lon)*ax+(p.lat-A.lat)*ay)/(ax*ax+ay*ay||1);const mids=comps.filter(c=>len(c)>.15).map(c=>c[Math.floor(c.length/2)]).filter(p=>TM.distance(p,A)>.2&&TM.distance(p,B)>.2).sort((a,b)=>proj(a)-proj(b));const step=Math.max(1,Math.ceil(mids.length/6));return[A,...mids.filter((_,i)=>i%step===0),B]}
async function geocode(q,signal){const l=S.location||{lat:43.2,lon:-4.85};const vb=[l.lon-1.2,l.lat+.9,l.lon+1.2,l.lat-.9].join(',');for(const bounded of [1,0]){const r=await fetch('https://nominatim.openstreetmap.org/search?'+new URLSearchParams({q,format:'jsonv2',limit:'1','accept-language':'es',countrycodes:'es,fr,ad,pt',viewbox:vb,bounded:String(bounded)}),{signal,credentials:'omit'});if(!r.ok)continue;const d=await r.json();if(d[0])return{lat:+d[0].lat,lon:+d[0].lon,name:d[0].name||q}}throw Error('No encuentro «'+q+'»')}
async function geometry(item,signal){if(item.kind==='ab'){const [A,B]=await Promise.all([geocode(item.from,signal),geocode(item.to,signal)]);if(TM.distance(A,B)>60)throw Error('Los puntos están a más de 60 km: elige lugares más cercanos');let pts=await brouter([A,B],signal);if(item.round)pts=pts.concat([...pts].reverse().slice(1));return{name:`${A.name} → ${B.name}${item.round?' (ida y vuelta)':''}`,points:pts,how:'brouter'}}if(item.kind==='canal'){const c=item.canal;const chain=c.chain||TMCanales.joinLines(c.lines);return{name:item.name,points:chain.map(p=>({lat:p.lat,lon:p.lon,ele:null}))}}
 let els;if(item.kind==='relation')els=await overpass(`[out:json][timeout:25];relation(${item.id});way(r);out geom;`,signal);else els=await overpass(`[out:json][timeout:25];way(id:${item.ids.slice(0,200).join(',')});out geom;`,signal);
 const lines=els.filter(e=>e.type==='way'&&e.geometry?.length).map(e=>e.geometry.map(g=>({lat:g.lat,lon:g.lon,ele:null})));const name=item.name+(item.ref&&!item.name.includes(item.ref)?' · '+item.ref:'');const comps=components(lines);const main=comps.sort((a,b)=>len(b)-len(a))[0]||[];const total=lines.reduce((s,l)=>s+len(l),0);if(comps.length===1||len(main)>=.85*total)return{name,points:main,how:'osm'};try{const pts=await brouter(viaPoints(comps),signal);return{name,points:pts,how:'brouter'}}catch(e){if(/Cancelado/.test(e.message))throw e;const pts=stitch(lines);if(pts.length<2)throw Error('OpenStreetMap no tiene geometría continua para esta ruta');return{name,points:pts,how:'osm'}}}

/* ---------- Carga ---------- */
async function load(item,{statusEl='#frStatus',analyze=true,note=''}={}){FR.ctrl?.abort();const ctrl=new AbortController();FR.ctrl=ctrl;const st=t=>{const el=$(statusEl);if(el){el.className='wl-status';el.innerHTML=t}};
 try{st('<span class="spinner"></span>Cargando el trazado de «'+esc(item.name)+'»…');const g=await geometry(item,ctrl.signal);st('<span class="spinner"></span>Trazado listo ('+fmt(g.points.length)+' puntos). Añadiendo altitudes…');let {points,source}=await addElevation(g.points,ctrl.signal);if(g.how==='brouter'&&source==='Wikiloc')source='modelo del terreno de BRouter (SRTM, suavizado)';if(ctrl.signal.aborted)return;
  await importRoute(new File([TMWikiloc.buildGPX(g.name,points)],'osm-'+(item.id||'ruta')+'.gpx',{type:'application/gpx+xml'}));if(S.route){S.route.sourceNote=(note?note+' ':'')+(g.how==='brouter'?'Tramos de OpenStreetMap unidos siguiendo la red de senderos (BRouter); ':'Trazado de OpenStreetMap; ')+`© colaboradores de OSM (ODbL); altitudes: ${source}.`;S.route.sourceUrl=item.kind==='relation'?'https://www.openstreetmap.org/relation/'+item.id:item.kind==='ways'?'https://www.openstreetmap.org/way/'+item.ids[0]:''}
  const el=$(statusEl);if(el){el.className='wl-status ok';el.innerHTML=`✓ «${esc(g.name)}» cargada y analizada${note?' · '+esc(note):''}. ${g.how==='brouter'?'Trazado por senderos de OpenStreetMap (BRouter)':'Trazado de OpenStreetMap'}; altitudes: ${esc(source)}.`}if(typeof sfx==='function')sfx('ok');
  if(analyze&&S.route&&typeof analyzeRoute==='function'){const v=new Date($('#startTime')?.value).getTime(),vh=new Date(v).getHours();if(!finite(v)||v<Date.now()||vh<6||vh>=19){const d=new Date(),h=d.getHours();d.setMinutes(0,0,0);if(h<6)d.setHours(8);else if(h>=14){d.setDate(d.getDate()+1);d.setHours(8)}else d.setHours(h+1);$('#startTime').value=localInput(d)}await analyzeRoute()}
  $('#routeContent')?.scrollIntoView?.({behavior:'smooth',block:'start'});return true}
 catch(e){if(ctrl.signal.aborted&&/Cancelado/.test(e.message))return false;const el=$(statusEl);if(el){el.className='wl-status err';el.innerHTML='No se pudo cargar: '+esc(e.message)+'.'}return false}}

/* ---------- Búsqueda ---------- */
function card(r,i){const meta=r.kind==='relation'?[r.ref,r.km?fmt(r.km,1)+' km':'',r.network?{iwn:'Internacional',nwn:'GR · Nacional',rwn:'PR · Regional',lwn:'SL · Local'}[r.network]||'':'',r.from&&r.to?r.from+' → '+r.to:'']:r.kind==='ways'?[r.ids.length+' tramo'+(r.ids.length>1?'s':''),r.alias?.length?'también «'+r.alias.slice(0,2).join('», «')+'»':'',r.surface?'SAC '+r.surface:'']:[r.massif?'Macizo '+r.massif:'','Canal de Picos'];const where=finite(r.dist)&&r.dist<900?`a ${fmt(r.dist)} km`:'';return `<article class="wl-card fr-card" style="animation-delay:${i*40}ms"><span class="wl-host">${r.kind==='relation'?'Ruta señalizada · OSM':r.kind==='ways'?'Sendero con nombre · OSM':'Canal · catálogo TrailMeteo'}</span><h4>${esc(r.name)}</h4><div class="wl-meta">${meta.filter(Boolean).map(m=>`<span>${esc(m)}</span>`).join('')}${where?`<span>${where}</span>`:''}</div><div class="wl-actions"><button class="primary" type="button" data-fr-load="${i}">⚡ Cargar y analizar</button>${r.kind==='relation'?`<a href="https://hiking.waymarkedtrails.org/#route?id=${r.id}" target="_blank" rel="noopener">Ver señalización ↗</a>`:''}</div></article>`}
async function search(query){query=String(query||'').trim();const st=$('#frStatus');if(query.length<3){if(st){st.className='wl-status err';st.textContent='Escribe al menos 3 letras.'}return[]}const seq=++FR.seq;FR.ctrl?.abort();const ctrl=new AbortController();FR.ctrl=ctrl;$('#frResults').textContent='';if(st){st.className='wl-status';st.innerHTML='<span class="spinner"></span>Buscando «'+esc(query)+'» en senderos y canales…'}if(typeof sfx==='function')sfx('scan');
 try{let items=[...searchCanales(query)];let osm=await searchOSM(query,ctrl.signal);if(!osm.length)osm=await searchOSM(query,ctrl.signal,NORTH);items=items.concat(osm);if(seq!==FR.seq)return[];FR.results=items;
  if(!items.length){st.className='wl-status err';st.innerHTML=`Sin rutas para «${esc(query)}». Prueba con el nombre del pueblo, la cima o el código (PR-PNPE 3), o importa tu GPX.`;return[]}
  st.className='wl-status ok';st.innerHTML=`${items.length} resultado${items.length>1?'s':''}. Toca <b>Cargar y analizar</b>: el trazado se carga solo.`;$('#frResults').innerHTML=items.map(card).join('');return items}
 catch(e){if(seq===FR.seq&&st){st.className='wl-status err';st.textContent='La búsqueda no respondió: '+e.message+'. Inténtalo en unos segundos.'}return[]}}
$('#frResults')?.addEventListener('click',e=>{const b=e.target.closest('[data-fr-load]');if(b)load(FR.results[+b.dataset.frLoad])});
$('#frForm')?.addEventListener('submit',e=>{e.preventDefault();search($('#frQuery').value)});
$('#frABForm')?.addEventListener('submit',e=>{e.preventDefault();const from=$('#frFrom').value.trim(),to=$('#frTo').value.trim();if(from.length<2||to.length<2){const st=$('#frStatus');st.className='wl-status err';st.textContent='Escribe el punto de salida y el de llegada.';return}load({kind:'ab',id:'medida',from,to,round:$('#frRound').checked,name:from+' → '+to})});

/* ---------- Wikiloc → mismo sendero en OSM ---------- */
function nameFromWikiloc(url,title){if(title)return title;try{const slug=new URL(url).pathname.split('/').filter(Boolean).pop()||'';return decodeURIComponent(slug).replace(/-\d{5,}$/,'').replace(/-/g,' ')}catch{return''}}
function keywords(name){return fold(name).replace(/[^a-z0-9ñ\s-]/g,' ').split(/\s+/).filter(w=>w.length>2&&!STOP.has(w))}
async function fromWikiloc(item,statusEl='#wlLinkStatus'){const name=nameFromWikiloc(item.url,item.title);const kw=keywords(name);if(!kw.length)return false;const st=$(statusEl);if(st){st.className='wl-status';st.innerHTML='<span class="spinner"></span>Wikiloc no deja leer su track. Busco «'+esc(name)+'» en OpenStreetMap…'}
 const tries=[kw.slice(0,3).join(' '),kw.slice(0,2).join(' '),kw[0]];let found=[];for(const t of tries){try{found=await searchOSM(t,null);if(!found.length)found=await searchOSM(t,null,NORTH)}catch{found=[]}if(found.length)break}
 const scored=found.map(r=>{const k=keywords(r.name+' '+(r.ref||''));const hit=kw.filter(w=>k.some(x=>x.startsWith(w)||w.startsWith(x))).length;return{...r,hit}}).filter(r=>r.hit>0).sort((a,b)=>b.hit-a.hit||a.score-b.score);if(!scored.length)return false;
 return load(scored[0],{statusEl,note:`Equivalente en OpenStreetMap de la ruta de Wikiloc «${name}»`})}


/* ---------- Rutas compartidas a la app (Android: Compartir → TrailMeteo) y archivos .gpx abiertos con la app ---------- */
async function analyzeLoaded(){if(S.route&&typeof analyzeRoute==='function'){const d=new Date(),h=d.getHours();d.setMinutes(0,0,0);if(h<6)d.setHours(8);else if(h>=14){d.setDate(d.getDate()+1);d.setHours(8)}else d.setHours(h+1);$('#startTime').value=localInput(d);await analyzeRoute()}}
async function inbox(){if(!/[?&]shared=1/.test(location.search)||!('caches'in globalThis))return;try{const c=await caches.open('tm-share');const g=await c.match('./shared.gpx'),t=await c.match('./shared.txt');history.replaceState(null,'',location.pathname+'#route');if(typeof enterApp==='function'&&$('#splash'))enterApp('route');showTab('route');
 if(g){const name=decodeURIComponent(g.headers.get('X-Name')||'compartida.gpx');await importRoute(new File([await g.blob()],name,{type:'application/gpx+xml'}));await analyzeLoaded()}
 else if(t){const text=await t.text(),u=(text.match(/https?:\/\/\S+/)||[])[0];if(u&&/wikiloc\.com/.test(u)){$('#wlLink').value=u;$$('#routeFinder [data-finder]').find(b=>b.dataset.finder==='link')?.click();await TMWikiloc.loadLink(u)}else if(u&&/\.gpx(\?|$)/i.test(u)){await TMWikiloc.loadLink(u)}else if(text.trim()){$('#frQuery').value=text.trim().slice(0,120);await search(text.trim().slice(0,120))}}
 await c.delete('./shared.gpx');await c.delete('./shared.txt')}catch(e){console.warn('[TrailMeteo] compartido',e)}}
if('launchQueue'in globalThis)launchQueue.setConsumer(async p=>{for(const h of p.files||[]){try{const f=await h.getFile();if(typeof enterApp==='function'&&$('#splash'))enterApp('route');showTab('route');await importRoute(f);await analyzeLoaded()}catch(e){console.warn(e)}}});
setTimeout(inbox,400);
globalThis.TMFinder={search,load,geocode,brouter,components,viaPoints,searchOSM,stitch,pattern,fromWikiloc,nameFromWikiloc,keywords,overpass};
})();
