'use strict';
/* Ensayo 3D: vuelo sobre el relieve real siguiendo la ruta, con la hora de paso y la previsión de cada sector. */
const FLY={lib:null,map:null,raf:0,playing:false,t:0,dur:40000,last:0};
const ML='https://unpkg.com/maplibre-gl@4.7.1/dist/maplibre-gl';
function loadMapLibre(){if(globalThis.maplibregl)return Promise.resolve(globalThis.maplibregl);if(FLY.lib)return FLY.lib;FLY.lib=new Promise((res,rej)=>{const css=document.createElement('link');css.rel='stylesheet';css.href=ML+'.css';document.head.append(css);const s=document.createElement('script');s.src=ML+'.js';s.onload=()=>globalThis.maplibregl?res(globalThis.maplibregl):rej(Error('MapLibre no disponible'));s.onerror=()=>rej(Error('No se pudo descargar el motor 3D'));document.head.append(s)});FLY.lib.catch(()=>{FLY.lib=null});return FLY.lib}
const inSpain=p=>p.lat>35.5&&p.lat<44&&p.lon>-9.6&&p.lon<4.5;
function flyStyle(center){const pnoa='https://www.ign.es/wmts/pnoa-ma?SERVICE=WMTS&REQUEST=GetTile&VERSION=1.0.0&LAYER=OI.OrthoimageCoverage&STYLE=default&TILEMATRIXSET=GoogleMapsCompatible&FORMAT=image/jpeg&TILEMATRIX={z}&TILEROW={y}&TILECOL={x}';return{version:8,sources:{base:{type:'raster',tiles:[inSpain(center)?pnoa:'https://tile.openstreetmap.org/{z}/{x}/{y}.png'],tileSize:256,maxzoom:inSpain(center)?19:18,attribution:inSpain(center)?'Ortofoto © IGN · PNOA':'© OpenStreetMap contributors'},dem:{type:'raster-dem',tiles:['https://s3.amazonaws.com/elevation-tiles-prod/terrarium/{z}/{x}/{y}.png'],encoding:'terrarium',tileSize:256,maxzoom:14,attribution:'Relieve: AWS Terrain Tiles (Mapzen)'}},layers:[{id:'bg',type:'background',paint:{'background-color':'#e9eeec'}},{id:'base',type:'raster',source:'base',paint:{'raster-saturation':-.15,'raster-contrast':.05}},{id:'shade',type:'hillshade',source:'dem',paint:{'hillshade-exaggeration':.35,'hillshade-shadow-color':'#33424a','hillshade-highlight-color':'#ffffff'}}],terrain:{source:'dem',exaggeration:1.35}}}
const RISK={low:'#1d9b72',medium:'#d4861a',high:'#e14545',unknown:'#1d8ea3'};
function interp(pts,f){const total=pts.at(-1).km;const target=f*total;let i=1;while(i<pts.length-1&&pts[i].km<target)i++;const a=pts[i-1],b=pts[i],t=b.km>a.km?(target-a.km)/(b.km-a.km):0;return{lat:a.lat+(b.lat-a.lat)*t,lon:a.lon+(b.lon-a.lon)*t,km:target,i}}
async function openFly({name,points,rows=null}){if(!points?.length||points.length<2)return;closeFly();document.body.insertAdjacentHTML('beforeend',`<div class="fly" id="fly" role="dialog" aria-modal="true" aria-label="Ensayo 3D"><div class="fly-map" id="flyMap"></div><div class="fly-msg" id="flyMsg"><p><span class="spinner"></span>Cargando relieve 3D…</p></div><div class="fly-top"><h3>${esc(name||'Ruta')}</h3><div class="action-row"><button class="quiet" type="button" id="flyPlay">❚❚</button><button class="quiet" type="button" id="flySpeed">×1</button><button class="quiet" type="button" id="flyClose" aria-label="Cerrar">✕</button></div></div><div class="fly-hud" id="flyHud"></div><div class="fly-progress"><i id="flyBar"></i></div></div>`);$('#flyClose').onclick=closeFly;document.addEventListener('keydown',flyKey);if(typeof sfx==='function')sfx('open');
 const pts=points.map(p=>({...p}));if(!finite(pts[0].km)){let km=0;pts.forEach((p,i)=>{if(i)km+=TM.distance(pts[i-1],p);p.km=km})}
 let gl;try{gl=await loadMapLibre();if(!gl.supported?.({failIfMajorPerformanceCaveat:false})&&gl.supported)throw Error('Este dispositivo no admite WebGL')}catch(e){$('#flyMsg').innerHTML=`<p>${esc(e.message)}. El ensayo 3D necesita conexión y WebGL.</p>`;return}if(!$('#fly'))return;
 const center=pts[0];FLY.map=new gl.Map({container:'flyMap',style:flyStyle(center),center:[center.lon,center.lat],zoom:13.6,pitch:66,bearing:0,maxPitch:80,attributionControl:{compact:true},interactive:true});
 FLY.map.on('error',e=>{if(/dem|terrarium/.test(String(e?.error?.message||e?.sourceId||'')))$('#flyMsg').innerHTML='<p>No se pudo cargar el relieve.</p>'});
 FLY.map.on('load',()=>{$('#flyMsg').remove();const segs=[];for(let i=1;i<pts.length;i++){const row=rows?rows.reduce((b,q)=>!b||Math.abs(q.km-pts[i].km)<Math.abs(b.km-pts[i].km)?q:b,null):null;segs.push({type:'Feature',properties:{c:RISK[row?.assessment?.level||'unknown']},geometry:{type:'LineString',coordinates:[[pts[i-1].lon,pts[i-1].lat],[pts[i].lon,pts[i].lat]]}})}FLY.map.addSource('route',{type:'geojson',data:{type:'FeatureCollection',features:segs}});FLY.map.addLayer({id:'route-glow',type:'line',source:'route',paint:{'line-color':'#ffffff','line-width':12,'line-opacity':.55,'line-blur':4}});FLY.map.addLayer({id:'route',type:'line',source:'route',paint:{'line-color':['get','c'],'line-width':5},layout:{'line-cap':'round','line-join':'round'}});FLY.map.addSource('me',{type:'geojson',data:{type:'Point',coordinates:[center.lon,center.lat]}});FLY.map.addLayer({id:'me-halo',type:'circle',source:'me',paint:{'circle-radius':16,'circle-color':'#2f3a44','circle-opacity':.25,'circle-blur':.6}});FLY.map.addLayer({id:'me',type:'circle',source:'me',paint:{'circle-radius':7,'circle-color':'#ffffff','circle-stroke-color':'#10161a','circle-stroke-width':3}});
  FLY.dur=Math.max(25000,Math.min(70000,pts.at(-1).km*4500));FLY.t=0;FLY.playing=true;FLY.last=performance.now();FLY.speed=1;$('#flyPlay').onclick=()=>{FLY.playing=!FLY.playing;$('#flyPlay').textContent=FLY.playing?'❚❚':'▶';FLY.last=performance.now();if(FLY.playing)tick()};$('#flySpeed').onclick=()=>{FLY.speed=FLY.speed===1?2:FLY.speed===2?4:1;$('#flySpeed').textContent='×'+FLY.speed};
  const tick=now=>{if(!FLY.map||!FLY.playing)return;now=now||performance.now();FLY.t=Math.min(1,FLY.t+(now-FLY.last)/FLY.dur*FLY.speed);FLY.last=now;const here=interp(pts,FLY.t),ahead=interp(pts,Math.min(1,FLY.t+.03));const brg=FieldCore.bearing(here,ahead);FLY.map.getSource('me')?.setData({type:'Point',coordinates:[here.lon,here.lat]});FLY.map.jumpTo({center:[here.lon,here.lat],bearing:brg,pitch:66,zoom:14.1});$('#flyBar').style.width=(FLY.t*100)+'%';hud(here,pts,rows);if(FLY.t<1)FLY.raf=requestAnimationFrame(tick);else{FLY.playing=false;$('#flyPlay').textContent='↺';$('#flyPlay').onclick=()=>{FLY.t=0;FLY.playing=true;FLY.last=performance.now();$('#flyPlay').textContent='❚❚';tick()};FLY.map.easeTo({pitch:45,zoom:12.6,duration:2500})}};FLY.raf=requestAnimationFrame(tick)})}
function hud(here,pts,rows){const p=pts[Math.min(pts.length-1,here.i)],row=rows?rows.reduce((b,q)=>!b||Math.abs(q.km-here.km)<Math.abs(b.km-here.km)?q:b,null):null;const cell=(k,v)=>`<div><span>${k}</span><strong>${v}</strong></div>`;$('#flyHud').innerHTML=cell('Km',fmt(here.km,1))+cell('Altitud',finite(p.ele)?fmt(p.ele)+' m':'—')+cell('Hora de paso',row?exTime(row.eta).split(', ').pop():'—')+cell('Tiempo',row?.h?`${weather(row.h.weather_code)[0]} ${fmt(row.h.temperature_2m)}°`:'—')+cell('Rachas',row?.h?fmt(row.h.wind_gusts_10m)+' km/h':'—')}
function flyKey(e){if(e.key==='Escape')closeFly()}
function closeFly(){cancelAnimationFrame(FLY.raf);FLY.playing=false;try{FLY.map?.remove()}catch{}FLY.map=null;$('#fly')?.remove();document.removeEventListener('keydown',flyKey)}
$('#saveExpedition')?.insertAdjacentHTML('beforebegin','<button id="flyRoute" class="primary" type="button">◭ Ensayo 3D del día</button>');
$('#flyRoute')?.addEventListener('click',()=>{const r=S.route;if(!r)return;const p=typeof currentPlan==='function'?currentPlan():null;openFly({name:r.name,points:sample(r.points,400),rows:p?.rows||null})});
globalThis.TMFly={open:openFly,close:closeFly,interp};
