'use strict';
/* Combustible: lo que llevas para comer y beber, con datos nutricionales reales (Open Food Facts),
   sumados y comparados con lo que pide tu salida. */
(function(){
const KEY='tm.fuel.v1';
const NUT=[ // clave Open Food Facts, etiqueta, unidad mostrada, factor desde g/100 g
 ['energy-kcal','Energía','kcal',1],['carbohydrates','Hidratos','g',1],['sugars','Azúcares','g',1],['fiber','Fibra','g',1],['proteins','Proteínas','g',1],['fat','Grasas','g',1],['saturated-fat','Saturadas','g',1],['salt','Sal','g',1],['sodium','Sodio','mg',1000],['potassium','Potasio','mg',1000],['magnesium','Magnesio','mg',1000],['calcium','Calcio','mg',1000],['iron','Hierro','mg',1000],['vitamin-c','Vitamina C','mg',1000],['caffeine','Cafeína','mg',1000]];
const MACRO=['energy-kcal','carbohydrates','sugars','fiber','proteins','fat','saturated-fat','salt'];
/* Básicos sin marca, por 100 g (referencia aproximada, tablas BEDCA/USDA). */
const BASIC=[
 ['Plátano',89,22.8,12.2,2.6,1.1,.3,.1,0.003,358,27,5,.26,8.7],['Dátiles secos',282,75,63,8,2.5,.4,0,.005,656,43,39,1,0],['Pasas',299,79,59,3.7,3.1,.5,.1,.03,749,32,50,1.9,2.3],['Orejones de albaricoque',241,63,53,7.3,3.4,.5,0,.025,1162,32,55,2.7,1],['Almendras',579,21.6,4.4,12.5,21.2,49.9,3.8,.001,733,270,269,3.7,0],['Nueces',654,13.7,2.6,6.7,15.2,65.2,6.1,.005,441,158,98,2.9,1.3],['Manzana',52,13.8,10.4,2.4,.3,.2,0,.001,107,5,6,.1,4.6],['Chocolate negro 70 %',598,45.9,24,10.9,7.8,42.6,24.5,.05,715,228,73,11.9,0],['Pan blanco (genérico)',265,49,5,2.7,9,3.2,.7,1.2,115,25,260,3.6,0],['Jamón serrano',241,0,0,0,30.5,13,4.5,5,350,20,10,1.4,0],['Queso curado',413,.5,.5,0,26,34,22,1.7,90,40,800,.5,0],['Arroz cocido',130,28,.1,.4,2.7,.3,.1,0,35,12,10,.2,0],['Pasta cocida',158,31,.6,1.8,5.8,.9,.2,0,44,18,7,.5,0],['Bebida isotónica (genérica)',26,6.4,6,0,0,0,0,.12,13,0,0,0,0],['Gel energético (genérico)',270,67,22,0,0,0,0,.5,40,0,0,0,0],['Barrita de cereales (genérica)',400,68,28,4,6,11,4,.3,200,40,30,1.5,0]];
const F={items:[],results:[],weight:70,intensity:'moderada',hours:null,seq:0,ctrl:null};
const n=v=>typeof v==='number'&&Number.isFinite(v);
const f1=(v,d=0)=>n(v)?v.toLocaleString('es-ES',{maximumFractionDigits:d,minimumFractionDigits:d}):'—';
function load(){try{const d=JSON.parse(localStorage.getItem(KEY)||'{}');F.items=Array.isArray(d.items)?d.items:[];F.weight=d.weight||70;F.intensity=d.intensity||'moderada'}catch{}}
function save(){try{localStorage.setItem(KEY,JSON.stringify({items:F.items,weight:F.weight,intensity:F.intensity}))}catch{}}
const per100=p=>{const o={};for(const [k] of NUT){const v=p.nutriments?.[k+'_100g'];if(n(Number(v)))o[k]=Number(v)}if(!n(o['energy-kcal'])&&n(Number(p.nutriments?.['energy_100g'])))o['energy-kcal']=Number(p.nutriments['energy_100g'])/4.184;if(!n(o.sodium)&&n(o.salt))o.sodium=o.salt/2.5;if(!n(o.salt)&&n(o.sodium))o.salt=o.sodium*2.5;return o};
const servingG=s=>{const m=String(s||'').replace(',','.').match(/(\d+(?:\.\d+)?)\s*(g|ml)\b/i);return m?Number(m[1]):null};
function basics(q){q=q.toLowerCase().normalize('NFD').replace(/[̀-ͯ]/g,'');return BASIC.filter(b=>b[0].toLowerCase().normalize('NFD').replace(/[̀-ͯ]/g,'').includes(q)).map(b=>({code:'basic:'+b[0],name:b[0],brand:'Referencia genérica',serving:null,source:'BEDCA/USDA (aprox.)',n:{'energy-kcal':b[1],carbohydrates:b[2],sugars:b[3],fiber:b[4],proteins:b[5],fat:b[6],'saturated-fat':b[7],salt:b[8],sodium:b[8]/2.5,potassium:b[9]/1000,magnesium:b[10]/1000,calcium:b[11]/1000,iron:b[12]/1000,'vitamin-c':b[13]/1000}}))}
async function searchOFF(q,signal){const params=new URLSearchParams({search_terms:q,search_simple:'1',action:'process',json:'1',page_size:'24',fields:'code,product_name,product_name_es,brands,nutriments,serving_size,quantity,image_small_url',tagtype_0:'countries',tag_contains_0:'contains',tag_0:'spain',sort_by:'unique_scans_n'});const ck='tm.off.'+q.toLowerCase();let d=null;try{const c=JSON.parse(sessionStorage.getItem(ck)||'null');if(c&&Date.now()-c.at<3600000)d=c.d}catch{}if(!d){let last;for(const [host,wait] of [['es',0],['world',1200],['es',2500]]){if(wait)await new Promise(r=>setTimeout(r,wait));if(signal?.aborted)throw Error('Cancelado');try{const r=await fetch(`https://${host}.openfoodfacts.org/cgi/search.pl?`+params,{signal,credentials:'omit'});if(!r.ok)throw Error('Open Food Facts no respondió ('+r.status+')');d=await r.json();break}catch(e){last=e;if(signal?.aborted)throw e}}if(!d)throw last||Error('Open Food Facts no disponible');try{sessionStorage.setItem(ck,JSON.stringify({at:Date.now(),d:{products:(d.products||[]).slice(0,24)}}))}catch{}}return(d.products||[]).map(p=>({code:p.code,name:(p.product_name_es||p.product_name||'').trim(),brand:String(p.brands||'').split(',').map(s=>s.trim()).filter(Boolean).slice(-1)[0]||'',serving:servingG(p.serving_size),servingText:p.serving_size||'',quantity:p.quantity||'',img:p.image_small_url||'',source:'Open Food Facts',n:per100(p)})).filter(p=>p.name&&n(p.n['energy-kcal']))}
async function byBarcode(code){const r=await fetch('https://world.openfoodfacts.org/api/v2/product/'+encodeURIComponent(code)+'.json?fields=code,product_name,product_name_es,brands,nutriments,serving_size,quantity',{credentials:'omit'});const d=await r.json();if(!d.product)throw Error('Producto no encontrado');const p=d.product;return{code:p.code,name:(p.product_name_es||p.product_name||'Producto').trim(),brand:String(p.brands||'').split(',').pop().trim(),serving:servingG(p.serving_size),servingText:p.serving_size||'',source:'Open Food Facts',n:per100(p)}}

/* ---------- Cálculos ---------- */
function totals(){const t={},cov={};for(const it of F.items){const g=it.grams*(it.units||1);for(const [k] of NUT){if(n(it.n[k])){t[k]=(t[k]||0)+it.n[k]*g/100;cov[k]=(cov[k]||0)+1}}}return{t,cov}}
function planHours(){try{const p=typeof currentPlan==='function'&&currentPlan();if(p)return{h:(p.arrival-p.start)/3600000,name:S.route?.name,temp:Math.max(...p.rows.map(q=>q.h?.temperature_2m).filter(n))}}catch{}return null}
function needs(h,temp){const I={suave:{met:5,carb:[20,30],na:[200,400]},moderada:{met:6.5,carb:[30,60],na:[300,600]},intensa:{met:8.5,carb:[60,90],na:[500,900]}}[F.intensity];const hot=n(temp)&&temp>=24;return{kcal:I.met*F.weight*h,carb:[I.carb[0]*h,I.carb[1]*h],na:[I.na[0]*h*(hot?1.3:1),I.na[1]*h*(hot?1.3:1)],water:[(hot?.6:.4)*h,(hot?.9:.7)*h]}}

/* ---------- Interfaz ---------- */
function shell(){const el=$('#pane-fuel');if(!el||el.dataset.ready)return;el.dataset.ready='1';el.innerHTML=`<header class="fu-head"><p class="eyebrow">Ruta</p><h2>Combustible para tu salida</h2><p class="fu-lead">Busca lo que vas a llevar, indica cuánto y suma calorías, hidratos, sales y micronutrientes con los datos reales de cada producto.</p></header>
<form class="fu-search" id="fuForm"><label class="sr" for="fuQuery">Alimento y marca</label><input id="fuQuery" maxlength="80" autocomplete="off" placeholder="Ej.: pan Bimbo natural, membrillo Hacendado, dátiles…"><button class="primary" type="submit">Buscar</button><button class="quiet" type="button" id="fuScan" hidden>▦ Código de barras</button></form>
<p class="fu-hint">Datos de <a href="https://es.openfoodfacts.org" target="_blank" rel="noopener">Open Food Facts</a> (etiquetas reales, base abierta) y una lista de básicos sin marca con valores de referencia.</p><p id="fuStatus" class="wl-status" role="status"></p><ul class="fu-results" id="fuResults"></ul>
<section class="fu-list"><h3>Lo que llevas</h3><ul id="fuItems"></ul><p class="fu-empty" id="fuEmpty">Aún no has añadido nada. Busca un alimento y pulsa <b>Añadir</b>.</p></section>
<section class="fu-tot"><h3>Total</h3><div id="fuTotals"></div><details class="fu-micro"><summary>Micronutrientes</summary><div id="fuMicro"></div></details></section>
<section class="fu-need"><h3>¿Es suficiente para tu salida?</h3><div class="fu-params"><label>Duración (h)<input id="fuHours" type="number" min="0.5" max="24" step="0.25"></label><label>Tu peso (kg)<input id="fuWeight" type="number" min="30" max="150" step="1"></label><label>Intensidad<select id="fuIntensity"><option value="suave">Suave · paseo</option><option value="moderada">Moderada · senderismo de montaña</option><option value="intensa">Intensa · trail o mucho desnivel</option></select></label></div><div id="fuNeed"></div><p class="footnote">Referencias habituales para actividad de resistencia: 30–60 g de hidratos por hora (hasta 90 g en esfuerzos intensos y largos), 300–600 mg de sodio por hora y 0,4–0,8 L de agua por hora según el calor. Son orientativas: ajusta según tu experiencia.</p></section>`;
 $('#fuWeight').value=F.weight;$('#fuIntensity').value=F.intensity;
 $('#fuForm').onsubmit=e=>{e.preventDefault();search($('#fuQuery').value)};
 $('#fuResults').onclick=e=>{const b=e.target.closest('[data-fu-add]');if(!b)return;const p=F.results[+b.dataset.fuAdd];if(!p)return;F.items.push({code:p.code,name:p.name,brand:p.brand,source:p.source,n:p.n,grams:p.serving||100,units:1,servingText:p.servingText||''});save();renderItems();if(typeof sfx==='function')sfx('ok');b.textContent='✓ Añadido';b.disabled=true};
 $('#fuItems').oninput=e=>{const i=e.target.closest('[data-i]');if(!i)return;const it=F.items[+i.dataset.i];if(e.target.name==='g')it.grams=Math.max(0,Number(e.target.value)||0);if(e.target.name==='u')it.units=Math.max(0,Number(e.target.value)||0);save();renderTotals()};
 $('#fuItems').onclick=e=>{const b=e.target.closest('[data-fu-del]');if(!b)return;F.items.splice(+b.dataset.fuDel,1);save();renderItems()};
 ['fuHours','fuWeight','fuIntensity'].forEach(id=>$('#'+id).addEventListener('input',()=>{F.weight=Number($('#fuWeight').value)||70;F.intensity=$('#fuIntensity').value;F.hours=Number($('#fuHours').value)||null;save();renderTotals()}));
 if('BarcodeDetector'in globalThis&&navigator.mediaDevices?.getUserMedia){$('#fuScan').hidden=false;$('#fuScan').onclick=scan}
 renderItems()}
async function search(q){q=String(q||'').trim();const st=$('#fuStatus');if(q.length<2){st.className='wl-status err';st.textContent='Escribe al menos 2 letras.';return}const seq=++F.seq;F.ctrl?.abort();const c=new AbortController();F.ctrl=c;st.className='wl-status';st.innerHTML='<span class="spinner"></span>Buscando «'+esc(q)+'»…';const base=basics(q);F.results=base;renderResults();
 try{const off=await searchOFF(q,c.signal);if(seq!==F.seq)return;F.results=[...off,...base];renderResults();st.className='wl-status ok';st.textContent=F.results.length?`${F.results.length} resultado${F.results.length>1?'s':''}. Valores por 100 g; al añadir se usa la ración de la etiqueta si existe.`:'Sin resultados. Prueba con otras palabras o con la marca.'}catch(e){if(c.signal.aborted&&seq!==F.seq)return;st.className='wl-status err';st.textContent=(base.length?'Solo básicos: ':'')+'Open Food Facts no respondió ('+e.message+'). Inténtalo de nuevo.'}}
function renderResults(){$('#fuResults').innerHTML=F.results.slice(0,24).map((p,i)=>`<li><div class="fu-r-main"><b>${esc(p.name)}</b><span>${esc(p.brand)}${p.quantity?' · '+esc(p.quantity):''}${p.serving?' · ración '+f1(p.serving)+' g':''}</span></div><div class="fu-r-n"><span>${f1(p.n['energy-kcal'])} kcal</span><span>${f1(p.n.carbohydrates,1)} g HC</span><span>${f1(p.n.proteins,1)} g P</span><span>${f1(p.n.fat,1)} g G</span><small>por 100 g</small></div><button class="quiet" type="button" data-fu-add="${i}">Añadir</button></li>`).join('')}
function renderItems(){const ul=$('#fuItems');if(!ul)return;$('#fuEmpty').hidden=F.items.length>0;ul.innerHTML=F.items.map((it,i)=>`<li data-i="${i}"><div class="fu-i-main"><b>${esc(it.name)}</b><span>${esc(it.brand||'')}${it.servingText?' · ración '+esc(it.servingText):''} · ${esc(it.source||'')}</span></div><label>g<input name="g" type="number" min="0" step="1" value="${it.grams}"></label><label>×<input name="u" type="number" min="0" step="1" value="${it.units||1}"></label><span class="fu-i-k" data-k="${i}"></span><button class="quiet" type="button" data-fu-del="${i}" aria-label="Quitar ${esc(it.name)}">✕</button></li>`).join('');renderTotals()}
function renderTotals(){const {t,cov}=totals();F.items.forEach((it,i)=>{const el=document.querySelector(`[data-k="${i}"]`);if(el)el.textContent=f1(it.n['energy-kcal']*it.grams*(it.units||1)/100)+' kcal'});const N=Object.fromEntries(NUT.map(x=>[x[0],x]));const cell=k=>{const [,l,u,fac]=N[k];return `<div class="fu-k"><strong>${f1((t[k]||0)*fac,u==='kcal'||u==='mg'?0:1)}<small>${u}</small></strong><span>${l}${F.items.length&&cov[k]<F.items.length?` · ${cov[k]||0}/${F.items.length} con dato`:''}</span></div>`};
 $('#fuTotals').innerHTML=`<div class="fu-kpis">${MACRO.map(cell).join('')}</div>${t.carbohydrates?`<p class="fu-split">${(()=>{const kc=(t.carbohydrates||0)*4+(t.proteins||0)*4+(t.fat||0)*9;return kc?`Reparto de la energía: <b>${f1((t.carbohydrates||0)*4/kc*100)} %</b> hidratos · <b>${f1((t.proteins||0)*4/kc*100)} %</b> proteínas · <b>${f1((t.fat||0)*9/kc*100)} %</b> grasas.`:''})()}</p>`:''}`;
 $('#fuMicro').innerHTML=`<div class="fu-kpis">${NUT.filter(x=>!MACRO.includes(x[0])).map(x=>cell(x[0])).join('')}</div><p class="footnote">Los micronutrientes solo cuentan si la etiqueta del producto los declara.</p>`;
 const plan=planHours();const hEl=$('#fuHours');if(hEl&&!F.hours&&plan&&!hEl.value)hEl.value=(Math.round(plan.h*4)/4).toString();const h=Number(hEl?.value)||plan?.h||null;const need=$('#fuNeed');if(!need)return;if(!h){need.innerHTML='<p class="muted">Indica la duración o analiza una ruta en Planificar para comparar.</p>';return}const nd=needs(h,plan?.temp);
 const bar=(have,[lo,hi],unit,label,dec=0)=>{const pct=Math.min(130,have/hi*100);const state=have<lo?'low':have>hi*1.3?'high':'ok';return `<div class="fu-bar ${state}"><div class="fu-bar-t"><b>${label}</b><span>${f1(have,dec)} ${unit} de ${f1(lo,dec)}–${f1(hi,dec)} ${unit}</span></div><i style="--p:${pct}%"></i><em>${state==='low'?'Te quedas corto':state==='high'?'Más de lo necesario':'Bien'}</em></div>`};
 need.innerHTML=`<p class="fu-need-ctx">${plan?`Ruta «${esc(plan.name)}» · `:''}${f1(h,1)} h de actividad · gasto estimado <b>${f1(nd.kcal)} kcal</b> (${F.weight} kg, intensidad ${F.intensity}).</p>${bar(t.carbohydrates||0,nd.carb,'g','Hidratos')}${bar((t.sodium||0)*1000,nd.na,'mg','Sodio')}${bar(t['energy-kcal']||0,[nd.kcal*.3,nd.kcal*.6],'kcal','Energía que repones')}<p class="fu-water">Agua recomendada: <b>${f1(nd.water[0],1)}–${f1(nd.water[1],1)} L</b>${plan&&n(plan.temp)&&plan.temp>=24?' (hace calor: apunta al máximo)':''}.</p>`}
async function scan(){const st=$('#fuStatus');let stream;try{stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:'environment'}});const v=document.createElement('video');v.srcObject=stream;v.playsInline=true;await v.play();document.body.insertAdjacentHTML('beforeend','<div class="fu-scan" id="fuScanBox"><p>Apunta al código de barras</p><button class="quiet" type="button" id="fuScanClose">Cancelar</button></div>');$('#fuScanBox').prepend(v);let stop=false;$('#fuScanClose').onclick=()=>{stop=true};const det=new BarcodeDetector({formats:['ean_13','ean_8','upc_a','upc_e']});while(!stop){const codes=await det.detect(v).catch(()=>[]);if(codes[0]){const p=await byBarcode(codes[0].rawValue);F.results=[p];renderResults();st.className='wl-status ok';st.textContent='Producto encontrado: '+p.name;break}await new Promise(r=>setTimeout(r,300))}}catch(e){st.className='wl-status err';st.textContent='No se pudo escanear: '+e.message}finally{stream?.getTracks().forEach(t=>t.stop());$('#fuScanBox')?.remove()}}

load();shell();
const prevShow=showTab;showTab=function(t){prevShow.apply(this,arguments);if(t==='fuel'){shell();renderTotals()}};
globalThis.TMFuel={search,searchOFF,basics,totals,needs,per100,servingG,get items(){return F.items},add(p,g){F.items.push({...p,grams:g||p.serving||100,units:1});save();renderItems()},clear(){F.items=[];save();renderItems()}};
})();
