'use strict';
/* Semáforo de la salida, mochila según la previsión y compartir el plan. Reglas visibles; no sustituyen el criterio propio. */
$('#expeditionBrief')?.insertAdjacentHTML('beforebegin','<div id="goMeter" class="go-meter unknown" aria-live="polite"></div>');
$('#saveExpedition')?.insertAdjacentHTML('afterend','<button id="shareExpedition" class="quiet" type="button">↗ Compartir plan</button>');
$('#expeditionPanel')?.querySelector('article.card:nth-of-type(2)')?.insertAdjacentHTML('beforebegin','<article class="card" id="gearCard"><div class="sectionhead"><div><p class="eyebrow">MOCHILA SEGÚN LA PREVISIÓN</p><h3>Qué llevar en esta salida</h3></div><span class="pill" id="gearCount"></span></div><div id="gearList" class="gear-grid"></div><p class="footnote">Lista generada por reglas a partir de la duración, la luz y la previsión en los puntos de la ruta. Marca lo que ya llevas; se recuerda en este dispositivo.</p></article>');
function gearKey(){return 'tm.gear.'+(S.route?.name||'ruta')}
function gearItems(p){const r=S.route,known=p.rows.filter(q=>q.h),items=[],add=(id,name,why,level='low')=>items.push({id,name,why,level});const hrs=finite(p.arrival)&&finite(p.start)?(p.arrival-p.start)/3600000:null;const temps=known.map(q=>q.h.temperature_2m).filter(finite),app=known.map(q=>finite(q.h.apparent_temperature)?q.h.apparent_temperature:q.h.temperature_2m).filter(finite),tmin=temps.length?Math.min(...app):null,tmax=temps.length?Math.max(...temps):null,uv=Math.max(0,...known.map(q=>q.h.uv_index).filter(finite)),vis=Math.min(Infinity,...known.map(q=>q.h.visibility).filter(finite)),storm=known.some(q=>q.h.weather_code>=95),fz=Math.min(Infinity,...known.map(q=>q.h.freezing_level_height).filter(finite)),topEle=Math.max(-Infinity,...r.points.map(q=>q.ele).filter(finite)),wet=known.filter(q=>q.h.precipitation>=.3).length;
 add('water',`Agua: ${hrs?fmt(Math.max(1,Math.ceil(hrs*(tmax>=24?.75:.5)*2)/2),1):'1+'} L`,hrs?`≈${fmt(hrs,1)} h de marcha${tmax>=24?' con calor':''}. Comprueba fuentes antes de contar con ellas.`:'Duración no calculada.',tmax>=26?'medium':'low');
 add('food','Comida y sales',hrs?`${fmt(Math.round(hrs*200/50)*50)} kcal aprox. (≈200 kcal/h)`:'Para toda la jornada');
 add('phone','Móvil cargado + batería externa','Emergencias 112. Guarda la ruta para usarla sin cobertura.');
 add('kit','Botiquín y manta térmica','Ligero, siempre.');
 const light=p.arrivalLight;if(!light||!light.day||light.remaining<90)add('lamp','Frontal con pilas',light?(light.day?`Llegas ${fmt(light.remaining)} min antes del ocaso`:'Llegada fuera de horas de sol'):'Sin dato de luz','medium');
 if(p.maxRain>=.3||wet)add('shell','Chaqueta impermeable',`Lluvia hasta ${fmt(p.maxRain,1)} mm/h en ${wet} puntos`,p.maxRain>=4?'high':'medium');
 if(wet>=3)add('spare','Ropa seca de recambio','Varias horas con lluvia prevista','medium');
 if(p.maxGust>=35)add('wind','Cortavientos',`Rachas hasta ${fmt(p.maxGust)} km/h${p.maxGust>=60?': evita crestas y collados expuestos':''}`,p.maxGust>=60?'high':'medium');
 if(tmin!==null&&tmin<=6)add('warm','Capa térmica, guantes y gorro',`Sensación mínima ${fmt(tmin)} °C`,tmin<=0?'high':'medium');
 if(finite(fz)&&finite(topEle)&&fz<topEle+200)add('ice','Valora microcrampones',`Isoterma 0 °C a ${fmt(fz)} m y la ruta llega a ${fmt(topEle)} m: posible hielo o nieve`,'high');
 if(tmax!==null&&tmax>=24||uv>=6)add('sun','Gorra, gafas y crema solar',`${tmax>=24?'Hasta '+fmt(tmax)+' °C':''}${uv>=6?(tmax>=24?' · ':'')+'UV '+fmt(uv,1):''}`,uv>=8||tmax>=30?'medium':'low');
 if(vis<3000)add('nav','Track sin conexión y brújula',`Visibilidad hasta ${fmt(vis/1000,1)} km`,vis<1000?'high':'medium');
 if(storm)add('storm','Plan B sin crestas','Tormenta prevista en algún punto: define dónde retirarte','high');
 if(r.summary.elevationComplete&&r.summary.up>800)add('poles','Bastones',`+${fmt(r.summary.up)} m de desnivel`);
 return items}
function renderGear(){const p=currentPlan();if(!p||!$('#gearList'))return;let checked={};try{checked=JSON.parse(localStorage.getItem(gearKey()))||{}}catch{}const items=gearItems(p);$('#gearList').innerHTML=items.map(it=>`<label class="gear-item why-${it.level}"><input type="checkbox" data-gear="${it.id}" ${checked[it.id]?'checked':''}><span><b>${esc(it.name)}</b><small>${esc(it.why)}</small></span></label>`).join('');const done=()=>{const n=$$('[data-gear]').filter(x=>x.checked).length;$('#gearCount').textContent=`${n}/${items.length} listo`};done();$('#gearList').onchange=e=>{const b=e.target.closest('[data-gear]');if(!b)return;checked[b.dataset.gear]=b.checked;try{localStorage.setItem(gearKey(),JSON.stringify(checked))}catch{}done();if(b.checked&&typeof sfx==='function')sfx('tap')};
 const medium=p.rows.filter(q=>q.assessment.level==='medium').length,level=p.high?'high':medium?'medium':p.complete?'low':'unknown',label={high:['STOP','Replantea la salida',`${p.high} puntos con condiciones exigentes a tu hora de paso. Prueba otra hora en «Comparar horas de salida».`],medium:['OJO','Sal con precauciones',`${medium} puntos con alguna señal: ${[...new Set(p.rows.flatMap(q=>q.assessment.risks))].slice(0,3).join(' · ')}.`],low:['GO','Ventana favorable','Sin señales adversas en los puntos consultados. No certifica el estado del terreno.'],unknown:['?','Datos incompletos',`${p.known}/${p.rows.length} puntos con previsión. Actualiza o elige una salida más próxima.`]}[level];$('#goMeter').className='go-meter '+level;$('#goMeter').innerHTML=`<div class="dial">${label[0]}</div><div><h3>${esc(label[1])}</h3><p>${esc(label[2])}</p></div>`}
const gearRenderExpedition=renderExpedition;renderExpedition=function(){gearRenderExpedition();try{renderGear()}catch{}};
$('#shareExpedition')?.addEventListener('click',async()=>{const p=currentPlan(),r=S.route;if(!p||!r)return;const text=`${r.name}\nSalida ${exTime(p.start)} · llegada ≈ ${exTime(p.arrival)}\n${fmt(r.summary.km,1)} km${r.summary.elevationComplete?' · +'+fmt(r.summary.up)+' m':''}\nRacha máx. ${fmt(p.maxGust)} km/h · lluvia máx. ${fmt(p.maxRain,1)} mm/h · ${p.high} puntos exigentes\n${$('#emergencyContact')?.value?'Contacto: '+$('#emergencyContact').value+'\n':''}Plan hecho con TrailMeteo. Emergencias: 112.`;try{if(navigator.share)await navigator.share({title:'Mi plan · '+r.name,text});else{await navigator.clipboard.writeText(text);$('#saveStatus').textContent='Plan copiado al portapapeles: pégalo en WhatsApp o un mensaje.'}}catch{}});
