'use strict';
const homeContours=Array.from({length:14},(_,i)=>{const y=70+i*27;return `<path d="M-40 ${y+160} C120 ${y+250},170 ${y-140},340 ${y-60} S540 ${y+210},720 ${y-15} S940 ${y-100},1100 ${y+110}"/>`}).join('');
$('#main').insertAdjacentHTML('beforebegin',`<section id="homeScreen" class="home-screen"><div class="home-hero"><div class="home-copy"><p class="eyebrow">TRAILMETEO · PLANIFICA CON PERSPECTIVA</p><h1>Tu ruta.<br>El tiempo.<br><em>La decisión.</em></h1><p class="home-intro">Entiende qué condiciones te esperan en cada tramo, compara cuándo salir y lleva tu plan contigo, incluso sin cobertura.</p><div class="home-actions"><button class="primary" data-go="route">Preparar una ruta <span aria-hidden="true">↗</span></button><button class="quiet" data-go="now">Consultar el tiempo</button></div><p class="home-note">Sin cuenta ni claves personales. En tu navegador.</p></div><div class="home-art" aria-hidden="true"><svg viewBox="0 0 1000 700" preserveAspectRatio="xMidYMid slice"><defs><radialGradient id="terrainGlow"><stop stop-color="#b9d9cb"/><stop offset="1" stop-color="#e7eeea"/></radialGradient></defs><rect width="1000" height="700" fill="url(#terrainGlow)"/><g class="contour-lines">${homeContours}</g><path class="hero-trail" d="M210 630 C240 540,480 570,380 440 S250 380,370 300 S620 310,610 190 S670 140,760 90"/><circle class="trail-beacon" cx="610" cy="190" r="13"/><circle cx="210" cy="630" r="8" fill="#174f67"/></svg><div class="art-label"><span>LEE EL RECORRIDO</span><strong>Antes de dar<br>el primer paso.</strong><small>Ilustración cartográfica</small></div><div class="art-coordinates">TIEMPO × TERRENO × HORARIO</div></div></div>
<nav class="home-shortcuts" aria-label="Accesos principales"><button data-go="radar"><span>01</span><b>Radar</b><small>Precipitación observada</small><i>↗</i></button><button data-go="mountain"><span>02</span><b>Montaña</b><small>Boletines oficiales AEMET</small><i>↗</i></button><button data-go="models"><span>03</span><b>Modelos</b><small>Acuerdos y diferencias</small><i>↗</i></button><button data-go="route" data-library="true"><span>04</span><b>Mis rutas</b><small>Planes guardados aquí</small><i>↗</i></button></nav>
<section class="home-explainer"><div><p class="eyebrow">DE LA PREVISIÓN A TU SALIDA</p><h2>Más contexto.<br>Mejores preguntas.</h2></div><div class="home-steps"><article><span>01 / CARGA</span><h3>Empieza por tu GPX</h3><p>Consulta el perfil, la distancia y el tiempo previsto en los puntos del recorrido a tu hora estimada de paso.</p></article><article><span>02 / CONTRASTA</span><h3>Compara escenarios</h3><p>Cambia la salida, revisa la luz restante, las diferencias entre modelos y los avisos que coinciden con tu ruta.</p></article><article><span>03 / DOCUMENTA</span><h3>Conoce lo que falta</h3><p>La tecnicidad se apoya en atributos cartográficos y referencias por tramo. Sin evidencia, aparece como desconocida.</p></article><article><span>04 / LLEVA</span><h3>Guarda tu plan</h3><p>Conserva datos, contacto, referencias y un mapa vectorial en este dispositivo. Recalcula tu llegada al avanzar.</p></article></div></section><section class="home-principles"><p class="eyebrow">FUENTES A LA VISTA</p><h2>Datos abiertos.<br>Incertidumbre visible.</h2><p>Open-Meteo, MET Norway, AEMET, RainViewer y OpenStreetMap. Cada lectura conserva sus límites: una previsión no es una observación y la ausencia de datos no significa ausencia de peligro.</p><button class="quiet" data-go="models">Conocer las fuentes →</button></section><footer class="home-footer"><span>TrailMeteo · Preparar, contrastar, salir.</span><button class="quiet" data-go="route">Empezar con una ruta ↗</button></footer></section>`);
$('.topbar').insertAdjacentHTML('beforeend',`<button id="homeButton" class="quiet" aria-label="Volver al inicio">Inicio</button><button id="menuButton" class="quiet" aria-expanded="false" aria-controls="siteMenu">Menú <span aria-hidden="true">☰</span></button><nav id="siteMenu" class="site-menu" aria-label="Menú principal" hidden><button data-home>Inicio</button><button data-go="now">Tiempo</button><button data-go="radar">Radar</button><button data-go="route">Planificador y rutas guardadas</button><button data-go="mountain">AEMET Montaña</button><button data-go="models">Modelos y fuentes</button></nav>`);
function closeSiteMenu(){$('#siteMenu').hidden=true;$('#menuButton').setAttribute('aria-expanded','false')}
function goHome(){stopRadar();$('#homeScreen').hidden=false;$('#main').hidden=true;closeSiteMenu();history.replaceState(null,'',location.pathname+location.search+'#inicio');window.scrollTo({top:0,behavior:'smooth'})}
function enterApp(tab,library=false){$('#homeScreen').hidden=true;$('#main').hidden=false;closeSiteMenu();showTab(tab);history.replaceState(null,'',location.pathname+location.search+'#'+tab);if(library)$('#routeLibrary').scrollIntoView({behavior:'smooth'});else window.scrollTo({top:0,behavior:'smooth'})}
$$('[data-go]').forEach(b=>b.onclick=()=>enterApp(b.dataset.go,b.dataset.library==='true'));$$('[data-home]').forEach(b=>b.onclick=goHome);$('#homeButton').onclick=goHome;$('.brand').onclick=e=>{e.preventDefault();goHome()};$('#menuButton').onclick=()=>{const open=$('#siteMenu').hidden;$('#siteMenu').hidden=!open;$('#menuButton').setAttribute('aria-expanded',String(open))};document.addEventListener('keydown',e=>{if(e.key==='Escape')closeSiteMenu()});document.addEventListener('click',e=>{if(!e.target.closest('#siteMenu')&&!e.target.closest('#menuButton'))closeSiteMenu()});
const priorAppTab=showTab;showTab=function(tab){$('#homeScreen').hidden=true;$('#main').hidden=false;priorAppTab(tab)};
function applyHash(){const tab=location.hash.slice(1);if(['now','radar','route','mountain','models'].includes(tab))enterApp(tab);else goHome()}
window.addEventListener('hashchange',()=>{if(['#inicio','#now','#radar','#route','#mountain','#models'].includes(location.hash))applyHash()});
const seen=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('revealed');seen.unobserve(e.target)}}),{threshold:.12});$$('.home-explainer article,.home-principles').forEach(el=>{el.classList.add('reveal');seen.observe(el)});applyHash();

$('.skip').onclick=e=>{if(!$('#homeScreen').hidden){e.preventDefault();$('#homeScreen').setAttribute('tabindex','-1');$('#homeScreen').focus()}};
