'use strict';
/* Comparación por horas entre modelos, estilo Windy: una fila por modelo, variable a variable. */
(function(){
const MODELS=[['ecmwf_ifs025','ECMWF'],['icon_seamless','ICON'],['gfs_seamless','GFS'],['meteofrance_seamless','Météo-France'],['ukmo_seamless','UKMO'],['gem_seamless','GEM']];
const VARS=[['temperature_2m','Temperatura','°C'],['precipitation','Lluvia','mm'],['wind_speed_10m','Viento','km/h'],['wind_gusts_10m','Rachas','km/h'],['cloud_cover','Nubes','%']];
const MG={step:1,data:null,key:'',seq:0};
const n=v=>typeof v==='number'&&Number.isFinite(v);
function color(k,v){if(!n(v))return'transparent';if(k==='temperature_2m'){const t=Math.max(-10,Math.min(35,v));const h=t<=0?220:t<15?200-(t/15)*110:90-((t-15)/20)*90;return `hsl(${h} 70% ${t<=0?78:72}%)`}if(k==='precipitation')return v<.1?'transparent':`hsl(210 80% ${Math.max(45,85-v*8)}%)`;if(k==='cloud_cover')return `hsl(210 10% ${96-v*.35}%)`;const w=Math.min(90,v);return w<10?'transparent':`hsl(${50-w*.55} 85% ${88-w*.35}%)`}
function arrow(d){return n(d)?`<i class="mg-dir" style="transform:rotate(${d+180}deg)">↑</i>`:''}
async function load(force){const l=S.location;if(!l)return;const key=l.lat.toFixed(2)+','+l.lon.toFixed(2);if(!force&&MG.key===key&&MG.data)return render();const seq=++MG.seq;const box=$('#mgBody');if(box)box.innerHTML='<p class="muted"><span class="spinner"></span>Cargando modelos…</p>';
 try{const url='https://api.open-meteo.com/v1/forecast?'+new URLSearchParams({latitude:l.lat,longitude:l.lon,hourly:[...VARS.map(v=>v[0]),'wind_direction_10m'].join(','),models:MODELS.map(m=>m[0]).join(','),forecast_days:'3',timezone:'auto'});const r=await fetch(url);if(!r.ok)throw Error('Open-Meteo '+r.status);const d=await r.json();if(seq!==MG.seq)return;MG.data=d;MG.key=key;render()}catch(e){if(box)box.innerHTML='<p class="muted">No se pudo cargar la comparación: '+esc(e.message)+'</p>'}}
function render(){const d=MG.data,box=$('#mgBody');if(!d||!box)return;const h=d.hourly,now=Date.now();const idx=h.time.map((t,i)=>[new Date(t).getTime()+(d.utc_offset_seconds||0)*0-0,i]).filter(([t])=>t>=now-3600000).filter((_,j)=>j%MG.step===0).slice(0,MG.step===1?36:40).map(([,i])=>i);
 const times=idx.map(i=>h.time[i]);const head=`<tr><th class="mg-sticky">Hora</th>${times.map((t,j)=>{const dt=new Date(t);const day=dt.getHours()<MG.step||j===0;return `<th class="${day?'mg-day':''}">${day?`<small>${dt.toLocaleDateString('es-ES',{weekday:'short',day:'numeric'})}</small>`:''}${String(dt.getHours()).padStart(2,'0')}</th>`}).join('')}</tr>`;
 const avail=MODELS.filter(([id])=>(h[VARS[0][0]+'_'+id]||[]).some(n));
 const body=VARS.map(([k,label,unit])=>`<tr class="mg-var"><th class="mg-sticky" colspan="1">${label} <small>${unit}</small></th><td colspan="${times.length}"></td></tr>`+avail.map(([id,name])=>`<tr><th class="mg-sticky mg-model">${name}</th>${idx.map(i=>{const v=h[k+'_'+id]?.[i];const dir=k==='wind_speed_10m'?h['wind_direction_10m_'+id]?.[i]:null;return `<td style="background:${color(k,v)}">${n(v)?(k==='precipitation'?(v<.1?'':v.toFixed(1)):Math.round(v)):'·'}${dir!=null?arrow(dir):''}</td>`}).join('')}</tr>`).join('')).join('');
 box.innerHTML=`<div class="mg-scroll"><table class="mg">${head}${body}</table></div><p class="footnote">Modelos vía Open-Meteo para ${esc(S.location.name)}. Cuando las filas de una variable se parecen, hay acuerdo; si difieren mucho, la previsión es incierta. Las flechas indican hacia dónde sopla el viento.</p>`}
function mount(){const anchor=$('#hourly')?.closest('article');if(!anchor||$('#mgCard'))return;anchor.insertAdjacentHTML('afterend',`<article class="card" id="mgCard"><div class="sectionhead"><div><h2>Comparación de modelos por horas</h2><span class="muted">Temperatura · lluvia · viento · rachas · nubes</span></div><div class="mg-step" role="group" aria-label="Paso"><button type="button" class="quiet" data-mg-step="1" aria-pressed="true">Cada hora</button><button type="button" class="quiet" data-mg-step="3" aria-pressed="false">Cada 3 h</button></div></div><div id="mgBody"></div></article>`);$('#mgCard').addEventListener('click',e=>{const b=e.target.closest('[data-mg-step]');if(!b)return;MG.step=+b.dataset.mgStep;$$('[data-mg-step]').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));render()})}
mount();
const prevShow=showTab;showTab=function(t){prevShow.apply(this,arguments);if(t==='now'){mount();load()}};
const prevSet=setLocation;setLocation=async function(){const r=await prevSet.apply(this,arguments);if(S.tab==='now'){mount();load(true)}return r};
globalThis.TMMeteogrid={load,render,color,models:MODELS};
})();
