'use strict';
/* Más modelos y conjuntos: UKMO, JMA, CMA, BOM, ECMWF AIFS, AROME y HARMONIE (cada uno por separado para que un fallo no tumbe al resto),
   abanico de incertidumbre de los conjuntos (ensembles) y meteograma multimodelo. Todo desde Open-Meteo, gratis y sin clave. */
const MX={extra:[['ukmo_seamless','UK Met Office','Reino Unido'],['jma_seamless','JMA','Japón'],['cma_grapes_global','CMA · GRAPES','China'],['bom_access_global','BOM · ACCESS','Australia'],['ecmwf_aifs025_single','ECMWF · AIFS (IA)','Europa'],['meteofrance_arome_france_hd','AROME 1,5 km','Francia'],['knmi_harmonie_arome_europe','HARMONIE · KNMI','Países Bajos']],
 ensModels:{ecmwf_ifs025:['ECMWF ENS',51],gfs_seamless:['GFS ENS',31],icon_seamless:['ICON EPS',40]},seq:0,ensSeq:0,data:null,ensModel:'ecmwf_ifs025',meteoVar:'temperature_2m'};
function pct(sorted,p){if(!sorted.length)return null;const i=(sorted.length-1)*p,lo=Math.floor(i),hi=Math.ceil(i);return sorted[lo]+(sorted[hi]-sorted[lo])*(i-lo)}
/* Resume los miembros de un conjunto por hora: percentiles 10/50/90 y probabilidades de umbral. */
function ensembleStats(d,v){const h=d?.hourly||{},keys=Object.keys(h).filter(k=>k===v||k.startsWith(v+'_'));return(h.time||[]).map((t,i)=>{const vals=keys.map(k=>h[k][i]).filter(finite).sort((a,b)=>a-b);return{time:t*1000,n:vals.length,p10:pct(vals,.1),p50:pct(vals,.5),p90:pct(vals,.9),min:vals[0]??null,max:vals.at(-1)??null,vals}})}
function probOver(stats,thr){return stats.map(s=>({time:s.time,p:s.n?s.vals.filter(x=>x>=thr).length/s.n:null}))}

$('#pane-models .card')?.insertAdjacentHTML('afterend',`<article class="card" id="ensCard"><div class="viz-title"><div><p class="eyebrow">Incertidumbre real</p><h2>Abanico de escenarios</h2></div><div class="seg" role="group" aria-label="Conjunto">${Object.entries(MX.ensModels).map(([k,[n,m]])=>`<button type="button" data-ens="${k}" aria-pressed="${k===MX.ensModel}">${n} <small>${m}</small></button>`).join('')}</div></div><p class="muted" id="ensLead">Un conjunto ejecuta el mismo modelo decenas de veces con condiciones iniciales ligeramente distintas: la anchura del abanico es la incertidumbre.</p><div id="ensOut" class="ens-out"><span class="spinner"></span>Consultando miembros del conjunto…</div><p class="footnote">Banda clara: 10–90 % de los miembros. Línea: mediana. Barras: fracción de miembros con lluvia ≥ 0,2 mm/h o rachas ≥ 50 km/h. Open-Meteo Ensemble API · CC BY 4.0.</p></article>
<article class="card" id="meteoCard"><div class="viz-title"><div><p class="eyebrow">Meteograma multimodelo</p><h2>Todos los modelos, 72 h</h2></div><div class="seg" role="group" aria-label="Variable"><button type="button" data-mv="temperature_2m" aria-pressed="true">Temperatura</button><button type="button" data-mv="precipitation" aria-pressed="false">Lluvia</button><button type="button" data-mv="wind_gusts_10m" aria-pressed="false">Rachas</button></div></div><div id="meteoOut" class="meteo-out muted">Esperando a los modelos…</div><div id="meteoLegend" class="meteo-legend"></div></article>`);

/* ---------- Modelos adicionales ---------- */
async function loadExtraModels(token){const loc={...S.location},seq=++MX.seq;const res=await Promise.allSettled(MX.extra.map(async([id,name,country])=>{const d=await json(forecastURL(loc.lat,loc.lon,{hourly:'temperature_2m,precipitation,wind_gusts_10m',current:'',models:id,daily:'',forecast_days:'3'}),1800000);let rows=hours(d).filter(r=>finite(r.temperature_2m));if(!rows.length)rows=hours(d,id).filter(r=>finite(r.temperature_2m));if(!rows.length)throw Error('Sin cobertura en este punto');return{id,name,country,provider:'Open-Meteo',rows,extra:true}}));if(token!==S.seq||seq!==MX.seq)return;const add=res.map((r,i)=>r.status==='fulfilled'?r.value:null).filter(Boolean);S.models=[...S.models.filter(m=>!m.extra),...add];renderModels();renderBrief();renderMeteogram()}
const mxLoad=loadModels;loadModels=async function(token){await mxLoad(token);if(token!==S.seq)return;renderMeteogram();loadExtraModels(token);loadEnsemble()};

/* ---------- Conjuntos ---------- */
async function loadEnsemble(){const loc={...S.location},seq=++MX.ensSeq,out=$('#ensOut');if(!out||!finite(loc.lat))return;out.innerHTML='<span class="spinner"></span>Consultando miembros del conjunto…';try{const d=await json('https://ensemble-api.open-meteo.com/v1/ensemble?'+new URLSearchParams({latitude:loc.lat.toFixed(3),longitude:loc.lon.toFixed(3),hourly:'temperature_2m,precipitation,wind_gusts_10m',models:MX.ensModel,forecast_days:'5',timezone:'auto',timeformat:'unixtime'}),3600000);if(seq!==MX.ensSeq)return;const now=Date.now()-1800000,cut=s=>s.filter(x=>x.time>=now).slice(0,96);MX.data={t:cut(ensembleStats(d,'temperature_2m')),rain:cut(probOver(ensembleStats(d,'precipitation'),.2)),gust:cut(probOver(ensembleStats(d,'wind_gusts_10m'),50)),gustStats:cut(ensembleStats(d,'wind_gusts_10m')),name:MX.ensModels[MX.ensModel]?.[0]};renderEnsemble()}catch(e){if(seq===MX.ensSeq)out.innerHTML=`<p class="muted">No se pudo leer el conjunto: ${esc(e.message)}</p>`}}
function planWindow(){const p=typeof currentPlan==='function'?currentPlan():null;return p?.start&&p?.arrival?[+p.start,+p.arrival]:null}
function renderEnsemble(){const e=MX.data,out=$('#ensOut');if(!e||!out)return;const t=e.t.filter(s=>finite(s.p50));if(t.length<6){out.innerHTML='<p class="muted">El conjunto no tiene datos para este punto.</p>';return}
 const W=100,H=46,t0=t[0].time,t1=t.at(-1).time,X=x=>(x-t0)/(t1-t0)*W,lo=Math.floor(Math.min(...t.map(s=>s.p10))-1),hi=Math.ceil(Math.max(...t.map(s=>s.p90))+1),Y=v=>H-(v-lo)/Math.max(1,hi-lo)*H;
 const band=`M${t.map(s=>`${X(s.time).toFixed(2)} ${Y(s.p90).toFixed(2)}`).join(' L')} L${t.slice().reverse().map(s=>`${X(s.time).toFixed(2)} ${Y(s.p10).toFixed(2)}`).join(' L')}Z`,med=`M${t.map(s=>`${X(s.time).toFixed(2)} ${Y(s.p50).toFixed(2)}`).join(' L')}`;
 const days=[];for(const s of t){const d=new Date(s.time);if(d.getHours()===0)days.push(s.time)}const zero=lo<0&&hi>0?`<line x1="0" x2="${W}" y1="${Y(0)}" y2="${Y(0)}" class="ens-zero"/>`:'';const win=planWindow(),wb=win&&win[1]>t0&&win[0]<t1?`<rect class="ens-win" x="${Math.max(0,X(win[0]))}" width="${Math.max(.6,Math.min(W,X(win[1]))-Math.max(0,X(win[0])))}" y="0" height="${H}"/>`:'';
 const bars=(arr,cls)=>`<div class="ens-bars ${cls}">${arr.filter(s=>s.time<=t1).map(s=>`<i style="height:${finite(s.p)?Math.max(2,s.p*100):0}%" title="${dateText(s.time)} · ${finite(s.p)?Math.round(s.p*100)+' %':'—'}"></i>`).join('')}</div>`;
 const w24=t.slice(0,24),spread=Math.max(...w24.map(s=>s.p90-s.p10)),rainMax=Math.max(0,...e.rain.slice(0,24).map(s=>s.p||0)),gustMax=Math.max(0,...e.gust.slice(0,24).map(s=>s.p||0));
 const conf=spread<3?'Alta coincidencia':spread<6?'Coincidencia media':'Escenarios muy abiertos';
 out.innerHTML=`<div class="ground"><div><span>Confianza 24 h</span><strong>${conf}</strong><p>abanico de ${fmt(spread,1)} °C entre P10 y P90</p></div><div><span>Lluvia 24 h</span><strong>${Math.round(rainMax*100)} %</strong><p>máx. de miembros con ≥ 0,2 mm/h</p></div><div><span>Rachas ≥ 50</span><strong>${Math.round(gustMax*100)} %</strong><p>máx. de miembros en 24 h</p></div></div>
 <svg class="ens-svg" viewBox="0 -2 ${W} ${H+4}" preserveAspectRatio="none" role="img" aria-label="Abanico de temperatura del conjunto ${esc(e.name||'')}">${wb}${days.map(d=>`<line x1="${X(d)}" x2="${X(d)}" y1="0" y2="${H}" class="ens-day"/>`).join('')}${zero}<path d="${band}" class="ens-band"/><path d="${med}" class="ens-med" vector-effect="non-scaling-stroke"/></svg>
 <div class="sky-axis"><span>${fmt(hi)} °C</span><span>${win?'franja: tu ruta':''}</span><span>${fmt(lo)} °C</span></div>
 <p class="ens-label">Probabilidad de lluvia</p>${bars(e.rain,'rain')}<p class="ens-label">Probabilidad de rachas ≥ 50 km/h</p>${bars(e.gust,'gust')}
 <div class="sky-axis"><span>${dateText(t0,{weekday:'short',hour:'2-digit'})}</span><span>${dateText(t[Math.floor(t.length/2)].time,{weekday:'short',hour:'2-digit'})}</span><span>${dateText(t1,{weekday:'short',hour:'2-digit'})}</span></div>`}
$('#ensCard')?.addEventListener('click',e=>{const b=e.target.closest('[data-ens]');if(!b)return;MX.ensModel=b.dataset.ens;$$('#ensCard [data-ens]').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));loadEnsemble()});

/* ---------- Meteograma multimodelo ---------- */
const MV_UNITS={temperature_2m:'°C',precipitation:'mm/h',wind_gusts_10m:'km/h'};
function renderMeteogram(){const out=$('#meteoOut');if(!out)return;const v=MX.meteoVar,now=Date.now()-1800000,end=now+72*3600000,series=S.models.filter(m=>m.rows?.length).map(m=>({name:m.name,extra:m.extra,pts:m.rows.filter(r=>r.time>=now&&r.time<=end&&finite(r[v])).map(r=>[r.time,r[v]])})).filter(s=>s.pts.length>3);
 if(!series.length){out.textContent='Esperando a los modelos…';$('#meteoLegend').innerHTML='';return}out.classList.remove('muted');
 const all=series.flatMap(s=>s.pts.map(p=>p[1])),lo=v==='temperature_2m'?Math.floor(Math.min(...all)-1):0,hi=Math.ceil(Math.max(...all,v==='precipitation'?1:v==='wind_gusts_10m'?30:lo+2)+.5),W=100,H=44,X=t=>(t-now)/(end-now)*W,Y=x=>H-(x-lo)/Math.max(.1,hi-lo)*H;
 const times=[...new Set(series.flatMap(s=>s.pts.map(p=>p[0])))].sort((a,b)=>a-b),median=times.map(t=>{const vals=series.map(s=>s.pts.find(p=>p[0]===t)?.[1]).filter(finite).sort((a,b)=>a-b);return vals.length>=3?[t,pct(vals,.5)]:null}).filter(Boolean);
 const path=pts=>'M'+pts.map(p=>`${X(p[0]).toFixed(2)} ${Y(p[1]).toFixed(2)}`).join(' L');
 out.innerHTML=`<svg class="meteo-svg" viewBox="0 -2 ${W} ${H+4}" preserveAspectRatio="none" role="img" aria-label="Meteograma de ${series.length} modelos">${[24,48].map(h=>`<line class="ens-day" x1="${X(now+h*3600000)}" x2="${X(now+h*3600000)}" y1="0" y2="${H}"/>`).join('')}${series.map((s,i)=>`<path d="${path(s.pts)}" class="meteo-line${s.extra?' x':''}" style="--i:${i}" vector-effect="non-scaling-stroke"><title>${esc(s.name)}</title></path>`).join('')}${median.length>3?`<path d="${path(median)}" class="meteo-med" vector-effect="non-scaling-stroke"><title>Mediana de modelos</title></path>`:''}</svg><div class="sky-axis"><span>${fmt(hi)} ${MV_UNITS[v]}</span><span>ahora → +72 h</span><span>${fmt(lo)} ${MV_UNITS[v]}</span></div>`;
 $('#meteoLegend').innerHTML=`<span class="med">Mediana</span>${series.map(s=>`<span${s.extra?' class="x"':''}>${esc(s.name)}</span>`).join('')}`}
$('#meteoCard')?.addEventListener('click',e=>{const b=e.target.closest('[data-mv]');if(!b)return;MX.meteoVar=b.dataset.mv;$$('#meteoCard [data-mv]').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));renderMeteogram()});
const mxRenderExp=renderExpedition;renderExpedition=function(){mxRenderExp();if(S.tab==='models')renderEnsemble()};
if(S.models?.length){renderMeteogram();loadExtraModels(S.seq);loadEnsemble()}
globalThis.TMModels={extra:MX.extra,ensembles:MX.ensModels,ensembleStats,probOver,pct,loadEnsemble,loadExtra:loadExtraModels,renderMeteogram,get ens(){return MX.data}};
