'use strict';
let mountainData=null,mountainSelected='peu1';
const zoneCenters={peu1:[43.18,-4.82],arn1:[42.65,-.2],cat1:[42.55,1.35],nav1:[42.95,-1.05],arn2:[40.4,-.8],rio1:[42.1,-2.85],gre1:[40.25,-5.2],nev1:[37.05,-3.32],mad2:[40.82,-3.96]};
const originalRenderNow=renderNow;
renderNow=function(){originalRenderNow();renderDays();if(mountainData)renderMountain()};
const originalModels=renderModels;
renderModels=function(){originalModels();if(mountainData)renderMountain()};
function renderDays(){const d=S.forecast?.daily;if(!d?.time)return;const day=d.time.findIndex(t=>new Date(t*1000).toLocaleDateString('en-CA',{timeZone:S.forecast.timezone})===new Date().toLocaleDateString('en-CA',{timeZone:S.forecast.timezone}));const i=Math.max(day,0);const now=nearest(hours(S.forecast),Date.now());$('#daySummary').innerHTML=`<div><span>Amanecer</span><strong>${finite(d.sunrise?.[i])?dateText(d.sunrise[i]*1000):'—'}</strong></div><div><span>Puesta de sol</span><strong>${finite(d.sunset?.[i])?dateText(d.sunset[i]*1000):'—'}</strong></div><div><span>Isoterma 0 °C · modelo</span><strong>${fmt(now?.freezing_level_height)} m</strong></div><div><span>UV actual · modelo</span><strong>${fmt(now?.uv_index,1)}</strong></div>`;let section=$('#sevenDays');if(!section){section=document.createElement('article');section.id='sevenDays';section.className='card';$('#pane-now').append(section)}section.innerHTML='<h2>Previsión de 7 días</h2><div class="tablewrap"><table><thead><tr><th>Día</th><th>Mín. / máx.</th><th>Lluvia total</th><th>Racha máxima</th><th>Puesta de sol</th></tr></thead><tbody>'+d.time.map((t,j)=>`<tr><td>${dateText(t*1000,{weekday:'short',day:'numeric',month:'short'})}</td><td>${fmt(d.temperature_2m_min?.[j])} / ${fmt(d.temperature_2m_max?.[j])} °C</td><td>${fmt(d.precipitation_sum?.[j],1)} mm</td><td>${fmt(d.wind_gusts_10m_max?.[j])} km/h</td><td>${finite(d.sunset?.[j])?dateText(d.sunset[j]*1000):'—'}</td></tr>`).join('')+'</tbody></table></div>'}
async function loadMountain(){try{const r=await fetch('./data/mountain.json',{cache:'no-store'});if(!r.ok)throw Error('No se pudo obtener el boletín');mountainData=await r.json();$('#mountainZone').innerHTML=mountainData.zones.map(z=>`<option value="${esc(z.code)}">${esc(z.name)}</option>`).join('');$('#mountainZone').value=mountainSelected;renderMountain()}catch(e){$('#mountainMeta').textContent='Boletín no disponible en la app. Consulta el original de AEMET.';$('#mountainCross').textContent='No se realiza cruce sin un boletín válido.'}}
function renderMountain(){if(S.briefFacts)delete S.briefFacts.boletinAemet;const z=mountainData?.zones.find(z=>z.code===mountainSelected);if(!z)return;$('#mountainOriginal').href=z.url;const today=new Date().toLocaleDateString('en-CA',{timeZone:'Europe/Madrid'}),valid=z.from?.slice(0,10)===today&&z.fields?.length;$('#mountainMeta').textContent=z.error?'No disponible: '+z.name:`${z.name} · validez ${z.from?.slice(0,10)} · emitido ${z.issued?.replace('T',' ')} · hora peninsular${valid?'':' · BOLETÍN FUERA DE FECHA'}`;
$('#mountainText').innerHTML=(z.fields||[]).filter(f=>f.section==='prediccion').map(f=>`<div class="bulletin-field"><h4>${esc(f.title)}</h4><p>${esc(f.text)}</p></div>`).join('')||'No hay texto disponible.';$('#mountainAtmosphere').innerHTML=(z.fields||[]).filter(f=>f.section==='atmosferalibre').map(f=>`<div class="atmosphere-row"><span>${esc(f.title)}</span><strong>${esc(f.text)}</strong></div>`).join('')||'No disponible para este boletín.';$('#mountainPlaces').innerHTML=z.places?.length?'<table><thead><tr><th>Lugar</th><th>Altitud</th><th>Mín. / máx.</th><th>Sensación mín.</th></tr></thead><tbody>'+z.places.map(p=>`<tr><td>${esc(p.name)}</td><td>${esc(p.elevation)}</td><td>${esc(p.minima)} / ${esc(p.maxima)} °C</td><td>${esc(p.stminima)} °C</td></tr>`).join('')+'</tbody></table>':'Sin tabla de lugares.';
const center=zoneCenters[z.code],dist=center?TM.distance({lat:center[0],lon:center[1]},S.location):Infinity;const hs=hours(S.forecast).filter(h=>new Date(h.time).toLocaleDateString('en-CA',{timeZone:'Europe/Madrid'})===z.from?.slice(0,10));const pcp=z.fields?.find(f=>f.key==='pcp')?.text||'',storm=z.fields?.find(f=>f.key==='tormentas')?.text||'';const dry=/^no se esperan[. ]*$/i.test(pcp),models=S.models.map(m=>({name:m.name,rows:(m.rows||[]).filter(h=>new Date(h.time).toLocaleDateString('en-CA',{timeZone:'Europe/Madrid'})===today)})).filter(m=>m.rows.length>=18&&m.rows.every(h=>finite(h.precipitation)));const wet=models.filter(m=>m.rows.some(h=>h.precipitation>=.2));let content='';if(!valid)content='El boletín no es válido para hoy. No se interpreta ni se cruza con la previsión actual.';else if(dist>100)content=`La ubicación seleccionada está a ${fmt(dist)} km del centro de referencia de esta zona. Selecciona una ubicación dentro de ${z.name} para un cruce pertinente.`;else if(!hs.length)content='Esperando la previsión del punto seleccionado para comparar el mismo día.';else if(!models.length)content='Esperando series completas de los modelos para comparar la precipitación del mismo día.';else if(dry)content=wet.length?`AEMET no espera precipitación en la zona. ${wet.length} de ${models.length} series numéricas comparables sí dan al menos 0,2 mm en alguna hora del punto elegido: ${wet.map(m=>m.name).join(', ')}. Hay una discrepancia que conviene revisar.`:`AEMET no espera precipitación. Las ${models.length} series comparables tampoco superan 0,2 mm en ninguna hora del punto seleccionado. Coinciden en ese aspecto; no es una garantía de tiempo seco.`;else content=`AEMET describe: «${pcp}». En el punto elegido, ${wet.length} de ${models.length} series comparables superan 0,2 mm en alguna hora. La descripción regional y las cantidades puntuales tienen escalas distintas.`;
$('#mountainCross').innerHTML=`<p class="eyebrow">CRUCE DEL MISMO DÍA</p><h3>${esc(S.location.name)} / ${esc(z.name)}</h3><p>${esc(content)}</p>${valid&&storm?`<p><b>Tormentas · AEMET:</b> ${esc(storm)}</p>`:''}<p class="footnote">Comparación por reglas, no IA generativa. La zona no se asigna por un límite oficial: se comprueba proximidad a su centro de referencia. Los modelos pueden compartir datos de origen. Actualización de boletines programada cada 3 h; GitHub puede retrasarla.</p>`;
if(valid&&dist<=100&&S.briefFacts){S.briefFacts.boletinAemet={zona:z.name,validez:z.from,precipitacion:pcp,tormentas:storm,viento:z.fields.find(f=>f.key==='viento')?.text,cruce:content}}}
$('#mountainZone').onchange=e=>{mountainSelected=e.target.value;renderMountain()};
loadMountain();if(S.forecast)renderDays();
