'use strict';
/* Tu ritmo real: aprende minutos por km en llano y por 100 m de subida a partir de un GPX tuyo con tiempos. */
$('.route-settings')?.insertAdjacentHTML('afterend',`<details class="card" id="paceCard"><summary>Tu ritmo real · aprende de un GPX tuyo con tiempos</summary><p class="muted">Importa una salida que hayas hecho (Wikiloc, Strava, Garmin…). Se ajusta un modelo con tus tramos en movimiento: minutos por km y por cada 100 m de subida. Las paradas largas no cuentan.</p><div class="action-row"><label class="quiet file-button">↥ Importar mi GPX con tiempos<input id="paceGpx" type="file" accept=".gpx,application/gpx+xml,application/xml,text/xml"></label><button class="primary" type="button" id="paceApply" hidden>Aplicar a mi plan</button></div><div id="paceOut"></div></details>`);
function parseTimedGPX(text){if(/<!DOCTYPE|<!ENTITY/i.test(text))throw Error('GPX no admitido');const xml=new DOMParser().parseFromString(text,'application/xml');const pts=[...xml.getElementsByTagNameNS('*','trkpt')].map(n=>({lat:+n.getAttribute('lat'),lon:+n.getAttribute('lon'),ele:Number(n.getElementsByTagNameNS('*','ele')[0]?.textContent),t:Date.parse(n.getElementsByTagNameNS('*','time')[0]?.textContent||'')})).filter(p=>finite(p.lat)&&finite(p.lon)&&finite(p.t));if(pts.length<20)throw Error('El GPX no tiene suficientes puntos con hora');return pts}
/* Mínimos cuadrados sin término independiente: t = a·km + b·(subida/100). */
function fitPace(pts){const chunks=[];let s=pts[0],km=0,up=0,anchor=finite(s.ele)?s.ele:null;for(let i=1;i<pts.length;i++){const p=pts[i],d=TM.distance(pts[i-1],p),dt=(p.t-pts[i-1].t)/60000;if(dt>10||dt<=0){s=p;km=0;up=0;anchor=finite(p.ele)?p.ele:null;continue}km+=d;if(finite(p.ele)&&anchor!==null){const dz=p.ele-anchor;if(Math.abs(dz)>=4){if(dz>0)up+=dz;anchor=p.ele}}if(km>=.25){const min=(p.t-s.t)/60000;if(min>0&&km/(min/60)>.8)chunks.push({km,up,min});s=p;km=0;up=0;anchor=finite(p.ele)?p.ele:null}}if(chunks.length<4)throw Error('Pocos tramos en movimiento para ajustar el ritmo');let skk=0,skh=0,shh=0,skt=0,sht=0;for(const c of chunks){const h=c.up/100;skk+=c.km*c.km;skh+=c.km*h;shh+=h*h;skt+=c.km*c.min;sht+=h*c.min}const det=skk*shh-skh*skh;let a,b;if(Math.abs(det)<1e-9||shh<.05){a=skt/skk;b=null}else{a=(skt*shh-sht*skh)/det;b=(skk*sht-skh*skt)/det}if(b!==null&&(b<0||!finite(b))){a=skt/skk;b=null}a=Math.max(2,Math.min(60,a));if(b!==null)b=Math.max(0,Math.min(60,b));const totalKm=chunks.reduce((s,c)=>s+c.km,0),totalUp=chunks.reduce((s,c)=>s+c.up,0),totalMin=chunks.reduce((s,c)=>s+c.min,0);return{pace:a,climb:b,chunks:chunks.length,km:totalKm,up:totalUp,moving:totalMin}}
function showFit(f,name){$('#paceOut').innerHTML=`<div class="pace-fit"><div><span>Llano</span><strong>${fmt(f.pace,1)} min/km</strong></div><div><span>Subida</span><strong>${f.climb==null?'—':fmt(f.climb,1)+' min/100 m'}</strong></div><div><span>Datos usados</span><strong>${fmt(f.km,1)} km</strong></div></div><p class="footnote">${esc(name||'Tu GPX')}: ${f.chunks} tramos en movimiento, +${fmt(f.up)} m, ${fmt(f.moving/60,1)} h. ${f.climb==null?'Sin desnivel suficiente para estimar la subida: se mantiene el valor actual.':''} Se guarda en este dispositivo.</p>`;$('#paceApply').hidden=false}
let paceFit=null;try{paceFit=JSON.parse(localStorage.getItem('tm.pace'))}catch{}if(paceFit)showFit(paceFit,paceFit.name);
$('#paceGpx').onchange=async e=>{const f=e.target.files[0];if(!f)return;try{const fit=fitPace(parseTimedGPX(await f.text()));fit.name=f.name;paceFit=fit;try{localStorage.setItem('tm.pace',JSON.stringify(fit))}catch{}showFit(fit,f.name);if(typeof sfx==='function')sfx('ok')}catch(err){$('#paceOut').innerHTML=`<p class="error">${esc(err.message)}</p>`}finally{e.target.value=''}};
$('#paceApply').onclick=()=>{if(!paceFit)return;$('#pace').value=paceFit.pace.toFixed(1);if(paceFit.climb!=null)$('#climb').value=Math.round(paceFit.climb);['pace','climb'].forEach(id=>$('#'+id).dispatchEvent(new Event('change')));if(S.route)analyzeRoute()};
globalThis.TMPace={fit:fitPace,parse:parseTimedGPX};
