'use strict';
/* Agua y refugios cerca del track (OpenStreetMap vía Overpass). Lo cartografiado no garantiza caudal ni apertura. */
const POI={byRoute:new WeakMap(),layers:new Map()};
const POI_KINDS={drinking_water:['Agua potable','💧'],spring:['Fuente / manantial','💧'],water_point:['Punto de agua','💧'],water_tap:['Grifo','💧'],alpine_hut:['Refugio guardado','⌂'],wilderness_hut:['Refugio libre','⌂'],shelter:['Abrigo / cabaña','⛺']};
function poiKind(t){if(t.amenity==='drinking_water'||t.drinking_water==='yes'&&t.natural!=='spring')return'drinking_water';if(t.natural==='spring')return'spring';if(t.amenity==='water_point')return'water_point';if(t.man_made==='water_tap')return'water_tap';if(t.tourism==='alpine_hut')return'alpine_hut';if(t.tourism==='wilderness_hut')return'wilderness_hut';if(t.amenity==='shelter')return'shelter';return null}
function poiRows(r,elements,maxKm=.4){const out=[];for(const e of elements){const lat=e.lat??e.center?.lat,lon=e.lon??e.center?.lon,kind=poiKind(e.tags||{});if(!finite(lat)||!finite(lon)||!kind)continue;const q=Expedition.locate(r.points,{lat,lon});if(!q||q.distance>maxKm)continue;out.push({id:e.type+'/'+e.id,kind,name:e.tags.name||POI_KINDS[kind][0],lat,lon,km:q.km,off:q.distance*1000,potable:e.tags.drinking_water,seasonal:e.tags.seasonal||e.tags.intermittent,ele:e.tags.ele})}return out.sort((a,b)=>a.km-b.km)}
function poiHTML(rows,r){if(!rows.length)return '<p class="muted">No hay fuentes ni refugios cartografiados a menos de 400 m del track. Que no aparezcan no significa que no existan.</p>';const water=rows.filter(p=>POI_KINDS[p.kind][1]==='💧');let gap=0,prev=0;for(const p of water){gap=Math.max(gap,p.km-prev);prev=p.km}gap=Math.max(gap,r.summary.km-prev);return `<p>${water.length} puntos de agua y ${rows.length-water.length} refugios o abrigos cerca del track. ${water.length?`Tramo más largo sin agua cartografiada: <b>${fmt(gap,1)} km</b>.`:'<b>Sin agua cartografiada: lleva toda la que necesites.</b>'}</p><div class="poi-list">${rows.map(p=>`<div class="poi"><b>km ${fmt(p.km,1)}</b><div><span class="tag">${POI_KINDS[p.kind][1]} ${esc(POI_KINDS[p.kind][0])}</span><br>${esc(p.name)}<small>a ${fmt(p.off)} m del track${p.potable==='no'?' · marcada como no potable':''}${p.seasonal==='yes'?' · estacional':''}${p.ele?' · '+esc(p.ele)+' m':''}</small></div><a href="https://www.openstreetmap.org/${esc(p.id)}" target="_blank" rel="noopener" aria-label="Ver en OpenStreetMap">↗</a></div>`).join('')}</div><p class="footnote">© OpenStreetMap contributors. Una fuente cartografiada puede estar seca o no ser potable; un refugio puede estar cerrado. Contrasta antes de depender de ellos.</p>`}
async function loadPois(r,force=false){if(!r?.points?.length)return null;if(POI.byRoute.has(r)&&!force)return POI.byRoute.get(r);let a=90,b=180,c=-90,d=-180;for(const p of r.points){a=Math.min(a,p.lat);b=Math.min(b,p.lon);c=Math.max(c,p.lat);d=Math.max(d,p.lon)}if((c-a)*(d-b)>1.2||r.summary.km>200)return{error:'Ruta demasiado extensa para consultar fuentes y refugios.'};const pad=.005,bbox=[a-pad,b-pad,c+pad,d+pad].map(x=>x.toFixed(5)).join(',');const q=`[out:json][timeout:25];(nwr["amenity"~"^(drinking_water|water_point|shelter)$"](${bbox});nwr["natural"="spring"](${bbox});nwr["man_made"="water_tap"](${bbox});nwr["tourism"~"^(alpine_hut|wilderness_hut)$"](${bbox}););out center tags;`;
 const job=(async()=>{const ctrl=new AbortController(),t=setTimeout(()=>ctrl.abort(),35000);try{const res=await fetch('https://overpass-api.de/api/interpreter',{method:'POST',body:new URLSearchParams({data:q}),signal:ctrl.signal});if(!res.ok)throw Error('servicio ocupado ('+res.status+')');const data=await res.json();return{rows:poiRows(r,data.elements||[]),at:Date.now()}}catch(e){return{error:'No se pudieron consultar fuentes y refugios: '+(e.message||e)}}finally{clearTimeout(t)}})();POI.byRoute.set(r,job);const out=await job;POI.byRoute.set(r,out);if(out.error)POI.byRoute.delete(r);else r.pois=out;return out}
function drawOn(map){if(!map||!window.L)return;POI.layers.get(map)?.remove();const rows=S.route?.pois?.rows;if(!rows?.length)return;const g=L.featureGroup(rows.map(p=>L.circleMarker([p.lat,p.lon],{radius:7,weight:2,color:'#fff',fillColor:POI_KINDS[p.kind][1]==='💧'?'#00a3e0':'#ff4d1f',fillOpacity:1}).bindPopup(`<b>${esc(p.name)}</b><br>${esc(POI_KINDS[p.kind][0])} · km ${fmt(p.km,1)}<br><small>Cartografiado en OSM; no garantiza caudal ni apertura.</small>`))).addTo(map);POI.layers.set(map,g)}
async function renderPois(force=false){const r=S.route;const targets=[$('#routePois'),$('#terrainPois')].filter(Boolean);if(!r){targets.forEach(t=>t.innerHTML='<p class="muted">Carga una ruta para ver fuentes y refugios cercanos al track.</p>');return}if(r.pois&&!force){targets.forEach(t=>t.innerHTML=poiHTML(r.pois.rows,r));drawOn(S.routeMap);drawOn(globalThis.TMRelief?.map);return}if(!navigator.onLine&&!r.pois){targets.forEach(t=>t.innerHTML='<p class="muted">Sin conexión: guarda la ruta con cobertura para tener fuentes y refugios.</p>');return}targets.forEach(t=>t.innerHTML='<p class="muted"><span class="spinner"></span>Buscando fuentes y refugios cerca del track…</p>');const out=await loadPois(r,force);if(S.route!==r)return;targets.forEach(t=>t.innerHTML=out?.error?`<p class="muted">${esc(out.error)}</p>`:poiHTML(out.rows,r));drawOn(S.routeMap);drawOn(globalThis.TMRelief?.map)}
$('#expeditionPanel article.card:nth-of-type(2)')?.insertAdjacentHTML('afterend','<article class="card" id="routePoisCard"><div class="sectionhead"><div><p class="eyebrow">AGUA Y REFUGIOS</p><h3>A lo largo de tu ruta</h3></div><button class="quiet" type="button" id="refreshPois">↻ Volver a consultar</button></div><div id="routePois"></div></article>');
$('#refreshPois')?.addEventListener('click',()=>renderPois(true));
const poiImport=importRoute;importRoute=async function(file){const before=S.route;await poiImport(file);if(S.route&&S.route!==before)renderPois()};
const poiRestore=restoreRecord;restoreRecord=function(rec){poiRestore(rec);renderPois()};
const poiDrawRoute=drawRoute;drawRoute=function(){poiDrawRoute();drawOn(S.routeMap)};
if(typeof packRoute==='function'){const poiPack=packRoute;packRoute=function(r){const out=poiPack(r);if(r.pois&&!r.pois.error)out.pois=structuredClone(r.pois);return out}}
globalThis.TMPois={load:loadPois,render:renderPois,rows:poiRows,drawOn};
