/* Public, keyless retrieval. Failed/blocked pages never become evidence. */
(function(root){
function safeURL(value){try{const u=new URL(value);if(u.protocol!=='https:'||u.username||u.password||u.port||!u.hostname.includes('.')||/(^|\.)(localhost|local|internal)$/.test(u.hostname)||/^\d+\.\d+\./.test(u.hostname))return null;return u.href}catch{return null}}
function parseResults(markdown){const results=[],seen=new Set();for(const m of markdown.matchAll(/^##\s+\[([^\n]+?)\]\((https?:\/\/[^\s)]+)\)/gm)){let url;try{const u=new URL(m[2]);url=safeURL(u.searchParams.get('uddg')||u.href)}catch{continue}if(!url)continue;const host=new URL(url).hostname;if(/(^|\.)(wikipedia\.org|duckduckgo\.com|jina\.ai)$/.test(host)||seen.has(url))continue;seen.add(url);results.push({title:m[1].replace(/\*\*/g,''),url,host})}return results}
function extractText(markdown,query){if(/captcha|verify you are human|checking your browser|access denied|making sure you.?re not a bot/i.test(markdown.slice(0,1800)))return null;const body=markdown.split('Markdown Content:').slice(1).join('Markdown Content:')||markdown;const words=query.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').split(/\W+/).filter(w=>w.length>3);const paras=body.split(/\n\s*\n/).map(s=>s.replace(/!\[[^\]]*\]\([^)]*\)/g,'').replace(/\[([^\]]*)\]\([^)]*\)/g,'$1').replace(/[#*_>|]/g,'').replace(/\s+/g,' ').trim()).filter(s=>s.length>70&&!/cookie|iniciar sesi[oó]n|suscr[ií]b|all rights reserved/i.test(s));const scored=paras.map((s,i)=>({s,i,score:words.reduce((n,w)=>n+Number(s.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').includes(w)),0)}));const selected=scored.filter(p=>p.score>0).sort((a,b)=>b.score-a.score||a.i-b.i).slice(0,4).sort((a,b)=>a.i-b.i);if(!selected.length)return null;return selected.map(p=>p.s).join('\n\n').slice(0,3000)}
async function read(url,signal){if(!safeURL(url))throw Error('URL no admitida');const r=await fetch('https://r.jina.ai/'+url,{signal,credentials:'omit',referrerPolicy:'no-referrer'});if(!r.ok)throw Error('Fuente no accesible ('+r.status+')');const text=await r.text();if(text.length>1500000)throw Error('Página demasiado extensa');return text}
async function search(query,signal,onProgress=()=>{}){const q=query.trim().slice(0,160),searchURL='https://html.duckduckgo.com/html/?q='+encodeURIComponent(q+' senderismo ruta -site:wikipedia.org');const page=await read(searchURL,signal),candidates=parseResults(page),selected=[],hosts=new Set();for(const candidate of candidates){if(hosts.has(candidate.host))continue;hosts.add(candidate.host);selected.push(candidate);if(selected.length===3)break}if(!selected.length)throw Error('El buscador no devolvió fuentes legibles. No se inventa una descripción.');const sources=[];for(let i=0;i<selected.length;i++){const item=selected[i];onProgress('Leyendo '+(i+1)+'/'+selected.length+': '+item.host);try{const raw=await read(item.url,signal),text=extractText(raw,q);sources.push({...item,id:'F'+(i+1),text:text||'',published:(raw.match(/^Published Time: (.+)$/m)||[])[1]||null,status:text?'read':'unusable',fetched:Date.now(),note:text?'Extractos pertinentes recuperados; no es una lectura íntegra.':'Sin texto pertinente o acceso bloqueado.'})}catch(e){if(signal.aborted)throw e;sources.push({...item,id:'F'+(i+1),text:'',status:'failed',fetched:Date.now(),note:e.message})}}return{query:q,searched:Date.now(),searchURL,sources}}
root.PublicSources={safeURL,parseResults,extractText,search};if(typeof module!=='undefined')module.exports=root.PublicSources;
})(typeof globalThis!=='undefined'?globalThis:this);
