'use strict';
/* Terreno: sol y sombra por tramo con el relieve real (MDT Copernicus 90 m vía Open-Meteo), estado del terreno y nieve. */
const RL={cache:new Map(),seq:0,map:null};
const RL_AZ=8,RL_DIST=[120,250,500,900,1500,2500],RL_STEP=60;
async function elevations(points){const out=new Array(points.length).fill(null);for(let i=0;i<points.length;i+=100){const b=points.slice(i,i+100);const d=await json('https://api.open-meteo.com/v1/elevation?'+new URLSearchParams({latitude:b.map(p=>p.lat.toFixed(5)).join(','),longitude:b.map(p=>p.lon.toFixed(5)).join(',')}),7*86400000);(d.elevation||[]).forEach((e,j)=>{out[i+j]=finite(e)?e:null})}return out}
/* Para cada punto: pendiente, orientación y horizonte en 8 direcciones. */
async function analyzeRelief(points){const key=points.map(p=>p.lat.toFixed(4)+','+p.lon.toFixed(4)).join(';');if(RL.cache.has(key))return RL.cache.get(key);const job=(async()=>{const q=[];for(const p of points){for(const dy of [1,0,-1])for(const dx of [-1,0,1])q.push(FieldCore.offset(FieldCore.offset(p,dy*RL_STEP,0),dx*RL_STEP,90));for(let k=0;k<RL_AZ;k++)for(const d of RL_DIST)q.push(FieldCore.offset(p,d,k*360/RL_AZ))}const z=await elevations(q),per=9+RL_AZ*RL_DIST.length;return points.map((p,i)=>{const o=i*per,g=z.slice(o,o+9),c=g[4],sa=FieldCore.slopeAspect(g,RL_STEP);const horizon=[];for(let k=0;k<RL_AZ;k++){let best=0;RL_DIST.forEach((d,j)=>{const e=z[o+9+k*RL_DIST.length+j];if(finite(e)&&finite(c))best=Math.max(best,Math.atan2(e-c-1.7,d)*180/Math.PI)});horizon.push(best)}return{ele:c,slope:sa?.slope??null,aspect:sa?.aspect??null,horizon}})})();RL.cache.set(key,job);try{const r=await job;RL.cache.set(key,r);return r}catch(e){RL.cache.delete(key);throw e}}
function sunState(info,p,time){const sun=FieldCore.sunPosition(time,p.lat,p.lon);return{...FieldCore.illumination(info,sun),sun}}
const ASPECT=a=>finite(a)?FieldCore.cardinal(a):'—';
/* Horas de sol directo en un punto para un día (pasos de 10 min). */
function sunHours(info,p,day){const t=FieldCore.sunTimes(day,p.lat,p.lon);if(!finite(t.sunrise))return{spans:[],minutes:0};const spans=[];let cur=null,mins=0;for(let x=t.sunrise;x<=t.sunset;x+=600000){const s=sunState(info,p,x).state==='sun';if(s){mins+=10;if(!cur)cur=[x,x];cur[1]=x}else if(cur){spans.push(cur);cur=null}}if(cur)spans.push(cur);return{spans,minutes:mins,sunrise:t.sunrise,sunset:t.sunset}}

$('#terrainApp').innerHTML=`<div class="route-hero"><p class="eyebrow">Terreno · el día que vas</p><h2>Cómo estará <b>el suelo</b></h2><p class="route-hero-sub">Sol y sombra con el relieve real a tu hora de paso, lluvia y nieve de los últimos días, nieve vista desde satélite, cota de nieve, agua y refugios.</p></div>
<section class="card" id="shadeCard"><div class="viz-title"><div><p class="eyebrow">Sol y sombra por tramo</p><h2>Luz en cada sector</h2></div><div class="legend-dots"><span><i style="background:#ffbe4d"></i>Sol directo</span><span><i style="background:#8aa2b4"></i>Sombra del relieve</span><span><i style="background:#c3ced6"></i>Ladera de espaldas</span><span><i style="background:#2d3a44"></i>Noche</span></div></div><div id="shadeOut" class="muted">Analiza una ruta en Planificar para ver qué tramos estarán al sol o en umbría.</div><p class="footnote">Relieve: modelo digital Copernicus 90 m (Open-Meteo). Se tiene en cuenta la pendiente, la orientación y el horizonte hasta 2,5 km en 8 direcciones. Paredes de canal más estrechas que 90 m pueden dar más sombra de la calculada.</p></section>
<section class="card" id="groundCard"><p class="eyebrow">Estado del terreno</p><h2>Lo que ha caído</h2><div id="groundOut" class="muted">Carga una ruta o elige un lugar.</div></section>
<section class="card"><div class="viz-title"><div><p class="eyebrow">Agua y refugios</p><h2>A lo largo de tu ruta</h2></div></div><div id="terrainPois" class="muted">Carga una ruta para ver fuentes y refugios cercanos al track.</div></section>`;

async function renderShade(){const r=S.route,out=$('#shadeOut');if(!r?.rows?.length){out.textContent='Analiza una ruta en Planificar para ver qué tramos estarán al sol o en umbría.';return}const seq=++RL.seq;out.innerHTML='<span class="spinner"></span>Leyendo el relieve alrededor de cada sector…';try{const pts=r.rows.map(q=>({lat:q.lat,lon:q.lon}));const info=r.relief?.key===JSON.stringify(pts)?r.relief.data:await analyzeRelief(pts);r.relief={key:JSON.stringify(pts),data:info};if(seq!==RL.seq)return;const plan=typeof currentPlan==='function'?currentPlan():null,rows=(plan?.rows||r.rows).map((q,i)=>{const st=sunState(info[i],q,q.eta),t=q.h?.apparent_temperature??q.h?.temperature_2m,fz=q.h?.freezing_level_height,ice=st.state!=='sun'&&(finite(t)&&t<=2||finite(fz)&&finite(q.ele)&&q.ele>fz-200),heat=st.state==='sun'&&finite(t)&&t>=22&&st.incidence>.75;return{q,info:info[i],st,ice,heat,t}});const col={sun:'#ffbe4d',night:'#2d3a44',relieve:'#8aa2b4',ladera:'#c3ced6'};const k=s=>s.state==='shade'?s.reason:s.state;const shadeN=rows.filter(x=>x.st.state==='shade').length,iceN=rows.filter(x=>x.ice).length,heatN=rows.filter(x=>x.heat).length;
 out.innerHTML=`<div class="shade-band" aria-hidden="true">${rows.map(x=>`<i style="background:${col[k(x.st)]}" title="km ${fmt(x.q.km,1)} · ${exTime(x.q.eta)}"></i>`).join('')}</div><div class="sky-axis"><span>km 0</span><span>km ${fmt(r.summary.km,1)}</span></div><div class="ground" style="margin-top:18px"><div><span>Sectores en sombra</span><strong>${shadeN}/${rows.length}</strong><p>a tu hora de paso</p></div><div><span>Riesgo de hielo</span><strong class="${iceN?'high':''}">${iceN}</strong><p>sombra con ≤ 2 °C o cerca de la isoterma 0</p></div><div><span>Golpe de calor</span><strong class="${heatN?'medium':''}">${heatN}</strong><p>sol directo intenso con ≥ 22 °C</p></div></div><div class="shade-list">${rows.map(x=>`<div class="shade-row"><span class="k">km ${fmt(x.q.km,1)}<br>${exTime(x.q.eta).split(', ').pop()}</span><span class="sun-dot ${x.st.state}">${x.st.state==='sun'?'☀':x.st.state==='night'?'☾':'◐'}</span><span>${x.st.state==='sun'?'Sol directo':x.st.state==='night'?'Antes del alba o tras el ocaso':x.st.reason==='relieve'?`Sombra de montaña (horizonte ${fmt(x.st.horizon)}°, sol a ${fmt(x.st.sun.altitude)}°)`:'Ladera de espaldas al sol'}<br><small class="muted">Ladera ${fmt(x.info.slope)}° orientada al ${ASPECT(x.info.aspect)} · ${finite(x.t)?fmt(x.t)+' °C':'sin temperatura'}</small></span><span>${x.ice?'<span class="tag ice">hielo posible</span>':x.heat?'<span class="tag heat">calor</span>':''}</span></div>`).join('')}</div>`}catch(e){if(seq===RL.seq)out.textContent='No se pudo leer el relieve: '+e.message}}
async function renderGround(){const out=$('#groundOut'),r=S.route;const pts=r?.points;const c=pts?.length?{lat:pts.reduce((s,p)=>s+p.lat,0)/pts.length,lon:pts.reduce((s,p)=>s+p.lon,0)/pts.length}:S.location;if(!c)return;const top=r?.summary?.elevationComplete?Math.max(...r.points.map(p=>p.ele).filter(finite)):null;out.innerHTML='<span class="spinner"></span>Consultando lluvia y nieve recientes…';try{const d=await json('https://api.open-meteo.com/v1/forecast?'+new URLSearchParams({latitude:c.lat.toFixed(3),longitude:c.lon.toFixed(3),daily:'precipitation_sum,snowfall_sum,temperature_2m_min,temperature_2m_max',hourly:'snow_depth,freezing_level_height',past_days:'3',forecast_days:'3',timezone:'auto',timeformat:'unixtime',...(finite(top)?{elevation:String(Math.round(top))}:{})}),1800000);const dl=d.daily||{},now=Date.now()/1000,idx=(dl.time||[]).map((t,i)=>({t,i})).filter(x=>x.t<now-3600);const last3=idx.slice(-3).map(x=>x.i),sum=k=>last3.reduce((s,i)=>s+(dl[k]?.[i]||0),0),rain=sum('precipitation_sum'),snow=sum('snowfall_sum'),frost=last3.filter(i=>dl.temperature_2m_min?.[i]<0).length;const hh=d.hourly||{},hi=(hh.time||[]).findIndex(t=>t>=now),depth=hi>=0?hh.snow_depth?.[hi]:null;const fzNext=(hh.freezing_level_height||[]).slice(Math.max(0,hi),hi+48).filter(finite),fzMin=fzNext.length?Math.min(...fzNext):null,snowLine=finite(fzMin)?Math.max(0,fzMin-300):null;
 const verdict=snow>=2||depth>=.05?'Nieve en el terreno: valora crampones y piolet según la ruta.':rain>=15?'Suelo muy mojado: barro, roca caliza y hierba resbaladizas, riegas crecidas.':rain>=3?'Terreno húmedo: roca y hierba resbaladizas a primera hora o en umbría.':frost?'Seco pero con heladas nocturnas: hielo posible en umbrías y charcos a primera hora.':'Terreno seco según los modelos.';
 out.innerHTML=`<p class="sky-verdict">${esc(verdict)}</p><div class="ground"><div><span>Lluvia 72 h</span><strong>${fmt(rain,1)} mm</strong><p>acumulado modelo</p></div><div><span>Nieve 72 h</span><strong>${fmt(snow,1)} cm</strong><p>${finite(depth)?`espesor actual ≈ ${fmt(depth*100)} cm`:'sin espesor'}${finite(top)?` a ${fmt(top)} m`:''}</p></div><div><span>Noches con helada</span><strong>${frost}/3</strong><p>mínimas bajo 0 °C</p></div><div><span>Isoterma 0 · 48 h</span><strong>${finite(fzMin)?fmt(fzMin)+' m':'—'}</strong><p>mínimo previsto</p></div><div><span>Cota de nieve aprox.</span><strong>${finite(snowLine)?fmt(snowLine)+' m':'—'}</strong><p>isoterma − 300 m (regla práctica)</p></div><div><span>Tu cota máxima</span><strong class="${finite(top)&&finite(snowLine)&&top>snowLine?'high':''}">${finite(top)?fmt(top)+' m':'—'}</strong><p>${finite(top)&&finite(snowLine)?(top>snowLine?'por encima de la cota de nieve prevista':'por debajo de la cota de nieve'):'carga una ruta con altitudes'}</p></div></div><p class="footnote">Datos de modelo (Open-Meteo) para ${r?'el centro de tu ruta':esc(S.location.name)}${finite(top)?` corregidos a ${fmt(top)} m`:''}. No sustituyen al boletín de aludes ni a la observación directa.</p>`}catch(e){out.textContent='No se pudo consultar el estado del terreno: '+e.message}}
function renderTerrainPane(){renderShade();renderGround();globalThis.TMPois?.render()}
const rlShowTab=showTab;showTab=function(tab){rlShowTab(tab);if(tab==='terrain')renderTerrainPane()};
const rlRender=renderExpedition;renderExpedition=function(){rlRender();if(S.tab==='terrain')renderShade()};
globalThis.TMRelief={analyze:analyzeRelief,sunState,sunHours,elevations,render:renderTerrainPane,get map(){return globalThis.TMSnow?.map}};
