'use strict';
/* Carretera: cómo llegar al inicio de la ruta. Ruta en coche (OSRM sobre OpenStreetMap, alternativas incluidas), avisos de la
   DGT en tu trayecto (nieve, cadenas, cortes, obras, accidentes; DATEX II actualizado por el flujo de publicación), niveles de
   cadenas, puertos de montaña y el tiempo previsto en cada tramo a la hora en que pasarás. Todo gratuito y sin clave. */
const RD={origin:null,dest:null,routes:[],sel:0,dgt:null,seq:0,map:null,layers:null,wx:null,park:null};
const CHAIN_LEVELS={verde:['#2e7d32','Verde','Calzada con nieve parcial: precaución y velocidad moderada; limitaciones para camiones.'],amarillo:['#d8a400','Amarillo','Calzada cubierta de nieve: prohibido camiones y articulados; turismos y autobuses a 60 km/h como máximo.'],rojo:['#c62828','Rojo','Obligatorio cadenas o neumáticos de invierno; prohibido camiones, articulados y autobuses; turismos a 30 km/h como máximo.'],negro:['#111','Negro','Circulación prohibida para todos los vehículos.']};
const KIND={chains:['Cadenas','#c62828'],closed:['Corte','#111'],snow:['Nieve','#1d8ea3'],ice:['Hielo','#4a7fb5'],fog:['Niebla','#6a767c'],accident:['Accidente','#e14545'],works:['Obras','#d4861a'],obstruction:['Obstáculo','#8a5a2b'],other:['Aviso','#5d6f7a']};
const QUICK=['Arenas de Cabrales','Poncebos','Caín de Valdeón','Sotres','Tielve','Fuente Dé','Lagos de Covadonga','Posada de Valdeón'];
const kmBetween=(a,b)=>TM.distance(a,b);
/* Distancia (km) de un punto a la polilínea y posición (km) del punto más cercano sobre ella. */
function nearestOnLine(p,line){let best={d:Infinity,km:0};const c=Math.cos(p.lat*Math.PI/180),X=q=>q.lon*c*111.32,Y=q=>q.lat*110.57;for(let i=1;i<line.length;i++){const a=line[i-1],b=line[i],ax=X(a),ay=Y(a),bx=X(b),by=Y(b),px=X(p),py=Y(p),dx=bx-ax,dy=by-ay,L=dx*dx+dy*dy,t=L?Math.max(0,Math.min(1,((px-ax)*dx+(py-ay)*dy)/L)):0,qx=ax+t*dx,qy=ay+t*dy,d=Math.hypot(px-qx,py-qy);if(d<best.d)best={d,km:a.km+(b.km-a.km)*t,i}}return best}
/* ---------- Geocodificación precisa: Nominatim (OSM) y, si falla, Open-Meteo ---------- */
async function geocode(q){q=String(q||'').trim();if(q.length<2)return[];try{const d=await json('https://nominatim.openstreetmap.org/search?'+new URLSearchParams({format:'jsonv2',limit:'6',countrycodes:'es',addressdetails:'0','accept-language':'es',q}),86400000);const out=(d||[]).map(x=>({name:String(x.display_name||q).split(',').slice(0,3).join(','),full:x.display_name,lat:+x.lat,lon:+x.lon,type:x.type||''})).filter(x=>finite(x.lat)&&finite(x.lon));if(out.length)return out}catch{}
 try{const d=await json('https://geocoding-api.open-meteo.com/v1/search?'+new URLSearchParams({name:q,count:'6',language:'es',countryCode:'ES'}),86400000);return(d.results||[]).map(x=>({name:[x.name,x.admin2,x.admin1].filter(Boolean).join(', '),full:[x.name,x.admin3,x.admin2,x.admin1].filter(Boolean).join(', '),lat:x.latitude,lon:x.longitude,type:x.feature_code||''}))}catch{return[]}}
/* ---------- Ruta en coche: OSRM (con alternativas); Valhalla como respaldo ---------- */
function buildRoute(geo,steps,distance,duration,source){const line=[];let km=0,t=0;for(const st of steps){const cs=(st.coords||[]);const stepKm=cs.reduce((s,p,i)=>i?s+kmBetween(cs[i-1],p):0,0);let acc=0;cs.forEach((p,i)=>{if(i)acc+=kmBetween(cs[i-1],p);if(line.length&&i===0)return;const prev=line.at(-1);const k=prev?km+acc:0;line.push({lat:p.lat,lon:p.lon,km:k,t:t+(stepKm?acc/stepKm:0)*st.duration})});km+=stepKm;t+=st.duration}
 if(line.length<2){let k=0;geo.forEach((p,i)=>{if(i)k+=kmBetween(geo[i-1],p);line.push({...p,km:k,t:0})});const tot=k||1;line.forEach(p=>p.t=p.km/tot*duration)}
 const roads={};for(const st of steps){const k=(st.ref||st.name||'').split(';')[0].trim();if(k)roads[k]=(roads[k]||0)+st.distance/1000}
 return{line,km:distance/1000,min:duration/60,roads:Object.entries(roads).sort((a,b)=>b[1]-a[1]).filter(r=>r[1]>=.8).slice(0,8),source}}
async function routeOSRM(o,d){const r=await fetch(`https://router.project-osrm.org/route/v1/driving/${o.lon.toFixed(5)},${o.lat.toFixed(5)};${d.lon.toFixed(5)},${d.lat.toFixed(5)}?`+new URLSearchParams({overview:'full',geometries:'geojson',steps:'true',alternatives:'true'}));if(!r.ok)throw Error('Servidor de rutas ocupado ('+r.status+')');const j=await r.json();if(j.code!=='Ok'||!j.routes?.length)throw Error(j.message||'No hay ruta por carretera');const snap=(j.waypoints||[]).map(w=>w.distance);return j.routes.slice(0,3).map(rt=>{const steps=rt.legs.flatMap(l=>l.steps).map(s=>({coords:(s.geometry?.coordinates||[]).map(([lon,lat])=>({lat,lon})),duration:s.duration,distance:s.distance,ref:s.ref||'',name:s.name||''}));const out=buildRoute(rt.geometry.coordinates.map(([lon,lat])=>({lat,lon})),steps,rt.distance,rt.duration,'OSRM · OpenStreetMap');out.snap=snap;return out})}
async function routeValhalla(o,d){const q={locations:[{lat:o.lat,lon:o.lon},{lat:d.lat,lon:d.lon}],costing:'auto',directions_options:{language:'es-ES'}};const r=await fetch('https://valhalla1.openstreetmap.de/route?json='+encodeURIComponent(JSON.stringify(q)));if(!r.ok)throw Error('Servidor de rutas no disponible');const j=await r.json(),leg=j.trip?.legs?.[0];if(!leg)throw Error('No hay ruta por carretera');const pts=TMWikiloc.decodePolyline(leg.shape,6);const steps=(leg.maneuvers||[]).map(m=>({coords:pts.slice(m.begin_shape_index,m.end_shape_index+1),duration:m.time,distance:m.length*1000,ref:'',name:(m.street_names||[])[0]||''}));return[buildRoute(pts,steps,j.trip.summary.length*1000,j.trip.summary.time,'Valhalla · OpenStreetMap')]}
async function driveRoutes(o,d){try{return await routeOSRM(o,d)}catch(e){try{return await routeValhalla(o,d)}catch{throw e}}}
/* ---------- DGT ---------- */
async function loadDGT(){try{const r=await fetch('data/dgt.json',{cache:'no-cache'});if(!r.ok)throw Error();RD.dgt=await r.json()}catch{RD.dgt={complete:false,incidents:[],errors:['sin datos']}}return RD.dgt}
function incidentsOn(route,dgt,depart){const arr=depart+route.min*60000;return(dgt?.incidents||[]).map(x=>{const a=nearestOnLine({lat:x.lat,lon:x.lon},route.line),b=x.lat2!=null?nearestOnLine({lat:x.lat2,lon:x.lon2},route.line):a,near=Math.min(a.d,b.d),kmAt=a.d<=b.d?a.km:b.km,start=Date.parse(x.start),end=Date.parse(x.end),when=depart+(route.line.length?(route.line[Math.max(0,(a.d<=b.d?a.i:b.i)-1)]?.t||0):0)*1000,active=!(finite(start)&&start>arr)&&!(finite(end)&&end<depart);return{...x,near,kmAt,when,active}}).filter(x=>x.near<=25).sort((a,b)=>a.near<=.6&&b.near<=.6?a.kmAt-b.kmAt:a.near-b.near)}
/* ---------- Tiempo en la carretera ---------- */
function samplesOf(route){const tot=route.km,step=Math.max(1.5,tot/40),out=[];let next=0;for(const p of route.line){if(p.km>=next){out.push(p);next+=step}}if(out.at(-1)!==route.line.at(-1))out.push(route.line.at(-1));return out.slice(0,45)}
function roadRisk(h,prev12,depth){if(!h)return{level:'unknown',label:'sin datos'};const t=h.temperature_2m,pr=h.precipitation||0,sf=h.snowfall||0;if(sf>=.2||(pr>=.2&&finite(t)&&t<=1))return{level:'high',label:'Nevando',icon:'❄'};if(finite(t)&&t<=1&&(prev12>=.5||depth>=.01))return{level:'high',label:'Hielo probable',icon:'⧆'};if(depth>=.03)return{level:'medium',label:'Nieve en el entorno',icon:'❄'};if(finite(t)&&t<=0)return{level:'medium',label:'Helada',icon:'✱'};if(finite(h.visibility)&&h.visibility<1000)return{level:'medium',label:'Niebla',icon:'≋'};if(pr>=2)return{level:'medium',label:'Lluvia intensa',icon:'☂'};if(h.wind_gusts_10m>=70)return{level:'medium',label:'Rachas fuertes',icon:'➶'};return{level:'low',label:'Sin incidencias meteorológicas',icon:''}}
async function roadWeather(route,depart){const pts=samplesOf(route);const d=await json('https://api.open-meteo.com/v1/forecast?'+new URLSearchParams({latitude:pts.map(p=>p.lat.toFixed(4)).join(','),longitude:pts.map(p=>p.lon.toFixed(4)).join(','),hourly:'temperature_2m,precipitation,snowfall,snow_depth,visibility,wind_gusts_10m,freezing_level_height',past_days:'1',forecast_days:'7',timezone:'auto',timeformat:'unixtime'}),1800000);const list=Array.isArray(d)?d:[d];
 return pts.map((p,i)=>{const rows=hours(list[i]),eta=depart+p.t*1000,h=nearest(rows,eta,5400000),prev12=rows.filter(r=>r.time<=eta&&r.time>eta-12*3600000).reduce((a,r)=>a+(r.precipitation||0),0);return{...p,eta,ele:list[i]?.elevation,h,risk:roadRisk(h,prev12,h?.snow_depth||0)}})}
/* Puertos: máximos locales con al menos 120 m de prominencia a ambos lados en el perfil muestreado. */
function passes(samples){const out=[];for(let i=1;i<samples.length-1;i++){const e=samples[i].ele;if(!finite(e)||e<600)continue;const left=Math.min(...samples.slice(0,i).map(s=>s.ele).filter(finite)),right=Math.min(...samples.slice(i+1).map(s=>s.ele).filter(finite));if(e-left>=120&&e-right>=120&&samples.slice(Math.max(0,i-2),i+3).every(s=>!finite(s.ele)||s.ele<=e))out.push(samples[i])}const top=samples.reduce((a,b)=>finite(b.ele)&&(!a||b.ele>a.ele)?b:a,null);if(top&&!out.includes(top)&&top.ele>=600)out.push(top);return out.sort((a,b)=>a.km-b.km)}

/* ---------- Interfaz ---------- */
$('#pane-canales')?.insertAdjacentHTML('afterend',`<section id="pane-road" class="pane" hidden><div class="route-hero"><p class="eyebrow">Carretera · antes de arrancar el coche</p><h2>Cómo <b>llegar</b></h2><p class="route-hero-sub">Dime de dónde sales y a dónde vas: calculo el trayecto y te digo qué avisos de la DGT hay en él, si piden cadenas, por qué puertos pasas y qué tiempo hará en cada tramo a la hora en que pases.</p></div>
<section class="card"><form id="roadForm" class="road-form" autocomplete="off"><label>Salgo de<div class="road-input"><input id="roadFrom" placeholder="Ej.: Arenas de Cabrales" maxlength="120"><button type="button" class="quiet" id="roadGeo" title="Usar mi ubicación">📍</button></div></label><div class="road-cands" id="roadFromCands"></div><label>Voy a<div class="road-input"><input id="roadTo" placeholder="Inicio de tu ruta, pueblo o aparcamiento" maxlength="120"><button type="button" class="quiet" id="roadUseRoute" title="Inicio de la ruta cargada">⚑</button></div></label><div class="road-cands" id="roadToCands"></div><div class="road-quick" id="roadQuick">${QUICK.map(q=>`<button type="button" data-road-quick="${esc(q)}">${esc(q)}</button>`).join('')}</div><label>Salida<input type="datetime-local" id="roadDepart"></label><div class="action-row"><button class="primary" type="submit">Buscar trayecto y avisos</button><button class="quiet" type="button" id="roadFit" hidden>Llegar a la hora de mi ruta</button></div><p class="wl-status" id="roadStatus" role="status"></p></form></section>
<div id="roadOut" hidden><section class="card"><div class="viz-title"><div><p class="eyebrow">Trayecto</p><h2 id="roadTitle">—</h2></div><div class="seg" id="roadAlts" role="group" aria-label="Alternativas"></div></div><div class="ground" id="roadKpis"></div><div id="roadMap" class="road-map"></div><p class="footnote" id="roadNote"></p></section>
<section class="card"><div class="viz-title"><div><p class="eyebrow">DGT en tu trayecto</p><h2>Avisos y cadenas</h2></div><span class="pill" id="roadDgtAge"></span></div><div id="roadIncidents"></div><details class="road-levels"><summary>Niveles de circulación con nieve (DGT)</summary>${Object.entries(CHAIN_LEVELS).map(([k,[c,n,t]])=>`<p><span class="chain-dot" style="background:${c}"></span><b>${n}</b> · ${t}</p>`).join('')}<p class="footnote">Resumen orientativo. La señalización y los agentes mandan. <a href="https://www.dgt.es/muevete-con-seguridad/viaja-seguro/viaja-seguro-en-invierno/" target="_blank" rel="noopener">DGT · viajar en invierno ↗</a></p></details></section>
<section class="card"><div class="viz-title"><div><p class="eyebrow">Tiempo en la carretera</p><h2>Tramo a tramo, a tu hora</h2></div></div><div id="roadProfile"></div><div id="roadPasses"></div><div id="roadWx"></div><p class="footnote">Previsión Open-Meteo en puntos del trayecto a la hora estimada de paso, con la altitud real del terreno (90 m). El hielo se estima por temperatura ≤ 1 °C con precipitación en las 12 h previas o nieve en el suelo; no detecta placas locales en sombras o puentes.</p></section>
<section class="card"><p class="eyebrow">Fuentes en directo</p><div class="cn-links"><a href="https://infocar.dgt.es/etraffic/" target="_blank" rel="noopener"><b>Mapa DGT en tiempo real</b><small>Incidencias, cámaras y puertos</small></a><a href="https://www.dgt.es/conoce-el-estado-del-trafico/" target="_blank" rel="noopener"><b>Estado del tráfico (DGT)</b><small>También por teléfono: 011</small></a><a href="https://www.aemet.es/es/eltiempo/prediccion/avisos" target="_blank" rel="noopener"><b>Avisos AEMET</b><small>Nieve, viento y lluvia</small></a></div></section></div></section>`);
const roadFromEl=()=>$('#roadFrom'),roadToEl=()=>$('#roadTo');
try{const o=JSON.parse(localStorage.getItem('tm.road.origin')||'null');if(o&&finite(o.lat)){RD.origin=o;$('#roadFrom').value=o.name}}catch{}
function defaultDepart(){const d=new Date(Date.now()+3600000);d.setMinutes(Math.ceil(d.getMinutes()/15)*15,0,0);return d}
$('#roadDepart').value=localInput(defaultDepart());
function routeStart(){const p=S.route?.points?.[0];return p?{name:'Inicio de «'+(S.route.name||'tu ruta')+'»',lat:p.lat,lon:p.lon,fromRoute:true}:null}
function setDest(d){RD.dest=d;roadToEl().value=d?.name||''}
function cands(box,list,pick){const el=$(box);if(!el)return;el.innerHTML=list.length>1?list.slice(0,5).map((c,i)=>`<button type="button" data-cand="${i}" aria-pressed="${!i}" title="${esc(c.full)}">${esc(c.name)}</button>`).join(''):'';el.onclick=e=>{const b=e.target.closest('[data-cand]');if(!b)return;pick(list[+b.dataset.cand]);el.querySelectorAll('[data-cand]').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));run(false)}}
async function resolve(input,current,box,pick){const v=input.value.trim();if(current&&current.name===v)return current;const list=await geocode(v);if(!list.length)throw Error(`No encuentro «${v}»`);cands(box,list,pick);pick(list[0]);return list[0]}
async function run(regeo=true){const seq=++RD.seq,st=$('#roadStatus');st.className='wl-status';st.innerHTML='<span class="spinner"></span>Localizando origen y destino…';
 try{if(!roadToEl().value.trim()&&routeStart())setDest(routeStart());if(!roadFromEl().value.trim())throw Error('Escribe de dónde sales (o usa 📍)');if(!roadToEl().value.trim())throw Error('Escribe a dónde vas o carga una ruta');
  const o=regeo?await resolve(roadFromEl(),RD.origin,'#roadFromCands',c=>{RD.origin=c;roadFromEl().value=c.name}):RD.origin,d=regeo?await resolve(roadToEl(),RD.dest,'#roadToCands',c=>setDest(c)):RD.dest;if(seq!==RD.seq)return;try{localStorage.setItem('tm.road.origin',JSON.stringify(o))}catch{}
  st.innerHTML='<span class="spinner"></span>Calculando el trayecto por carretera…';const [routes,dgt]=await Promise.all([driveRoutes(o,d),loadDGT()]);if(seq!==RD.seq)return;RD.routes=routes;RD.sel=0;
  st.innerHTML='<span class="spinner"></span>Cruzando avisos de la DGT y el tiempo en cada tramo…';await evaluate(seq);if(seq!==RD.seq)return;st.className='wl-status ok';st.textContent=`✓ ${o.name} → ${d.name}`;if(typeof sfx==='function')sfx('ok');findParking(d,seq)}
 catch(e){if(seq===RD.seq){st.className='wl-status err';st.textContent=e.message;if(typeof sfx==='function')sfx('warn')}}}
async function evaluate(seq=RD.seq){const depart=new Date($('#roadDepart').value).getTime()||Date.now();await Promise.all(RD.routes.map(async r=>{r.depart=depart;r.incidents=incidentsOn(r,RD.dgt,depart);try{r.wx=await roadWeather(r,depart)}catch(e){r.wx=null;r.wxError=e.message}r.passes=r.wx?passes(r.wx):[];r.score=r.incidents.filter(x=>x.near<=.6&&x.active&&['chains','closed','snow','ice'].includes(x.kind)).length*3+(r.wx||[]).filter(w=>w.risk.level==='high').length}));if(seq!==RD.seq)return;
 RD.best=RD.routes.length>1?RD.routes.reduce((a,b,i)=>b.score<RD.routes[a].score?i:a,0):0;render()}
function fmtMin(m){return m>=60?`${Math.floor(m/60)} h ${String(Math.round(m%60)).padStart(2,'0')} min`:`${Math.round(m)} min`}
function render(){const r=RD.routes[RD.sel];if(!r)return;$('#roadOut').hidden=false;const arrive=r.depart+r.min*60000,onRoute=r.incidents.filter(x=>x.near<=.6),nearby=r.incidents.filter(x=>x.near>.6&&['chains','closed','snow','ice'].includes(x.kind)),top=r.wx?.reduce((a,b)=>finite(b.ele)&&(!a||b.ele>a.ele)?b:a,null),high=(r.wx||[]).filter(w=>w.risk.level==='high');
 $('#roadTitle').textContent=`${RD.origin.name.split(',')[0]} → ${RD.dest.name.split(',')[0]}`;
 $('#roadAlts').innerHTML=RD.routes.length>1?RD.routes.map((x,i)=>`<button type="button" data-road-alt="${i}" aria-pressed="${i===RD.sel}">${i?'Alternativa '+i:'Principal'} <small>${fmtMin(x.min)}${i&&i===RD.best?' · ★ menos avisos':''}</small></button>`).join(''):'';
 $('#roadKpis').innerHTML=`<div><span>Distancia</span><strong>${fmt(r.km,0)} km</strong><p>${esc(r.roads.map(x=>x[0]).slice(0,4).join(' · ')||'—')}</p></div><div><span>Tiempo</span><strong>${fmtMin(r.min)}</strong><p>llegada ≈ ${exTime(arrive)}</p></div><div><span>Cota máxima</span><strong>${top?fmt(top.ele)+' m':'—'}</strong><p>${top?'km '+fmt(top.km,0):''}</p></div><div><span>Avisos en el trayecto</span><strong>${onRoute.filter(x=>x.active).length}</strong><p>${high.length?'previsión: '+high.length+' tramos con nieve o hielo':'previsión: sin nieve ni hielo'}</p></div>`;
 const snapEnd=r.snap?.[1],better=RD.best!==RD.sel&&RD.routes[RD.best];$('#roadNote').innerHTML=`${better?`<b>La ${RD.best?'alternativa '+RD.best:'ruta principal'} tiene menos avisos de nieve, hielo o cadenas (${fmtMin(better.min)}).</b> `:''}Ruta ${esc(r.source)}. Tiempos sin tráfico ni paradas.${finite(snapEnd)&&snapEnd>150?` <b>La carretera termina a ${fmt(snapEnd)} m del destino</b>: el último tramo es a pie o por pista.`:''}${RD.park?` · <a href="#" id="roadToPark">Ir al aparcamiento más cercano (${esc(RD.park.name)}, ${fmt(RD.park.d*1000)} m)</a>`:''}`;
 const age=RD.dgt?.fetched?Math.round((Date.now()-Date.parse(RD.dgt.fetched))/60000):null;$('#roadDgtAge').textContent=RD.dgt?.complete?`DGT · hace ${age<1?'<1':age} min`:'DGT no disponible';
 const inc=x=>{const k=KIND[x.kind]||KIND.other,lv=CHAIN_LEVELS[x.level];return `<div class="road-inc ${x.active?'':'off'}"><span class="inc-kind" style="--c:${lv?lv[0]:k[1]}">${lv?'Nivel '+lv[1]:k[0]}</span><div><b>${esc(x.road||'Vía sin identificar')}${x.km?.length?` · km ${fmt(x.km[0],1)}${x.km[1]!==x.km[0]?'–'+fmt(x.km[1],1):''}`:''}</b><small>${x.near<=.6?`en tu trayecto, km ${fmt(x.kmAt,0)} · paso ≈ ${exTime(x.when)}`:`a ${fmt(x.near,0)} km de tu trayecto`}${x.place?' · '+esc(x.place):''}${x.dir?' · sentido '+esc(x.dir):''}</small>${x.text?`<p>${esc(x.text)}</p>`:''}<small>${x.start?'desde '+exTime(Date.parse(x.start)):''}${x.end?' · hasta '+exTime(Date.parse(x.end)):''}${x.active?'':' · no vigente a tu hora'}</small></div></div>`};
 $('#roadIncidents').innerHTML=(RD.dgt?.complete?'':`<p class="wl-status err">La última lectura de la DGT falló. Comprueba el mapa oficial antes de salir.</p>`)+(onRoute.length?onRoute.map(inc).join(''):`<p class="sky-verdict">${RD.dgt?.complete?'Sin avisos de la DGT sobre tu trayecto ahora mismo.':'Sin datos de la DGT.'}</p>`)+(nearby.length?`<h4 class="tr-title">Nieve, cadenas y cortes cerca (≤ 25 km)</h4>${nearby.slice(0,8).map(inc).join('')}`:'');
 renderProfile(r);drawMap(r)}
function renderProfile(r){const wx=r.wx;if(!wx){$('#roadProfile').innerHTML=`<p class="muted">Sin previsión en ruta (${esc(r.wxError||'')}).</p>`;$('#roadWx').innerHTML='';$('#roadPasses').innerHTML='';return}const e=wx.map(w=>w.ele).filter(finite);if(e.length<2){$('#roadProfile').innerHTML='';return}const lo=Math.min(...e),hi=Math.max(...e),W=100,H=34,X=k=>k/r.km*W,Y=v=>H-(v-lo)/Math.max(1,hi-lo)*H,col={high:'#c62828',medium:'#d4861a',low:'#1d8ea3',unknown:'#9aa4a8'};
 const segs=wx.slice(1).map((w,i)=>`<line x1="${X(wx[i].km)}" y1="${Y(wx[i].ele??lo)}" x2="${X(w.km)}" y2="${Y(w.ele??lo)}" stroke="${col[w.risk.level]}" stroke-width="2.4" stroke-linecap="round" vector-effect="non-scaling-stroke"/>`).join('');
 $('#roadProfile').innerHTML=`<svg class="road-svg" viewBox="0 -3 ${W} ${H+6}" preserveAspectRatio="none" aria-label="Perfil de la carretera coloreado por condiciones"><path d="M${wx.map(w=>`${X(w.km)} ${Y(w.ele??lo)}`).join(' L')} L${W} ${H+3} L0 ${H+3}Z" fill="rgba(29,142,163,.08)"/>${segs}${r.passes.map(p=>`<circle cx="${X(p.km)}" cy="${Y(p.ele)}" r="1.1" fill="#10161a"/>`).join('')}</svg><div class="sky-axis"><span>${fmt(lo)}–${fmt(hi)} m</span><span>${fmt(r.km,0)} km</span></div><div class="legend-dots"><span><i style="background:#1d8ea3"></i>Sin incidencias</span><span><i style="background:#d4861a"></i>Helada, niebla, lluvia o viento</span><span><i style="background:#c62828"></i>Nieve o hielo</span></div>`;
 $('#roadPasses').innerHTML=r.passes.length?`<h4 class="tr-title">Puntos altos del trayecto</h4><div class="snow-sec">${r.passes.map(p=>`<div class="${p.risk.level==='high'?'fall':''}"><b>km ${fmt(p.km,0)}</b><span>${exTime(p.eta)} · ${fmt(p.ele)} m</span><strong>${finite(p.h?.temperature_2m)?fmt(p.h.temperature_2m,0)+' °C':'—'}</strong><small>${esc(p.risk.label)}${finite(p.h?.snow_depth)&&p.h.snow_depth>=.01?` · ${fmt(p.h.snow_depth*100)} cm nieve`:''}</small></div>`).join('')}</div>`:'';
 const bad=wx.filter(w=>w.risk.level!=='low');$('#roadWx').innerHTML=bad.length?`<h4 class="tr-title">Tramos a vigilar</h4>${bad.map(w=>`<div class="road-inc"><span class="inc-kind" style="--c:${col[w.risk.level]}">${esc(w.risk.label)}</span><div><b>km ${fmt(w.km,0)} · ${exTime(w.eta)}</b><small>${finite(w.ele)?fmt(w.ele)+' m · ':''}${finite(w.h?.temperature_2m)?fmt(w.h.temperature_2m,1)+' °C':''}${finite(w.h?.precipitation)&&w.h.precipitation>0?' · '+fmt(w.h.precipitation,1)+' mm/h':''}${finite(w.h?.visibility)&&w.h.visibility<5000?' · visibilidad '+fmt(w.h.visibility)+' m':''}</small></div></div>`).join('')}`:'<p class="sky-verdict">Sin nieve, hielo, niebla ni lluvia fuerte previstos en el trayecto a tu hora.</p>'}
function drawMap(r){const el=$('#roadMap');if(!el||typeof L==='undefined'||!el.offsetParent)return;if(!RD.map){RD.map=L.map(el,{scrollWheelZoom:false});L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:18,attribution:'© OpenStreetMap contributors'}).addTo(RD.map)}else RD.map.invalidateSize();RD.layers?.remove();const items=[];
 RD.routes.forEach((x,i)=>{if(i!==RD.sel)items.push(L.polyline(x.line.map(p=>[p.lat,p.lon]),{color:'#5d6f7a',weight:4,opacity:.45,dashArray:'6 8'}))});const col={high:'#c62828',medium:'#d4861a',low:'#1d8ea3',unknown:'#1d8ea3'};items.push(L.polyline(r.line.map(p=>[p.lat,p.lon]),{color:'#fff',weight:9,opacity:.9}));if(r.wx){for(let i=1;i<r.wx.length;i++){const a=r.wx[i-1],b=r.wx[i];items.push(L.polyline(r.line.filter(p=>p.km>=a.km&&p.km<=b.km).map(p=>[p.lat,p.lon]),{color:col[b.risk.level],weight:5}))}}else items.push(L.polyline(r.line.map(p=>[p.lat,p.lon]),{color:'#1d8ea3',weight:5}));
 for(const x of r.incidents){const k=KIND[x.kind]||KIND.other,lv=CHAIN_LEVELS[x.level];items.push(L.circleMarker([x.lat,x.lon],{radius:x.near<=.6?8:6,color:'#fff',weight:2,fillColor:lv?lv[0]:k[1],fillOpacity:x.active?1:.4}).bindTooltip(`${lv?'Cadenas · nivel '+lv[1]:k[0]} · ${x.road||''}`))}
 items.push(L.circleMarker([r.line[0].lat,r.line[0].lon],{radius:7,color:'#10161a',weight:2,fillColor:'#fff',fillOpacity:1}).bindTooltip('Salida'));items.push(L.circleMarker([RD.dest.lat,RD.dest.lon],{radius:7,color:'#fff',weight:2,fillColor:'#ff5a1f',fillOpacity:1}).bindTooltip(RD.dest.name));if(RD.park)items.push(L.circleMarker([RD.park.lat,RD.park.lon],{radius:6,color:'#fff',weight:2,fillColor:'#2b86c5',fillOpacity:1}).bindTooltip('P · '+RD.park.name));
 RD.layers=L.featureGroup(items).addTo(RD.map);RD.map.fitBounds(RD.layers.getBounds(),{padding:[24,24]})}
/* Aparcamiento cartografiado más cercano al destino (≤ 1,5 km). */
async function findParking(d,seq){if(typeof overpass!=='function')return;try{const els=await overpass(`[out:json][timeout:20];nwr["amenity"="parking"](around:1500,${d.lat.toFixed(5)},${d.lon.toFixed(5)});out center tags 20;`,25000);if(seq!==RD.seq)return;const ps=els.map(e=>({lat:e.lat??e.center?.lat,lon:e.lon??e.center?.lon,name:e.tags?.name||'aparcamiento'})).filter(p=>finite(p.lat)).map(p=>({...p,d:kmBetween(p,d)})).sort((a,b)=>a.d-b.d);RD.park=ps[0]||null;if(RD.park&&RD.routes.length)render()}catch{}}
/* ---------- Eventos ---------- */
$('#roadForm').onsubmit=e=>{e.preventDefault();run(true)};
$('#roadFrom').oninput=()=>{RD.origin=null;$('#roadFromCands').innerHTML=''};$('#roadTo').oninput=()=>{RD.dest=null;RD.park=null;$('#roadToCands').innerHTML=''};
$('#roadQuick').onclick=e=>{const b=e.target.closest('[data-road-quick]');if(!b)return;const target=document.activeElement===roadFromEl()||!roadFromEl().value.trim()?roadFromEl():roadToEl();target.value=b.dataset.roadQuick;target.dispatchEvent(new Event('input'))};
$('#roadUseRoute').onclick=()=>{const s=routeStart();if(s){setDest(s);$('#roadToCands').innerHTML=''}else{$('#roadStatus').textContent='Carga primero una ruta en Planificar.'}};
$('#roadGeo').onclick=()=>{if(!navigator.geolocation){$('#roadStatus').textContent='Tu navegador no da la ubicación.';return}$('#roadStatus').innerHTML='<span class="spinner"></span>Buscando tu ubicación…';navigator.geolocation.getCurrentPosition(p=>{RD.origin={name:'Mi ubicación',lat:p.coords.latitude,lon:p.coords.longitude};roadFromEl().value='Mi ubicación';$('#roadStatus').textContent='Ubicación lista.'},()=>{$('#roadStatus').textContent='No se pudo obtener tu ubicación.'},{enableHighAccuracy:true,timeout:15000})};
$('#roadDepart').onchange=()=>{if(RD.routes.length)evaluate()};
$('#roadFit').onclick=()=>{const p=typeof currentPlan==='function'?currentPlan():null,r=RD.routes[RD.sel];if(!p||!r)return;const dep=new Date(+p.start-r.min*60000-20*60000);$('#roadDepart').value=localInput(dep);evaluate()};
document.addEventListener('click',e=>{const a=e.target.closest('[data-road-alt]');if(a){RD.sel=+a.dataset.roadAlt;render();return}if(e.target.id==='roadToPark'){e.preventDefault();setDest({name:RD.park.name+' (aparcamiento)',lat:RD.park.lat,lon:RD.park.lon});RD.park=null;run(false)}});
function syncFit(){$('#roadFit').hidden=!(typeof currentPlan==='function'&&currentPlan())}
const rdShowTab=showTab;showTab=function(tab){rdShowTab(tab);if(tab==='road'){syncFit();if(!roadToEl().value.trim()&&routeStart())setDest(routeStart());setTimeout(()=>{if(RD.routes.length)drawMap(RD.routes[RD.sel])},80)}};
if(typeof TAB_IDS!=='undefined'&&!TAB_IDS.includes('road'))TAB_IDS.push('road');
globalThis.TMTheme?.addMore(['road','Carretera','DGT, cadenas, puertos y tiempo en el trayecto','<path d="M5 21 9 3M19 21 15 3M12 5v2M12 11v2M12 17v2"/>'],()=>enterApp('road'),'library');
/* Accesos directos desde Planificar y desde la ficha de cada canal. */
$('#routeFinder')?.insertAdjacentHTML('afterend','<div class="road-cta"><button class="quiet" type="button" data-go-road>🚗 Cómo llegar · DGT, cadenas y carretera</button></div>');
document.addEventListener('click',e=>{if(e.target.closest('[data-go-road]')){if(routeStart())setDest(routeStart());enterApp('road')}});
function goRoadTo(dest){setDest(dest);RD.park=null;enterApp('road');if(roadFromEl().value.trim())run(true)}
const rdOpenCanal=globalThis.TMCanales?.open;if(rdOpenCanal){new MutationObserver(()=>{const acts=$('#cnDetail .cn-actions');if(acts&&!acts.querySelector('[data-canal-road]')){acts.insertAdjacentHTML('beforeend','<button class="quiet" type="button" data-canal-road>🚗 Cómo llegar</button>')}}).observe(document.body,{childList:true})}
document.addEventListener('click',e=>{if(!e.target.closest('[data-canal-road]'))return;const c=TMCanales.selected;const park=c?.access?.bottom?.park,b=c?.profile?.prof?.[0]||c?.chain?.[0]||c?.center;TMCanales.close();if(park)goRoadTo({name:(park.f.tags.name||'Aparcamiento')+' · '+c.name,lat:park.f.p.lat,lon:park.f.p.lon});else if(b)goRoadTo({name:'Pie de la '+c.name,lat:b.lat,lon:b.lon})});
function context(){const r=RD.routes[RD.sel];if(!r)return null;return{origen:RD.origin?.name,destino:RD.dest?.name,salida:exTime(r.depart),llegada:exTime(r.depart+r.min*60000),km:Math.round(r.km),minutos:Math.round(r.min),carreteras:r.roads.map(x=>x[0]),avisos_dgt_en_trayecto:r.incidents.filter(x=>x.near<=.6).slice(0,10).map(x=>({tipo:x.kind,nivel_cadenas:x.level||null,via:x.road,km:x.km,vigente:x.active,texto:x.text.slice(0,200)})),cadenas_o_cortes_cerca:r.incidents.filter(x=>x.near>.6&&['chains','closed','snow','ice'].includes(x.kind)).slice(0,6).map(x=>({tipo:x.kind,nivel:x.level||null,via:x.road,a_km:Math.round(x.near)})),tramos_a_vigilar:(r.wx||[]).filter(w=>w.risk.level!=='low').map(w=>({km:Math.round(w.km),hora:exTime(w.eta),cota:w.ele,riesgo:w.risk.label})),datos_dgt:RD.dgt?.complete?RD.dgt.fetched:'no disponibles'}}
globalThis.TMRoad={geocode,driveRoutes,buildRoute,nearestOnLine,incidentsOn,roadRisk,passes,samplesOf,loadDGT,run,evaluate,context,goTo:goRoadTo,CHAIN_LEVELS,get state(){return RD}};
