'use strict';
/* Mar de nubes: capas por niveles de presión (Open-Meteo) para saber si estarás por encima o dentro de las nubes. */
const SKY={levels:[1000,950,925,900,850,800,700,600],seq:0,data:null};
$('#pane-now .overview')?.insertAdjacentHTML('afterend',`<section class="card" id="skyCard"><div class="viz-title"><div><p class="eyebrow">Mar de nubes</p><h2>¿Por encima o dentro?</h2></div><label class="muted">Hora <input type="range" id="skyHour" min="0" max="47" value="0" style="width:180px"> <b id="skyHourLbl" class="sky-hlbl">ahora</b></label></div><div class="sky-stack" id="skyStack"></div><p class="sky-verdict" id="skyVerdict">Leyendo las capas de la atmósfera…</p><p class="muted" id="skyDetail"></p><div class="sky-strip" id="skyStrip" aria-label="Techo de nubes bajas próximas 24 h"></div><div class="sky-axis"><span>ahora</span><span>+12 h</span><span>+24 h</span></div><p class="footnote">Capas con nubosidad ≥ 60 % en los niveles de 1000 a 600 hPa (≈ 100–4200 m) del modelo, interpoladas a su altura geopotencial. Útil para inversiones y nieblas de valle; el detalle real depende del relieve local.</p></section>`);
function skyURL(lat,lon){const v=[];for(const l of SKY.levels)v.push(`cloud_cover_${l}hPa`,`geopotential_height_${l}hPa`,`relative_humidity_${l}hPa`);return 'https://api.open-meteo.com/v1/forecast?'+new URLSearchParams({latitude:lat.toFixed(3),longitude:lon.toFixed(3),hourly:'freezing_level_height,cloud_cover_low,cloud_cover_mid,cloud_cover_high,'+v.join(','),forecast_days:'3',timezone:'auto',timeformat:'unixtime'})}
/* Devuelve la capa nubosa baja (base y techo en m) para una hora. */
function cloudLayer(h,i){const lv=SKY.levels.map(l=>({l,cc:h[`cloud_cover_${l}hPa`]?.[i],z:h[`geopotential_height_${l}hPa`]?.[i],rh:h[`relative_humidity_${l}hPa`]?.[i]})).filter(x=>finite(x.z)).sort((a,b)=>a.z-b.z);if(!lv.length)return null;const cloudy=x=>finite(x.cc)?x.cc>=60:finite(x.rh)&&x.rh>=95;let first=lv.findIndex(cloudy);if(first<0)return{clear:true,levels:lv};let last=first;while(last+1<lv.length&&cloudy(lv[last+1]))last++;const base=first?Math.round((lv[first-1].z+lv[first].z)/2):Math.max(0,lv[first].z-80),top=last+1<lv.length?Math.round((lv[last].z+lv[last+1].z)/2):lv[last].z,above=lv.slice(last+1),clearAbove=above.length&&above.slice(0,2).every(x=>!cloudy(x));return{base,top,clearAbove,levels:lv,cover:Math.max(...lv.slice(first,last+1).map(x=>x.cc??0))}}
function skyTarget(){const r=S.route,el=r?.summary?.elevationComplete?r.points.map(p=>p.ele).filter(finite):[];return{lat:r?.points?.[0]?.lat??S.location.lat,lon:r?.points?.[0]?.lon??S.location.lon,top:el.length?Math.max(...el):S.forecast?.elevation??null,bottom:el.length?Math.min(...el):null,name:r?.name||S.location.name}}
async function loadSky(){const t=skyTarget();if(!finite(t.lat))return;const seq=++SKY.seq;try{const d=await json(skyURL(t.lat,t.lon),1800000);if(seq!==SKY.seq)return;const h=d.hourly||{},now=Date.now()/1000,start=Math.max(0,(h.time||[]).findIndex(x=>x>=now-1800));SKY.data={h,start,t};$('#skyHour').max=Math.min(47,(h.time||[]).length-start-1);renderSky()}catch(e){$('#skyVerdict').textContent='No se pudieron leer las capas de nubes: '+e.message}}
function renderSky(){const s=SKY.data;if(!s)return;const {h,start,t}=s,i=start+Number($('#skyHour').value),L=cloudLayer(h,i),time=h.time[i]*1000,maxZ=Math.min(5200,Math.max(3200,(t.top||0)+600,L&&!L.clear?L.top+400:0,finite(h.freezing_level_height?.[i])?h.freezing_level_height[i]+400:0)),Y=z=>Math.max(0,Math.min(100,100-z/maxZ*100));
 let verdict='—',detail='';if(!L){verdict='Sin datos de capas para esta hora.'}else if(L.clear){verdict='Sin capas nubosas bajas: cielo abierto en altura.';detail=`Nubes altas ${fmt(h.cloud_cover_high?.[i])} %.`}else{const sea=L.base<1200&&L.clearAbove;if(finite(t.top)){if(t.top>L.top+50)verdict=sea?`Mar de nubes con techo a ≈ ${fmt(L.top)} m: por encima de esa cota estarás al sol.`:`Nubes entre ${fmt(L.base)} y ${fmt(L.top)} m; tu cota máxima (${fmt(t.top)} m) queda por encima.`;else if(t.top>=L.base)verdict=`Dentro de la nube: capa entre ${fmt(L.base)} y ${fmt(L.top)} m. Visibilidad reducida en tu cota (${fmt(t.top)} m).`;else verdict=`Bajo las nubes: base a ≈ ${fmt(L.base)} m, por encima de tu cota máxima (${fmt(t.top)} m).`}else verdict=`Capa nubosa entre ${fmt(L.base)} y ${fmt(L.top)} m.`;detail=`${sea?'Inversión probable (capa baja con cielo despejado encima). ':''}Cobertura de la capa ${fmt(L.cover)} %.`}
 $('#skyVerdict').textContent=verdict;const hl=$('#skyHourLbl');if(hl)hl.textContent=new Date(time).toLocaleString('es-ES',{weekday:'short',day:'numeric',hour:'2-digit',minute:'2-digit'});$('#skyDetail').textContent=`${dateText(time,{weekday:'long',hour:'2-digit',minute:'2-digit'})} · ${t.name}. ${detail}`;
 const peaks=finite(t.top)?t.top:2000;
 const W=160,H=90,Yv=z=>Math.max(0,Math.min(H,H-z/maxZ*H)),F='font-family="Plus Jakarta Sans, system-ui, sans-serif"',fz=h.freezing_level_height?.[i],above=L&&!L.clear&&finite(t.top)&&t.top>L.top+50;
 const ridge=[[0,.35],[10,.5],[20,.62],[30,.55],[42,.8],[52,.72],[62,1],[72,.84],[84,.66],[96,.78],[110,.58],[124,.7],[138,.48],[150,.4],[160,.3]].map(([x,f])=>`L${x} ${Yv(peaks*f).toFixed(1)}`).join(' ');
 let cloud='';if(L&&!L.clear){const y1=Yv(L.top),y2=Yv(L.base),hh=Math.max(1.5,y2-y1),o=(.42+L.cover/450).toFixed(2);let puffs='';for(let x=-4;x<=W+4;x+=9)puffs+=`<circle cx="${x}" cy="${(y1+1.2).toFixed(1)}" r="${(3.2+((x*7)%5)/2).toFixed(1)}"/>`;cloud=`<g fill="#eef2f5" opacity="${o}" filter="url(#soft)">${puffs}<rect x="-6" y="${y1.toFixed(1)}" width="${W+12}" height="${hh.toFixed(1)}"/></g><line x1="0" x2="${W}" y1="${y1.toFixed(1)}" y2="${y1.toFixed(1)}" stroke="#5c6b73" stroke-width=".35" stroke-dasharray="1.6 1.2"/><text x="${W-2}" y="${(y1-1.4).toFixed(1)}" text-anchor="end" font-size="3.3" font-weight="700" fill="#10161a" ${F}>techo nubes ${fmt(L.top)} m</text><text x="${W-2}" y="${Math.min(H-2,y2+4).toFixed(1)}" text-anchor="end" font-size="3" font-weight="600" fill="#ffffff" ${F}>base ${fmt(L.base)} m</text>`}
 const iso=finite(fz)&&fz<maxZ?`<line x1="0" x2="${W}" y1="${Yv(fz).toFixed(1)}" y2="${Yv(fz).toFixed(1)}" stroke="#1d6fd1" stroke-width=".5" stroke-dasharray="3 1.5"/><text x="4" y="${(Yv(fz)-1.4).toFixed(1)}" font-size="3.2" font-weight="700" fill="#1d6fd1" ${F}>0 °C · ${fmt(fz)} m</text>`:'';
 const me=finite(t.top)?`<line x1="58" x2="66" y1="${Yv(t.top).toFixed(1)}" y2="${Yv(t.top).toFixed(1)}" stroke="#ff5a1f" stroke-width=".7"/><circle cx="62" cy="${Yv(t.top).toFixed(1)}" r="1.6" fill="#ff5a1f" stroke="#fff" stroke-width=".5"/><text x="68" y="${(Yv(t.top)+1.1).toFixed(1)}" font-size="3.3" font-weight="700" fill="#10161a" paint-order="stroke" stroke="#ffffffcc" stroke-width="1.2" ${F}>tu cota ${fmt(t.top)} m</text>`:'';
 const grid=[500,1000,1500,2000,2500,3000,3500,4000].filter(z=>z<maxZ).map(z=>`<line x1="0" x2="${W}" y1="${Yv(z)}" y2="${Yv(z)}" stroke="#ffffff" stroke-opacity=".35" stroke-width=".25"/><text x="2" y="${Yv(z)-.9}" font-size="2.6" fill="#ffffff" fill-opacity=".9" ${F}>${z} m</text>`).join('');
 $('#skyStack').innerHTML=`<svg viewBox="0 0 ${W} ${H}" preserveAspectRatio="xMidYMid meet" role="img" aria-label="${esc(verdict)}"><defs><linearGradient id="skyG" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stop-color="#3f7fb6"/><stop offset=".6" stop-color="#8dbbdb"/><stop offset="1" stop-color="#c9dde8"/></linearGradient><linearGradient id="mtn" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stop-color="#5d6d74"/><stop offset="1" stop-color="#2c373c"/></linearGradient><filter id="soft" x="-10%" y="-60%" width="120%" height="220%"><feGaussianBlur stdDeviation=".9"/></filter></defs><rect width="${W}" height="${H}" fill="url(#skyG)"/>${grid}${above||!L||L.clear?`<circle cx="136" cy="14" r="6" fill="#ffd36b"/><circle cx="136" cy="14" r="10" fill="#ffd36b" opacity=".25"/>`:''}<path d="M0 ${H} ${ridge} L${W} ${H}Z" fill="url(#mtn)"/>${cloud}${iso}${me}</svg>`;
 const strip=[];for(let k=0;k<24;k++){const j=start+k;const l=cloudLayer(h,j);strip.push(l&&!l.clear?`<i style="height:${Math.min(100,l.top/maxZ*100)}%;opacity:${.35+l.cover/160}" title="${dateText(h.time[j]*1000)} · techo ${fmt(l.top)} m"></i>`:'<i style="height:2%"></i>')}$('#skyStrip').innerHTML=strip.join('')}
$('#skyHour').oninput=renderSky;
const skyRenderNow=renderNow;renderNow=function(){skyRenderNow();loadSky()};
const skyImport=importRoute;importRoute=async function(f){await skyImport(f);loadSky()};
if(S.forecast)loadSky();
globalThis.TMSky={cloudLayer,load:loadSky,get data(){return SKY.data}};
