'use strict';
/* Mar de nubes: capas por niveles de presión (Open-Meteo) para saber si estarás por encima o dentro de las nubes. */
const SKY={levels:[1000,950,925,900,850,800,700,600],seq:0,data:null};
$('#pane-now .overview')?.insertAdjacentHTML('afterend',`<section class="card" id="skyCard"><div class="viz-title"><div><p class="eyebrow">Mar de nubes</p><h2>¿Por encima o dentro?</h2></div><label class="muted">Hora <input type="range" id="skyHour" min="0" max="47" value="0" style="width:180px"></label></div><div class="sky-stack" id="skyStack"></div><p class="sky-verdict" id="skyVerdict">Leyendo las capas de la atmósfera…</p><p class="muted" id="skyDetail"></p><div class="sky-strip" id="skyStrip" aria-label="Techo de nubes bajas próximas 24 h"></div><div class="sky-axis"><span>ahora</span><span>+12 h</span><span>+24 h</span></div><p class="footnote">Capas con nubosidad ≥ 60 % en los niveles de 1000 a 600 hPa (≈ 100–4200 m) del modelo, interpoladas a su altura geopotencial. Útil para inversiones y nieblas de valle; el detalle real depende del relieve local.</p></section>`);
function skyURL(lat,lon){const v=[];for(const l of SKY.levels)v.push(`cloud_cover_${l}hPa`,`geopotential_height_${l}hPa`,`relative_humidity_${l}hPa`);return 'https://api.open-meteo.com/v1/forecast?'+new URLSearchParams({latitude:lat.toFixed(3),longitude:lon.toFixed(3),hourly:'cloud_cover_low,cloud_cover_mid,cloud_cover_high,'+v.join(','),forecast_days:'3',timezone:'auto',timeformat:'unixtime'})}
/* Devuelve la capa nubosa baja (base y techo en m) para una hora. */
function cloudLayer(h,i){const lv=SKY.levels.map(l=>({l,cc:h[`cloud_cover_${l}hPa`]?.[i],z:h[`geopotential_height_${l}hPa`]?.[i],rh:h[`relative_humidity_${l}hPa`]?.[i]})).filter(x=>finite(x.z)).sort((a,b)=>a.z-b.z);if(!lv.length)return null;const cloudy=x=>finite(x.cc)?x.cc>=60:finite(x.rh)&&x.rh>=95;let first=lv.findIndex(cloudy);if(first<0)return{clear:true,levels:lv};let last=first;while(last+1<lv.length&&cloudy(lv[last+1]))last++;const base=first?Math.round((lv[first-1].z+lv[first].z)/2):Math.max(0,lv[first].z-80),top=last+1<lv.length?Math.round((lv[last].z+lv[last+1].z)/2):lv[last].z,above=lv.slice(last+1),clearAbove=above.length&&above.slice(0,2).every(x=>!cloudy(x));return{base,top,clearAbove,levels:lv,cover:Math.max(...lv.slice(first,last+1).map(x=>x.cc??0))}}
function skyTarget(){const r=S.route,el=r?.summary?.elevationComplete?r.points.map(p=>p.ele).filter(finite):[];return{lat:r?.points?.[0]?.lat??S.location.lat,lon:r?.points?.[0]?.lon??S.location.lon,top:el.length?Math.max(...el):S.forecast?.elevation??null,bottom:el.length?Math.min(...el):null,name:r?.name||S.location.name}}
async function loadSky(){const t=skyTarget();if(!finite(t.lat))return;const seq=++SKY.seq;try{const d=await json(skyURL(t.lat,t.lon),1800000);if(seq!==SKY.seq)return;const h=d.hourly||{},now=Date.now()/1000,start=Math.max(0,(h.time||[]).findIndex(x=>x>=now-1800));SKY.data={h,start,t};$('#skyHour').max=Math.min(47,(h.time||[]).length-start-1);renderSky()}catch(e){$('#skyVerdict').textContent='No se pudieron leer las capas de nubes: '+e.message}}
function renderSky(){const s=SKY.data;if(!s)return;const {h,start,t}=s,i=start+Number($('#skyHour').value),L=cloudLayer(h,i),time=h.time[i]*1000,maxZ=Math.max(3200,(t.top||0)+600),Y=z=>Math.max(0,Math.min(100,100-z/maxZ*100));
 let verdict='—',detail='';if(!L){verdict='Sin datos de capas para esta hora.'}else if(L.clear){verdict='Sin capas nubosas bajas: cielo abierto en altura.';detail=`Nubes altas ${fmt(h.cloud_cover_high?.[i])} %.`}else{const sea=L.base<1200&&L.clearAbove;if(finite(t.top)){if(t.top>L.top+50)verdict=sea?`Mar de nubes con techo a ≈ ${fmt(L.top)} m: por encima de esa cota estarás al sol.`:`Nubes entre ${fmt(L.base)} y ${fmt(L.top)} m; tu cota máxima (${fmt(t.top)} m) queda por encima.`;else if(t.top>=L.base)verdict=`Dentro de la nube: capa entre ${fmt(L.base)} y ${fmt(L.top)} m. Visibilidad reducida en tu cota (${fmt(t.top)} m).`;else verdict=`Bajo las nubes: base a ≈ ${fmt(L.base)} m, por encima de tu cota máxima (${fmt(t.top)} m).`}else verdict=`Capa nubosa entre ${fmt(L.base)} y ${fmt(L.top)} m.`;detail=`${sea?'Inversión probable (capa baja con cielo despejado encima). ':''}Cobertura de la capa ${fmt(L.cover)} %.`}
 $('#skyVerdict').textContent=verdict;$('#skyDetail').textContent=`${dateText(time,{weekday:'long',hour:'2-digit',minute:'2-digit'})} · ${t.name}. ${detail}`;
 const peaks=finite(t.top)?t.top:2000,band=L&&!L.clear?`<rect class="cloud" x="-5" y="${Y(L.top)}" width="110" height="${Y(L.base)-Y(L.top)}" fill="#fff" opacity="${.55+L.cover/300}"/>`:'';
 $('#skyStack').innerHTML=`<svg viewBox="0 0 100 100" preserveAspectRatio="none" aria-hidden="true"><defs><filter id="cloudBlur" x="-20%" y="-50%" width="140%" height="200%"><feGaussianBlur stdDeviation="2.2"/></filter><linearGradient id="mtn" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stop-color="#7f8f96"/><stop offset="1" stop-color="#3f4c52"/></linearGradient></defs>${[500,1000,1500,2000,2500,3000].filter(z=>z<maxZ).map(z=>`<line x1="0" x2="100" y1="${Y(z)}" y2="${Y(z)}" stroke="#10161a" stroke-opacity=".08" stroke-width=".2"/><text x="1" y="${Y(z)-.8}" font-size="2.6" fill="#6a767c" font-family="Plus Jakarta Sans, sans-serif, monospace">${z} m</text>`).join('')}<circle cx="82" cy="${Y(maxZ*.92)}" r="5" fill="#ffd36b" opacity=".85" filter="url(#cloudBlur)"/><path d="M0 100 L0 ${Y(400)} L14 ${Y(peaks*.55)} L24 ${Y(peaks*.8)} L33 ${Y(peaks*.6)} L46 ${Y(peaks)} L58 ${Y(peaks*.7)} L70 ${Y(peaks*.86)} L84 ${Y(peaks*.5)} L100 ${Y(600)} L100 100Z" fill="url(#mtn)" opacity=".85"/>${band}${finite(t.top)?`<line x1="46" x2="64" y1="${Y(t.top)}" y2="${Y(t.top)}" stroke="#ff5a1f" stroke-width=".5"/><circle cx="46" cy="${Y(t.top)}" r="1.4" fill="#ff5a1f"/><text x="65" y="${Y(t.top)+1}" font-size="3" fill="#10161a" font-family="Plus Jakarta Sans, sans-serif, monospace">tu cota ${fmt(t.top)} m</text>`:''}</svg>`;
 const strip=[];for(let k=0;k<24;k++){const j=start+k;const l=cloudLayer(h,j);strip.push(l&&!l.clear?`<i style="height:${Math.min(100,l.top/maxZ*100)}%;opacity:${.35+l.cover/160}" title="${dateText(h.time[j]*1000)} · techo ${fmt(l.top)} m"></i>`:'<i style="height:2%"></i>')}$('#skyStrip').innerHTML=strip.join('')}
$('#skyHour').oninput=renderSky;
const skyRenderNow=renderNow;renderNow=function(){skyRenderNow();loadSky()};
const skyImport=importRoute;importRoute=async function(f){await skyImport(f);loadSky()};
if(S.forecast)loadSky();
globalThis.TMSky={cloudLayer,load:loadSky,get data(){return SKY.data}};
