'use strict';
/* Nieve: satélite MODIS/VIIRS de los últimos días (NASA GIBS), cubierta de nieve NDSI, nevadas y espesor en la cota de la ruta,
   cota de nieve hora a hora y nieve prevista en cada sector a tu hora de paso. Todo gratuito y sin clave. */
const SN={map:null,layer:null,route:null,day:1,product:'true',seq:0,secSeq:0,data:null};
const GIBS={true:['MODIS_Terra_CorrectedReflectance_TrueColor','GoogleMapsCompatible_Level9','jpg',9,'Color real · MODIS Terra'],viirs:['VIIRS_SNPP_CorrectedReflectance_TrueColor','GoogleMapsCompatible_Level9','jpg',9,'Color real · VIIRS'],ndsi:['MODIS_Terra_NDSI_Snow_Cover','GoogleMapsCompatible_Level8','png',8,'Cubierta de nieve · NDSI']};
function gibsDate(daysAgo){const d=new Date(Date.now()-daysAgo*86400000);return d.toISOString().slice(0,10)}
function gibsURL(product,date){const [layer,matrix,ext]=GIBS[product];return `https://gibs.earthdata.nasa.gov/wmts/epsg3857/best/${layer}/default/${date}/${matrix}/{z}/{y}/{x}.${ext}`}
/* Cota de nieve aproximada: la nieve suele cuajar unos 300 m por debajo de la isoterma de 0 °C. */
function snowLine(freezing){return finite(freezing)?Math.max(0,Math.round((freezing-300)/50)*50):null}
function routeTop(){const r=S.route,e=r?.summary?.elevationComplete?r.points.map(p=>p.ele).filter(finite):[];return e.length?{top:Math.max(...e),bottom:Math.min(...e)}:{top:null,bottom:null}}
function snowTarget(){const r=S.route;if(r?.points?.length){const e=r.points.filter(p=>finite(p.ele)),hi=e.length?e.reduce((a,b)=>b.ele>a.ele?b:a):r.points[0];return{lat:hi.lat,lon:hi.lon,ele:finite(hi.ele)?hi.ele:null,name:'cota máxima de '+(r.name||'la ruta')}}return{lat:S.location.lat,lon:S.location.lon,ele:S.forecast?.elevation??null,name:S.location.name}}

$('#groundCard')?.insertAdjacentHTML('afterend',`<section class="card" id="snowCard"><div class="viz-title"><div><p class="eyebrow">Nieve</p><h2>Lo que hay y lo que viene</h2></div></div><div id="snowOut" class="muted"><span class="spinner"></span>Consultando nieve…</div><div id="snowLine" class="snow-line"></div><div id="snowSectors"></div><p class="footnote">Modelo Open-Meteo a la altitud indicada (corrección por cota). La cota de nieve se estima 300 m bajo la isoterma 0 °C; con precipitación intensa o aire seco puede variar ±300 m. No es un boletín de aludes: consulta el oficial antes de entrar en terreno nevado. <a href="https://www.avalanches.org/standards/avalanche-danger-scale/" target="_blank" rel="noopener">Escala europea de peligro ↗</a></p></section>
<section class="card" id="satCard"><div class="viz-title"><div><p class="eyebrow">Satélite</p><h2>Nieve vista desde el espacio</h2></div><div class="seg" role="group" aria-label="Producto"><button type="button" data-sat="true" aria-pressed="true">Color real</button><button type="button" data-sat="viirs" aria-pressed="false">VIIRS</button><button type="button" data-sat="ndsi" aria-pressed="false">Nieve NDSI</button></div></div><div id="satMap" class="sat-map" role="region" aria-label="Mapa de satélite"></div><label class="sat-day">Día <input type="range" id="satDay" min="0" max="10" value="1"><output id="satDate"></output></label><p class="footnote">NASA GIBS / EOSDIS · MODIS Terra y VIIRS SNPP (≈ 250–500 m por píxel, una pasada al día hacia las 11–13 h). Las nubes tapan la nieve: si ves blanco algodonoso, retrocede unos días con el control. NDSI: azul claro = nieve, más intenso = más cobertura.</p></section>`);

/* ---------- Datos de nieve en la cota de la ruta ---------- */
async function loadSnow(){const t=snowTarget(),out=$('#snowOut');if(!out||!finite(t.lat))return;const seq=++SN.seq;out.innerHTML='<span class="spinner"></span>Consultando nieve…';
 try{const q={latitude:t.lat.toFixed(4),longitude:t.lon.toFixed(4),hourly:'snowfall,snow_depth,freezing_level_height,temperature_2m,precipitation',daily:'snowfall_sum',past_days:'7',forecast_days:'7',timezone:'auto',timeformat:'unixtime'};if(finite(t.ele))q.elevation=String(Math.round(t.ele));const d=await json('https://api.open-meteo.com/v1/forecast?'+new URLSearchParams(q),1800000);if(seq!==SN.seq)return;SN.data={d,t};renderSnow()}catch(e){if(seq===SN.seq)out.innerHTML=`<p class="muted">No se pudo consultar la nieve: ${esc(e.message)}</p>`}}
function renderSnow(){const s=SN.data;if(!s)return;const {d,t}=s,h=hours(d),now=Date.now(),cur=nearest(h,now)||{},daily=(d.daily?.time||[]).map((x,i)=>({time:x*1000,snow:d.daily.snowfall_sum?.[i]}));const today=new Date(now).toDateString();
 const past=daily.filter(x=>x.time<now-86400000/2),next=daily.filter(x=>x.time>=now-86400000/2),fell7=past.reduce((a,x)=>a+(x.snow||0),0),coming=next.reduce((a,x)=>a+(x.snow||0),0),lastSnow=[...h].reverse().find(r=>r.time<=now&&r.snowfall>=.2),lastDay=[...past].reverse().find(x=>x.snow>=.5),since=lastSnow?Math.floor((now-lastSnow.time)/86400000):lastDay?Math.max(1,Math.round((now-lastDay.time)/86400000)):null,melt=h.filter(r=>r.time<=now&&r.time>now-72*3600000&&r.temperature_2m>2).length;
 const depth=cur.snow_depth,verdict=finite(depth)&&depth>=.3?'Manto continuo: terreno invernal. Crampones, piolet y conocimiento de aludes.':finite(depth)&&depth>=.05?'Nieve en el suelo a esta cota: tramos helados o blandos según la hora.':coming>=5?'Sin nieve ahora, pero llegan nevadas en los próximos días.':fell7>=2?'Nevó en la última semana; puede quedar en umbrías y neveros.':'Sin nieve significativa en el modelo a esta cota.';
 const max=Math.max(1,...daily.map(x=>x.snow||0));
 $('#snowOut').innerHTML=`<p class="sky-verdict">${esc(verdict)}</p><p class="muted">${esc(t.name)}${finite(t.ele)?` · ${fmt(t.ele)} m`:''}</p><div class="ground"><div><span>Espesor ahora</span><strong>${finite(depth)?fmt(depth*100)+' cm':'—'}</strong><p>${since===null?'sin nevadas en 7 días':since===0?'nevando o nevó hoy':`última nevada hace ${since} d`}</p></div><div><span>Nevada 7 días</span><strong>${fmt(fell7,1)} cm</strong><p>caída en la última semana</p></div><div><span>Próximos 7 días</span><strong>${fmt(coming,1)} cm</strong><p>nieve nueva prevista</p></div><div><span>Fusión</span><strong>${melt} h</strong><p>sobre 2 °C en 72 h</p></div></div>
 <div class="snow-bars" aria-label="Nevada diaria, 7 días atrás y 7 adelante">${daily.map(x=>`<div class="${x.time<now-43200000?'past':''}${new Date(x.time).toDateString()===today?' today':''}"><i style="height:${Math.max(1,(x.snow||0)/max*100)}%"></i><small>${new Date(x.time).toLocaleDateString('es-ES',{weekday:'narrow'})}</small><b>${x.snow>=.5?fmt(x.snow,0):''}</b></div>`).join('')}</div><div class="sky-axis"><span>hace 7 días</span><span>hoy</span><span>+7 días</span></div>`;
 renderSnowLine(h)}
/* Cota de nieve hora a hora frente a la cota alta y baja de la ruta. */
function renderSnowLine(h){const el=$('#snowLine'),now=Date.now(),rows=h.filter(r=>r.time>=now-3600000&&finite(r.freezing_level_height)).slice(0,72);if(!el||rows.length<6){if(el)el.innerHTML='';return}const {top,bottom}=routeTop(),lines=rows.map(r=>snowLine(r.freezing_level_height)),hi=Math.max(...lines,top||0)+300,lo=Math.max(0,Math.min(...lines,bottom??Infinity)-300),W=100,H=36,X=i=>i/(rows.length-1)*W,Y=z=>H-(z-lo)/Math.max(1,hi-lo)*H;
 const path='M'+lines.map((z,i)=>`${X(i).toFixed(2)} ${Y(z).toFixed(2)}`).join(' L'),area=path+` L${W} 0 L0 0Z`,minL=Math.min(...lines),when=rows[lines.indexOf(minL)];
 const above=finite(top)?rows.filter((r,i)=>top>=lines[i]).length:0;
 el.innerHTML=`<div class="viz-title"><div><p class="eyebrow">Cota de nieve · 72 h</p><h3>${finite(top)?(above?`Tu cota alta (${fmt(top)} m) queda sobre la cota de nieve ${above} de ${rows.length} h`:`Cota de nieve siempre por encima de tu ruta`):`Mínima ${fmt(minL)} m`}</h3></div></div><svg class="snowline-svg" viewBox="0 -1 ${W} ${H+2}" preserveAspectRatio="none" aria-hidden="true"><path d="${area}" class="sl-area"/><path d="${path}" class="sl-line" vector-effect="non-scaling-stroke"/>${finite(top)?`<line x1="0" x2="${W}" y1="${Y(top)}" y2="${Y(top)}" class="sl-top" vector-effect="non-scaling-stroke"/>`:''}${finite(bottom)?`<line x1="0" x2="${W}" y1="${Y(bottom)}" y2="${Y(bottom)}" class="sl-bottom" vector-effect="non-scaling-stroke"/>`:''}</svg><div class="sky-axis"><span>ahora</span><span>mínima ${fmt(minL)} m · ${dateText(when.time,{weekday:'short',hour:'2-digit',minute:'2-digit'})}</span><span>+72 h</span></div><div class="legend-dots"><span><i style="background:#e8f1f5;outline:1px solid #9fb9c4"></i>Zona con nieve posible</span>${finite(top)?'<span><i style="background:#ff5a1f"></i>Tu cota alta</span>':''}${finite(bottom)?'<span><i style="background:#2f3a44"></i>Tu cota baja</span>':''}</div>`}

/* ---------- Nieve en cada sector a tu hora de paso (consulta multipunto) ---------- */
async function loadSectors(){const box=$('#snowSectors'),p=typeof currentPlan==='function'?currentPlan():null;if(!box)return;if(!p?.rows?.length){box.innerHTML='';return}const rows=p.rows.slice(0,40),seq=++SN.secSeq;box.innerHTML='<p class="muted"><span class="spinner"></span>Nieve en cada sector a tu hora de paso…</p>';
 try{const q={latitude:rows.map(r=>r.lat.toFixed(4)).join(','),longitude:rows.map(r=>r.lon.toFixed(4)).join(','),hourly:'snow_depth,snowfall',past_days:'2',forecast_days:'7',timezone:'auto',timeformat:'unixtime'};if(rows.every(r=>finite(r.ele)))q.elevation=rows.map(r=>Math.round(r.ele)).join(',');const d=await json('https://api.open-meteo.com/v1/forecast?'+new URLSearchParams(q),1800000);if(seq!==SN.secSeq)return;const list=Array.isArray(d)?d:[d];
  const out=rows.map((r,i)=>{const hr=nearest(hours(list[i]),+r.eta,5400000)||{},fz=r.h?.freezing_level_height,line=snowLine(fz),pr=r.h?.precipitation,falling=finite(line)&&finite(r.ele)&&r.ele>=line&&pr>=.1;return{r,depth:hr.snow_depth,fall:hr.snowfall,line,falling}});
  const any=out.some(x=>x.depth>=.02||x.falling);
  box.innerHTML=`<div class="viz-title"><div><p class="eyebrow">Sector a sector</p><h3>${any?'Nieve en tu ruta a la hora de paso':'Sin nieve prevista en los sectores a tu hora'}</h3></div></div><div class="snow-sec">${out.map(x=>`<div class="${x.depth>=.3?'deep':x.depth>=.02?'some':x.falling?'fall':''}"><b>km ${fmt(x.r.km,1)}</b><span>${typeof exTime==='function'?exTime(x.r.eta):''}${finite(x.r.ele)?' · '+fmt(x.r.ele)+' m':''}</span><strong>${finite(x.depth)&&x.depth>=.01?fmt(x.depth*100)+' cm':'—'}</strong><small>${x.falling?'nevando probable':finite(x.line)?'cota '+fmt(x.line)+' m':''}</small></div>`).join('')}</div>`}
 catch(e){if(seq===SN.secSeq)box.innerHTML=`<p class="muted">Sin datos de nieve por sector: ${esc(e.message)}</p>`}}

/* ---------- Mapa de satélite ---------- */
function satLayer(){if(!SN.map||typeof L==='undefined')return;const date=gibsDate(SN.day),[,, ,maxN,label]=GIBS[SN.product];if(SN.layer)SN.layer.remove();SN.layer=L.tileLayer(gibsURL(SN.product,date),{maxNativeZoom:maxN,maxZoom:13,attribution:`${label} · ${date} · NASA GIBS`,crossOrigin:true}).addTo(SN.map);SN.layer.bringToBack();const o=$('#satDate');if(o)o.textContent=new Date(date).toLocaleDateString('es-ES',{weekday:'short',day:'numeric',month:'short'})}
function satRoute(){if(!SN.map)return;SN.route?.remove();SN.route=null;const r=S.route;if(r?.points?.length){const pts=sample(r.points,400).map(p=>[p.lat,p.lon]);SN.route=L.polyline(pts,{color:'#ff5a1f',weight:3,opacity:.95}).addTo(SN.map);SN.map.fitBounds(SN.route.getBounds(),{padding:[30,30],maxZoom:11})}else SN.map.setView([S.location.lat,S.location.lon],9)}
function ensureSat(){const el=$('#satMap');if(!el||typeof L==='undefined'||!el.offsetParent)return;if(!SN.map){SN.map=L.map(el,{zoomControl:true,attributionControl:true,scrollWheelZoom:false}).setView([43.2,-4.85],9);satLayer();satRoute()}else SN.map.invalidateSize()}
$('#satCard')?.addEventListener('click',e=>{const b=e.target.closest('[data-sat]');if(!b)return;SN.product=b.dataset.sat;$$('#satCard [data-sat]').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));satLayer();if(SN.product==='ndsi'&&typeof sfx==='function')sfx('snow')});
$('#satDay')?.addEventListener('input',e=>{SN.day=Number(e.target.value);clearTimeout(SN.t);SN.t=setTimeout(satLayer,250)});
$('#satDay')&&($('#satDay').value=String(SN.day));

/* ---------- Integración ---------- */
function renderSnowPane(){loadSnow();loadSectors();setTimeout(ensureSat,60)}
const snShowTab=showTab;showTab=function(tab){snShowTab(tab);if(tab==='terrain')renderSnowPane()};
const snImport=importRoute;importRoute=async function(f){await snImport(f);SN.data=null;if(SN.map)satRoute();if(S.tab==='terrain')renderSnowPane()};
const snRender=renderExpedition;renderExpedition=function(){snRender();if(S.tab==='terrain')loadSectors()};
/* Consulta puntual reutilizable (p. ej. desde la ficha de una canal). */
async function snowAt(lat,lon,ele){const q={latitude:lat.toFixed(4),longitude:lon.toFixed(4),hourly:'snow_depth,snowfall,freezing_level_height',past_days:'3',forecast_days:'3',timezone:'auto',timeformat:'unixtime'};if(finite(ele))q.elevation=String(Math.round(ele));const d=await json('https://api.open-meteo.com/v1/forecast?'+new URLSearchParams(q),1800000),h=hours(d),now=Date.now(),cur=nearest(h,now)||{};return{depth:cur.snow_depth??null,fell72:h.filter(r=>r.time<=now&&r.time>now-72*3600000).reduce((a,r)=>a+(r.snowfall||0),0),next72:h.filter(r=>r.time>now&&r.time<=now+72*3600000).reduce((a,r)=>a+(r.snowfall||0),0),line:snowLine(cur.freezing_level_height)}}
globalThis.TMSnow={get map(){return SN.map},snowLine,gibsURL,gibsDate,load:loadSnow,sectors:loadSectors,at:snowAt,get data(){return SN.data}};
