'use strict';
/* Más fuentes de rutas: senderos señalizados de OpenStreetMap (GR, PR, SL) con su trazado completo, enlaces de búsqueda en
   Komoot, Outdooractive y AllTrails, y en la ficha de cada canal: senderos que la recorren, tracks de Wikiloc superpuestos
   en el mapa, pendiente coloreada y marcas de kilómetro. */
const TR={seq:0,results:[],canalSeq:0,overlay:null,slope:null,tracks:[]};
const reEsc=s=>String(s).replace(/[.*+?^${}()|[\]\\"]/g,'\\$&');
function trailKind(t){const ref=String(t.ref||'');return/^GR/i.test(ref)||['iwn','nwn'].includes(t.network)?'GR':/^PR/i.test(ref)||t.network==='rwn'?'PR':/^SL/i.test(ref)||t.network==='lwn'?'SL':'Sendero'}
function trailInfo(e){const t=e.tags||{};return{id:e.id,ref:t.ref||'',name:t.name||t['name:es']||t.ref||'Sendero sin nombre',kind:trailKind(t),network:t.network||'',distance:parseFloat(String(t.distance||'').replace(',','.'))||null,from:t.from||'',to:t.to||'',operator:t.operator||'',web:t.website||t.url||'',ascent:t.ascent||''}}
/* Une los tramos de una relación en el trazado continuo más largo; informa de la cobertura si hay huecos. */
function relationLine(rel){const ways=(rel.members||[]).filter(m=>m.type==='way'&&m.geometry?.length>1).map(m=>m.geometry.filter(g=>g&&finite(g.lat)).map(g=>({lat:g.lat,lon:g.lon})));if(!ways.length)return{line:[],coverage:0};const total=ways.reduce((a,w)=>a+w.reduce((s,p,i)=>i?s+TM.distance(w[i-1],p):0,0),0),line=joinLines(ways),len=line.reduce((s,p,i)=>i?s+TM.distance(line[i-1],p):0,0);return{line,coverage:total?len/total:0}}
function searchBox(){const c=S.route?.points?.[0]||S.location;return[c.lat-.7,c.lon-.9,c.lat+.7,c.lon+.9].map(v=>v.toFixed(3)).join(',')}
async function osmTrails(query,box=searchBox()){const q=reEsc(String(query).trim().slice(0,60));if(q.length<2)return[];const els=await overpass(`[out:json][timeout:25];(rel["route"~"^(hiking|foot)$"]["name"~"${q}",i](${box});rel["route"~"^(hiking|foot)$"]["ref"~"${q}",i](${box}););out tags;`,30000);return els.filter(e=>e.type==='relation').map(trailInfo).slice(0,20)}
async function trailsCrossing(chain){const b=[Math.min(...chain.map(p=>p.lat)),Math.min(...chain.map(p=>p.lon)),Math.max(...chain.map(p=>p.lat)),Math.max(...chain.map(p=>p.lon))].map((v,i)=>(v+(i<2?-.004:.004)).toFixed(4)).join(',');const els=await overpass(`[out:json][timeout:25];way["highway"](${b});rel(bw)["route"~"^(hiking|foot)$"];out tags;`,30000);return els.filter(e=>e.type==='relation').map(trailInfo)}
async function trailGPX(t){const els=await overpass(`[out:json][timeout:40];rel(${Number(t.id)});out geom;`,45000),rel=els.find(e=>e.type==='relation');if(!rel)throw Error('Relación no encontrada');const {line,coverage}=relationLine(rel);if(line.length<2)throw Error('El sendero no tiene trazado cartografiado');let pts=line;if(pts.length>600){const step=pts.length/600;pts=Array.from({length:600},(_,i)=>line[Math.floor(i*step)]).concat([line.at(-1)])}try{const z=await TMRelief.elevations(pts);pts=pts.map((p,i)=>({...p,ele:z[i]}))}catch{}return{name:[t.ref,t.name].filter(Boolean).filter((x,i,a)=>a.indexOf(x)===i).join(' · '),points:pts,coverage}}
async function loadTrailOSM(t,status){const set=h=>{if(status)status.innerHTML=h};set('<span class="spinner"></span>Descargando el trazado del sendero desde OpenStreetMap…');try{const g=await trailGPX(t);await importRoute(new File([TMWikiloc.buildGPX(g.name,g.points)],'osm-'+t.id+'.gpx',{type:'application/gpx+xml'}));set(`✓ «${esc(g.name)}» cargado desde OpenStreetMap${g.coverage<.9?` (tramo continuo ≈ ${Math.round(g.coverage*100)} % del sendero: hay huecos en el mapa)`:''}.`);if(typeof sfx==='function')sfx('ok');return g}catch(e){set('No se pudo cargar: '+esc(e.message));if(typeof sfx==='function')sfx('warn');return null}}
const trailBadge=t=>`<span class="tr-badge ${t.kind.toLowerCase()}">${esc(t.ref||t.kind)}</span>`;
function trailCard(t,i,key){return `<article class="wl-card" style="animation-delay:${i*40}ms"><span class="wl-host">OpenStreetMap · ${esc(t.kind==='Sendero'?'sendero':t.kind==='GR'?'gran recorrido':t.kind==='PR'?'pequeño recorrido':'sendero local')}</span><h4>${trailBadge(t)} ${esc(t.name)}</h4><div class="wl-meta">${t.distance?`<span>${fmt(t.distance,1)} km</span>`:''}${t.from&&t.to?`<span>${esc(t.from)} → ${esc(t.to)}</span>`:''}${t.operator?`<span>${esc(t.operator)}</span>`:''}</div><div class="wl-actions"><button class="primary" type="button" data-tr-load="${key}:${i}">Cargar trazado</button><a href="https://hiking.waymarkedtrails.org/#route?id=${t.id}" target="_blank" rel="noopener">Waymarked Trails ↗</a><a href="https://www.openstreetmap.org/relation/${t.id}" target="_blank" rel="noopener">OSM ↗</a></div></article>`}
function otherSources(q){const e=encodeURIComponent(q),dd=s=>'https://duckduckgo.com/?q='+encodeURIComponent(q+' site:'+s);return `<div class="tr-more"><span>Otras fuentes</span><a href="${dd('komoot.com')}" target="_blank" rel="noopener">Komoot ↗</a><a href="${dd('outdooractive.com')}" target="_blank" rel="noopener">Outdooractive ↗</a><a href="${dd('alltrails.com')}" target="_blank" rel="noopener">AllTrails ↗</a><a href="https://www.google.com/search?q=${e}+gpx" target="_blank" rel="noopener">Google · GPX ↗</a></div><p class="footnote">Si encuentras un GPX en otra web, pega su enlace en «Enlace» o descárgalo e impórtalo.</p>`}

/* ---------- Buscador de Planificar: añade senderos señalizados y otras fuentes ---------- */
$('#wlResults')?.insertAdjacentHTML('afterend','<div id="trOut" class="tr-out"></div>');
async function searchTrails(query){const out=$('#trOut');if(!out)return;const seq=++TR.seq;out.innerHTML='<p class="wl-status"><span class="spinner"></span>Buscando senderos señalizados en OpenStreetMap…</p>';try{const list=await osmTrails(query);if(seq!==TR.seq)return;TR.results=list;out.innerHTML=(list.length?`<h4 class="tr-title">Senderos señalizados · ${list.length}</h4><div class="wl-results">${list.map((t,i)=>trailCard(t,i,'s')).join('')}</div>`:'<p class="wl-status">Sin senderos señalizados con ese nombre cerca de la zona.</p>')+otherSources(query)+'<p class="wl-status" id="trStatus" role="status"></p>'}catch(e){if(seq===TR.seq)out.innerHTML=`<p class="wl-status err">OpenStreetMap no respondió (${esc(e.message)}).</p>`+otherSources(query)}}
$('#wlForm')?.addEventListener('submit',()=>searchTrails($('#wlQuery').value));
document.addEventListener('click',e=>{const b=e.target.closest('[data-tr-load]');if(!b)return;const [k,i]=b.dataset.trLoad.split(':'),t=(k==='s'?TR.results:TR.canal||[])[+i];if(!t)return;if(k==='c')TMCanales.close();loadTrailOSM(t,k==='s'?$('#trStatus'):null).then(g=>{if(g&&k==='c')showTab('route')})});

/* ---------- Ficha de canal: pendiente coloreada, km, senderos y tracks ---------- */
const SLOPE_COLORS=[[15,'#1d8ea3','< 15 %'],[30,'#7aa35a','15–30 %'],[45,'#d4861a','30–45 %'],[60,'#ff5a1f','45–60 %'],[Infinity,'#b3261e','> 60 %']];
function slopeColor(s){return SLOPE_COLORS.find(x=>Math.abs(s)<x[0])[1]}
function slopeSegments(prof){const out=[];for(let i=1;i<prof.length;i++){const a=prof[i-1],b=prof[i],run=(b.d-a.d)*1000;if(run<=0)continue;out.push({a,b,slope:(b.ele-a.ele)/run*100})}return out}
function drawSlope(map,prof){if(!map||!prof?.length)return;TR.slope?.remove();const items=[];for(const s of slopeSegments(prof))items.push(L.polyline([[s.a.lat,s.a.lon],[s.b.lat,s.b.lon]],{color:slopeColor(s.slope),weight:6,opacity:1,lineCap:'round'}).bindTooltip(`${fmt(Math.abs(s.slope))} % · ${fmt(s.b.ele)} m`));const tot=prof.at(-1).d,step=tot<1.5?.25:tot<4?.5:1;for(let k=step;k<tot-step/3;k+=step){const p=prof.reduce((a,b)=>Math.abs(b.d-k)<Math.abs(a.d-k)?b:a);items.push(L.marker([p.lat,p.lon],{icon:L.divIcon({className:'km-mark',html:`<span>${fmt(k,step<1?2:0)}</span>`,iconSize:[30,16],iconAnchor:[15,8]}),interactive:false}))}TR.slope=L.featureGroup(items).addTo(map);return TR.slope}
function overlayTrack(map,points,label){if(!map)return;TR.overlay?.remove();const ll=points.map(p=>[p.lat,p.lon]);TR.overlay=L.featureGroup([L.polyline(ll,{color:'#fff',weight:7,opacity:.8}),L.polyline(ll,{color:'#2f3a44',weight:3,dashArray:'6 6'}).bindTooltip(label)]).addTo(map);map.fitBounds(TR.overlay.getBounds(),{padding:[30,30],maxZoom:16})}
async function canalSources(c){const box=$('#cnSources');if(!box)return;const seq=++TR.canalSeq,chain=c.chain||[];TR.canal=[];TR.tracks=[];
 box.innerHTML=`<div id="cnTrails" class="muted">${chain.length?'<span class="spinner"></span>Buscando senderos señalizados que pasan por la canal…':'Sin trazado cartografiado: no se pueden cruzar senderos.'}</div><div class="cn-wl"><div class="action-row"><button class="quiet" type="button" id="cnWlFind">Buscar tracks de Wikiloc aquí</button>${otherSources(c.name+' Picos de Europa').replace('<p class="footnote">','<p class="footnote" hidden>')}</div><div id="cnWlList"></div></div>`;
 $('#cnWlFind').onclick=()=>canalWikiloc(c);
 if(chain.length)try{const list=await trailsCrossing(chain);if(seq!==TR.canalSeq||!$('#cnTrails'))return;TR.canal=list;$('#cnTrails').classList.remove('muted');$('#cnTrails').innerHTML=list.length?`<div class="tr-list">${list.map((t,i)=>`<div class="tr-row">${trailBadge(t)}<div><b>${esc(t.name)}</b><small>${[t.distance?fmt(t.distance,1)+' km':'',t.from&&t.to?t.from+' → '+t.to:'',t.operator].filter(Boolean).map(esc).join(' · ')}</small></div><button class="quiet" type="button" data-tr-load="c:${i}">Planificar</button><a href="https://hiking.waymarkedtrails.org/#route?id=${t.id}" target="_blank" rel="noopener" aria-label="Ver en Waymarked Trails">↗</a></div>`).join('')}</div>`:'<p class="muted">Ningún sendero señalizado (GR/PR/SL) de OpenStreetMap pasa por esta canal: se recorre fuera de la red oficial.</p>'}catch(e){if($('#cnTrails'))$('#cnTrails').innerHTML=`<p class="muted">No se pudieron leer los senderos (${esc(e.message)}).</p>`}}
async function canalWikiloc(c){const out=$('#cnWlList');if(!out)return;out.innerHTML='<p class="wl-status"><span class="spinner"></span>Buscando tracks de «'+esc(c.name)+'» en Wikiloc…</p>';try{const items=await TMWikiloc.find(c.name+' Picos de Europa');if(TMCanales.selected!==c)return;TR.tracks=items.slice(0,8);out.innerHTML=TR.tracks.length?`<div class="tr-list">${TR.tracks.map((r,i)=>`<div class="tr-row"><span class="tr-badge wl">WL</span><div><b>${esc(r.title)}</b><small>${[r.km?r.km+' km':'',r.up?'+'+r.up+' m':'',r.level].filter(Boolean).map(esc).join(' · ')}</small></div><button class="quiet" type="button" data-wl-over="${i}">Ver en el mapa</button><a href="${esc(r.url)}" target="_blank" rel="noopener" aria-label="Abrir en Wikiloc">↗</a></div>`).join('')}</div><p class="footnote">Tracks de usuarios: compáralos con el trazado de la canal. Pueden ser antiguos o equivocados.</p>`:'<p class="muted">Wikiloc no devolvió tracks con ese nombre.</p>'}catch(e){out.innerHTML=`<p class="muted">La búsqueda no respondió (${esc(e.message)}).</p>`}}
document.addEventListener('click',async e=>{const b=e.target.closest('[data-wl-over]');if(!b)return;const r=TR.tracks[+b.dataset.wlOver],c=TMCanales.selected;if(!r)return;b.disabled=true;b.innerHTML='<span class="spinner"></span>Leyendo…';try{const g=await TMWikiloc.geometry(r);if(TMCanales.selected!==c)return;overlayTrack(TMCanales.map,g.points,g.title);b.outerHTML=`<button class="primary" type="button" data-wl-plan="${b.dataset.wlOver}">Planificar este track</button>`;TR.last={title:g.title,points:g.points};if(typeof sfx==='function')sfx('ok')}catch(err){b.disabled=false;b.textContent='Sin trazado público';b.title=err.message}});
document.addEventListener('click',async e=>{if(!e.target.closest('[data-wl-plan]')||!TR.last)return;const {title,points}=TR.last;TMCanales.close();await importRoute(new File([TMWikiloc.buildGPX(title,points)],'wikiloc.gpx',{type:'application/gpx+xml'}));showTab('route')});
globalThis.TMTrails={osmTrails,trailsCrossing,trailGPX,relationLine,trailInfo,trailKind,slopeColor,slopeSegments,drawSlope,canalSources,searchTrails,loadTrailOSM};
