'use strict';
/* Mapa de la semana: todas las horas de salida de los próximos días, valoradas con la previsión en cada tramo. */
const WK={sel:null,first:5,last:15};
$('#routeForecast')?.insertAdjacentHTML('beforebegin',`<section class="card" id="weekCard" hidden><div class="viz-title"><div><p class="eyebrow">Mapa de la semana</p><h2>¿Qué día y a qué hora?</h2></div><div class="legend-dots"><span><i style="background:#3fbf8f"></i>Favorable</span><span><i style="background:#f2c14e"></i>Precauciones</span><span><i style="background:#ef6b5a"></i>Exigente</span><span><i style="background:rgba(16,22,26,.07)"></i>Sin previsión</span></div></div><div class="week-best" id="weekBest"></div><div class="week" id="weekGrid"></div><p class="footnote">Cada casilla es una hora de salida: se calcula tu paso por los 16 sectores con tu ritmo y se cruza con la previsión horaria. Valora tormenta, lluvia, rachas, visibilidad, temperatura y llegar con luz. Toca una casilla para planificar con esa hora.</p></section>`);
function weekScore(p){if(!p.complete)return null;const medium=p.rows.filter(q=>q.assessment.level==='medium').length,light=p.arrivalLight&&!p.arrivalLight.day?35:0,dark=p.rows.filter(q=>q.light&&!q.light.day).length*6;return p.high*100+medium*9+(p.maxRain||0)*10+Math.max(0,(p.maxGust||0)-30)*1.2+light+dark}
function weekColor(s){if(s===null)return'rgba(16,22,26,.07)';if(s<12)return'#3fbf8f';if(s<30)return'#9fd27a';if(s<60)return'#f2c14e';if(s<110)return'#f39a52';return'#ef6b5a'}
function weekCells(){const r=S.route;if(!r?.data)return[];const pace=Number($('#pace').value),climb=Number($('#climb').value),now=Date.now(),cells=[];const base=new Date();base.setHours(0,0,0,0);for(let d=0;d<7;d++)for(let h=WK.first;h<=WK.last;h++){const t=new Date(base);t.setDate(base.getDate()+d);t.setHours(h,0,0,0);const start=t.getTime();if(start<now-1800000){cells.push({d,h,start,past:true});continue}if(start>now+6*86400000-120000){cells.push({d,h,start,score:null,p:null});continue}const p=Expedition.plan(r,start,pace,climb);cells.push({d,h,start,p,score:weekScore(p)})}return cells}
function renderWeek(){const r=S.route,card=$('#weekCard');if(!card)return;if(!r?.data){card.hidden=true;return}card.hidden=false;const cells=weekCells(),cols=WK.last-WK.first+1,grid=$('#weekGrid');grid.style.setProperty('--cols',cols);const valid=cells.filter(c=>c.score!=null).sort((a,b)=>a.score-b.score),best=[];for(const c of valid){if(best.every(b=>b.d!==c.d))best.push(c);if(best.length===3)break}
 let html='<span></span>'+Array.from({length:cols},(_,i)=>`<span class="wk-h">${WK.first+i}</span>`).join('');for(let d=0;d<7;d++){const day=cells.find(c=>c.d===d);html+=`<span class="wk-d">${new Date(day.start).toLocaleDateString('es-ES',{weekday:'short',day:'numeric'})}</span>`;for(const c of cells.filter(c=>c.d===d)){const isBest=best.includes(c),sel=WK.sel===c.start;html+=c.past?'<button type="button" disabled aria-label="Hora pasada" style="opacity:.25"></button>':`<button type="button" data-week="${c.start}" class="${isBest?'best':''} ${sel?'sel':''}" style="background:${weekColor(c.score)}" aria-label="${new Date(c.start).toLocaleString('es-ES',{weekday:'long',hour:'2-digit',minute:'2-digit'})}: ${c.score==null?'sin previsión':c.p.high+' sectores exigentes'}" title="${c.score==null?'Sin previsión completa':`${c.p.high} exigentes · racha ${fmt(c.p.maxGust)} km/h · lluvia ${fmt(c.p.maxRain,1)} mm/h · llegada ${exTime(c.p.arrival)}`}">${isBest?'★':''}</button>`}}grid.innerHTML=html;
 $('#weekBest').innerHTML=best.length?best.map((c,i)=>`<button type="button" data-week="${c.start}"><span class="eyebrow">${i===0?'Mejor ventana':'Alternativa'}</span><strong>${new Date(c.start).toLocaleDateString('es-ES',{weekday:'long'})} ${String(c.h).padStart(2,'0')}:00</strong><small>${c.p.high?c.p.high+' sectores exigentes':'sin sectores exigentes'} · racha ${fmt(c.p.maxGust)} km/h · llegada ${exTime(c.p.arrival).split(', ').pop()}</small></button>`).join(''):'<p class="muted">La previsión no cubre ninguna salida completa en estos días.</p>'}
document.addEventListener('click',e=>{const b=e.target.closest('[data-week]');if(!b)return;const t=Number(b.dataset.week);WK.sel=t;$('#startTime').value=localInput(new Date(t));if(typeof X!=='undefined')X.progress=null;analyzeRoute();if(typeof sfx==='function')sfx('ok')});
const wkRender=renderExpedition;renderExpedition=function(){wkRender();try{renderWeek()}catch(e){}};
const wkImport=importRoute;importRoute=async function(f){WK.sel=null;$('#weekCard')&&($('#weekCard').hidden=true);await wkImport(f)};
globalThis.TMWeek={cells:weekCells,score:weekScore,render:renderWeek};
