'use strict';
/* Buscador de rutas: Wikiloc (sin API pública) mediante búsqueda web y lectura del original; enlaces GPX; guía de descarga manual. */
const WL={seq:0,controller:null,results:[]};
const WL_LEVELS=/\b(F[aá]cil|Moderado|Dif[ií]cil|Muy dif[ií]cil|S[oó]lo expertos)\b/i;
$('.route-hero')?.insertAdjacentHTML('afterend',`<article class="card finder" id="routeFinder"><div class="finder-tabs" role="tablist"><button type="button" role="tab" aria-selected="true" data-finder="wikiloc">🔎 Wikiloc</button><button type="button" role="tab" aria-selected="false" data-finder="link">🔗 Enlace</button><button type="button" role="tab" aria-selected="false" data-finder="library">★ Mis rutas</button></div>
<div class="finder-body" data-finder-pane="wikiloc"><form class="finder-form" id="wlForm"><label class="sr" for="wlQuery">Ruta o zona</label><input id="wlQuery" maxlength="120" placeholder="Ej.: Canal de Trea, Vega de Ario, Ruta del Cares…" autocomplete="off"><button class="primary" type="submit">Buscar rutas</button></form><p class="finder-hint">Busca rutas públicas de Wikiloc. Al cargar una, TrailMeteo intenta leer su trazado; si Wikiloc lo exige, te guío para descargar el GPX con tu cuenta gratuita.</p><p id="wlStatus" class="wl-status" role="status"></p><div id="wlResults" class="wl-results"></div><div id="wlHelp"></div></div>
<div class="finder-body" data-finder-pane="link" hidden><form class="finder-form" id="wlLinkForm"><label class="sr" for="wlLink">Enlace de Wikiloc o de un archivo GPX</label><input id="wlLink" type="url" placeholder="https://es.wikiloc.com/rutas-senderismo/…-12345678" autocomplete="off"><button class="primary" type="submit">Cargar ruta</button></form><p class="finder-hint">Admite enlaces de rutas de Wikiloc (también los compartidos desde la app) y enlaces directos a archivos .gpx.</p><p id="wlLinkStatus" class="wl-status" role="status"></p></div></article>`);

/* ---------- Utilidades ---------- */
async function wlRead(url,signal,format='markdown',timeout=20000){const c=new AbortController(),abort=()=>c.abort();signal?.addEventListener('abort',abort,{once:true});const t=setTimeout(abort,timeout);try{const r=await fetch('https://r.jina.ai/'+url,{signal:c.signal,credentials:'omit',referrerPolicy:'no-referrer',headers:format==='html'?{'X-Return-Format':'html'}:{}});if(!r.ok)throw Error(r.status===429?'Servicio de lectura saturado; espera un minuto':'No accesible ('+r.status+')');return await r.text()}catch(e){if(c.signal.aborted&&!signal?.aborted)throw Error('La página tardó demasiado');throw e}finally{clearTimeout(t);signal?.removeEventListener('abort',abort)}}
function wikilocId(url){try{const u=new URL(url);if(!/(^|\.)wikiloc\.com$/.test(u.hostname))return null;const m=u.pathname.match(/-(\d{5,})\/?$/)||u.search.match(/[?&]id=(\d{5,})/);return m?m[1]:null}catch{return null}}
function wlActivity(url){const m=String(url).match(/wikiloc\.com\/(rutas|trails|routes|percorsi|itineraires|wanderwege)-([a-z-]+)\//i);return m?m[2].replace(/-/g,' '):''}
function wlParse(markdown){const out=[],seen=new Set(),lines=markdown.split('\n');for(let i=0;i<lines.length;i++){const ms=[...lines[i].matchAll(/\[([^\]\n]{3,}?)\]\((https?:\/\/[^\s)]+)\)/g)];for(const m of ms){let url;try{const u=new URL(m[2]);url=u.searchParams.get('uddg')||u.href}catch{continue}const id=wikilocId(url);if(!id||seen.has(id))continue;seen.add(id);let snippet='';for(let j=i+1;j<Math.min(lines.length,i+5)&&snippet.length<320;j++){const l=lines[j].replace(/!\[[^\]]*\]\([^)]*\)/g,'').replace(/\[([^\]]*)\]\([^)]*\)/g,'$1').replace(/[#*_>|]/g,'').trim();if(!l)continue;if(/\]\(https?:/.test(lines[j])&&wikilocId((lines[j].match(/\((https?:[^)]+)\)/)||[])[1]||''))break;snippet+=(snippet?' ':'')+l}const title=m[1].replace(/[*_`]/g,'').replace(/\s*[|·-]\s*Wikiloc.*$/i,'').trim();const text=title+' '+snippet;out.push({id,url:url.split('#')[0],title,snippet:snippet.slice(0,320),km:(text.match(/(\d+(?:[.,]\d+)?)\s?km\b/i)||[])[1]||null,up:(text.match(/(?:desnivel(?: positivo)?|elevation gain|\+)\s*:?\s*(\d[\d.,]*)\s?m\b/i)||[])[1]||null,level:(text.match(WL_LEVELS)||[])[1]||null,activity:wlActivity(url)})}}return out}
function decodePolyline(str,precision=5){const f=10**precision,coords=[];let i=0,lat=0,lon=0;while(i<str.length){for(const k of [0,1]){let shift=0,result=0,b;do{if(i>=str.length)return coords;b=str.charCodeAt(i++)-63;result|=(b&31)<<shift;shift+=5}while(b>=32);const d=result&1?~(result>>1):result>>1;if(k===0)lat+=d;else lon+=d}coords.push({lat:lat/f,lon:lon/f})}return coords}
function plausible(points,ref){if(!points||points.length<20)return false;let km=0,maxStep=0;for(let i=0;i<points.length;i++){const p=points[i];if(!finite(p.lat)||!finite(p.lon)||Math.abs(p.lat)>90||Math.abs(p.lon)>180)return false;if(i){const d=TM.distance(points[i-1],p);km+=d;maxStep=Math.max(maxStep,d)}}if(km<.2||km>600||maxStep>6)return false;if(ref&&TM.distance(ref,points[0])>60&&TM.distance(ref,points[Math.floor(points.length/2)])>60)return false;return true}
function refPoint(html){const lat=html.match(/(?:latitude|"lat"|place:location:latitude"\s+content=)["':\s]*(-?\d{1,2}\.\d{3,})/i),lon=html.match(/(?:longitude|"lng"|"lon"|place:location:longitude"\s+content=)["':\s]*(-?\d{1,3}\.\d{3,})/i);return lat&&lon?{lat:+lat[1],lon:+lon[1]}:null}
function extractGeometry(html){const ref=refPoint(html),candidates=[];
 // 1) Listas de pares/tríos [a,b(,ele)] consecutivos.
 const pair=/\[\s*(-?\d{1,3}\.\d{3,})\s*,\s*(-?\d{1,3}\.\d{3,})(?:\s*,\s*(-?\d{1,5}(?:\.\d+)?))?\s*\]/g;let run=[],lastEnd=-1;const flush=()=>{if(run.length>=20)candidates.push(run);run=[]};for(const m of html.matchAll(pair)){if(lastEnd>=0&&!/^\s*,\s*$/.test(html.slice(lastEnd,m.index)))flush();run.push([+m[1],+m[2],m[3]!==undefined?+m[3]:null]);lastEnd=m.index+m[0].length}flush();
 const oriented=[];for(const c of candidates){const a=c.map(([x,y,z])=>({lat:y,lon:x,ele:z})),b=c.map(([x,y,z])=>({lat:x,lon:y,ele:z}));const okA=plausible(a,ref),okB=plausible(b,ref);if(okA&&okB&&ref){oriented.push(TM.distance(ref,a[0])<=TM.distance(ref,b[0])?a:b)}else if(okA)oriented.push(a);else if(okB)oriented.push(b)}
 // 2) Objetos {lat,lng}.
 const obj=/\{\s*"?lat"?\s*:\s*(-?\d{1,2}\.\d{3,})\s*,\s*"?(?:lng|lon)"?\s*:\s*(-?\d{1,3}\.\d{3,})(?:\s*,\s*"?(?:ele|alt|elevation)"?\s*:\s*(-?\d{1,5}(?:\.\d+)?))?[^}]*\}/g;const objs=[...html.matchAll(obj)].map(m=>({lat:+m[1],lon:+m[2],ele:m[3]!==undefined?+m[3]:null}));if(plausible(objs,ref))oriented.push(objs);
 // 3) Polilíneas codificadas.
 for(const m of html.matchAll(/"(?:geom|polyline|encodedPolyline|encoded_polyline|points|line|path|trackGeom)"\s*:\s*"((?:[^"\\]|\\.){40,})"/gi)){let s;try{s=JSON.parse('"'+m[1]+'"')}catch{continue}for(const prec of [5,6]){const pts=decodePolyline(s,prec).map(p=>({...p,ele:null}));if(plausible(pts,ref)){oriented.push(pts);break}}}
 if(!oriented.length)return null;return oriented.sort((a,b)=>b.length-a.length)[0]}
function thin(points,max=900){if(points.length<=max)return points;const step=points.length/max,out=[];for(let i=0;i<max;i++)out.push(points[Math.floor(i*step)]);out.push(points.at(-1));return out}
async function addElevation(points,signal){if(points.every(p=>finite(p.ele)))return{points,source:'Wikiloc'};const pts=thin(points,900);for(let i=0;i<pts.length;i+=100){const b=pts.slice(i,i+100);const d=await json('https://api.open-meteo.com/v1/elevation?'+new URLSearchParams({latitude:b.map(p=>p.lat.toFixed(5)).join(','),longitude:b.map(p=>p.lon.toFixed(5)).join(',')}),86400000);if(signal?.aborted)throw Error('Cancelado');(d.elevation||[]).forEach((e,j)=>{if(b[j])b[j]={...b[j],ele:finite(e)?e:null}});pts.splice(i,b.length,...b)}return{points:pts,source:'modelo digital del terreno (Open-Meteo / Copernicus 90 m)'}}
function buildGPX(name,points){const x=s=>String(s).replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));return `<?xml version="1.0" encoding="UTF-8"?><gpx version="1.1" creator="TrailMeteo" xmlns="http://www.topografix.com/GPX/1/1"><trk><name>${x(name)}</name><trkseg>${points.map(p=>`<trkpt lat="${p.lat.toFixed(6)}" lon="${p.lon.toFixed(6)}">${finite(p.ele)?`<ele>${Math.round(p.ele*10)/10}</ele>`:''}</trkpt>`).join('')}</trkseg></trk></gpx>`}
function wlStatus(el,text,kind=''){const s=$(el);if(!s)return;s.className='wl-status '+kind;s.innerHTML=text}
function manualHelp(item,reason){const url=item?.url&&safeLink(item.url);$('#wlHelp').innerHTML=`<div class="wl-help"><h4>Trae el GPX en 3 pasos</h4><p class="footnote">${esc(reason||'Wikiloc no publica el trazado sin iniciar sesión.')}</p><ol><li>${url?`<a href="${esc(url)}" target="_blank" rel="noopener">Abre la ruta en Wikiloc ↗</a>`:'Abre la ruta en Wikiloc'} e inicia sesión (cuenta gratuita).</li><li>Pulsa <b>Descargar</b> → formato <b>GPX</b>. En iPhone se guarda en Archivos → Descargas.</li><li>Vuelve aquí y pulsa <b>Importar GPX</b>: TrailMeteo hará el resto.</li></ol><div class="action-row"><button class="primary" type="button" id="wlPick">↥ Importar GPX</button>${url?`<a href="${esc(url)}" target="_blank" rel="noopener">Ver en Wikiloc ↗</a>`:''}</div></div>`;$('#wlPick').onclick=()=>$('#gpxInput').click();$('#wlHelp').scrollIntoView?.({behavior:'smooth',block:'nearest'})}

/* ---------- Funciones puras (sin tocar la interfaz), reutilizadas por la ficha de canales ---------- */
async function findWikiloc(query,signal){let items=[];for(const q of [query+' site:wikiloc.com',query+' wikiloc']){const md=await wlRead('https://html.duckduckgo.com/html/?q='+encodeURIComponent(q),signal,'markdown',22000);items=wlParse(md);if(items.length||signal?.aborted)break}return items}
async function trailGeometry(item,signal,onFound){const html=await wlRead(item.url,signal,'html',30000);if(/captcha|verify you are human|access denied|cf-chl/i.test(html.slice(0,3000)))throw Error('Wikiloc ha bloqueado la lectura automática');const title=item.title||(html.match(/<title>([^<]+)<\/title>/i)||[])[1]?.replace(/\s*[|·-]\s*Wikiloc.*$/i,'').trim()||'Ruta de Wikiloc';const geom=extractGeometry(html);if(!geom)throw Error('El trazado no está disponible sin iniciar sesión');onFound?.(geom.length);const {points,source}=await addElevation(geom,signal);return{title,points,source}}

/* ---------- Carga de una ruta ---------- */
async function loadTrail(item,statusEl='#wlStatus'){if(!item?.url)return;WL.controller?.abort();const ctrl=new AbortController();WL.controller=ctrl;$('#wlHelp').textContent='';wlStatus(statusEl,'<span class="spinner"></span>Leyendo el trazado de «'+esc(item.title||'la ruta')+'»…');
 try{const {title,points,source}=await trailGeometry(item,ctrl.signal,n=>wlStatus(statusEl,'<span class="spinner"></span>Trazado encontrado ('+fmt(n)+' puntos). Añadiendo altitudes…'));const file=new File([buildGPX(title,points)],'wikiloc-'+(item.id||'ruta')+'.gpx',{type:'application/gpx+xml'});await importRoute(file);if(S.route){S.route.sourceUrl=item.url;S.route.sourceNote=`Trazado leído de la página pública de Wikiloc; altitudes: ${source}.`}
  wlStatus(statusEl,`✓ «${esc(title)}» cargada desde Wikiloc. Altitudes: ${esc(source)}. Comprueba el trazado con el original antes de seguirlo. <button class="quiet" type="button" data-copilot-research>✦ Investigar esta ruta con IA</button>`,'ok');if(typeof sfx==='function')sfx('ok');$('#routeContent')?.scrollIntoView?.({behavior:'smooth',block:'start'})}
 catch(e){if(ctrl.signal.aborted&&!/Cancelado/.test(e.message))return;wlStatus(statusEl,'No se pudo cargar automáticamente: '+esc(e.message)+'.','err');manualHelp(item,e.message+'.');if(typeof sfx==='function')sfx('warn')}}
async function loadLink(url){const safe=PublicSources.safeURL(url)||(()=>{try{const u=new URL(url);return u.protocol==='http:'?u.href:null}catch{return null}})();if(!safe){wlStatus('#wlLinkStatus','Enlace no válido. Debe empezar por https://','err');return}const id=wikilocId(safe);if(id)return loadTrail({id,url:safe,title:''},'#wlLinkStatus');wlStatus('#wlLinkStatus','<span class="spinner"></span>Descargando GPX…');
 try{let text=null;try{const r=await fetch(safe,{credentials:'omit'});if(r.ok)text=await r.text()}catch{}if(!text||!/<gpx[\s>]/i.test(text))text=await wlRead(safe,null,'html',30000);const start=text.search(/<\?xml|<gpx[\s>]/i);if(start<0)throw Error('El enlace no devuelve un archivo GPX');text=text.slice(start);const name=decodeURIComponent(new URL(safe).pathname.split('/').pop()||'ruta.gpx');await importRoute(new File([text],name.endsWith('.gpx')?name:name+'.gpx',{type:'application/gpx+xml'}));wlStatus('#wlLinkStatus','✓ GPX cargado.','ok')}catch(e){wlStatus('#wlLinkStatus','No se pudo cargar: '+esc(e.message)+'. Descarga el archivo e impórtalo.','err')}}

/* ---------- Búsqueda ---------- */
async function searchWikiloc(query){query=String(query||'').trim();if(query.length<3){wlStatus('#wlStatus','Escribe al menos 3 letras.','err');return[]}const seq=++WL.seq;WL.controller?.abort();const ctrl=new AbortController();WL.controller=ctrl;$('#wlResults').textContent='';$('#wlHelp').textContent='';wlStatus('#wlStatus','<span class="spinner"></span>Buscando «'+esc(query)+'» en Wikiloc…');if(typeof sfx==='function')sfx('scan');
 try{const items=await findWikiloc(query,ctrl.signal);if(seq!==WL.seq)return[];WL.results=items;renderResults(items,query);return items}
 catch(e){if(seq===WL.seq){wlStatus('#wlStatus','La búsqueda no respondió: '+esc(e.message)+'. ','err');$('#wlResults').innerHTML=fallbackLinks(query)}return[]}}
function fallbackLinks(q){const g='https://www.google.com/search?q='+encodeURIComponent(q+' site:wikiloc.com');return `<div class="wl-card"><h4>Busca directamente</h4><p class="wl-snippet">Abre la búsqueda, copia el enlace de la ruta y pégalo en «Pegar enlace».</p><div class="wl-actions"><a href="${g}" target="_blank" rel="noopener">Google · Wikiloc ↗</a><a href="https://es.wikiloc.com/" target="_blank" rel="noopener">Wikiloc ↗</a></div></div>`}
function renderResults(items,query){if(!items.length){wlStatus('#wlStatus','Sin rutas de Wikiloc para «'+esc(query)+'». Prueba con el nombre del lugar o la cima.','err');$('#wlResults').innerHTML=fallbackLinks(query);return}wlStatus('#wlStatus',`${items.length} rutas encontradas en Wikiloc. Toca <b>Cargar</b> para analizarla.`,'ok');
 $('#wlResults').innerHTML=items.slice(0,12).map((r,i)=>`<article class="wl-card" style="animation-delay:${i*45}ms"><span class="wl-host">Wikiloc${r.activity?' · '+esc(r.activity):''}</span><h4>${esc(r.title)}</h4><div class="wl-meta">${r.km?`<span>${esc(r.km)} km</span>`:''}${r.up?`<span>+${esc(r.up)} m</span>`:''}${r.level?`<span>${esc(r.level)}</span>`:''}<span>#${esc(r.id)}</span></div>${r.snippet&&r.snippet.replace(/[\d.,]+\s?(km|m)\b|desnivel( positivo)?|distancia|f[aá]cil|moderado|muy dif[ií]cil|dif[ií]cil|s[oó]lo expertos|[·:+|-]/gi,'').trim().length>24?`<p class="wl-snippet">${esc(r.snippet.slice(0,180))}${r.snippet.length>180?'…':''}</p>`:''}<div class="wl-actions"><button class="primary" type="button" data-wl-load="${i}">⚡ Cargar</button><a href="${esc(safeLink(r.url))}" target="_blank" rel="noopener">Wikiloc ↗</a><button class="quiet" type="button" data-wl-ai="${i}" aria-label="Investigar con IA">✦ IA</button></div></article>`).join('')}
$('#wlResults').addEventListener('click',e=>{const l=e.target.closest('[data-wl-load]'),a=e.target.closest('[data-wl-ai]');if(l)loadTrail(WL.results[+l.dataset.wlLoad]);if(a&&globalThis.Copilot){const r=WL.results[+a.dataset.wlAi];Copilot.ask(`Investiga la ruta «${r.title}» (Wikiloc ${r.url}): recorrido, dificultad, pasos clave, agua, tiempos y estado reciente. Cita fuentes.`,{research:r.title,label:'🔎 Investigar: '+r.title})}});
document.addEventListener('click',e=>{if(e.target.closest('[data-copilot-research]')&&globalThis.Copilot)Copilot.research()});
$('#wlForm').onsubmit=e=>{e.preventDefault();searchWikiloc($('#wlQuery').value)};
$('#wlLinkForm').onsubmit=e=>{e.preventDefault();loadLink($('#wlLink').value.trim())};
$('#routeFinder .finder-tabs').onclick=e=>{const b=e.target.closest('[data-finder]');if(!b)return;if(b.dataset.finder==='library'){$('#routeLibrary')?.scrollIntoView({behavior:'smooth'});return}$$('#routeFinder [data-finder]').forEach(x=>x.setAttribute('aria-selected',String(x===b)));$$('#routeFinder [data-finder-pane]').forEach(p=>p.hidden=p.dataset.finderPane!==b.dataset.finder)};
globalThis.TMWikiloc={find:findWikiloc,geometry:trailGeometry,search:searchWikiloc,loadTrail,loadLink,extractGeometry,decodePolyline,buildGPX,parse:wlParse,wikilocId};
