import importlib.util,pathlib,unittest
spec=importlib.util.spec_from_file_location('dgt',pathlib.Path(__file__).parents[1]/'scripts/update-dgt.py');mod=importlib.util.module_from_spec(spec);spec.loader.exec_module(mod)
V3=b'''<?xml version="1.0"?><d2:payload xmlns:d2="http://datex2.eu/schema/3/d2Payload" xmlns:sit="http://datex2.eu/schema/3/situation" xmlns:com="http://datex2.eu/schema/3/common" xmlns:loc="http://datex2.eu/schema/3/locationReferencing" xmlns:lse="http://datex2.eu/schema/3/locationReferencingSpanishExtension" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:type="sit:SituationPublication">
<sit:situation id="s1"><sit:situationRecord id="r1" xsi:type="sit:WinterDrivingManagement"><sit:situationRecordVersionTime>2026-01-10T07:00:00Z</sit:situationRecordVersionTime><sit:validity><com:validityStatus>active</com:validityStatus><com:validityTimeSpecification><com:overallStartTime>2026-01-10T06:00:00Z</com:overallStartTime></com:validityTimeSpecification></sit:validity>
<sit:generalPublicComment><com:comment><com:values><com:value lang="es">Nivel rojo: cadenas o neumaticos de invierno obligatorios</com:value></com:values></com:comment></sit:generalPublicComment>
<sit:locationReference xsi:type="loc:SingleRoadLinearLocation"><loc:roadInformation><loc:roadNumber>LE-2703</loc:roadNumber></loc:roadInformation><loc:linearExtension><lse:kilometerPoint>12.3</lse:kilometerPoint><lse:kilometerPoint>21,0</lse:kilometerPoint></loc:linearExtension><loc:pointCoordinates><loc:latitude>43.11</loc:latitude><loc:longitude>-4.88</loc:longitude></loc:pointCoordinates><loc:pointCoordinates><loc:latitude>43.06</loc:latitude><loc:longitude>-4.84</loc:longitude></loc:pointCoordinates></sit:locationReference>
<sit:winterEquipmentManagementType>useSnowChainsOrTyres</sit:winterEquipmentManagementType></sit:situationRecord></sit:situation>
<sit:situation id="s2"><sit:situationRecord id="r2" xsi:type="sit:MaintenanceWorks"><sit:validity><com:validityStatus>active</com:validityStatus></sit:validity><sit:locationReference><loc:roadNumber>A-8</loc:roadNumber><loc:latitude>43.40</loc:latitude><loc:longitude>-4.70</loc:longitude></sit:locationReference><sit:roadMaintenanceType>roadworks</sit:roadMaintenanceType></sit:situationRecord></sit:situation>
<sit:situation id="s3"><sit:situationRecord id="r3" xsi:type="sit:Accident"><sit:locationReference><loc:latitude>40.4</loc:latitude><loc:longitude>-3.7</loc:longitude></sit:locationReference></sit:situationRecord></sit:situation>
<sit:situation id="s4"><sit:situationRecord id="r4" xsi:type="sit:PoorEnvironmentConditions"><sit:validity><com:validityStatus>suspended</com:validityStatus></sit:validity><sit:locationReference><loc:latitude>43.2</loc:latitude><loc:longitude>-4.9</loc:longitude></sit:locationReference></sit:situationRecord></sit:situation>
</d2:payload>'''
V1=b'''<d2LogicalModel xmlns="http://datex2.eu/schema/1_0/1_0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"><payloadPublication xsi:type="SituationPublication"><situation id="x"><situationRecord xsi:type="PoorEnvironmentConditions" id="p1"><poorEnvironmentType>snowfall</poorEnvironmentType><groupOfLocations><locationContainedInGroup><tpegpointLocation><point><pointCoordinates><latitude>43.23</latitude><longitude>-4.57</longitude></pointCoordinates></point></tpegpointLocation><roadNumber>N-621</roadNumber></locationContainedInGroup></groupOfLocations></situationRecord></situation></payloadPublication></d2LogicalModel>'''
class DGT(unittest.TestCase):
 def test_v3_chains_level_road_km_and_filters(self):
  out=mod.parse(V3);self.assertEqual(len(out),2,'fuera de zona y suspendidas descartadas')
  c=out[0];self.assertEqual(c['kind'],'chains');self.assertEqual(c['level'],'rojo');self.assertEqual(c['road'],'LE-2703');self.assertEqual(c['km'],[12.3,21.0]);self.assertEqual((c['lat2'],c['lon2']),(43.06,-4.84));self.assertIn('useSnowChainsOrTyres',c['details'])
  self.assertEqual(out[1]['kind'],'works');self.assertEqual(out[1]['road'],'A-8')
 def test_v1_snow(self):
  out=mod.parse(V1);self.assertEqual(len(out),1);self.assertEqual(out[0]['kind'],'snow');self.assertEqual(out[0]['road'],'N-621');self.assertEqual(out[0]['level'],'')
if __name__=='__main__':unittest.main()
