import {Window} from 'happy-dom';
import fs from 'node:fs';
import xmldom from '@xmldom/xmldom';
import assert from 'node:assert/strict';
const w=new Window({url:'http://localhost:8765/',settings:{disableJavaScriptFileLoading:true,disableCSSFileLoading:true}});
w.DOMParser=xmldom.DOMParser;
w.document.write(fs.readFileSync(new URL('../index.html',import.meta.url),'utf8'));
w.eval(fs.readFileSync(new URL('../core.js',import.meta.url),'utf8'));
const GPX=(pts,ns='')=>`<gpx xmlns="http://www.topografix.com/GPX/1/1"><trk><name>Prueba &amp; cero</name><trkseg>${pts}</trkseg></trk></gpx>`;
let parsed=w.TM.parseGPX(GPX('<trkpt lat="0" lon="0"><ele>0</ele></trkpt><trkpt lat="0.01" lon="0"><ele>10</ele></trkpt>'));
assert.equal(parsed.points[0].ele,0);assert.equal(parsed.name,'Prueba & cero');
assert.throws(()=>w.TM.parseGPX(GPX('<trkpt lon="0"/><trkpt lat="1" lon="1"/>')));
assert.throws(()=>w.TM.parseGPX('<gpx><broken>'));
assert.throws(()=>w.TM.parseGPX('<!DOCTYPE gpx><gpx/>'));
parsed=w.TM.parseGPX('<g:gpx xmlns:g="http://www.topografix.com/GPX/1/1"><g:rte><g:name>Route</g:name><g:rtept lat="43" lon="-4"/><g:rtept lat="43.1" lon="-4"/></g:rte></g:gpx>');assert.equal(parsed.points.length,2);assert.equal(parsed.summary.elevationComplete,false);
let calls=0;
const now=Math.floor(Date.now()/3600000)*3600;
function forecast(u){const ids=u.searchParams.get('models')?.split(',');const n=168,time=Array.from({length:n},(_,i)=>now+i*3600),hourly={time};for(const k of u.searchParams.get('hourly').split(',')){for(const id of ids||[''])hourly[k+(id?'_'+id:'')]=time.map((_,i)=>k==='temperature_2m'?12:k==='apparent_temperature'?10:k==='wind_gusts_10m'?20:k==='visibility'?10000:k==='weather_code'?2:0)}const d={hourly,current:{temperature_2m:12,apparent_temperature:10,weather_code:2,wind_gusts_10m:20,precipitation:0},timezone:'Europe/Madrid',elevation:1200};const locations=u.searchParams.get('latitude').split(',').length;return locations>1?Array.from({length:locations},()=>structuredClone(d)):d}
w.fetch=async(url)=>{calls++;const u=new URL(url);let data;if(u.hostname==='api.met.no')data={properties:{timeseries:[]}};else if(u.hostname==='geocoding-api.open-meteo.com')data={results:[{name:'Cangas de Onís',latitude:43.35,longitude:-5.13,country:'España'}]};else data=forecast(u);return {ok:true,status:200,json:async()=>data}};
w.eval(fs.readFileSync(new URL('../app.js',import.meta.url),'utf8')+';globalThis.testAPI={search,importRoute,analyzeRoute,setLocation};');
await new Promise(r=>setTimeout(r,100));
assert.match(w.document.querySelector('#current').textContent,/12/);assert.equal(w.document.querySelectorAll('.hour').length,24);assert.equal(w.document.querySelectorAll('.model').length,6);
w.document.querySelector('#placeSearch').value='Cangas';await w.testAPI.search();assert.match(w.document.querySelector('#searchResults').textContent,/Cangas/);
const pts=Array.from({length:10001},(_,i)=>`<trkpt lat="${43+i/1000000}" lon="-4"><ele>${1000+i/100}</ele></trkpt>`).join('');
await w.testAPI.importRoute(new w.File([GPX(pts)],'test.gpx'));
console.log('Route status:',w.document.querySelector('#routeStatus').textContent);assert.equal(w.document.querySelector('#routeContent').hidden,false);assert.equal(w.document.querySelector('#routeForecast').hidden,false);assert.equal(w.document.querySelectorAll('#routeTable tbody tr').length,16);
assert.doesNotMatch(w.document.querySelector('#routeTable').textContent,/Sin datos/);
assert.match(w.document.querySelector('#routeStatus').textContent,/Análisis terminado/);
const rowCount=w.document.querySelectorAll('#routeStats .stat').length;await w.testAPI.analyzeRoute();assert.equal(w.document.querySelectorAll('#routeStats .stat').length,rowCount);
w.document.querySelector('#startTime').value='2000-01-01T12:00';await w.testAPI.analyzeRoute();assert.match(w.document.querySelector('#routeStatus').textContent,/salida futura/);
w.fetch=async()=>{throw Error('simulated offline')};await w.testAPI.setLocation({name:'Sin conexión',lat:1,lon:2});assert.match(w.document.querySelector('#current').textContent,/No se pudo/);
console.log('Integration checks passed: GPX namespaces, zero elevation, malformed XML, coordinate validation, rendering, search, 10,001-point GPX import, 16 weather sectors, repeat analysis, invalid date, offline error. API calls:',calls);
await w.happyDOM.close();
