import {Window} from 'happy-dom';import fs from 'node:fs';import assert from 'node:assert/strict';import {indexedDB} from 'fake-indexeddb';import xmldom from '@xmldom/xmldom';
const w=new Window({url:'http://localhost:8765/',settings:{disableJavaScriptFileLoading:true,disableCSSFileLoading:true}});w.DOMParser=xmldom.DOMParser;w.indexedDB=indexedDB;w.structuredClone=structuredClone;w.IntersectionObserver=class{observe(){}unobserve(){}};w.scrollTo=()=>{};w.HTMLElement.prototype.scrollIntoView=()=>{};
w.document.write(fs.readFileSync('index.html','utf8'));w.eval(fs.readFileSync('core.js','utf8'));
const start=Math.floor(Date.now()/3600000)*3600;let aiCalls=[],commons=0;
function forecast(u){const time=Array.from({length:168},(_,i)=>start+i*3600),hourly={time};for(const k of (u.searchParams.get('hourly')||'temperature_2m').split(','))for(const id of u.searchParams.get('models')?.split(',')||[''])hourly[k+(id?'_'+id:'')]=time.map(()=>k==='temperature_2m'?4:k==='apparent_temperature'?-1:k==='wind_gusts_10m'?40:k==='visibility'?10000:k==='freezing_level_height'?900:k.startsWith('geopotential_height_')?({1000:110,950:540,925:760,900:990,850:1460,800:1950,700:3010,600:4200})[k.match(/_(\d+)hPa/)[1]]:/^cloud_cover_(1000|950)hPa/.test(k)?90:k.startsWith('cloud_cover_')?5:k==='precipitation'?.5:0);const daily={sunrise:[start-3600],sunset:[start+12*3600]};const d={timezone:'Europe/Madrid',elevation:1000,current:{temperature_2m:4,weather_code:61},hourly,daily};return u.searchParams.get('latitude').split(',').length>1?u.searchParams.get('latitude').split(',').map(()=>structuredClone(d)):d}
w.fetch=async(url,opts={})=>{const u=new URL(url,'http://localhost:8765');let d;
 if(u.hostname==='text.pollinations.ai'){const body=JSON.parse(opts.body);aiCalls.push(body);d={choices:[{message:{content:'**Sal a las 9:00**\n- Lleva chaqueta\n- Vigila el km 1'}}]}}
 else if(u.hostname==='commons.wikimedia.org'){commons++;d={query:{pages:{1:{title:'File:Picos.jpg',imageinfo:[{thumburl:'https://upload.wikimedia.org/x/Picos.jpg',url:'https://upload.wikimedia.org/x/Picos.jpg',descriptionurl:'https://commons.wikimedia.org/wiki/File:Picos.jpg',width:3000,height:2000,mime:'image/jpeg',extmetadata:{Artist:{value:'<a>Autora</a>'},LicenseShortName:{value:'CC BY-SA 4.0'},LicenseUrl:{value:'https://creativecommons.org/licenses/by-sa/4.0'}}}]},2:{title:'File:Vertical.jpg',imageinfo:[{thumburl:'https://upload.wikimedia.org/x/V.jpg',width:1000,height:3000,mime:'image/jpeg',extmetadata:{LicenseShortName:{value:'CC0'}}}]}}}}}
 else if(u.pathname.includes('dgt.json'))d={fetched:new Date(Date.now()-300000).toISOString(),complete:true,incidents:[{id:'c1',type:'WinterDrivingManagement',kind:'chains',level:'rojo',road:'AS-264',km:[3,5],dir:'',severity:'high',start:'',end:'',lat:43.28,lon:-4.82,lat2:43.279,lon2:-4.8205,place:'Cabrales',details:['useSnowChainsOrTyres'],text:'Nivel rojo'},{id:'s9',type:'PoorEnvironmentConditions',kind:'snow',level:'',road:'LE-2711',km:[],lat:43.20,lon:-4.82,lat2:43.20,lon2:-4.82,place:'Posada',details:[],text:'Nieve'},{id:'far',kind:'works',level:'',road:'A-8',km:[],lat:43.6,lon:-3.0,lat2:43.6,lon2:-3.0,place:'',details:[],text:''}]};
 else if(u.hostname==='nominatim.openstreetmap.org')d=String(u.searchParams.get('q')).includes('Arenas')?[{display_name:'Arenas de Cabrales, Cabrales, Asturias, España',lat:'43.3000',lon:'-4.8100',type:'village'},{display_name:'Arenas, Cantabria',lat:'43.4',lon:'-4.1',type:'hamlet'}]:[{display_name:'Poncebos, Cabrales, Asturias',lat:'43.2600',lon:'-4.8300',type:'hamlet'}];
 else if(u.hostname==='router.project-osrm.org'){const pts=Array.from({length:21},(_,i)=>[-4.81-i*.001,43.30-i*.002]);d={code:'Ok',waypoints:[{distance:5},{distance:420}],routes:[{distance:5200,duration:600,geometry:{coordinates:pts},legs:[{steps:[{distance:2600,duration:300,ref:'AS-114',name:'',geometry:{coordinates:pts.slice(0,11)}},{distance:2600,duration:300,ref:'AS-264',name:'Carretera de Poncebos',geometry:{coordinates:pts.slice(10)}}]}]},{distance:9000,duration:1100,geometry:{coordinates:[[-4.81,43.30],[-4.85,43.28],[-4.83,43.26]]},legs:[{steps:[{distance:9000,duration:1100,ref:'',name:'Otra',geometry:{coordinates:[[-4.81,43.30],[-4.85,43.28],[-4.83,43.26]]}}]}]}]}}
 else if(u.pathname.includes('mountain.json'))d=JSON.parse(fs.readFileSync('data/mountain.json'));
 else if(u.pathname.includes('alerts.json'))d={complete:true,fetched:new Date().toISOString(),alerts:[]};
 else if(u.hostname==='overpass-api.de'){const q=String(opts.body||'');const ql=decodeURIComponent(q.replace(/\+/g,' '));if(/Canal\|Canal/.test(ql)||ql.includes('Canalón'))d={elements:[{type:'way',id:101,tags:{name:'Canal de Trea',highway:'path',sac_scale:'demanding_mountain_hiking'},geometry:Array.from({length:30},(_,i)=>({lat:43.245-i*.0004,lon:-4.88-i*.0006}))},{type:'way',id:102,tags:{name:'Canal de Trea',highway:'path'},geometry:Array.from({length:10},(_,i)=>({lat:43.245-29*.0004-i*.0004,lon:-4.88-29*.0006-i*.0006}))},{type:'way',id:103,tags:{name:'Canal de Mesones',highway:'path'},geometry:[{lat:43.20,lon:-4.93},{lat:43.198,lon:-4.935}]},{type:'node',id:104,lat:43.2,lon:-4.72,tags:{name:'Canal del Vaso',natural:'valley'}},{type:'way',id:105,tags:{name:'Canal de Castilla',waterway:'canal'},geometry:[{lat:43.2,lon:-4.9},{lat:43.21,lon:-4.9}]}]};else if(ql.includes('rel(bw)'))d={elements:[{type:'relation',id:9001,tags:{route:'hiking',ref:'PR-PNPE 22',name:'Canal de Trea',network:'rwn',distance:'8.4',from:'Caín',to:'Vega Maor'}}]};else if(/rel\(\d+\);out geom/.test(ql))d={elements:[{type:'relation',id:9001,tags:{route:'hiking',ref:'PR-PNPE 22',name:'Canal de Trea'},members:[{type:'way',geometry:Array.from({length:30},(_,i)=>({lat:43.245-i*.0004,lon:-4.88-i*.0006}))},{type:'way',geometry:Array.from({length:10},(_,i)=>({lat:43.245-29*.0004-i*.0004,lon:-4.88-29*.0006-i*.0006}))}]}]};else if(/route.*hiking.*name/.test(ql))d={elements:[{type:'relation',id:9002,tags:{route:'hiking',ref:'GR 202',name:'Ruta de la Reconquista',network:'nwn'}}]};else if(ql.includes('saddle'))d={elements:[{type:'way',id:201,tags:{highway:'path',name:'Senda de Cuarroble',sac_scale:'mountain_hiking'},geometry:[{lat:43.2414,lon:-4.886},{lat:43.2414,lon:-4.880}]},{type:'node',id:202,lat:43.2452,lon:-4.8805,tags:{natural:'saddle',name:'Collado de prueba'}},{type:'node',id:203,lat:43.233,lon:-4.904,tags:{tourism:'alpine_hut',name:'Refugio de prueba'}},{type:'node',id:204,lat:43.25,lon:-4.875,tags:{amenity:'parking',name:'Aparcamiento de prueba'}},{type:'node',id:205,lat:43.2401,lon:-4.8875,tags:{natural:'spring',name:'Fuente de prueba'}}]};else d={elements:[],osm3s:{}}}
 else if(u.hostname==='ensemble-api.open-meteo.com'){const time=Array.from({length:120},(_,i)=>start+i*3600),hourly={time};for(const k of u.searchParams.get('hourly').split(',')){hourly[k]=time.map(()=>k==='temperature_2m'?5:k==='precipitation'?0:30);for(let m=1;m<=10;m++)hourly[`${k}_member${String(m).padStart(2,'0')}`]=time.map(()=>k==='temperature_2m'?m:k==='precipitation'?(m>5?1:0):m*8)}d={hourly}}
 else if(u.hostname==='api.met.no')d={properties:{timeseries:[]}};
 else if(u.hostname==='r.jina.ai')return{ok:true,text:async()=>String(url).includes('duckduckgo')?'## [Canal de Trea - Wikiloc | Ruta Senderismo](https://es.wikiloc.com/rutas-senderismo/canal-de-trea-12345678)\nDistancia 8,5 km · Desnivel positivo 1.250 m · Difícil\n## [Otra](https://blog.example/x)':'<html><title>Canal de Trea | Wikiloc</title><script>var d={"geometry":{"coordinates":['+Array.from({length:40},(_,i)=>`[${(-4.87+i*.001).toFixed(5)},${(43.22+i*.0008).toFixed(5)}]`).join(',')+']}}</script></html>'};
 else if(u.hostname==='api.open-meteo.com'&&u.pathname.includes('elevation'))d={elevation:u.searchParams.get('latitude').split(',').map((_,i)=>500+i*20)};
 else d=forecast(u);return{ok:true,status:200,json:async()=>d,text:async()=>JSON.stringify(d)}};
const scripts=['app.js','mountain.js','expedition-core.js','expedition.js','terrain.js','route-library.js','home.js','public-sources.js','route-knowledge.js','cares-archive.js','fx.js','firebase-config.js','ai.js','copilot-expert.js','parte.js','wikiloc.js','canales.js','gear.js','field-core.js','pois.js','relief.js','sky.js','week.js','pace.js','flyover.js','card.js','modelsx.js','snow.js','trails.js','account.js','contact.js','road.js','finder.js','results.js','palette.js','shell.js','fuel.js'];
w.eval(scripts.map(s=>fs.readFileSync(s,'utf8')).join('\n')+'\nglobalThis.T={get route(){return S.route},importRoute,enterApp,showTab,get S(){return S}};');
await new Promise(r=>setTimeout(r,150));
const $=s=>w.document.querySelector(s),$$=s=>[...w.document.querySelectorAll(s)];
// Arranque y navegación
assert.ok($('#splash'),'splash visible al cargar');assert.equal($('#main').hidden,true);
$('#splashEnter').click();await new Promise(r=>setTimeout(r,800));assert.equal($('#splash'),null,'splash retirado');assert.equal($('#main').hidden,false);assert.equal($('#pane-route').hidden,false,'el arranque lleva al planificador');
assert.equal($$('.tabs [data-tab]')[0].dataset.tab,'route');assert.ok($('[data-tab="canales"]'));
w.T.showTab('canales');assert.equal($('#pane-canales').hidden,false);
// Fotos con atribución
assert.ok(commons>0);const photos=await w.TMPhotos.commonsPhotos('Picos de Europa');assert.equal(photos.length,1,'filtra verticales y sin licencia');assert.equal(photos[0].artist,'Autora');assert.match(w.TMPhotos.creditHTML(photos[0]),/CC BY-SA 4\.0/);
// Canales: catálogo OSM de los tres macizos + fichas 2003
assert.equal($$('#caresArchive .cares-route').length,15);await new Promise(r=>setTimeout(r,80));
const cat=w.TMCanales.list;assert.ok(cat.some(c=>c.name==='Canal de Trea'&&c.lines.length===2&&c.doc!=null),'Trea con dos tramos y ficha 2003');assert.ok(!cat.some(c=>/Castilla/.test(c.name)),'excluye canales de agua');assert.equal(cat.find(c=>c.name==='Canal del Vaso').massif,'oriental');assert.equal(cat.find(c=>c.name==='Canal de Trea').massif,'occidental');assert.equal(cat.find(c=>c.name==='Canal de Mesones').massif,'occidental');assert.equal(cat.find(c=>c.name==='Canal de Moéño').massif,'central');assert.equal(cat.filter(c=>c.doc!=null).length,15,'las 15 fichas documentadas siguen presentes');
assert.equal(w.TMCanales.massifOf(43.25,-4.95),'occidental');assert.equal(w.TMCanales.massifOf(43.2,-4.85),'central');assert.equal(w.TMCanales.massifOf(43.2,-4.70),'oriental');
assert.equal(w.TMCanales.joinLines([[{lat:0,lon:0},{lat:0,lon:.001}],[{lat:0,lon:.002},{lat:0,lon:.001}]]).length,3);
assert.equal($$('#cnList .cn-item').length,16);$('[data-cn-filter="oriental"]').click();assert.equal($$('#cnList .cn-item').length,1);$('[data-cn-filter="all"]').click();
$('#cnSearch').value='Cuarroble';$('#cnSearch').dispatchEvent(new w.Event('input'));assert.ok($$('#cnList .cn-item').some(c=>/Trea/.test(c.textContent)));$('#cnSearch').value='';$('#cnSearch').dispatchEvent(new w.Event('input'));
const trea=cat.find(c=>c.name==='Canal de Trea');await w.TMCanales.open(trea.id);await new Promise(r=>setTimeout(r,250));assert.match($('#cnDetail').textContent,/Pyrenaica 2003/);assert.match($('#cnDetail').textContent,/2025/);assert.ok($$('#cnDetail .cn-steps li').length>=3);
assert.match($('#cnStats').textContent,/Longitud/);assert.ok($('#cnProfile svg.cn-profile'));assert.match($('#cnAccess').textContent,/Senda de Cuarroble/);assert.match($('#cnAccess').textContent,/Collado de prueba/);assert.match($('#cnAccess').textContent,/Aparcamiento de prueba/);assert.match($('#cnAccess').textContent,/Fuente de prueba/);assert.match($('#cnSun').textContent,/Parte baja/);
const ctx=JSON.parse(w.Copilot.context());assert.equal(ctx.canal.canal,'Canal de Trea');assert.ok(ctx.canal.ficha_2003);$('#cnClose').click();assert.equal($('#cnDetail'),null);
// Wikiloc
const md='1. [Canal de Trea - Wikiloc](https://duckduckgo.com/l/?uddg=https%3A%2F%2Fes.wikiloc.com%2Frutas-senderismo%2Fcanal-de-trea-12345678)\nDistancia 8,5 km · Desnivel 1.250 m · Moderado\n2. [Blog](https://blog.example/x)';
const parsed=w.TMWikiloc.parse(md);assert.equal(parsed.length,1);assert.equal(parsed[0].id,'12345678');assert.equal(parsed[0].km,'8,5');assert.equal(parsed[0].level,'Moderado');
assert.equal(JSON.stringify(w.TMWikiloc.decodePolyline('_p~iF~ps|U_ulLnnqC_mqNvxq`@').map(p=>[p.lat,p.lon])),'[[38.5,-120.2],[40.7,-120.95],[43.252,-126.453]]');
assert.equal(w.TMWikiloc.extractGeometry('<p>sin datos</p>'),null);
w.T.showTab('route');const found=await w.TMWikiloc.search('Canal de Trea');assert.equal(found.length,1);assert.equal($$('#wlResults .wl-card').length,1);
await w.TMWikiloc.loadTrail(found[0]);assert.equal(w.T.route.name,'Canal de Trea');assert.equal(w.T.route.points.length,40);assert.equal(w.T.route.summary.elevationComplete,true,'altitudes añadidas');assert.match($('#wlStatus').textContent,/cargada desde Wikiloc/);
await new Promise(r=>setTimeout(r,100));
// Semáforo, mochila y compartir
assert.equal($('#expeditionPanel').hidden,false);assert.match($('#goMeter').textContent,/OJO|STOP|GO|\?/);const gear=$$('#gearList .gear-item').map(x=>x.textContent).join(' ');assert.match(gear,/Agua/);assert.match(gear,/impermeable/);assert.match(gear,/microcrampones/,'isoterma bajo la cota máxima');assert.match(gear,/Cortavientos/);assert.ok($('#shareExpedition'));
// Copiloto: proveedor gratuito sin Firebase, contexto real y adaptador de botones existentes
const repoFirebase=w.TRAILMETEO_FIREBASE;assert.ok(!repoFirebase||w.Copilot.parseFirebaseConfig(repoFirebase),'firebase-config.js válido');assert.equal(w.Copilot.provider(),repoFirebase?'firebase':'free');w.TRAILMETEO_FIREBASE=null;assert.equal(w.Copilot.provider(),'free');assert.equal(w.Copilot.parseFirebaseConfig('const firebaseConfig = {\n apiKey: "AIzaX",\n authDomain: "p.firebaseapp.com",\n projectId: "p",\n appId: "1:2:web:3", // app\n};').projectId,'p');assert.equal(w.Copilot.parseFirebaseConfig('{apiKey:"x"}'),null);
const before=aiCalls.length;const out=await w.Copilot.ask('¿A qué hora salgo?');assert.match(out.text,/9:00/);const last=aiCalls.at(-1);assert.ok(aiCalls.length>before);assert.match(last.messages.at(-1).content,/Canal de Trea/,'el contexto incluye la ruta');assert.match(last.messages.at(-1).content,/sectores/);assert.match($('#cpLog').textContent,/Lleva chaqueta/);assert.equal($$('#cpLog li').length>=2,true,'markdown en listas');
assert.equal(w.Copilot.md('<img src=x onerror=alert(1)> [x](javascript:alert(1))').includes('<img'),false);assert.equal(w.Copilot.md('[x](javascript:alert(1))').includes('href'),false);
const ai=w.T.S.qwen;const r=await ai.chat.completions.create({messages:[{role:'system',content:'S'},{role:'user',content:'U'}]});assert.match(r.choices[0].message.content,/9:00/);
// v10 · Terreno, mar de nubes, semana, ritmo, parte, menú Más
const rp=w.T.route.points;
assert.ok(!$('#weekCard').hidden,'mapa de la semana visible tras analizar');const cells=w.TMWeek.cells();assert.equal(cells.length,7*11);assert.ok(cells.some(c=>c.score!=null));assert.ok($$('#weekGrid button[data-week]').length>10);assert.ok($('#weekBest').textContent.length>5);
const sky=w.TMSky.cloudLayer({cloud_cover_1000hPa:[90],cloud_cover_950hPa:[90],cloud_cover_925hPa:[10],cloud_cover_900hPa:[5],cloud_cover_850hPa:[5],cloud_cover_800hPa:[5],cloud_cover_700hPa:[5],cloud_cover_600hPa:[5],geopotential_height_1000hPa:[110],geopotential_height_950hPa:[540],geopotential_height_925hPa:[760],geopotential_height_900hPa:[990],geopotential_height_850hPa:[1460],geopotential_height_800hPa:[1950],geopotential_height_700hPa:[3010],geopotential_height_600hPa:[4200]},0);assert.equal(sky.top,650);assert.equal(sky.clearAbove,true);
w.T.showTab('now');await new Promise(r=>setTimeout(r,120));assert.match($('#skyVerdict').textContent,/nubes|Nubes|capa/);assert.ok($('#skyStack svg'));
w.T.showTab('terrain');assert.equal($('#pane-terrain').hidden,false);await new Promise(r=>setTimeout(r,300));assert.match($('#shadeOut').textContent,/Sectores en sombra/);assert.equal($$('#shadeOut .shade-row').length,16);assert.match($('#groundOut').textContent,/Lluvia 72 h/);
const timed=Array.from({length:200},(_,i)=>`<trkpt lat="${43+i*.0005}" lon="-5"><ele>${1000+i*2}</ele><time>${new Date(Date.UTC(2026,5,1,8)+i*30000).toISOString()}</time></trkpt>`).join('');const fit=w.TMPace.fit(w.TMPace.parse(`<gpx xmlns="http://www.topografix.com/GPX/1/1"><trk><trkseg>${timed}</trkseg></trk></gpx>`));assert.ok(fit.pace>2&&fit.pace<20);assert.ok(fit.km>9);
// mastines retirados en v11
assert.equal(w.TMDogs,undefined);//({lat:43.2,lon:-4.9,t:Date.now(),count:2,beh:'bark'}));assert.equal(w.TMDogs.validReport({lat:43.2,lon:-4.9,t:Date.now(),count:2,beh:'x'}),false);w.localStorage.setItem('tm.dogs',JSON.stringify([{lat:rp[20].lat,lon:rp[20].lon,t:Date.now()-86400000,count:3,beh:'approach',flock:'yes',notes:'majada'},{lat:44,lon:-3,t:Date.now(),count:1,beh:'calm'}]));await w.TMDogs.load();assert.equal(w.TMDogs.nearRoute().length,1);assert.match($('#dogAlert').textContent,/1 aviso a menos de 500 m/);
const ctx2=JSON.parse(w.Copilot.context());assert.equal(ctx2.mastines_cerca_de_la_ruta,undefined);
const rows=w.TMPois.rows(w.T.route,[{type:'node',id:1,lat:rp[30].lat+.0005,lon:rp[30].lon,tags:{natural:'spring',name:'Fuente Cuarroble'}},{type:'node',id:2,lat:rp[5].lat,lon:rp[5].lon+.0003,tags:{tourism:'alpine_hut',name:'Refugio'}},{type:'node',id:3,lat:44,lon:-4,tags:{amenity:'drinking_water'}},{type:'node',id:4,lat:rp[8].lat,lon:rp[8].lon,tags:{amenity:'bench'}}]);assert.equal(rows.length,2);assert.equal(rows[0].kind,'alpine_hut');
assert.ok($('#cardMake'));assert.ok($('#flyRoute'));assert.equal(await w.TMCard.make(),null,'sin canvas en el entorno de prueba no falla');
w.TMTheme.openMore();assert.ok($('#moreSheet'));$('#moreSheet [data-more="radar"]').click();assert.equal($('#moreSheet'),null);assert.equal($('#pane-radar').hidden,false);assert.ok($('.tabs [data-tab="now"]').classList.contains('active'),'Cielo resaltado en subsecciones');
assert.equal($('#pane-field'),null,'sin modo En ruta');
// v11 · partículas, sonido, modelos extra, conjuntos, nieve, senderos, cuentas y buzón
assert.ok(['snow','rain','motes','fog'].includes(w.TMParticles.mode));assert.equal(typeof w.TMSound.setWind,'function');
assert.equal(w.TMModels.pct([1,2,3,4,5],.5),3);const es=w.TMModels.ensembleStats({hourly:{time:[start],temperature_2m:[0],temperature_2m_member01:[2],temperature_2m_member02:[4]}},'temperature_2m');assert.equal(es[0].n,3);assert.equal(es[0].p50,2);
assert.ok(w.T.S.models.some(m=>m.extra&&m.name==='UK Met Office'),'modelos adicionales cargados');assert.ok(w.T.S.models.length>=12);
w.T.showTab('models');await new Promise(r=>setTimeout(r,200));assert.ok($('#meteoOut svg.meteo-svg'),'meteograma multimodelo');assert.match($('#meteoLegend').textContent,/JMA/);assert.ok($('#ensOut svg.ens-svg'),'abanico del conjunto');assert.match($('#ensOut').textContent,/Lluvia 24 h/);assert.match($('#ensOut').textContent,/45 %/);assert.match($('#ensOut').textContent,/36 %/);
$('#meteoCard [data-mv="wind_gusts_10m"]').click();assert.equal($('#meteoCard [data-mv="wind_gusts_10m"]').getAttribute('aria-pressed'),'true');
assert.equal(w.TMSnow.snowLine(1500),1200);assert.equal(w.TMSnow.snowLine(null),null);assert.match(w.TMSnow.gibsURL('ndsi','2026-01-02'),/MODIS_Terra_NDSI_Snow_Cover\/default\/2026-01-02\/GoogleMapsCompatible_Level8/);
w.T.showTab('terrain');await new Promise(r=>setTimeout(r,300));assert.match($('#snowOut').textContent,/Espesor ahora/);assert.ok($('#snowOut .snow-bars'));assert.match($('#snowLine').textContent,/Cota de nieve/);assert.match($('#snowSectors').textContent,/km/);assert.ok($('#satCard [data-sat="ndsi"]'));
const sn=await w.TMSnow.at(43.2,-4.9,2000);assert.ok('depth' in sn&&'line' in sn);
const enc=w.TMAccount.encodePolyline([{lat:38.5,lon:-120.2},{lat:40.7,lon:-120.95},{lat:43.252,lon:-126.453}]);assert.equal(enc,'_p~iF~ps|U_ulLnnqC_mqNvxq`@');
const rec={id:'abc',saved:1,route:w.T.route,pace:14,climb:9};const cr=w.TMAccount.cloudRecord(rec);assert.ok(cr.poly.length>10&&cr.ele.length===w.T.route.points.length);const back=w.TMAccount.recordFromCloud('abc',cr);assert.equal(back.route.points.length,w.T.route.points.length);assert.equal(back.route.name,w.T.route.name);assert.equal(back.pace,14);
assert.equal(w.TMAccount.thinPoints(Array.from({length:5000},(_,i)=>({lat:i,lon:0})),3000).length,3000);
assert.ok($('#accountBtn'));$('#accountBtn').click();assert.ok($('#accSheet'));assert.match($('#accSheet').textContent,/Usar sin registrarme/);assert.match($('#accSheet').textContent,/Continuar con Google/);$('#accSheet [data-acc="guest"]').click();assert.equal($('#accSheet'),null);assert.equal(w.localStorage.getItem('tm.account'),'guest');assert.equal(w.TMAccount.guest,true);assert.match($('#accHint').textContent,/este dispositivo/);
assert.equal(w.TMContact.email,'mariawilderwest@gmail.com');assert.match(w.TMContact.mailtoURL({type:'idea',message:'Hola',email:''}),/^mailto:mariawilderwest@gmail\.com\?subject=/);assert.match($('footer').textContent,/mariawilderwest@gmail\.com/);
w.TMContact.open();assert.ok($('#fbSheet textarea'));w.TMContact.close();
w.TMTheme.openMore();assert.ok($('#moreSheet [data-more="account"]'));assert.ok($('#moreSheet [data-more="contact"]'));$('#moreSheet [data-more="contact"]').click();assert.ok($('#fbSheet'),'buzón desde Más');w.TMContact.close();
assert.equal(w.TMTrails.trailKind({ref:'GR 202'}),'GR');assert.equal(w.TMTrails.trailKind({ref:'PR-PNPE 22'}),'PR');assert.equal(w.TMTrails.slopeColor(70),'#b3261e');
const ts=await w.TMTrails.osmTrails('Reconquista');
// v12 · carretera: DGT, cadenas, trayecto, tiempo en ruta
const nl=w.TMRoad.nearestOnLine({lat:43.001,lon:0},[{lat:43,lon:-.01,km:0},{lat:43,lon:.01,km:1.6}]);assert.ok(nl.d>.1&&nl.d<.12);assert.ok(Math.abs(nl.km-.8)<.01);
assert.equal(w.TMRoad.roadRisk({temperature_2m:0,precipitation:1,snowfall:.5},0,0).label,'Nevando');assert.equal(w.TMRoad.roadRisk({temperature_2m:.5,precipitation:0},2,0).label,'Hielo probable');assert.equal(w.TMRoad.roadRisk({temperature_2m:8,precipitation:0,visibility:20000},0,0).level,'low');
const ps=w.TMRoad.passes([{km:0,ele:200},{km:5,ele:500},{km:10,ele:1300},{km:15,ele:700},{km:20,ele:400}]);assert.equal(ps.length,1);assert.equal(ps[0].ele,1300);
w.T.showTab('road');assert.equal($('#pane-road').hidden,false);assert.ok($('#roadTo').value.startsWith('Inicio de'),'destino por defecto: inicio de la ruta cargada');
$('#roadFrom').value='Arenas de Cabrales';$('#roadFrom').dispatchEvent(new w.Event('input'));$('#roadTo').value='Poncebos';$('#roadTo').dispatchEvent(new w.Event('input'));
await w.TMRoad.run(true);await new Promise(r=>setTimeout(r,100));
assert.equal($('#roadOut').hidden,false);assert.match($('#roadStatus').textContent,/Arenas de Cabrales/);assert.equal($$('#roadFromCands [data-cand]').length,2,'candidatos para elegir el lugar exacto');
assert.match($('#roadKpis').textContent,/AS-114/);assert.match($('#roadKpis').textContent,/10 min/);assert.match($('#roadIncidents').textContent,/Nivel Rojo/);assert.match($('#roadIncidents').textContent,/AS-264/);assert.match($('#roadIncidents').textContent,/en tu trayecto/);assert.match($('#roadIncidents').textContent,/LE-2711/,'nieve cercana listada');assert.ok(!/A-8/.test($('#roadIncidents').textContent),'lejanos fuera');
assert.match($('#roadNote').textContent,/420 m del destino/);assert.match($('#roadDgtAge').textContent,/hace 5 min/);assert.equal($$('#roadAlts [data-road-alt]').length,2);assert.match($('#roadAlts').textContent,/menos avisos/);assert.match($('#roadNote').textContent,/alternativa 1 tiene menos avisos/);
const rc=w.TMRoad.context();assert.equal(rc.avisos_dgt_en_trayecto[0].nivel_cadenas,'rojo');assert.ok(rc.carreteras.includes('AS-264'));assert.ok(JSON.parse(w.Copilot.context()).carretera);
w.TMTheme.openMore();assert.ok($('#moreSheet [data-more="road"]'));w.TMTheme.closeMore();assert.ok($('[data-go-road]'));
assert.equal(ts[0].ref,'GR 202');
w.T.showTab('route');$('#wlQuery').value='Reconquista';$('#wlForm').dispatchEvent(new w.Event('submit',{cancelable:true}));await new Promise(r=>setTimeout(r,200));assert.match($('#trOut').textContent,/GR 202/);assert.match($('#trOut').textContent,/Komoot/);
const g=await w.TMTrails.trailGPX({id:9001,ref:'PR-PNPE 22',name:'Canal de Trea'});assert.equal(g.points.length,39);assert.ok(g.coverage>.95);
w.T.showTab('canales');await w.TMCanales.open(trea.id);await new Promise(r=>setTimeout(r,300));assert.match($('#cnSources').textContent,/PR-PNPE 22/);assert.match($('#cnSnow').textContent,/Espesor arriba/);assert.match($('#cnSlopeLegend').textContent,/45–60 %/);$('#cnWlFind').click();await new Promise(r=>setTimeout(r,150));assert.match($('#cnWlList').textContent,/Canal de Trea/);$('#cnClose').click();
assert.equal($('#sosButton'),null,'sin SOS');
// v13 · Decisión, plan de seguridad, copiloto propio, buscador con carga automática y paleta
w.T.showTab('route');w.T.S.route&&w.renderRouteForecast?.();
assert.ok($('#rsNav'),'navegación de resultados');assert.equal($$('#rsGroups .rs-group').length,7);assert.ok($('#rs-decision #rsSummary'));assert.match($('#rsSummary').textContent,/Horario MIDE/);assert.match($('#rsSummary').textContent,/Agua\s*[\d,]+ L\s*Recomendada|Recomendada/);assert.match($('#rsSummary').textContent,/Meteorología en ruta/);assert.match($('.rs-dial').textContent,/GO|OJO|STOP|\?/);
assert.ok($('#rs-when #weekCard'),'semana en «Cuándo salir»');assert.ok($('#rs-sectors #routeForecast'));assert.ok($('#rs-pack #gearCard'));assert.ok($('#rs-onroute #rsSafety'));
assert.equal(Math.round(w.TMResults.mideMinutes({km:12,up:800,down:800})),Math.round((3.333+1.5)*60+0));
const sText=w.TMResults.safetyText();assert.match(sText,/112/);assert.match(sText,/maps\.google\.com\/\?q=/);assert.match(w.TMResults.ics(),/BEGIN:VEVENT[\s\S]*VALARM/);
const cx13=w.Copilot.contextObj();assert.equal(typeof cx13,'object');
for(const [q,re] of [['¿Qué tiempo hace?',/°C/],['¿A qué hora salgo?',/salida/i],['¿Qué material llevo?',/Agua|agua/],['Plan B',/Plan B/],['¿Habrá viento?',/rachas?|Viento/i],['¿Hay nieve o hielo?',/Isoterma|isoterma|nieve/i],['¿Es realista mi ritmo?',/MIDE/]]){const a=w.TMExpert.answer(q,cx13);assert.match(a.text,re,q)}
assert.equal(w.TMExpert.route('Dame el parte en 3 líneas'),'parte3');assert.equal(w.TMExpert.route('¿Tormentas esta tarde?'),'storm');
{try{w.localStorage.setItem('tm.ai.provider','expert')}catch{}}const ex=await w.Copilot.ask('¿Qué tiempo hace?');assert.equal(ex.provider,'expert');assert.match(ex.text,/°C/);try{w.localStorage.removeItem('tm.ai.provider')}catch{}
assert.equal(w.TMFinder.pattern('Ruta del Cares'),'c[aáà]r[eéè]s');assert.match(w.TMFinder.pattern('PR-PNPE 3'),/^pr\[- \]\?p\[nñ\]p/);
const segs=[[{lat:43,lon:-4.9},{lat:43.001,lon:-4.9}],[{lat:43.001,lon:-4.9},{lat:43.002,lon:-4.9}],[{lat:43.1,lon:-4.8},{lat:43.101,lon:-4.8}]];assert.equal(w.TMFinder.components(segs).length,2);assert.equal(w.TMFinder.viaPoints(w.TMFinder.components(segs)).length>=2,true);
assert.equal(w.TMFinder.nameFromWikiloc('https://es.wikiloc.com/rutas-senderismo/ruta-del-cares-poncebos-cain-poncebos-5145198'),'ruta del cares poncebos cain poncebos');assert.equal(w.TMFinder.keywords('Ruta del Cares (Poncebos - Caín)').join(','),'cares,poncebos,cain');
assert.ok($('[data-finder="osm"]'),'pestaña Buscar ruta');assert.equal($('#frABForm'),null,'sin ruta a medida');
w.TMPalette.open('cana');assert.ok($('#pal'));assert.match($('#palList').textContent,/Canales de Picos/);w.TMPalette.close();assert.equal($('#pal'),null);

// v14 · menú completo, instrucciones y combustible
assert.ok($('#mainNav'));for(const k of ['route','library','fuel','road','now','radar','models','mountain','terrain','canales','copilot','guide','account','contact','home'])assert.ok($(`#mainNav [data-nav="${k}"]`),'menú: '+k);assert.ok($$('#siteMenu [data-nav]').length>=15,'menú ☰ completo');
assert.ok($$('#pane-guide .g-sec').length>=10,'instrucciones');w.TMShell.go('guide');assert.equal($('#pane-guide').hidden,false);
w.TMShell.go('fuel');assert.equal($('#pane-fuel').hidden,false);const pl=w.TMFuel.basics('plátano');assert.equal(pl.length,1);w.TMFuel.clear();w.TMFuel.add(pl[0],120);w.TMFuel.add(w.TMFuel.basics('dátiles')[0],50);const tt=w.TMFuel.totals().t;assert.equal(Math.round(tt['energy-kcal']),Math.round(89*1.2+282*.5));assert.equal(Math.round(tt.carbohydrates),Math.round(22.8*1.2+75*.5));assert.match($('#fuTotals').textContent,/Hidratos/);
const nd=w.TMFuel.needs(4,15);assert.equal(nd.carb[0],120);assert.equal(nd.carb[1],240);assert.equal(w.TMFuel.servingG('1 rebanada 28 g'),28);assert.equal(w.TMFuel.per100({nutriments:{'energy-kcal_100g':100,'salt_100g':1}}).sodium,.4);
assert.equal($('.splash-topo'),null,'sin círculos en la bienvenida');
console.log('v14 checks passed: full top menu (15 entries), guide, fuel basics/totals/needs/serving parsing, splash without circles.');
console.log('v13 checks passed: decision summary (MIDE, water, turnaround), 7 result groups, safety plan + ICS, expert copilot intents and provider, OSM finder pattern/components/Wikiloc names, no A→B builder, command palette.');
console.log('v10+v11+v12 checks passed (road: DGT, chains, OSRM, weather en ruta): OSM canal catalog (3 massifs, joins, filters, ficha with access/links/sun/profile), week heatmap, sea of clouds, relief shade, ground state, personal pace, card, v11 particles/sound/extra models/ensembles/meteogram/snow+satellite/OSM trails/canal sources+slope+snow/accounts/contact, Más sheet, POIs, splash→planner, dock order, Commons attribution, 15 visual canales + filters/search/detail, Wikiloc parse/search/load with elevation, go-meter + gear, copilot context/markdown safety/adapter.');await w.happyDOM.close();
