window.NAVAL_MODALS_DATA = (function () {
  "use strict";

  const QUESTIONS = [
    { id: 1, difficulty: "easy", points: 100, category: "Obligación",
      prompt: "According to the Safety Management System, the duty engineer ___ record the engine room parameters every hour.",
      options: ["must", "might", "could", "needn't"], correct: 0,
      explain: "\"Must\" expresa una obligación impuesta por una norma (el SMS). No es una opción personal." },
    { id: 2, difficulty: "easy", points: 100, category: "Prohibición",
      prompt: "You ___ enter a confined space without a valid Permit to Work and atmosphere testing.",
      options: ["mustn't", "don't have to", "might not", "needn't"], correct: 0,
      explain: "\"Mustn't\" es prohibición absoluta: está terminantemente prohibido, no solo innecesario." },
    { id: 3, difficulty: "easy", points: 100, category: "Consejo",
      prompt: "The bilge level is rising slowly; you ___ report it to the Chief Engineer just in case.",
      options: ["should", "must", "can't", "needn't"], correct: 0,
      explain: "\"Should\" da un consejo razonable, sin ser una obligación legal estricta." },
    { id: 4, difficulty: "medium", points: 150, category: "Permiso",
      prompt: "\"___ I use the emergency generator for testing during the drill?\"",
      options: ["May", "Must", "Should", "Ought to"], correct: 0,
      explain: "\"May\" es la forma formal y correcta para pedir permiso." },
    { id: 5, difficulty: "easy", points: 100, category: "Habilidad",
      prompt: "The Third Engineer ___ operate the purifier alone after completing the familiarization checklist.",
      options: ["can", "must", "should", "needn't"], correct: 0,
      explain: "\"Can\" expresa capacidad/habilidad adquirida tras la formación." },
    { id: 6, difficulty: "medium", points: 150, category: "Deducción",
      prompt: "The alarm panel shows a red light and the pump has stopped; there ___ be a power failure.",
      options: ["must", "can", "should", "needn't"], correct: 0,
      explain: "\"Must\" para deducción lógica con alto grado de certeza sobre el presente." },
    { id: 7, difficulty: "medium", points: 150, category: "Ausencia de necesidad",
      prompt: "Since the tank was already gas-freed yesterday, you ___ test the atmosphere again before a short visual check, but it's still recommended.",
      options: ["don't have to", "mustn't", "shouldn't", "can't"], correct: 0,
      explain: "\"Don't have to\" indica ausencia de obligación, no prohibición." },
    { id: 8, difficulty: "hard", points: 200, category: "Deducción pasada",
      prompt: "The oil mist detector triggered but no fire was found; the sensor ___ have malfunctioned.",
      options: ["must", "should", "needn't", "can't"], correct: 0,
      explain: "\"Must have + participio\" para una deducción muy probable sobre el pasado." },
    { id: 9, difficulty: "hard", points: 200, category: "Crítica pasada",
      prompt: "The engineer ___ have isolated the fuel valve before starting the repair — the near-miss was avoidable.",
      options: ["should", "must", "needn't", "couldn't"], correct: 0,
      explain: "\"Should have + participio\" critica una acción pasada que no se hizo." },
    { id: 10, difficulty: "medium", points: 150, category: "Acción innecesaria",
      prompt: "We ___ have called the shore technician; the crew fixed the governor themselves.",
      options: ["needn't", "mustn't", "shouldn't", "couldn't"], correct: 0,
      explain: "\"Needn't have + participio\": se hizo algo (o no hizo falta) que resultó innecesario." },
    { id: 11, difficulty: "easy", points: 100, category: "Obligación normativa",
      prompt: "Under SOLAS regulations, all crew ___ participate in the monthly abandon ship drill.",
      options: ["must", "might", "could", "would"], correct: 0,
      explain: "Obligación impuesta por un convenio internacional (SOLAS)." },
    { id: 12, difficulty: "medium", points: 150, category: "Posibilidad",
      prompt: "The vibration in the shaft ___ be caused by a misaligned coupling.",
      options: ["might", "must", "needn't", "mustn't"], correct: 0,
      explain: "\"Might\" expresa posibilidad, sin certeza." },
    { id: 13, difficulty: "medium", points: 150, category: "Prohibición",
      prompt: "Crew members ___ smoke within the enclosed engine room at any time.",
      options: ["mustn't", "may", "should", "needn't"], correct: 0,
      explain: "\"Mustn't\" prohíbe totalmente la acción por seguridad." },
    { id: 14, difficulty: "hard", points: 200, category: "Crítica pasada",
      prompt: "Given the near-miss, the company ___ have reviewed its permit-to-work procedure sooner.",
      options: ["should", "must", "can", "could"], correct: 0,
      explain: "\"Should have\" para criticar que algo debería haberse hecho antes." },
    { id: 15, difficulty: "easy", points: 100, category: "Obligación normativa",
      prompt: "An Officer of the Watch ___ hold a valid STCW certificate of competency.",
      options: ["must", "can", "might", "would"], correct: 0,
      explain: "Requisito obligatorio del convenio STCW." },
    { id: 16, difficulty: "medium", points: 150, category: "Prohibición",
      prompt: "You ___ operate lifting equipment unless you are an authorised and trained person.",
      options: ["mustn't", "don't have to", "may", "needn't"], correct: 0,
      explain: "Prohibición salvo excepción explícita (persona autorizada)." },
    { id: 17, difficulty: "medium", points: 150, category: "Permiso",
      prompt: "\"___ we start the bunkering operation before the checklist is completed?\"",
      options: ["Can", "Must", "Should", "Ought"], correct: 0,
      explain: "\"Can\" se usa para pedir permiso de forma directa (aunque la respuesta correcta en procedimiento sería \"no\")." },
    { id: 18, difficulty: "hard", points: 200, category: "Deducción negativa pasada",
      prompt: "The gauge reading was normal all watch; the leak ___ have started before the handover.",
      options: ["can't", "mustn't", "shouldn't", "needn't"], correct: 0,
      explain: "\"Can't have + participio\": imposibilidad deducida sobre el pasado." },
    { id: 19, difficulty: "easy", points: 100, category: "Obligación",
      prompt: "All personnel ___ wear a hard hat and safety boots in the engine room workshop.",
      options: ["must", "might", "could", "would"], correct: 0,
      explain: "Norma de seguridad obligatoria en el taller." },
    { id: 20, difficulty: "medium", points: 150, category: "Habilidad pasada",
      prompt: "Thanks to the backup pump, the crew ___ maintain cooling water pressure during the failure.",
      options: ["was able to", "can", "must", "should"], correct: 0,
      explain: "Para un logro concreto y puntual en pasado se usa \"was able to\", no \"could\" en afirmativo." },
    { id: 21, difficulty: "medium", points: 150, category: "Consejo negativo",
      prompt: "You ___ ignore a minor oil leak; it can quickly become a major hazard.",
      options: ["shouldn't", "mustn't", "needn't", "couldn't"], correct: 0,
      explain: "\"Shouldn't\" es un consejo en contra, más suave que una prohibición estricta." },
    { id: 22, difficulty: "hard", points: 200, category: "Deducción",
      prompt: "The new cadet completed the task perfectly; he ___ have received excellent training.",
      options: ["must", "might", "mustn't", "needn't"], correct: 0,
      explain: "Deducción muy probable sobre un hecho pasado." },
    { id: 23, difficulty: "medium", points: 150, category: "Obligación normativa",
      prompt: "Under the ISM Code, the Master ___ ensure that a safety management system is properly implemented on board.",
      options: ["must", "could", "might", "would"], correct: 0,
      explain: "Obligación establecida por el Código IGS (ISM Code)." },
    { id: 24, difficulty: "easy", points: 100, category: "Permiso informal",
      prompt: "\"___ I borrow your torch to check the shaft tunnel?\"",
      options: ["Can", "Must", "Shall", "Need"], correct: 0,
      explain: "\"Can\" para pedir permiso de forma informal entre compañeros." },
    { id: 25, difficulty: "medium", points: 150, category: "Obligación",
      prompt: "Visitors ___ report to the gangway watchman before boarding.",
      options: ["must", "might", "could", "would rather"], correct: 0,
      explain: "Norma de acceso obligatoria a bordo." },
    { id: 26, difficulty: "hard", points: 200, category: "Habilidad negativa pasada",
      prompt: "Despite the rough weather, the tug ___ not manage to keep the tow line taut.",
      options: ["could", "can", "must", "should"], correct: 0,
      explain: "\"Could not / couldn't\" para incapacidad general en el pasado." },
    { id: 27, difficulty: "medium", points: 150, category: "Prohibición",
      prompt: "Reduced ballast operations ___ be carried out without informing the Officer of the Watch.",
      options: ["mustn't", "don't have to", "needn't", "may"], correct: 0,
      explain: "Prohibición: siempre hay que informar antes." },
    { id: 28, difficulty: "easy", points: 100, category: "Ofrecimiento",
      prompt: "\"___ I inform the bridge about the blackout?\"",
      options: ["Shall", "Must", "Might", "Need"], correct: 0,
      explain: "\"Shall I...?\" se usa para hacer un ofrecimiento o sugerencia." },
    { id: 29, difficulty: "hard", points: 200, category: "Posibilidad/Permiso",
      prompt: "The class surveyor ___ request additional thickness measurements if corrosion is suspected.",
      options: ["may", "must", "needn't", "mustn't"], correct: 0,
      explain: "\"May\" expresa una posibilidad/potestad condicional del inspector." },
    { id: 30, difficulty: "easy", points: 100, category: "Obligación",
      prompt: "Before entering port, the engine room log ___ be completed and signed.",
      options: ["must", "might", "could", "would"], correct: 0,
      explain: "Requisito administrativo obligatorio antes de puerto." },
    { id: 31, difficulty: "medium", points: 150, category: "Habilidad",
      prompt: "A well-trained motorman ___ change a fuel injector without supervision.",
      options: ["can", "must", "should", "might"], correct: 0,
      explain: "\"Can\" para una habilidad general adquirida." },
    { id: 32, difficulty: "hard", points: 200, category: "Acción innecesaria pasada",
      prompt: "We ___ have shut down the auxiliary engine — the vibration alarm was only a faulty sensor, so it turned out to be unnecessary.",
      options: ["needn't", "shouldn't", "mustn't", "couldn't"], correct: 0,
      explain: "\"Needn't have + participio\": se hizo algo que, a posteriori, no era necesario." }
  ];

  const GLOSSARY = [
    { term: "Bilge", es: "Sentina", def: "Zona inferior del casco donde se acumulan aguas residuales y aceites." },
    { term: "Ballast", es: "Lastre", def: "Agua o peso usado para la estabilidad del buque." },
    { term: "Bunkering", es: "Aprovisionamiento de combustible", def: "Operación de carga de combustible al buque." },
    { term: "Mooring", es: "Amarre", def: "Sujeción del buque a un muelle o boya." },
    { term: "Watchkeeping", es: "Guardia", def: "Turno de vigilancia en puente o en máquinas." },
    { term: "Chief Engineer", es: "Jefe de Máquinas", def: "Máximo responsable del departamento de máquinas." },
    { term: "Officer of the Watch", es: "Oficial de guardia", def: "Oficial responsable durante un turno de guardia." },
    { term: "Permit to Work", es: "Permiso de trabajo", def: "Autorización documentada para trabajos de riesgo." },
    { term: "Confined Space", es: "Espacio confinado", def: "Recinto con ventilación y acceso restringidos." },
    { term: "Muster Station", es: "Punto de reunión", def: "Lugar de congregación de la tripulación en emergencias." },
    { term: "Lifeboat", es: "Bote salvavidas", def: "Embarcación de supervivencia." },
    { term: "MARPOL", es: "Convenio MARPOL", def: "Convenio internacional para prevenir la contaminación por buques." },
    { term: "SOLAS", es: "Convenio SOLAS", def: "Convenio internacional para la seguridad de la vida humana en el mar." },
    { term: "STCW", es: "Convenio STCW", def: "Normas de formación, titulación y guardia para la gente de mar." },
    { term: "ISM Code", es: "Código IGS", def: "Código Internacional de Gestión de la Seguridad." },
    { term: "Port State Control", es: "Inspección por el Estado Rector del Puerto", def: "Control de buques extranjeros mientras están en puerto." },
    { term: "Bulkhead", es: "Mamparo", def: "Pared estructural estanca o divisoria del buque." },
    { term: "Manifold", es: "Colector", def: "Sistema de tuberías de conexión para carga o descarga." },
    { term: "Purifier", es: "Purificadora", def: "Centrífuga para separar impurezas del combustible o aceite." },
    { term: "Crankcase", es: "Cárter", def: "Alojamiento del cigüeñal del motor." },
    { term: "Scavenging", es: "Barrido", def: "Proceso de renovación de aire en el cilindro del motor." },
    { term: "Freeboard", es: "Francobordo", def: "Distancia entre la línea de flotación y la cubierta." },
    { term: "Draught", es: "Calado", def: "Profundidad sumergida del casco." },
    { term: "Stern", es: "Popa", def: "Parte posterior del buque." },
    { term: "Bow", es: "Proa", def: "Parte delantera del buque." },
    { term: "Hawser", es: "Estacha", def: "Cabo grueso usado para amarre o remolque." },
    { term: "Fender", es: "Defensa", def: "Elemento que protege el casco de impactos." },
    { term: "Deadweight", es: "Peso muerto", def: "Capacidad de carga total del buque (DWT)." },
    { term: "Flag State", es: "Estado de abanderamiento", def: "País bajo cuya bandera navega el buque." },
    { term: "Classification Society", es: "Sociedad de Clasificación", def: "Entidad que certifica el estado técnico del buque." }
  ];

  const LIVE_EVENTS = [
    { key: "fire", icon: "🔥", title: "¡Alarma de incendio en sala de máquinas!",
      desc: "Fuego simulado en el separador de sentinas. La próxima pregunta vale x2 puntos.",
      effect: { multiplier: 2, questions: 1 } },
    { key: "psc", icon: "🕵️", title: "Inspección PSC a bordo",
      desc: "El inspector del Estado Rector del Puerto exige precisión. Próxima pregunta a x1.5 puntos.",
      effect: { multiplier: 1.5, questions: 1 } },
    { key: "storm", icon: "🌊", title: "Mar gruesa — Fuerza 8",
      desc: "La plataforma se mueve con fuerza. Se descuentan 15s del cronómetro general.",
      effect: { timeDeltaSeconds: -15 } },
    { key: "blackout", icon: "⚡", title: "Apagón — Fallo del generador principal",
      desc: "Sin generador de emergencia disponible: el glosario queda bloqueado 30 segundos.",
      effect: { lockGlossarySeconds: 30 } },
    { key: "mob", icon: "🆘", title: "¡Hombre al agua!",
      desc: "Maniobra de emergencia Williamson. La próxima respuesta correcta da +250 puntos extra.",
      effect: { flatBonus: 250, questions: 1 } },
    { key: "oilspill", icon: "🛢️", title: "Alerta MARPOL: posible vertido",
      desc: "Se activa el plan SOPEP. La próxima pregunta vale x3 puntos.",
      effect: { multiplier: 3, questions: 1 } },
    { key: "calm", icon: "☀️", title: "Aguas tranquilas",
      desc: "Guardia sin incidencias. +20 segundos de bonificación en el cronómetro.",
      effect: { timeDeltaSeconds: 20 } },
    { key: "drill", icon: "🚨", title: "Ejercicio de abandono de buque",
      desc: "Zafarrancho general: doble de puntos para toda la tripulación durante los próximos 45s.",
      effect: { multiplier: 2, windowMs: 45000 } }
  ];

  return { QUESTIONS, GLOSSARY, LIVE_EVENTS };
})();
